### ISSUE TITLE
S3.headObject type mismatch in 2.3.15

### ISSUE THREAD

**Issue by mlconnor** [aws/aws-sdk-js#1002]
Hey guys, I'm calling s3 headObjectType using apiVersion: '2006-03-01' and the LastModified property of the response is a string where the API [spec](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property) indicates a Date.  The other methods I'm using that return a LastModified property have returned Javascript date so it seems weird to parse it.  Can you confirm?

```
{
  "AcceptRanges": "bytes",
  "LastModified": "Tue, 15 Nov 2011 16:23:44 GMT",
  "ContentLength": "1150509",
  "ETag": "\"aed78a76753b26cf977c33d29f239aa9\"",
  "ContentType": "video/webm",
  "Metadata": {}
} 
```

**Comment by LiuJoyceC** [comment]
Hi @mlconnor 
Can you tell us which other methods you are using that are returning the `LastModified` property as a Javascript date? `getObject` also returns `LastModified` as a string. You are right that the API docs say it should be a date, and the docs should be corrected. We may not be able to change the return type in the response to a date object because this would be a breaking change for customers who are currently parsing the string. If you would like to convert the string to a Javascript date object, it's not necessary to parse the string. You can just pass it in to the `Date` constructor: `new Date(data.LastModified)`

For now I will mark this is a documentation issue, but please let us know which methods you are calling return a date object instead of a string so we can determine how to best correct this inconsistency. Thanks!

**Comment by jeskew** [comment]
I was checking in on our outstanding documentation issues and was unable to reproduce the behavior described in the ticket description. The object returned from the SDK has a `Date` object for the `LastModified` property and a number for the `ContentLength` property.
