### ISSUE TITLE
Proposal upgrade xmlbuilder

### ISSUE THREAD

**Issue by cloudkite** [aws/aws-sdk-js#1012]
Happy todo a PR for this but thought I would raise the question here first.

The latest version of xmlbuilder does not depend on lodash. This can reduce initialisation time by ~100ms see https://github.com/oozcitak/xmlbuilder-js/issues/43 and https://github.com/lodash/lodash/issues/632.

~100ms probably isn't significant in most cases, but for environments like lambda where you are more likely to get a cold environment it could help reduce latency of cold requests?

However if your project or any other dependencies depend on lodash it wont make any difference.

**Comment by LiuJoyceC** [comment]
Hi @cloudkite 
Thanks for the suggestion. However, since it is so many major version bumps above the version we're using, we need to be very careful about potential breaking changes. Upgrading to a new major version of a dependency would require a significant justification, such as a bug fix that requires it.

**Comment by AJShippify** [comment]
Due to the way that node modules is handled as a flattened tree, many libraries which depend on lodash have higher versions than the one provided on the xmlbuilder used in aws-sdk. This results in conflicts on dependency resolution and calls to deprecated and/or deleted functions.
