### ISSUE TITLE
[question] Does s3.getSignedUrl Expires conflict with s3.putObject Expires?

### ISSUE THREAD

**Issue by mjmasn** [aws/aws-sdk-js#1015]
I'm using `CacheControl` not `Expires` so this is not actually a problem for me but just wondering if I was using the `Expires` key on a `s3.putObject` request, surely if I want to use `s3.getSignedUrl` for that request then the `Expires` fields will conflict (i.e. the expires header served with the image will be equivalent to the expiry time of the signed url). Or is the `Expires` field just not passed through to `putObject` if used in a `getSignedUrl` request?

**Comment by chrisradek** [comment]
@mjmasn 
Sorry for the delayed response.

If `Expires` is set when using `putObject` in conjunction with `getSignedUrl`, then `Expires` will not be passed through to `putObject`, it will only apply to the expiry time of the signed url.

It looks like at the time `getSignedUrl` was written, there weren't any parameters that supported `Expires`, so it was removed to fix a parameter validation bug. Instead, we should check if the operation supports passing in `Expires` as a parameter.

**Comment by chrisradek** [comment]
@mjmasn 
I looked into this issue some more. 
Using `signatureVersion: v2`, we can't put `Expires` in the query string of the URL because it is already there and represents the expiry time of the url. Using `signatureVersion: v4`, we can add `Expires` to the query string of the URL, but S3 ignores it anyway.

It looks like the only way to specify the `Expires` header when using a presigned url is to send the header when making a request using the URL. That's easy to do in node.js but may be more difficult in the browser.

Unfortunately there isn't anything we can do from the SDK side at this time.

**Comment by mjmasn** [comment]
Thanks for the investigation and reply @chrisradek. As I say, doesn't affect me but hopefully this will be helpful to anyone who stumbles on the issue.
