### ISSUE TITLE
CloudWatch API Version?

### ISSUE THREAD

**Issue by ctindel** [aws/aws-sdk-js#1032]
I am new to this SDK, but am I fundamentally misunderstanding something?  It looks like the node.js sdk only supports a cloudwatch api from back in 2010?

I'm just trying to use the node.js sdk to give me a list of alarms for a specific instance, and I can't seem to find which function will allow me to do that.

**Comment by chrisradek** [comment]
@ctindel 
Many of the services only update the api version when they make a backwards incompatible change. That's why many of the services in the SDKs will appear to be an old API version, but they may have been updated anytime since the original version.

I believe you are looking for the `describeAlarmsForMetric` operation:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#describeAlarmsForMetric-property

You can find the namespace to use here:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/aws-namespaces.html

Assuming `AWS/EC2`, the metrics and dimensions for metrics (including instance id) are here:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/ec2-metricscollected.html#ec2-metric-dimensions
 
In the future, if you have a question about a specific operation to use for a service, you might have better luck on the forums. We try to focus on SDK specific issues in this repo, and don't always know the services as well as the service teams do!
