### ISSUE TITLE
Uncatchable TimeoutError when using AWS.config.loadFromPath() w/ faulty credentials

### ISSUE THREAD

**Issue by dustinbolton** [aws/aws-sdk-js#1037]
Faulty credentials (example of these & how they came about in next comment below) being loaded via config.loadFromPath() seem to result in an error which I cannot see a way to catch because it is passed back to the loadFromPath() method in config.js for resolution.

/aws-sdk/lib/config.js:389
   if (err) throw err;

TimeoutError: Connection timed out after 1000ms
   at ClientRequest.<anonymous> (/aws-sdk/lib/http/node.js:56:34)

**Comment by dustinbolton** [comment]
Note that this was discovered with credentials returned from STL for a federated user not having their starting letter converted to lower-case prior to storing in a .json file.  That STL API returns credentials for a federated user with keys beginning with a capital letter such as:
AccessKeyId
SecretAccessKey
SessionToken
Expiration

However, this SDK throws the connection timed out after 1000ms error when using config.loadFromPath() unless they are corrected to begin with lower case letters:
accessKeyId
secretAccessKey
sessionToken
expiration

I'm not sure if this is expected behavior or not either.

**Comment by LiuJoyceC** [comment]
Hi @dustinbolton 
`loadFromPath()` is actually creating a new instance of a `CredentialProviderChain` which will be determined by `AWS.CredentialProviderChain.defaultProviders` (see `lib/aws.js`). It then creates an instance of `FileSystemCredentials` from the path you provided, and adds this credential provider to the front of the chain. The `TimeoutError` that is getting thrown is unrelated to the .json file you provided a path to, and is coming from the last credential provider in the chain, the `EC2MetadataCredentials`. In `loadFromPath()`, `chain.resolve()` gets called, which will try to source credentials from the chain that was created in order. If your .json is incorrectly capitalizing the property names, the resolver will fail to get credentials from it and will move on to the next provider in the chain. After failing to get credentials from the rest of the providers, it will finally get to the last provider, the `EC2MetadataCredentials` provider and try to request credentials form EC2's Metadata Service. Since you're not running your application on EC2, the request will timeout, and because there are no more providers down the chain, the error is thrown.

**Comment by LiuJoyceC** [comment]
If you don't intend to source credentials from anywhere but the specified .json and would like an error to be raised after failing to retrieve credentials from it, you can create your own chain with just the `FileSystemCredentials` provider:
```
var getMyCredentials = function() { return new AWS.FileSystemCredentials(path); };
var chain = new AWS.CredentialProviderChain([getMyCredentials]);
chain.resolve(function(err, creds) {
    if (err) {
        // handle the error however you like here
    } else {
        AWS.config.credentials = creds;
    }
});
```

Another workaround, if you want to use `loadFromPath()` and catch the error, is to set the default provider to an empty array. Then `loadFromPath()` becomes synchronous (since it's no longer sending a request to EC2 Metadata Service), and you can use a try-catch block to catch the error.
```
AWS.CredentialProviderChain.defaultProviders = [];
try {
    AWS.config.loadFromPath(path);
} catch (err) {
    // handle the error here
}
```

**Comment by LiuJoyceC** [comment]
By STL, do you mean STS (Security Token Service)? If so, what API are you calling to get credentials? It may not be necessary to load the credentials from STS to a JSON file. If you are calling either the `assumeRole` or `getSessionToken` APIs to get credentials, then you can directly use the `TemporaryCredentials` provider to load the credentials from STS to `AWS.config.credentials`. (See http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TemporaryCredentials.html). If you are calling `assumeRoleWithWebIdentity` or `assumeRoleWithSAML`, you can similarly use the `WebIdentityCredentials` and `SAMLCredentials` providers, respectively.

Let me know if that helps!

**Comment by dustinbolton** [comment]
Thank you very much for this information.  The workarounds you provided did work for my needs and allow me to catch the error. I am indeed using STS so I am looking into using this method as a more 'direct' way of applying the credentials.  Thank you for letting me know about that as well.

I very much appreciate all of your explanation here as I now understand how this all works much better.

**Comment by LiuJoyceC** [comment]
I'm glad to hear it!
