### ISSUE TITLE
RequestTimeout in s3 putObject when region is not specified

### ISSUE THREAD

**Issue by glenswift** [aws/aws-sdk-js#1043]
I'm not sure if it's by design (there's a point in docs that sdk doesn't auto-select region). It took me like several hours of attempts to make it work and I've found several issues with same problem without solution (#281, #454). So I've decide to let you know about it.

This will fail with timeout for me:

```
const s3Client = new aws.S3({
  accessKeyId: 'such-a-key',
  secretAccessKey: 'so-secret'
});
s3Client.putObject(//...
```

and this will work:
```
const s3Client = new aws.S3({
  accessKeyId: 'such-a-key',
  secretAccessKey: 'so-secret',
  region: 'eu-central-1'
});
s3Client.putObject(//...
```

**Comment by LiuJoyceC** [comment]
Hi @glenswift 
What is your S3 client's region when you don't explicitly put a region in the options when instantiating? You can check `s3Client.config.region`. Also, what version of the AWS SDK are you using? Can you provide any further information about your SDK configuration and other steps to replicate this? I was not able to replicate the error with the above information. What is the exact error code and error message you are receiving? Another helpful diagnostic to see if your request is failing on the first try or on subsequent retries is to put to pass in the console as the logger param (`s3Client = new aws.S3({logger: console, //...})`). If the timeout error you are receiving is happening on a retry rather than the first try, it might help to see what kind of error you are receiving on the first try. You can see this by setting `maxRetries` to 0 (`new aws.S3({maxRetries: 0, //...})`).

**Comment by LiuJoyceC** [comment]
Hi @glenswift 
I was able to replicate this error when the Body param is a stream. The reason this is occurring is that when the S3 client is configured to a region that is different from the region of the bucket you are making a request to, the SDK attempts to get the correct region and retry your request in the correct region. However, in Node.js, streams are not rewindable, so the SDK is unable to retry the request, and you will get a timeout.

The recommended solution is to configure your S3 client to the correct region. You can either configure the region globally by setting `AWS.config.region` before instantiating your S3 client or by specifying the region when you instantiate the S3 client, as you have done above.

If you don't know a bucket's region beforehand, here are a couple of workarounds:

Call S3's `getBucketLocation` operation to get the region before configuring your S3 client.

If you prefer to use the SDK's region redirection feature for S3 (such as the case when you are using one S3 client to make requests to multiple buckets in different regions), you can set `maxRetries` to 0 when instantiating the S3 client, and manually retry the request if an error is returned. The SDK will cache the bucket's region, and when you retry the request, the request will automatically be corrected to use the correct region for that bucket.

Let me know if these workarounds work for your use case!

**Comment by glenswift** [comment]
Yes, It setting region works for me from the very beginning. I just wanted to point you to this stuff, as I don't find anything relevant in doc. Thanks for explanation, feel free to close the issue.

**Comment by LiuJoyceC** [comment]
Hi @glenswift 
A slight correction to my comment above: the SDK cannot retry requests with stream bodies for putObject. However, the SDK's managed uploader (`s3client.upload`) is able to retry them because it buffers the stream (or each upload part if the file is greater than 5MB) into memory before sending the request or series of requests. The PR above adds a comment to the API docs about this. Feel free to open up a new issue if you have any trouble with the managed uploader.
