### ISSUE TITLE
Error : s3.upload.promise() is not a funciton

### ISSUE THREAD

**Issue by dhatawesomedude** [aws/aws-sdk-js#1076]
I'm trying to call the setPromisesAWS.config.setPromisesDependency config function but my config object doesn't seem to have the setPromisesDependency property.
Am I missing something?

    AWS.config.setPromisesDependency(bluebird)
    // Error : AWS.config.setPromisesDependency is not a function

I have version 2.2.48 installed via bower.
Any help would be appreciated.

**Comment by LiuJoyceC** [comment]
Hi @dhatawesomedude 

Thanks for your question. Promises are not supported in the SDK prior to version `2.3.0`. If you update to `2.3.0` or later, the `setPromisesDependency` property will be on `AWS.config`.

**Comment by dhatawesomedude** [comment]
Thanks @LiuJoyceC 

Updating my version fixed this issue, but I still cannot call `.promise` on `s3.upload()`. The promise property is undefined. Any idea how to fix that?

**Comment by LiuJoyceC** [comment]
Hi @dhatawesomedude 

Promises are currently only supported on operations that return a Request object. Since `s3.upload` is a custom function that returns an instance of ManagedUpload rather than Request, promises are not currently supported for that operation. However, this is a feature request that we are looking into.

As a current workaround, if you know your file's size, you can use the `putObject` operation for file sizes <= 5MB, or use the multipart upload operations for file sizes greater than 5MB. The SDK does support promises on all of these operations. You could also create the promise:
```
var s3UploadPromise = new Promise(function(resolve, reject) {
	s3.upload(params, function(err, data) {
		if (err) {
			reject(err);
		} else {
			resolve(data);
		}
	});
});
```
I hope that helps!

**Comment by niftylettuce** [comment]
Another way to do this in the meanwhile is to use `es6-promisify` at <https://www.npmjs.com/package/es6-promisify>.  Here's an example:

```js
const params = { ... }
await promisify(s3.upload, s3)(params);
```

... or if you're not using async/await ...

```js
const params = { ... }
promisify(s3.upload, s3)(params).then(fn).catch(fn);
```

**Comment by niftylettuce** [comment]
Also, if you attempt to use promises with this and do not pass configuration object, it will throw an unhandled promise rejection!  Definitely a bug?

```
(node:38374) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MissingRequiredParameter: Missing required key 'Bucket' in params
```

**Comment by LiuJoyceC** [comment]
Hi @niftylettuce 
For your above comment about the unhandled promise rejection, are you referring to when you use `es6-promisify`? Are you referring to when you use the SDK promise support in the PR I submitted? I've tried to replicate this but have not gotten any rejections thrown (it's expected for the promise to be rejected if not all required params are present, but it shouldn't be getting thrown). Could you provide the exact code you are using to replicate this error? Thanks.

**Comment by niftylettuce** [comment]
Referring to SDK in library.

**Comment by LiuJoyceC** [comment]
@niftylettuce 
Are you using Node v6.6.0 or higher? As of Node v6.6.0, a warning will be emitted when a promise is rejected and a `catch` handler isn't attached to the promise. It is not throwing an error, and execution will not stop. This is a new feature of Node, not a bug in the SDK.
https://news.ycombinator.com/item?id=12509832

**Comment by niftylettuce** [comment]
Yes I know that, I'm saying that there's somewhere in the AWS SDK where there is a promise that is not wrapped with a try catch.  In my code I wrapped it with a try catch and STILL got an unhandled promise rejection.  I'm on latest Node, which is 6.6.x.

**Comment by LiuJoyceC** [comment]
Promises don't work with try-catch blocks because they don't throw errors. They reject the errors, and you'll need to add a `catch` handler to the promise to handle the error. The SDK's promises are designed to reject any errors that would normally get passed into the error-first callback when a callback is used instead of a promise. In the case of callbacks, if you don't pass in the required params, an error will be passed into your callback, and you as the user can decide how you want to handle the error in your callback. If you don't write explicit logic in your callback to handle the error, then the error is silently swallowed (and the SDK cannot control what happens in the user-supplied callback). Similarly for promises, it's up to the user to add a `catch` handler to handle rejected promises. If you don't add a `catch` handler, then it is analogous to receiving the error in a callback but not writing any error-handling logic in the callback. The SDK cannot handle the error for you because then the user will no longer be able to choose how to handle the error.
There are no unhandled promises somewhere in the internals of the SDK. The SDK does not generate promises anywhere unless you explicitly call the `.promise()` method on the `AWS.Request` class (and in the PR, a few additional classes), in which case the method returns the raw promise to you to handle as you see fit. If `then` and `catch` handlers are not added by the user, then the behavior is consistent with any regular promises outside of the SDK, which is that rejections and resolutions get swallowed silently. Does that make sense?

**Comment by niftylettuce** [comment]
Yes it does but I had await in front of the promise..   I'll try again...

**Comment by MrHubble** [comment]
As an update, I believe promises are now supported on ManagedUploads so `upload` can be used instead of `putObject` if so desired: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#promise-property

**Comment by niftylettuce** [comment]
This is still an issue though.  The following code will result in an unhandled promise rejection.  There is definitely a core bug in the AWS-SDK.

```js
try {
  const s3 = new AWS.S3({}); // of course you put config here
  const data = await s3.upload.promise();
} catch (err) {
  throw err;
}
```

Results in the following:

```log
(node:28391) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: params.Body is required
(node:28391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by niftylettuce** [comment]
cc @LiuJoyceC @MrHubble

**Comment by niftylettuce** [comment]
Also, we can no longer use `s3.upload().promise()` - have to use `s3.upload()` with latest version.

**Comment by jeskew** [comment]
@niftylettuce I believe you're rethrowing the error inside of an async function. SDK constructors do not use promises in any way. Let's keep the discussion to #1650

**Comment by MrHubble** [comment]
One last response and then I'll leave it for you to discuss in https://github.com/aws/aws-sdk-js/issues/1650 as suggested by @jeskew 

@niftylettuce I am using code similar to you and am **not** getting getting an error:

````js
var AWS = require('aws-sdk/dist/aws-sdk-react-native');
AWS.config.update({
  accessKeyId: myKeyId,
  secretAccessKey: mySecretKey,
  region: myRegion
})

var s3 = new AWS.S3()   
var params = {
  Bucket: "mybucket",
  Key: myKeyPrefix,
  Body: myBody,
  ContentType: 'image/png',
  ContentEncoding: 'base64',
  ACL: 'public-read'  
}
let putObjectPromise = await s3.upload(params).promise()
let location = putObjectPromise.Location
````

**Comment by arvi** [comment]
@MrHubble if there is an error in the s3.upload().promise(), how would you handle it on your implementation?

**Comment by bermann** [comment]
@arvi You could use `try` `catch` block

**Comment by OmarKhattab** [comment]
@arvi 
var s3 = new AWS.S3({apiVersion: '2006-03-01', region: 'us-west-2'});
var params = {
  Bucket: 'bucket',
  Key: 'example2.txt',
  Body: 'Uploaded text using the promise-based method!'
};
var putObjectPromise = s3.putObject(params).promise();
putObjectPromise.then(function(data) {
  console.log('Success');
}).catch(function(err) {
  console.log(err);
});

**Comment by chagaspac** [comment]
> @arvi
> 
> ```
> var s3 = new AWS.S3({apiVersion: '2006-03-01', region: 'us-west-2'});
> var params = {
>   Bucket: 'bucket',
>   Key: 'example2.txt',
>   Body: 'Uploaded text using the promise-based method!'
> };
> var putObjectPromise = s3.putObject(params).promise();
> putObjectPromise.then(function(data) {
>   console.log('Success');
> }).catch(function(err) {
>   console.log(err);
> });
> ```

try put await before s3.putObject(..., like this:

var putObjectPromise = await s3.putObject(params).promise();

if you have a parent function, it must be async, otherwise it will not work
