### ISSUE TITLE
Better documentation for AWS.S3.copyObject on updating ContentType

### ISSUE THREAD

**Issue by yvele** [aws/aws-sdk-js#1092]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property

Updating `ContentType` is so confusing as it requires to pass `MetadataDirective` to `REPLACE`

I lost a lot of time to figure out why passing `ContentType` alone doesn't have any effect.
I find out how to do with this answer : https://github.com/aws/aws-sdk-php/issues/717#issuecomment-165298178

I think the doc (not only JavaScriptSDK) should say that ContentType is considered as a metadata and not a simple header.

Summary :
- There is a **Metadata**, a **ContentType** and a  **MetadataDirective** field
- If I only pass a **ContentType** nothing appends.. Not even an error
- Even I don't pass  **Metadata**, I have to pass **MetadataDirective** in order to update **ContentType**
- **ContentType** update does not have the same behaviour as other header (eg ContentEncoding)

**Comment by jlumia** [comment]
@denisw 

Thank you. The MetadataDirective worked perfectly!

**Comment by ArthurRM** [comment]
Similarly it is equally confusing when you just want to upload the metadata and thus pass  MetadataDirective = REPLACE but then you lose the original ContentType if you don't explicitly set it in the copy again.

**Comment by arnulfojr** [comment]
Would be amazing if the docs could be updated to mention what happens if the MetadataDirective is not present and what's the default value? I think is ok as is, just more clear docs would be appreciated :+1:

**Comment by danieljfrith** [comment]
+1, I lost a couple of hours wondering why Content-Disposition was not getting applied. It's been three years, come on

**Comment by leahzxxz** [comment]
+1

**Comment by clintfoster** [comment]
On the broader topic of updating metadata efficiently without copying the object content, I'm looking at this again after a couple of years, and I see there is no information in the S3 User's Guide or the detailed JavaDoc about this seemingly obvious use case. Am I missing something?

Doing a Google search returns a tremendous amount of lore and speculation for different SDKs covering a period of several years, none of which seems definitive.

**Comment by bozerkins** [comment]
+1

**Comment by shakhal** [comment]
+1

**Comment by yidianier** [comment]
> For reference, this is a `copyObject` call that changes the content type of an object:
> 
> ```js
> s3.copyObject({
>   Bucket: bucket,ha
>   Key: key,
>   CopySource: `${bucket}/${key}`,
>   ContentType: newContentType,
>   MetadataDirective: 'REPLACE'
> })
> ```

It works, but ContentType will be added extra property => charset=UTF-8, how to avoid this property, I just want what user rewrite

**Comment by RanVaknin** [comment]
Hi everyone on the thread. 
This is a super old issue but after reviewing the S3 docs I don't see that anything changed.

I have created an internal documentation request with the S3 team (`V1378929322`) asking them to add clarification wrt the use of `ContentType`. 

Since the SDK docs are generated from the each service's API docs, the SDK cannot directly make changes to the CopyObject API docs. 

One thing you can all do is either: 
1. If you have a access to support via the AWS Developer Console, you can create a ticket to S3 and reference the ticket ID mentioned above.
2. Give feedback to the S3 team directly using the `Feedback` button found on the top right corner of each AWS documentation page, or by clicking the link [here](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=S3&topic_url=https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html).

Since this is not actionable by the SDK team, I'm going to go ahead and close this issue.

Thanks again for all of your patience and participation.
Ran~
