### ISSUE TITLE
DynamoDB retryDelayOptions configuration not working, or documentation out-of-sync

### ISSUE THREAD

**Issue by Shadowblazen** [aws/aws-sdk-js#1100]
According to the [documentation here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property), it says for retries that I should be able to use `retryDelayOptions` to either specify a `base` number of milliseconds for exponential backoff, or a `customBackoff` function.

However, when I try to use these configuration options, they don't seem to be working as documented. I'm using aws-sdk v2.5.0 in NodeJS.

Here's how I'm constructing the DynamoDB object in my NodeJS application.

``` javascript
var DynamoDB = require('aws-sdk').DynamoDB;
var dynamoDB = new DynamoDB({
    region: 'us-west-2',
    endpoint: 'http://dynamodb.us-west-2.amazonaws.com',
    maxRetries: 6,
    retryDelayOptions: {
        base: 1000 // I want to use a base of 1000ms in exponential backoff
    },
    logger: {
        // debugging: log what's happening with my requests
        log: function (r) {
            console.log(r);
        }
    }
});
```

As a test, when I call `dynamoDB.putItem()` repeatedly on a table with 1 WCU of throughput and I start getting throttled, what I'm expecting to see is that the 1st retry = 1000ms, the 2nd retry = 2000ms, 3rd retry = 4000ms, etc.

However, what I'm actually seeing doesn't agree with these numbers. I'm seeing data that suggests 1st retry = ~50ms, 2nd retry = ~100ms, 3rd retry = ~200ms, etc. So it seems that the `retryDelayOptions.base` configuration option is not being honored, and is hard-coded to ~50. I also tried to use the `retryDelayOptions.customBackoff` configuration option to specify my own backoff method, but that doesn't seem to work either.

In the codebase, I can see [this commit](https://github.com/aws/aws-sdk-js/commit/c715ca8bfe6da72840409adbf209ea274695b752) where it looks like these configuration options were added to the base `lib/service.js`, but in `lib/services/dynamodb.js` the retry function looks like it's being overridden with a hard-coded base of 50ms, which correlates with the empirical data in my experiments.

It seems like the current behavior and documentation are out-of-sync. Can you please clarify what the expected behavior is?

**Comment by chrisradek** [comment]
Sorry, it looks like that issue was caused due to the way our docs are generated. On the main [Config](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property) page, there is actually a note that this doesn't work with DynamoDB. 

That said, there's no reason we can't have this work for DynamoDB as well.

**Comment by jppellerin** [comment]
+1

**Comment by jppellerin** [comment]
Any word on allowing DynamoDB to define it's `customBackoff`?  The currently implemented (which is forced on us) is greatly flawed as it doesn't take into account any jitter.  Multiple requests that are concurrent will all be retrying at the exact same time.

**Comment by Rhysjc** [comment]
+1

The docs are incredibly misleading since they show the `retryDelayOptions` field in the config object for the DynamoDB service. Seems ridiculous that EVERY service supports this apart from DynamoDB.

**Comment by Shadowblazen** [comment]
Tested and confirmed that the `retryDelayOptions` configuration now works as documented in aws-sdk v2.31.0. This ticket can probably be closed. Thanks!

**Comment by pemagnier** [comment]
This ticket can be closed indeed, i also tried on my side it is now properly working as expected.

However i have a consideration:
Using an exponential backoff algorithm enables us to meet an acceptable rate for our retries, ok. Besides that, DynamoDB only charges for the actually consumed capacities, and the whole bulk of the rejected requests (due to `ProvisionedThroughputExceededException`) is free! And we are not charged neither for the data transfer if we stay in the same region (e.g. a Lambda function requesting DynamoDB in the same datacenter).
Knowing all this, what is wrong doing the following:
```
const dynamodb = new AWS.DynamoDB(
  {
    retryDelayOptions: { customBackoff: retryCount => 1 }
  }
)
```

I know it's a bad practice which looks like a brute-force throttle bypass, but compared to the default configuration we do not lose any money and potentially reduce the request latencies no?
Did i miss something?

Disclaimer: i do not plan to implement this neither encourage you doing so, i just hope that i am missing something and i'd like to ensure that this is not a weakness.

**Comment by ajredniwja** [comment]
Closing this, since the feature was implemented.
