### ISSUE TITLE
no way to use createbucket S3

### ISSUE THREAD

**Issue by Jovons** [aws/aws-sdk-js#1112]
S3 CORS is on a level of bucket. But createbucket aaa is actually a PUT method on /aaa. When it does not exist. the server would reply with a 404 to OPTION (CORS preflight) and does not contain any ACCESS-CONTROL-ALLOWED-ORIGION. And then chrome replies 403 access forbidden. But I realize there is createbucket API in SDK. So what is correct way to call createbucket?

**Comment by LiuJoyceC** [comment]
Hi @Jovons 

Thanks for your question. Currently there is not a way to make calls to S3 from the browser that are not on the level of a bucket, since CORS is configured for individual buckets, not for the entire service. This is a service issue, not an SDK issue. I have contacted the service team about this feature request, but please post on the AWS Forum for S3 to let them know how important this feature is to you, as this helps them prioritize feature requests: https://forums.aws.amazon.com/forum.jspa?forumID=24

One workaround you could try is create an AWS Lambda function that creates the bucket in S3, and you can invoke the Lambda function from the browser, since CORS is fully supported for Lambda. The AWS SDK is automatically included in the Lambda function, so you can make the same SDK calls as you would in the browser, but without the CORS restrictions. Let me know if this works for your use case.

**Comment by Jovons** [comment]
Then why createbucket is in the JSSDK? How is it used?

**Comment by LiuJoyceC** [comment]
Hi @Jovons 
The `createBucket` operation can be used in Node and in any environment that doesn't enforce CORS. The code is shared between the Node SDK and the browser SDK, which is why the operations that don't support CORS are in the SDK. Also, some customers are using the browser SDK in environments that don't enforce CORS, so we cannot simply take those operations out of the browser SDK. We can certainly add a note to the API documentation though.

**Comment by Jovons** [comment]
Thanks! that helps.
