### ISSUE TITLE
Object doesn't support property or method 'fill' (IE10 compatability)

### ISSUE THREAD

**Issue by Masterdanielsan** [aws/aws-sdk-js#1115]
aws-sdk contains an array.fill() call that is not supported in IE10 or older.

I found a solution here:
> http://stackoverflow.com/questions/37729002/object-doesnt-support-property-or-method-fill

by including code for polyfill.js 

>https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Polyfill

before the aws-sdk it no longer throws errors in IE10.  I suggest you add this code so that others do not have to and so that this sdk works for IE10 out of the box.

--- Update ---
It seemed to work for a minute, but now it looks like the fill issue still exists... can I get this confirmed and a bugfix?

**Comment by LiuJoyceC** [comment]
Hi @Masterdanielsan 
Thanks for bringing this to our attention. We'll look into this request.

**Comment by Masterdanielsan** [comment]
Thank you.  I think it should be marked as a bug, unless you can find a workaround.  Polyfills don't seem to be fixing this on my machine.  Can it be confirmed?

**Comment by LiuJoyceC** [comment]
Hi @Masterdanielsan 
Can you point to where in the SDK the array method `fill` is called? After running a search on the entire repository, the only part of the code for which I could find a `.fill` call was code inserted by browserify which called `fill` on the Buffer class (not on an array), but the method is defined by browserify anyway, so it should still be able to run in IE10. Running our tests on IE10 doesn't reveal any errors with `fill` either. What version of the SDK are you using?

Are you getting an error message in IE10 saying that `fill` is not a function? If not, then how are you verifying that it indeed is because of `fill` not being defined? You mentioned in your update that the issue still exists even after you add the polyfill, which shouldn't be the case if that method is causing the issue. Does the error occur anytime you try to load the SDK into the browser, or is it only occurring when you call certain functions or when you work with certain services? Could you provide the exact error message you are seeing? Thanks.

**Comment by Masterdanielsan** [comment]
Sorry it is a buffer.
line #9868 var zeroBuffer = new Buffer(intSize); zeroBuffer.fill(0);

**Comment by LiuJoyceC** [comment]
Hi @Masterdanielsan 

That line is part of browserify's code, and the `fill` method is defined before it gets called. I tested this in IE10 and it works. One simple test you could do to verify that the method is being defined before it gets called: put a breakpoint on the line you just referenced above (of if you want, just simply `console.log` a message), then search for the line `Buffer.prototype.fill =` and put a breakpoint there (or a `console.log`). When you reload the SDK, you should see that the method gets defined before it gets called. Let me know if this is not the case when you try this.

**Comment by Masterdanielsan** [comment]
I placed a console.log('1') on line 9511 and console.log('2') on line 9868

the console shows 

>1 
2 

as would be expected. I really don't know what the issue is.

**Comment by LiuJoyceC** [comment]
Hi @Masterdanielsan 
I was able to replicate this issue when I tested it in IE11 in IE10 mode, and it seems to only be an issue there. This error does not happen in the actual IE10. Also, the error isn't due to the method not being defined, because when inspecting the Buffer class in the debugger, it showed the method as being defined on Buffer.prototype.

This issue has been reported before, and it looks like it's a developer-only issue, since it only happens when IE11 emulates older browsers but does not actually cause a problem in the older versions of the browsers. https://github.com/feross/buffer/issues/121

We can look into updating the version of the `buffer` dependency, but we'll need to test it properly to make sure it does not cause any breaking changes.

**Comment by Masterdanielsan** [comment]
@LiuJoyceC Thank you soooo much for looking into this! I was pulling my hair out trying to figure out how to fix it!!!

Were you able to find any workarounds for this so that the aws sdk can be tested in IE10? That would really help.  Again, thanks a lot!

**Comment by LiuJoyceC** [comment]
Hi @Masterdanielsan 
If you update to the latest version of the SDK (currently v2.6.3), this issue should now be resolved, including in IE10 mode within the IE11 browser. Thanks for opening the issue!

**Comment by Prashant-Gayke** [comment]
Hi,
I solved above issue after un-commentating following lines in src/polyfills.ts

import 'core-js/es6/string';
import 'core-js/es6/array';

**Comment by svnnagesh** [comment]
> There solution given in **polyfill.ts** specific to IE Browser
> Just **un-comment** the imports as shown in snap below
> 
> ![image](https://user-images.githubusercontent.com/10792780/50135755-59307a80-02bb-11e9-8f18-3629a09b4407.png)

Thanks for the help ShujaathKhan.
I got the same issue while running Angular 6 project in IE browser.

Once I uncommented below imports.

import "core-js/es6/symbol";
import "core-js/es6/object";
import "core-js/es6/function";
import "core-js/es6/parse-int";
import "core-js/es6/parse-float";
import "core-js/es6/number";
import "core-js/es6/math";
import "core-js/es6/string";
import "core-js/es6/date";
import "core-js/es6/array";
import "core-js/es6/regexp";
import "core-js/es6/map";
import "core-js/es6/weak-map";
import "core-js/es6/set";


then its is loading fine in IE browser also.
