### ISSUE TITLE
listBucket method gives 403 error whereas CORS has configured already

### ISSUE THREAD

**Issue by zymr-keshav** [aws/aws-sdk-js#1161]
I just want to verify whether my AWS s3  credentials are valid or not? there is no such method to verify and after searching over web  I found a suggestion which says that once you generate s3 object than need to call any method to check, so I have tried AWS S3 [ listBuckets()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listBuckets-property) method
 but it always gives error. whereas other method like `getBucketLocation` is working fine but it need bucket name as param , so I have choose minimal params method 

 below is my code.
```
S3Bucket = new AWS.S3({
                        accessKeyId: id,
                        secretAccessKey: key,
                        region: region
 });

S3Bucket.listBuckets({},function(err, data) {
                        console.log('ListBucket');
                        // console.log(err);
                        if(err) {
                            console.log(err, err.stack);
                            // deferred.reject(err);
                        }
                        else {
                             console.log(data);
                            // deferred.resolve(data);
                        }
                    });

```
in console it gives

> XMLHttpRequest cannot load https://s3.amazonaws.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403

I have configure CORS as below
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
<AllowedOrigin>*</AllowedOrigin>
<AllowedMethod>HEAD</AllowedMethod>
<AllowedMethod>GET</AllowedMethod>
<AllowedMethod>PUT</AllowedMethod>
<AllowedMethod>POST</AllowedMethod>
<AllowedMethod>DELETE</AllowedMethod>
<AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
Why  this error comes than?

**Comment by LiuJoyceC** [comment]
Hi @zymr-keshav 
Certain S3 operations do not support CORS, since CORS must be configured on the bucket level. Operations performed specifically on an already-existing bucket with CORS configured will work, such as `getObject`, `listObjects`, etc. Operations that span buckets or that are performed on currently-non-existent buckets will not work, such as `listBuckets` and `createBucket`. Even if all of your buckets in your account have CORS properly configured, `listBuckets` will not work because it does not access any of the CORS configuration on individual buckets. If you just want to perform a check by calling any method, I recommend you call `headBucket` or `listObjects`, which each only require the bucket name as a param. Also note that you can pre-attach params when you construct the S3 service client so that you don't need to specify params when making operation calls (which can save some work if you are going to make multiple calls with the same service client):
```
S3Bucket = new AWS.S3({
                        accessKeyId: id,
                        secretAccessKey: key,
                        region: region,
                        params: {Bucket: bucket}
 });
```
If you would like S3 to support CORS for non-bucket operations, you can voice your feature request on the AWS Forums for S3: https://forums.aws.amazon.com/forum.jspa?forumID=24

I hope that helps. I will close this issue, as it is not an SDK issue. Thanks!

**Comment by zymr-keshav** [comment]
Thank you for the suggestions. will there any documents where one can check which methods required CORS and which does not?

**Comment by LiuJoyceC** [comment]
That's a great idea! I will work on updating our documentation to show which methods do not support CORS.
