### ISSUE TITLE
v4 signer doesn't refresh credentials before using them

### ISSUE THREAD

**Issue by mutaflux** [aws/aws-sdk-js#1167]
v4 signer in `lib/signers/v4.js`  tries to use the passed credentials object right away without refreshing it:

```
updateForPresigned: function updateForPresigned(credentials, datetime) {
  var credString = this.credentialString(datetime);
  var qs = {
    'X-Amz-Date': datetime,
    'X-Amz-Algorithm': this.algorithm,
    'X-Amz-Credential': credentials.accessKeyId + '/' + credString,
    'X-Amz-Expires': this.request.headers[expiresHeader],
    'X-Amz-SignedHeaders': this.signedHeaders()
  };
```

That makes it impossible to use AWS.TemporaryCredentials or any other expiring AWS.Credentials with the signer.

**Comment by LiuJoyceC** [comment]
Hi @mutaflux 
Are you trying to directly pass expiring credentials into the `updateForPresigned()` method? The entire V4 signer class (and all other signer classes in the SDK), including its methods, are marked as a private API, which means it's only meant to be called internally by the SDK. Tracing back the stack, the only function that calls `updateForPresigned()` is the `addAuthorization()` method in the V4 signer class, which is only invoked by the `SIGN` event listener callback (in `lib/event_listeners.js`), which invokes `service.config.getCredentials()` before invoking `addAuthorization()`. The `getCredentials()` method (in `lib/config.js`) refreshes the credentials if they are expiring. All of the other functions I mentioned that get invoked after it are private, and only get invoked after `getCredentials()` has refreshed the credentials. Users of the SDK are able to successfully use V4 signing in their requests even with expiring credentials, because `getCredentials()` makes sure they are refreshed. What is your use case for directly passing credentials into `updateForPresigned()`?

**Comment by jeskew** [comment]
Closing, as @LiuJoyceC's comment explains why refreshing is handled in `service.config.getCredentials()` rather than directly in the v4 signer. The signer itself is marked private and not designed to be used on its own.
