### ISSUE TITLE
Cloning a AWS.S3 connection object?

### ISSUE THREAD

**Issue by ath88** [aws/aws-sdk-js#1173]
Hello,

I have this issue that I have been struggling with. I would like to take an instance of AWS.S3 (which has a bound bucket name) and bind a different bucket name on there, without altering the original instance. 

What would be the best solution to this problem?

Regards, Asbjørn

**Comment by LiuJoyceC** [comment]
Hi @ath88 
You should just be able to specify the bucket name as a param when you make the request, and it should override the bound bucket name without altering the original instance. I've tried this multiple times and it works:
```
var s3 = new AWS.S3({params: {Bucket: 'bucket1'}});
// this should make a call to 'bucket1'
s3.headBucket(callback);
// this should make a call to 'bucket2'
s3.headBucket({Bucket: 'bucket2'}, callback);
// and since the instance was not altered, this should again go to 'bucket1'
s3.headBucket(callback);
```
Is this not the case for you? If so, which part is not working for you? Is the problem that the bucket name isn't being overridden (second call not going to 'bucket2')? Or is the problem that this is altering your instance (3rd call is going to 'bucket2' instead of back to 'bucket1')? What version of the SDK are you using?

**Comment by ath88** [comment]
Hello @LiuJoyceC,

Thanks for the response! 

Ill explain my case further. We have some functions that expect an s3-instance with a bound bucket. They can have the interface `uploadObject(s3, callback)`. This is 'nicer' than having to pass both an s3-instance and a bucket name; `uploadObject(s3, bucketName, callback)`. 

Ill try to make a short example:

``` javascript
var s3 = aws.S3({ params: { Bucket: "red-fruits" } });
var uploadAppleToRedFruitsBucket = () => uploadApple(s3);

s3.config.params.Bucket = "sweet-fruits";
var uploadAppleToSweetFruitsBucket = () => uploadApple(s3);

uploadAppleToRedFruitsBucket();
uploadAppleToSweetFruitsBucket();

function uploadApple(s3) {
    s3.upload({ Body: "red-and-sweet-apple" });
}
```

It is a very contrived example, I know. Summa summarum; the upload would only go to one bucket. Imagine the function is way more elaborate, and the s3-instance is initiated somewhere else. I would like something like:

``` javascript
var s3 = aws.S3({ params: { Bucket: "red-fruits" } });
var uploadAppleToRedFruitsBucket = () => uploadApple(s3);

var s3Clone = s3.clone();
s3Clone.config.params.Bucket = "sweet-fruits";
var uploadAppleToSweetFruitsBucket = () => uploadApple(s3Clone);

uploadAppleToRedFruitsBucket();
uploadAppleToSweetFruitsBucket();

function uploadApple(s3) {
    s3.upload({ Body: "red-and-sweet-apple" });
}
```

Does this make any sense at all?

**Comment by LiuJoyceC** [comment]
Hi @ath88 
The first code example you provided is not programmatically possible in its current form (at least for achieving what you described), since when you call `uploadApple(s3)`, neither `uploadApple()` nor `s3` has any way of knowing which function (`uploadAppleToRedFruitsBasket()` or `uploadAppleToSweetFruitsBasket`) invoked it, and so it cannot change its params accordingly. No change can be made in the SDK that can make the first code example work. However, you can tweak the code example to make it do what you want without having to clone a new `s3` object. The easiest way I believe is:
```
var s3 = aws.S3();
var uploadAppleToRedFruitsBucket = () => uploadApple(s3, "red-fruits");

var uploadAppleToSweetFruitsBucket = () => uploadApple(s3, "sweet-fruits");

uploadAppleToRedFruitsBucket();
uploadAppleToSweetFruitsBucket();

function uploadApple(s3, bucketName) {
    s3.upload({ Body: "red-and-sweet-apple", Bucket: bucketName }); // don't forget the callback!
}
```
If you would rather not have to pass a the bucket name into `uploadApple()`, you could do:
```
var s3 = aws.S3({ params: { } });
var uploadAppleToRedFruitsBucket = () => {
    s3.config.params.Bucket = "red-fruits";
    uploadApple(s3);
}

var uploadAppleToSweetFruitsBucket = () => {
    s3.config.params.Bucket = "sweet-fruits";
    uploadApple(s3);
}

uploadAppleToRedFruitsBucket();
uploadAppleToSweetFruitsBucket();

function uploadApple(s3) {
    s3.upload({ Body: "red-and-sweet-apple" }); // again, don't forget the callback!
}
```
In my opinion, the first one I suggested is cleaner and uses a more appropriate functional design than the second one, but if not passing a bucket name into `uploadApple()` is important to you, then the second one will work.

Does that help?

**Comment by ath88** [comment]
@LiuJoyceC That is exactly my point. :) In my first example, the s3 instance params is changed in-place, and thus, an upload only happens to the final bucket. 

As I originally mentioned, I would love to have my function be completely agnostic about bucket-names. Passing one variable and not having to specify the bucket name every time seems cleaner to me. :) Your first example does exactly what I would like to not have the function do.

Your second code-example is not certain to work, since an asynchronous functions could change the bucket-name just after another function set it, but before the other got to actually use it (depending on when the execution is yielded, which I am not familiar enough with NodeJS to be certain of).

My current hack , which actually works, looks like this:

``` javascript
var s3 = aws.S3({ params: { Bucket: "red-fruits" } });
var uploadAppleToRedFruitsBucket = () => uploadApple(s3);

var cloneConfig = { 
    accessKeyId: s3.config.accessKeyId, 
    secretAccessKey: s3.config.secretAccessKey,
    params: { Bucket: "sweet-fruits" }
};
var s3Clone = new aws.S3(cloneConfig);
var uploadAppleToSweetFruitsBucket = () => uploadApple(s3Clone);

uploadAppleToRedFruitsBucket();
uploadAppleToSweetFruitsBucket();

function uploadApple(s3) {
    s3.upload({ Body: "red-and-sweet-apple" });
}
```

Here, I manually have to extract the parts of the config that I want to use. I don't really like this copying of internal stuff. Besides, there could be other configuration parameters that I should copy too.

And yes, Key and callback are needed, I just left them out for brevity. :)

**Comment by LiuJoyceC** [comment]
Hi @ath88 
Your first code example (without modifications) is just simply not possible in JavaScript, and it's not due to any limitation of the SDK, so no change in the SDK can make it possible. Neither `uploadApple()` nor `s3` is able to know which function invoked it, and if you modify `s3` outside of the two functions rather than in the functions, then it has no way of knowing which of the two functions is going to get invoked next and will just stay in its modified state (if you don't modify it inside the function, `s3` is not going to modify itself depending on which function gets invoked). It doesn't matter if one function is defined after the modification, as both functions are still referring to the same object in memory (and the reason that your current hack works is because the two functions are referring to different objects in memory). You can see the same thing outside of the context of the SDK with this example:
```
var obj = {hello: 'world'};
var func1 = () => finalfunction(obj);

obj.hello = 'everyone';
var func2 = () => finalfunction(obj);

func1(); // 'everyone'
func2(); 'everyone'

function finalfunction(obj) {
    console.log(obj.hello);
}
```
If you want `uploadApple(s3)` to have different behavior (in this case, upload to different buckets), then `uploadApple()` and `s3` cannot both be agnostic to which bucket needs to be used. And the only way `s3` knows which bucket to use before being passed into `uploadApple()` is if the function that invokes `uploadApple()` modifies `s3`. The way your first code example is set up, `uploadAppleToRedFruitsBasket` and `uploadAppleToSweetFruitsBasket` are ALSO agnostic to the bucket name (in fact, they are identical copies of the same function, just with different function names, so invoking them will have identical behavior). It doesn't make a difference where the functions are defined.

You're right that you should always be careful with depending on mutable arguments when dealing with asynchronous code, because of the race conditions caused by uncertainty of when the argument may get modified by other competing functions. This is why I prefer my first example over my second, because it's a more functional approach (and since we expect `uploadApple()` to have different behavior, I don't believe it should be agnostic to the parameter that determines the behavior). However, in this particular case, the second example also works because I know that `s3.upload()` copies the params onto the request (synchronously) before signing and sending the request. (You would have to be careful if any of the params were mutable objects).

I hope that helps :) Let me know if you have additional questions.

**Comment by ath88** [comment]
Hello again @LiuJoyceC,

I know the first example wont work, as I wrote; "the upload would only go to one bucket". I fully acknowledge that it will not work, and that the SDK can't handle such an abuse of javascript objects. 

You wrote:
> and the reason that your current hack works is because the two functions are referring to different objects in memory
.. which is exactly my point. I would love to have some supported way to make another object in memory, a clone, which uses the same config as the original one, but I can bind new `params`onto.

I am not certain how I can explain it any further. This is essentially a feature request, unless there's another way to make this 'different object in memory'. Which was what my original enquiry was about. :)

In Perl, we have this 'clone' method on a PostgreSQL connection object; http://search.cpan.org/~timb/DBI-1.636/DBI.pm#clone

**Comment by LiuJoyceC** [comment]
I see, thanks for clarifying.
You can currently copy the config of a service client object by passing the config into the constructor:
```
var s3 = aws.S3({ params: { Bucket: "red-fruits" } });
var s3Clone = new aws.S3(s3.config);
s3Clone.config.params = {Bucket: "sweet-fruits"};
```
The S3 constructor function will shallowly copy the object you pass to the config of the new instance. (Note that since it's only a shallow copy, you'll have to assign `s3Clone.config.params` to a new object rather than directly modifying `s3Clone.config.params.Bucket`.)
Is that the functionality you're looking for? Thanks.

**Comment by ath88** [comment]
That works, yes. Thank you! 

A clone-function would only be a convenience, then. :) It would let me not `require` the aws-sdk in places where I want to clone.

**Comment by LiuJoyceC** [comment]
Hi @ath88 
I'm glad to hear this works for your use case :)
If you already have access to `s3` but not `aws` and would not like to require the aws-sdk, you could do:
```
var s3Clone = new s3.constructor.__super__(s3.config);
s3Clone.config.params = {Bucket: "sweet-fruits"};
```
Cheers!

**Comment by ath88** [comment]
Good idea. :) Thanks!
