### ISSUE TITLE
Creating cognito userpool with custom message lambda trigger doesn't work

### ISSUE THREAD

**Issue by bedorlan** [aws/aws-sdk-js#1177]
Hello. I'm creating the following resources from nodejs, using the aws-sdk:

1. createFunction
2. createUserPool
3. createUserPoolClient

I associate the lambda function just created, to the userpool custom message lambda trigger, when creating the pool using aws-sdk.

When i tried to signUp a new user, i got the following error:

`Error: Exception when invoking lambda arn: arn:aws:lambda:us-west-2:379027740392:function:dev_cognito_custom-message(…)`

![1](https://cloud.githubusercontent.com/assets/4246233/19292033/b2cb422a-8fde-11e6-96c9-0d674d995a67.png)

When i enter into the aws console, and then reset the customMessage trigger (i put it in "None", then i put it the lambda function again), the user signUp starts to work correctly.

1. aws console status
![2](https://cloud.githubusercontent.com/assets/4246233/19292071/07fff556-8fdf-11e6-85e0-cd0b1949cd39.png)

2. Putting the trigger in None (and save)
![3](https://cloud.githubusercontent.com/assets/4246233/19292077/117a320e-8fdf-11e6-9aa0-9ef326dc9726.png)

3. Putting the trigger again in the old value (and save)
![4](https://cloud.githubusercontent.com/assets/4246233/19292083/1cb0f626-8fdf-11e6-9d78-3ec65c1d3d1d.png)

4. Now works!
![5](https://cloud.githubusercontent.com/assets/4246233/19292085/201de81e-8fdf-11e6-9bc7-67e81f161838.png)

Gladly i will provide more info

**Comment by chetanme** [comment]
This is expected because Cognito console, in addition to saving the pool with lambda trigger, adds permissions to your Lambda functions which allows Cognito service to invoke your function. When you associate a lambda function to user pool from CLI or any other SDK, you also need allow Cognito to invoke the trigger.

Call Lambda's [AddPermission](http://docs.aws.amazon.com/lambda/latest/dg/API_AddPermission.html) API with appropriate parameters. Here `SourceArn` should be your user pool ARN and `Principal` should be `cognito-idp.amazonaws.com`. You can use [GetPolicy](http://docs.aws.amazon.com/lambda/latest/dg/API_GetPolicy.html) to see a sample policy on a function which you use through Cognito console. Hope this solves your problem.

**Comment by bedorlan** [comment]
Thank you @chetanme 

How can i get the userpool arn, from the CLI?
I can't find how, in the api reference.

**Comment by chetanme** [comment]
Currently none of the APIs return the ARN value but it is a well known format which you can make yourself.

`arn:aws:cognito-idp:<your Cognito region>:<your AWS account id>:userpool/<your user pool id>`

**Comment by bedorlan** [comment]
@chetanme yes. it's working now! thanks
