### ISSUE TITLE
WebIdentityCredentials with Webpack

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-js#1178]
Hi there,

I've read http://blogs.aws.amazon.com/javascript/post/Tx2DL9CBUQFBC9L/Using-webpack-and-the-AWS-SDK-for-JavaScript-to-Create-and-Bundle-an-Application but I still have a couple of questions how to use **AWS.WebIdentityCredentials**.

So firstly I am wary that aws-sdk-2.1.12.min.js is 256K, but my bundles are 1.8MB with `require('aws-sdk/dist/aws-sdk');` which is a bit alarming.

Consider my source here:

https://static.spuul.com/devops/2016-10-12/app.js
https://static.spuul.com/devops/2016-10-12/webpack.config.js

It doesn't bundle in the code correctly. What am I missing?

Sidenote: Where is it documented that `aws-sdk/clients/s3` is that path for the S3 parts?

**Comment by chrisradek** [comment]
@kaihendry 
You need to remove `noParse: /aws-sdk/,` from your webpack.config.js file. That line is telling webpack to pull in the file referenced in your code (`aws-sdk/clients/s3` and `aws-sdk/global`), but to ignore anything that those files depend on.

We're actively working on improving our docs, and will include a section on using webpack as well. To require an individual service, you can require it by referencing the service using the service's class name, all lowercase:
`require('aws-sdk/clients/servicename')`

One sidenote, in your app.js, you are importing `S3`, so you don't have to access it via `AWS.S3`. `AWS.S3` will still work since the sdk adds the service constructor to the AWS namespace when it is required.

**Comment by kaihendry** [comment]
Thank you Chris.

```
import 'aws-sdk/global'
import 'aws-sdk/clients/s3'
```

Works great.
