### ISSUE TITLE
Multipart upload initiated with putObject is aborted

### ISSUE THREAD

**Issue by misterfresh** [aws/aws-sdk-js#1180]
I'm using this sdk in the browser.

I use the putObject method to upload files to S3. The user is authenticated with a temporary token generated server side, and is allowed to putObject in a specific folder on the bucket.

When the file is under 5MB, it works fine. When the file is over 5MB, the AbortMultiupload  method is called after the first chunk fails.

Can't find anything on stackoverflow about this problem. Any idea what could cause it and how to fix it?

**Comment by LiuJoyceC** [comment]
Hi @misterfresh 
Are you using `putObject` for files over 5MB as well? `putObject` is not used to initiate multipart uploads. You will have to initiate that with `createMultipartUpload`, and then subsequent calls to `uploadPart` before completing it with `completeMultipartUpload`. I recommend using the managed uploader in the SDK (call the `upload` operation instead of `putObject`). This will handle uploads for both small and large files, and will abstract away the complexity of multipart uploads so you don't have to call the individual operations needed. See http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

Let me know if that resolves your issue. Thanks.

**Comment by misterfresh** [comment]
Thanks, will try that tomorrow and will let you know how it goes.

2016-10-12 22:45 GMT+02:00 Joyce Liu <notifications@github.com>:

**Comment by misterfresh** [comment]
Actually I was already using the "upload" method, and the problem was "No access to ETag property on response. Check CORS configuration". Solved it with adding "`<ExposeHeader>ETag</ExposeHeader>`" in bucket CORS configuration. Thanks ! Closing this now.

**Comment by LiuJoyceC** [comment]
I'm glad to hear your issue is resolved!
