### ISSUE TITLE
module initialization error @ new aws.EC2({..})

### ISSUE THREAD

**Issue by decoursin** [aws/aws-sdk-js#1191]
We're suddenly getting an error in our Lambda function. Our file named createMatchingLambda.js, suddenly starting to blow up without changing anything.

Here's our stacktrace:
> module initialization error: Error
> at getLatestServiceVersion (/var/task/node_modules/aws-sdk/lib/service.js:129:11)
> at getLatestServiceClass (/var/task/node_modules/aws-sdk/lib/service.js:89:20)
> at loadServiceClass (/var/task/node_modules/aws-sdk/lib/service.js:81:19)
> at Service (/var/task/node_modules/aws-sdk/lib/service.js:27:29)
> at new features.constructor (/var/task/node_modules/aws-sdk/lib/util.js:585:24)
> at Object.<anonymous> (/var/task/createMatchingLambda.js:6:11)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Module.require (module.js:364:17)
> at require (module.js:380:17)

 Here's our first 8 lines of that createMatchingLambda.js:
```
1: console.log('Loading function');
2: 
3: var aws = require('aws-sdk-promise'); // Identical to AWS SDK except for promise support
4: var Promise = require('bluebird');
5: var s3 = new aws.S3({ apiVersion: '2006-03-01' });
6: var ec2 = new aws.EC2({ apiVersion: '2015-10-01' });
7:
8:
```

Since the stacktrace points to you and we didn't change our lambda function, we think the problem is somewhere in this ec2 library.

**Comment by chrisradek** [comment]
@decoursin 
Thanks for reporting the issue. There was a bug that was fixed in v2.6.5 of the SDK, where for some services, specifying an old apiVersion would break when a new one was introduced, but was backwards compatible with the existing versions.

To work-around this, you can specify an EC2 apiVersion of `2016-04-01`, which was the latest version in version 2.6.3 of the SDK, the version currently deployed to Lambda:
https://github.com/aws/aws-sdk-js/tree/v2.6.3/apis

Lambda is aware of the issue, but I don't know their current plans on updating the SDK.

**Comment by chrisradek** [comment]
Closing since this issue is already fixed in the SDK.

**Comment by decoursin** [comment]
Thank you very much!
