### ISSUE TITLE
IN operator won't work with array variable in FilterExpression?

### ISSUE THREAD

**Issue by nirmalgoswami** [aws/aws-sdk-js#1201]
```
var params = {
        TableName: "User",
        IndexName:"a-b-index",
        KeyConditionExpression: "Country = :country and #s = :status",
        FilterExpression: "Id IN (:e)",
        ExpressionAttributeValues: {
          ":country ": "USA",
          ":status": 1,
          ":e": ["1","2","3"]

        },
        ExpressionAttributeNames: {"#s": "Status"}
      };

      //get users
      dynamodb.query(params, function (err, data) {
        if (err)
          //error
        else {
          //success

        }
       });
```

above query run fine but i am not getting records if i change from `":e": ["1","2","3"]` to `":e": 1` i am getting records but i want to use array

**Comment by chrisradek** [comment]
@nirmalgoswami 
It looks like using when using `IN` in the `FilterExpression`, you need to provide `ExpressionAttributeValues` individually.

For example, I could update your params like this:
```javascript
var params = {
        TableName: "User",
        IndexName:"a-b-index",
        KeyConditionExpression: "Country = :country and #s = :status",
        FilterExpression: "Id IN (:a, :b, :c)",
        ExpressionAttributeValues: {
          ":country ": "USA",
          ":status": 1,
          ":a": "1",
          ":b": "2",
          ":c": "3"
        },
        ExpressionAttributeNames: {"#s": "Status"}
      };
```
I'm assuming that when you were attempting to pass the array of values before, it was trying to compare `Id` to the string `[1, 2, 3]` instead of treating `:e` as three separate values, but that's a better question for the [DynamoDB](https://forums.aws.amazon.com/forum.jspa?forumID=131) team.
