### ISSUE TITLE
cyclometric dependency issue for endpoint in s3 bucket

### ISSUE THREAD

**Issue by zymr-keshav** [aws/aws-sdk-js#1227]
I am using _aws.sdk.js v 2.7.1_ in browser ( javascript). With  reference from  [ AWS documentation ](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html)  I came to know that

if a bucket is created in *US-standard* region means in _US East (N. Virginia)_  than either it does not require any endpoint or endpoint must be `"https://s3.amazonaws.com/"` 

BUT if a bucket is in any other region than it must requires endpoint as either In a _path-style_ URL 
 `http://s3-{region}.amazonaws.com/{bucket} ` or   _virtual-hosted–style_ URL `http://{bucket}.s3-{region}.amazonaws.com`

so my query is how do I create a valid s3 object to call method [`getBucketLocation` ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property) to check the bucket location but it requires `s3` object and s3 object fail to create if `endpoint` param does not match with given bucket?

Steps to reproduce the issue.
---
created 2 buckets from aws console with valid CORS configuration 

1. *just-another-bucket* in US-standard region 
2. *just-another-bucket-us-west-2* in oregon region 

### without endpoint params 
Now below method to create S3 object  and call a method of S3 

```
s3 = new AWS.S3({
                apiVersion: '2006-03-01',
                accessKeyId: resource.accessid,
                secretAccessKey: resource.accesskey,
});

var params = { Bucket: resource.bucket };
s3.getBucketLocation(params).promise();

```

1) works fine for *just-another-bucket* 

1) failed for *just-another-bucket-us-west-2*  and gives status 307 with below error

 > XMLHttpRequest cannot load https://just-another-bucket-us-west-2.s3.amazonaws.com/?location. Response for preflight is invalid (redirect)

### with endpoint params 

as _path-style URL_ ==> **s3-{region}.amazonaws.com/{bucket}**
```
s3 = new AWS.S3({
                apiVersion: '2006-03-01',
                accessKeyId: resource.accessid,
                secretAccessKey: resource.accesskey,
                endpoint: "https://s3-" + region + ".amazonaws.com/" + resource.bucket
});

var params = { Bucket: resource.bucket };

s3.getBucketLocation(params).promise();

```

1) failed for *just-another-bucket* and status is 301 with 2 different kind of response

 - if `region = 'us-east-1'`  than it gives below error

 > OPTIONS https://just-another-bucket.s3-us-east-1.amazonaws.com/just-another-bucket?location net::ERR_NAME_NOT_RESOLVED

 - for any other region it gives below error

 > XMLHttpRequest cannot load https://just-another-bucket.s3-<region>.amazonaws.com/just-another-bucket?location. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

2) works fine for *just-another-bucket-us-west-2*  with any other `region`  except _us-east-1_

and if I set `endpoint : "https://s3.amazonaws.com/"`  than above result reversed.

**Comment by chrisradek** [comment]
@zymr-keshav 
Can you share your CORS configuration for your buckets?

Here's some background on what's happening with S3:

- If no region is defined in `AWS.config` or passed into the `S3` constructor, then S3 will use `us-east-1` by default. This is special for S3.
- It is not necessary to build an endpoint yourself. If you instantiate the `S3` service with the same region that your bucket is in, the SDK will figure out the endpoint on its own.

It also looks like you are providing a `bucket endpoint`, not the endpoint to the service. If that's intentional, you should also be setting the [`s3BucketEndpoint`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3BucketEndpoint-property) config option you pass into the S3 constructor to true.

I did run a test in Firefox where my S3 client was configured to use `us-east-1`, and I called `s3.getBucketLocation` on a bucket in `us-west-2` and was able to get a correct response. I did not specify an endpoint, and the SDK does attempt to automatically redirect when it can.

**Comment by zymr-keshav** [comment]
thank you for the response, below is my CORS configuration of my buckets

```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

 - and yes I have set `s3BucketEndpoint: true` in S3 constructor as well and tried the same but same error .

 - SDK respose the correct output for other region bucket when the bucket is old means not just created. I have tried with old bucket and it works fine but not working with newly created bucket.

- and how can we use `AWS.config` into S3 contructor in javascript method?

**Comment by zymr-keshav** [comment]
and now facing strange issue. it's not working  in **with** or **without endpoint** both case.

**Comment by srchase** [comment]
Create bucket operations are eventually consistent, as shown by getting the correct output on older buckets.  If it's possible, you can use regionalized endpoints instead of making calls to retrieve that location.

**Comment by DavyCode** [comment]
I am using AWS sdk for uploads, after spending some time searching online i stumbled upon this thread. thanks to @lsimoneau [45581857](https://github.com/component/s3/issues/7#issuecomment-45581857) its turns out the exact same thing was happening. I simply pointed my request Url to the region on my bucket by attaching the region property and it worked.

const s3 = new AWS.S3({
  accessKeyId: config.awsAccessKeyID,
  secretAccessKey: config.awsSecretAccessKey,
  region: 'eu-west-2'  // add region here
});
