### ISSUE TITLE
package name conflict with npm:aws-sdk

### ISSUE THREAD

**Issue by AckerApple** [aws/aws-sdk-js#1273]
GOAL: npm install both aws-sdk-js and aws-sdk inside one npm package.json file

ISSUE: the package.json name of aws-sdk-js is actually aws-sdk which causes undeterminable require() functionality when both aws-sdk-js and aws-sdk are installed using npm install.

My team has found it useful to have both a NodeJs and a web browser version of the aws-sdk under one package. 

We want to use Webpack to bundle aws-sdk-js code and NodeJs to require('aws-sdk'). We have accomplished our goal using JSPM which makes separate package references that do not collide with the npm package name dependencies.

> Please rename the package.json name from "aws-sdk" to "aws-sdk-js".

If this request is disagreed with or is a duplicate, please feel free to close. We are not committed to this issue, we got around it.

Our package, that supports both NodeJs and a web browser, is here: https://www.npmjs.com/package/ack-aws-s3-universal

**Comment by saadtazi** [comment]
Maybe I misunderstood your request, but after looking that your [package.json file](https://github.com/AckerApple/ack-aws-s3-universal/blob/master/package.json#L66-L71), it looks like you are loading [`aws-sdk` from npm](https://www.npmjs.com/package/aws-sdk) and `aws-sdk-js` from github... But `aws-sdk-js` is just the repo for `aws-sdk` npm package ( = `aws-sdk-js` *is* `aws-sdk`): check repo link in npm `aws-sdk` package page.

Why so you want to load twice the same package (once in a dep, once as devdep)? Why don't you use only `aws-sdk` package (as a dep)? Is it because you want to eventually have different versions for nodejs and web browser? If that's the case, then you might find [this npm](https://github.com/npm/npm/issues/5499#issuecomment-71089080) issue interesting.

**Comment by AckerApple** [comment]
Ahhhhhhhhh haaaaaaaaaaa, you are so extra right. We missed that all important detail that the npm aws-sdk actually points to the GITHUB aws-sdk-js. We've gotten so wrapped up in making KmsParams work with S3 bucket transfers, which took [another package](https://www.npmjs.com/package/node-s3-encryption-client) to get involved, that we thought we needed two AWS packages (one for NodeJs and another for Browser)...... Yeah, your reply greatly reduces the complexity we've created... Well thank you kindly.

I will close this issue. Perhaps it could be considered, in the future, to GITHUB name as NPM package name to prevent future confusion. Otherwise all is well and thank you kindly for your reply.

**Comment by saadtazi** [comment]
FYI:

> Perhaps it could be considered, in the future, to GITHUB name as NPM package name to prevent future confusion.

For companies that offer sdks for multiple languages (like amazon aws), it make sense to postfix their sdk repo names with the language (`aws-sdk-js`, `aws-sdk-java`). But having the language name in the [package name is not a good practice](https://docs.npmjs.com/files/package.json), at least with npm.

> Don't put "js" or "node" in the name
