### ISSUE TITLE
[InvalidParameterException: Invalid attributes given, name is missing] when calling cognitoidentityserviceprovider.adminRespondToAuthChallenge

### ISSUE THREAD

**Issue by Ballhorn** [aws/aws-sdk-js#1290]
Hi,

I get InvalidParameterException: Invalid attributes given, name is missing error when calling adminRespondToAuthChallenge function with following parameters:
`{ 
	ClientId: '*********',
	UserPoolId: 'eu-west-1_*******',
	ChallengeName: 'NEW_PASSWORD_REQUIRED',
	Session: '*******' /* Session string from calling adminInitiateAuth */,
	ChallengeResponses: { 
		requiredAttributes: '["userAttributes.family_name","userAttributes.name"]' /* From ChallengeParameters */,
		userAttributes: '{"name":"*****","family_name":"******","email":"*****@******"}', /* From ChallengeParameters with name and family_name added*/,
		NEW_PASSWORD: '********',
		USERNAME: '******@******'
	}
}`

The problem seems to be in required attributes and how they should be represented in parameters. I have name, family_name and email as required attributes in my Cognito user pool.

How should required attributes be set in parameters when calling adminRespondToAuthChallenge?

**Comment by chrisradek** [comment]
@Ballhorn 
Since this issue is pertaining to how a specific service API should work, you'll get a better response asking on the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0).

If you post there, feel free to reply with the link here and I can forward the post to that team as well.

There is another SDK built on top of this one that makes working with Cogntio User Pools easier:
https://github.com/aws/amazon-cognito-identity-js

Taking a look at their code:
https://github.com/aws/amazon-cognito-identity-js/blob/4a1bea0501fd8e90d1e57563672b7d9993da6de5/src/CognitoUser.js#L244-L248
It looks like that SDK is removing the `userAttributesPrefix`, which is [`userAttributes.`](https://github.com/aws/amazon-cognito-identity-js/blob/4a1bea0501fd8e90d1e57563672b7d9993da6de5/src/AuthenticationHelper.js#L38), from each of the elements in `requiredAttributes`. It might be worth giving that a shot in your code as well, but I'm not too familiar with how this API works.

**Comment by Ballhorn** [comment]
Thanks for the link. I got it working after taking more closer look to the code!

The prefix isn't removed but rebuilt as a string. This means that each `userAttributes.attribute` must be changed to `'userAttributes.attribute'`.

My ChallengeResponsesare now in form:

`{ 'userAttributes.name': '******', 'userAttributes.family_name': '********', 'userAttributes.email': '*****@*****', NEW_PASSWORD: '*********', USERNAME: '*****@*****' }`

**Comment by chrisradek** [comment]
Awesome, thanks for sharing how you fixed it as well!
