### ISSUE TITLE
AWS.S3.upload throws a unhandled error when file is missing

### ISSUE THREAD

**Issue by surfdude75** [aws/aws-sdk-js#1330]
The code bellow is set to get the errors but it stops due unhandled error

var fs = require('fs');
var AWS = require('aws-sdk');

var s3 = new AWS.S3({
  accessKeyId: 'myid',
  secretAccessKey: 'mysecret'
});

var callback = function(err) {
  if (err) return console.log('err:',err.message);
}

var file = '/missing.txt';

var body = fs.createReadStream(file);
body.on('err',callback);
try {
  s3.putObject({
    Bucket: 'my-bucket',
    Key: 'missing.txt',
    Body: body
  }, callback);
} catch (err) {
  callback(err);
}

**Comment by chrisradek** [comment]
@surfdude75 
You should be listening to the [`error`](https://nodejs.org/api/stream.html#stream_event_error_1) event on your readable stream to catch errors on the stream. The `try/catch` shouldn't catch any errors in this example since operations are asynchronous.

If you still get an error after making the above changes, can you share what your full error is?

**Comment by surfdude75** [comment]
sorry it was a typo err by error
