### ISSUE TITLE
Executing queries on RedShift

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-js#1354]
I'm looking at the redshift apis available via aws-sdk, I don't see anything for executing queries to execute against redshift?

There's a trigger on s3 object create on my Lambda function, I want to load that into AWS RedShfit via COPY public.my_table FROM s3://....

1. I don't want to store DB credentials into my Lambda function
2. I want to run the specified query above

I've already exhausted the search and documentation available around this.

**Comment by jeskew** [comment]
Hi @BardiaAfshin,

Unfortunately, Redshift doesn't expose any data-plane functionality through their API but instead is accessed like a traditional database using tools like ODBC. Lambda supports delivering sensitive data to functions via [encrypted environment variables](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html), so that might be a way to get the DB credentials to your function.

You can communicate this feature request directly to the Redshift team via [their AWS forum](https://forums.aws.amazon.com/forum.jspa?forumID=155), and they might have a few ideas to support your use case beyond Lambda environment variables.
