### ISSUE TITLE
How to update a ECS service with autoscaling?

### ISSUE THREAD

**Issue by etsangsplk** [aws/aws-sdk-js#1364]
If a EC2 instances already setup with autoscaling group with metrics and alarms, how can to add autoscaling group for ECS based on existing alarms or new alarms inside container (possible)?
It is not clear hot to do it from documentation.

**Comment by jeskew** [comment]
Hi @etsangsplk,

Could you post this as a feature request in the [ECS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=187)? That's the best way to get a feature request in front of a service team. Please update this issue with a link to the forum question so that anyone who lands on this issue from a Google search can follow the discussion.
