### ISSUE TITLE
Cannot Send SMS to Valid Number

### ISSUE THREAD

**Issue by asplogic** [aws/aws-sdk-js#1368]
Error Message:
==========
[InvalidParameter: Invalid parameter: PhoneNumber Reason: +166XXXXX085 is not valid to publish to]
message: 'Invalid parameter: PhoneNumber Reason: +166XXXXX085 is not valid to publish to',
code: 'InvalidParameter',

Code to Send:
===========

const params = {
      Message: message,
      MessageStructure: 'string',
      PhoneNumber: "+166XXXXX085"
    };
    sns.publish(params, function(err, data) {
      if (err) {
        console.log(">>> serror sending sms:", err);
        reject(err);
      } else {
        resolve({phone: phone});
      }
    });

Configuration
==========
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource: "*"

**Comment by asplogic** [comment]
I tried the same number using twilio without changing the number and it worked.  I also tried a different number but failed on aws.  I would like to use the aws since i dont have to manage another account.

**Comment by jeskew** [comment]
Hi @asplogic,

The InvalidParameter error is coming from the service, so the best place to get help on this issue would be the [AWS SNS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=72) or on StackOverflow. Since you would encounter the same issue in any SDK or when using the REST API, it's best to keep the discussion to a forum where your question and the answer are visible to any developers using SNS, not just JavaScript developers.
