### ISSUE TITLE
When AWS is down, JSON parser breaks...

### ISSUE THREAD

**Issue by simonbooth** [aws/aws-sdk-js#1379]
protocol/json.js should check the htttp status code and/or content-type before attempting to parse the result.
Current AWS outage in US East causing 
```
 statusCode :503 
<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
```

**Comment by jeskew** [comment]
Services using the JSON protocol also return their errors in JSON format, which is why the SDK attempts to parse 400- & 500-level responses.

Would it help if the SDK surfaced an explicit "unable to parse JSON" error in such cases?

**Comment by spencerhakim** [comment]
I think it'd make more sense to just return an error based on the HTTP code in this situation. "Service Unavailable" is far more relevant than "Unable to parse JSON"; especially for a service like DynamoDB, this would probably lead me to believe that my data is somehow corrupt rather than it simply being an issue with AWS.
