### ISSUE TITLE
getSingnedUrl('getObject', params) some times return s3.amazonaws.com, sometimes s3-us-west-1.amazonaws.com

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1381]
I had a problem with get download url function. Here is my code: 
var options = {
  apiVersion: config.s3_api_version, //'2006-03-01',
  accessKeyId: config.s3_accessKeyId,
  secretAccessKey: config.s3_secretAccessKey,
  signatureVersion: 'v4',
  sslEnabled: true,
  endpoint: process.env.S3_ENDPOINT   //config.s3_endpoint
};

s3 = new AWS.S3(options);

var params = {
        Bucket: config.bucket,
        Key: object_id,
        Expires:config.s3_url_timeout  // seconds
    };

s3.getSignedUrl('getObject', params, function(err, data) { });

It almost always return url with s3-us-west-1.amazonaws.com format and download file is OK. 

But this afternoon, download return 400 error, I checked the log and it return s3.amazonaws.com and the SSL connection had an alert 21. 

Since I do not specify any region info(I do not know since bucket was created by some admin). why s3.amazonaws.com return error?

Thanks,

**Comment by chrisradek** [comment]
@testtshoretel 
The URL generated should take the region or endpoint into account. If a region was defined using the AWS_REGION environment variable, or your endpoint changed (via the S3_ENDPOINT environment variable in this case), you would expect the url to change as well.

By default, if no region is provided to S3, it will use `us-east-1`. `us-east-1` is a special case in that it currently uses the `s3.amazonaws.com` endpoint.

It's always a good idea to set the region to be the same region as where your bucket is located, especially when using signatureVersion `v4` as well.

**Comment by testtshoretel** [comment]
@chrisradek Thanks for the quick response. I will try s3.getBucketLocation. But I still have questions: 
1. Why sometime getSighUrl return region and sometimes not? 
2. Why s3.amazonaws.com have ssl connection allert?

Thanks!

**Comment by chrisradek** [comment]
@testtshoretel 
1) This depends entirely on how you've configured your S3 client. `getSignedUrl` does not make any network calls to S3, so depending on how you've configured your `region` or `endpoint`, the region may change.
2) If urls with `s3.amazonaws.com` were failing with connection alerts, that was likely due to the issues with S3 yesterday.

**Comment by chrisradek** [comment]
@testtshoretel 
One more note, the SDK will try to detect what region a bucket is in if an operation fails, then cache the bucket location. So, if before you called `getSignedUrl`, you had previously called an operation using the same bucket, that could explain why you were seeing the region in your URL change despite no ENV or code changes. In this case, the wrong region would have been used due to the S3 event yesterday.

Closing this issue since it appears to be related to yesterdays event, but feel free to reopen if you see the same problem today.
