### ISSUE TITLE
"Optimistic Locking With Version Number" support for DynamoDB

### ISSUE THREAD

**Issue by leggiero** [aws/aws-sdk-js#1422]
As described on [Optimistic Locking With Version Number](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html) the Optimistic Locking With Version Number is implemented only on AWS SDK for Java, could this feature be implemented in Node.js SDK?

PS: this was already reported on the closed issue: https://github.com/aws/aws-sdk-js/issues/540 that was suggested to be opened on [DynamoDB Document SDK in Javascript](https://github.com/awslabs/dynamodb-document-js-sdk), but the project is now deprecated.

**Comment by jeskew** [comment]
It looks like the AWS SDK for Java implementation is only available in the context of the DynamoDB DataMapper; do you think this feature would make sense as a stand-alone addition to the SDK?

**Comment by sundeepkalt** [comment]
Perhaps I'm not understanding correctly, but we can acheive this like below?

```
    async updateOptimisticLocking(key) {
        var query = {
            TableName : "mytable",
            Key: {
                key: key
            }
        };

        const current = await this.dynamodbDocClient.get(query).promise();

        var params = {
            TableName: "mytable",
            Key: { key : key },
            UpdateExpression: 'set #olv = :olv + 1',
            ConditionExpression: '#olv = :olv',
            ExpressionAttributeNames: {'#olv': 'optimistic_locking_version'},
            ExpressionAttributeValues: {
                ':olv' : current.Item.optimistic_locking_version
            }
        };

        return await this.dynamodbDocClient.update(params).promise();
    }
```

Ofcourse this example is not that useful because you want to be updating something along with the locking version. Then you can do a try catch with `ConditionalCheckFailedException` if locking number does not match. E.g. requery and do the same logic or what ever you need. I think this would work?

I'm not sure how you would go about doing this in the aws sdk because you would need away to tell the dynamodb client what your optimistic locking verion field is called (unless it takes an opinionated approach). In Java you specifiy it will java annotations, so it's a little nicer.
