### ISSUE TITLE
File not close when s3 upload error .

### ISSUE THREAD

**Issue by 1msoft** [aws/aws-sdk-js#1426]
Hi,
     I upload some folder to s3 by gulp , I get "too many file open" error after network error 5 hour.  so file's readstream not autoclose.
     I see function cleanup in managed_upload.js
     ```
        self.body.removeAlllisteners('end');
        self.body.resume();
    ```
    why resume()?

**Comment by jeskew** [comment]
I believe the call to `resume` was added to shift a stream into flowing mode so that it would exhaust the source and close itself. You can use the managed uploader to upload any stream, not just those created with node's `fs` module, and the `close` method on file descriptors is unique to `fs` and not part of the generic [`stream.Readable`](https://nodejs.org/api/stream.html#stream_class_stream_readable) interface.

You will need to call [`fs.close`](https://nodejs.org/api/fs.html#fs_fs_close_fd_callback) in the callback provided to `AWS.S3::upload` or `AWS.S3.ManagedUpload::send`.
