### ISSUE TITLE
react-native support clarification

### ISSUE THREAD

**Issue by Quas94** [aws/aws-sdk-js#1431]
Hi, I want to use the AWS SDK in a React Native project (primarily for uploading images to S3).

The readme on the react-native branch says 'React Native support is currently a work in progress' but also has instructions on how to use it, too.

Was just wondering how mature this branch is (will I run into problems if I only use it for uploading images to S3?) and if development on it will continue, as there hasn't been any activity on the branch for nearly a month.

**Comment by jeskew** [comment]
It's stable; we're just working on the deployment strategy. Right now, you need to build a version of the SDK for react native (as you would build a version for the browser) instead of just using `require` statements.

There's more discussion and a link to the relevant issue on the react native repository on the pull request at https://github.com/aws/aws-sdk-js/pull/1393
