### ISSUE TITLE
cant upload image case sensitive error?

### ISSUE THREAD

**Issue by uopeydel** [aws/aws-sdk-js#1432]
whenuse this code it will return error  
```
uploadfile(event: any) { 
        AWS.config.update({
            accessKeyId: this.creds.access_key,
            secretAccessKey: this.creds.secret_key, 
            s3DisableBodySigning: true,
            region: 'ap-southeast-1'
        });
          
        let bucket = new AWS.S3(); 
        let paramss: AWS.S3.PutObjectRequest = {
            Key:   this.file.name,
            Body: this.file,
            Bucket: 'myBucketFolder' 
        };  
        bucket.upload(paramss, function (err :any, data:any) {
            console.log(err, data);
        });
    }
```

when case i type mybucketfolder bucket name will ran to front of link when i type Upper charactor it will be true position 

but when i create Bucket in link [ https://console.aws.amazon.com/s3/home?region=ap-southeast-1 ] i cant create Bucket uppercase

-samplelink 1
[ https://s3-ap-southeast-1.amazonaws.com/myBucketFolder/imagename.png ]

-samplelink 2
[ https://mybucketfolder.s3-ap-southeast-1.amazonaws.com/imagename.PNG ]

how can i do for upload image?

**Comment by jeskew** [comment]
Hi @uopeydel,

[S3 bucket names are case sensitive](https://forums.aws.amazon.com/thread.jspa?threadID=103148), but lowercasing a host is permissible under [RFC 3986](https://tools.ietf.org/html/rfc3986#section-6.2.2.1). S3 allows users to address a bucket in two ways: either by prepending the bucket name to the host ("virtual-hosted addressing," as in samplelink 2) or by prepending the bucket name to the path ("path-style addressing," as in samplelink 1). The SDK will use virtual-hosted addressing [unless a bucket's name contains uppercase characters or is otherwise DNS-incompatible](https://github.com/aws/aws-sdk-js/blob/88873eacb3f46ced71be9aa1b114e4e63e2f3792/lib/services/s3.js#L359), so the `myBucketFolder` bucket would use path-style addressing.

[S3 does not allow uppercase characters in bucket names outside of the `us-east-1` region](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html), so you wouldn't be able to create a bucket called `myBucketFolder` in the `ap-southeast-1` region. You will need to use only lowercase letters, numbers, hyphens, and periods.

**Comment by jeskew** [comment]
You can force the S3 client to use path-style addressing with the [`s3ForcePathStyle` configuration option](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor_details).
