### ISSUE TITLE
upload file is very slow this morning. 

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1449]
I noticed upload a file is very slow(5-7 seconds) compared with normal (less than one second). 

I captured Wireshark  and can you take a look?

Question: why ssl negotion always had encryption alert first and then second time it succeeded?

[uploadS3slow.zip](https://github.com/aws/aws-sdk-js/files/900493/uploadS3slow.zip)

Thanks!

**Comment by chrisradek** [comment]
@testtshoretel 
Did you update the version of your SDK recently? If so, from what to what?

Under the hood, we're making requests using node.js' `https` module. We haven't made any significant changes to how we call that code in quite a while.

Are you still seeing slow uploads now? If you did update your SDK, can you revert to the old version and see if uploads are still slow?

**Comment by testtshoretel** [comment]
@chrisradek I did not update the SDK. I noticed this problem since I captured Wireshark. I am running my test on windows to my s3 bucket. My pc is 10.57.4.203.  S3 ip is 52.219.28.46. 

Yes. Upload is still very load at this time.

**Comment by chrisradek** [comment]
@testtshoretel 
This doesn't seem like an issue we can investigate on the SDK side then if the code hasn't changed, but now uploads are taking longer to complete. You might check the S3 forums to see if anyone else has experienced similar latency issues.

I'm closing the issue since there isn't anything we can investigate right now. Since this just started happening with no code changes, there isn't enough for us to go off of. If you do discover there was a change in the SDK that caused this, feel free to re-open or open a new issue.
