### ISSUE TITLE
CloudWatchLogs filterLogEvents always empty

### ISSUE THREAD

**Issue by d10i** [aws/aws-sdk-js#1468]
Same as https://github.com/aws/aws-sdk-js/issues/1193 but the cause seems to be different. This used to work on Thursday (13/04/2017) and today is not working anymore (18/04/2017). 

Example:
```
var cloudwatchlogs = new AWS.CloudWatchLogs({region: 'eu-west-1'});
var params = {
  logGroupName: 'qa-my-service',
  endTime: 1492095170000,
  filterPattern: 'ERROR',
  startTime: 1492095000000
};
cloudwatchlogs.filterLogEvents(params, function(err, data) {
  ...
});
```

The response is always `errr === null` and `data.events.length === 0`. Running the code inside a lambda function that is triggered by an SNS event. The same call using the AWS CLI returns events.

Runtime: Node.js 6.10

**Comment by chrisradek** [comment]
@dario-simonetti 
Can you confirm that the region and logGroupName are the same in the CLI and the JS SDK? Are you able to run the JS code locally to verify the results?

We don't have any customizations around CloudWatchLogs in the SDK, so the most likely cause of the missing data is a difference in how the region/credentials are configured between your environments. Testing locally with the same creds as the CLI should help narrow down if there might be an issue with the role Lambda is using.

**Comment by attinderseesdragons** [comment]
I am running into the same issue. I can pull filtered logs via cli and also I get logs back when I provide stream names, but without stream name, there is nothing coming back

**Comment by dbburgess** [comment]
I ran into this. I'm guessing the results _do_ contain a `nextToken`. That was the key in my case. I was searching with a specified `startTime` which was relatively recent. I have two identical environments (dev and prod). In dev, it was working fine. In production, it was returning this:

```json
{
  "events": [],
  "searchedLogStreams": [],
  "nextToken": "big-long-token-was-here..."
}
```

As it turns out, it was related to the `startTime` and the amount of data (dev having a lot less). I noticed this because if I used a `startTime` further in the past, I'd get results. With no `startTime`, I'd get results even further in the past. I think it's due to the way aws searches the streams. It seems to be starting the search with the oldest stream and moving forward through time. There probably is a limit on how much data it will search before returning results. If it hasn't found any results by time it hits the limit, it will return an empty set with `nextToken` being a pointer to where it left off. If you search again, providing `nextToken`, it will continue the search there.

Depending on the length of your log history, you may need to repeat this a number of times. After repeating this enough times, eventually, you will get the results. Of course, if your logs are rather lengthy, it probably is a much better idea to find the streams your data is most likely in, and specify those, rather than just mindlessly looping through all of them until you find the data you want.

I hope that's helpful to someone! 🙂

**Comment by d10i** [comment]
@dbburgess YES! You are right! Thanks a lot, your message really helped fixing our issue :) It kind of makes sense after you pointed it out, we should have looked at the whole response...

Closing.

**Comment by linjimmy168** [comment]
@dbburgess 
Thanks. It is really helpful.
