### ISSUE TITLE
s3.createPresignedPost fields do not match S3 API docs

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-sdk-js#1488]
Hi,

I have difficulties to match the outputs of `s3.createPresignedPost` with the S3 docs here: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

Given the following code:

```
const s3 = new AWS.S3({
    endpoint: new AWS.Endpoint(config.get('s3.endpoint')),
    accessKeyId: config.get('s3.access_key_id'), // the app does not run on AWS, so I need credentials
    secretAccessKey: config.get('s3.secret_access_key'),
    s3ForcePathStyle: true,
  });

const key = 'somekey';

const params = {
    Bucket: config.get('s3.bucket'),
    Key: key,
    Expires: 60*60*12, // in seconds,
    Fields: {
      key: key,
    },
  };
  s3.createPresignedPost(params, function(err, data) {
    if (err) {
      throw err;
    }
    // data.fields
  });
```

data.fields contains entries for:

* key
* bucket
* X-Amz-Algorithm
* X-Amz-Credential
* X-Amz-Date
* Policy
* X-Amz-Signature

The docs at http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html tell me that different fields are expected:

* AWSAccessKeyId
* key
* policy

How does this fit together?

PS: I tried setting `signatureVersion: 'v2'` when creating the S3 client without any changes.

**Comment by jeskew** [comment]
Hi @michaelwittig,

The `s3.createPresignedPost` method will always v4 signatures so that it can be used in S3's many v4-only regions. The documentation for what a form looks like with a v4 signature can be found [here](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html).

You can safely include every field in `data.fields` as a hidden input field in the upload form, and that (plus a file field) would be sufficient for a v4-signed POST upload. Is there a particular reason you want to use v2 signatures?

**Comment by michaelwittig** [comment]
I assumed that is has something to with v2 vs v4. That's why I tried `signatureVersion: 'v2'`.

I use s3proxy as a S3 mock for local testing. They only support v2-signed Post: https://github.com/andrewgaul/s3proxy/issues/212

**Comment by jeskew** [comment]
I'll leave this open as a feature request, but I would consider that a bug in the S3 mock. Since S3 only supports V2 in some regions, you would run into compatibility issues if your production environment used S3 in v4-only regions.
