### ISSUE TITLE
GetSignedUrl Doesn't Return Error for Non-existent bucket Items [Feature Request]

### ISSUE THREAD

**Issue by cameck** [aws/aws-sdk-js#1529]
Calling obviously wrong data does not throw an error.
For example:

```javascript
  const params = {Bucket: '192.168..5.4', Key: '!#(#$^(*#&(#*())))', Expires: 60};
  s3.getSignedUrl('getObject', params, function (err, result) {
    if (result) {
      console.log(result);
      callback(null, {'url': result});
    } else {
      console.log(err);
      callback(err, null);
    }
  });
```

This results in success:
```shell
https://s3.amazonaws.com/192.168..5.4/%21%23%28%23%24%5E%28%2A%23%26%28%23%2A%28%29%29%29%29?AWSAccessKeyId={REDACTED}&Expires={REDACTED}&Signature={REDACTED}
```

**My Environment:**
* MacOs: OS X El Capitan - 10.11.6
* Node: v6.10.3
* AWS-SDK:  `AWS.S3({apiVersion: '2006-03-01'})`

******

An easy workaround is to write another method checking for the object's existence first, but ideally I don't think this should be necessary.

**Comment by jeskew** [comment]
I'd be hesitant to add this feature to the SDK because I'm not sure if the SDK can do any validation here short of calling out to S3 to check if the item exists. That would change `getSignedUrl` from a purely CPU-bound operation to one that must make a network call, which would negatively impact the performance of applications that generate a large number of presigned URLs.

While bucket names in most regions must be DNS-compatible, [S3 lists the following exception to that rule](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html):

> The rules for bucket names in the US East (N. Virginia) region allow bucket names to be as long as 255 characters, and bucket names can contain any combination of uppercase letters, lowercase letters, numbers, periods (.), hyphens (-), and underscores (_).

In that particular region, `'192.168..5.4'` would be a valid bucket name. 

Similarly, [the rules on object naming](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) are fairly lax:

> The name for a key is a sequence of Unicode characters whose UTF-8 encoding is at most 1024 bytes long.

Additionally, I've seen a number of "S3-compatible" services that are designed to be used with an official AWS SDK but that do not necessarily enforce the same naming rules as Amazon S3.

**Comment by cameck** [comment]
Hmm that's interesting and I get your point. 
Maybe it's not such a big deal, but I think there should be at least a little validation.
I can literally pass the unicorn emoji (🦄  ) and still get a successful response.

**Comment by jeskew** [comment]
That's a legal object name, and I suspect that some otherwise S3-compatible services would accept it as a valid bucket name, too.

**Comment by cameck** [comment]
hehe, that's true it is UTF-8
