### ISSUE TITLE
documentation for leavePartsOnError scenario 

### ISSUE THREAD

**Issue by davidmaxwaterman** [aws/aws-sdk-js#1538]
I see the mention of `leavePartsOnError` option in the docs. It explains that it doesn't clear up the chunks to enable a more aggressive recovery, but it doesn't explain how the user might do such a recovery. I see some examples in issues here, eg:

https://github.com/aws/aws-sdk-js/issues/778

but that just does the recovery, and doesn't seem to do any clearup. The docs for abort() suggest that calling that would normally do the clearup, but that it doesn't do so if the 'leavePartsOnError' option is set. So, I am left wondering how, after an unsuccessful 'more aggressive' recovery, how I then actually use the SDK to clear up the parts.

I know the docs are quite, er, 'extensive', so perhaps I'm missing some reference somewhere. If not, is it possible to add some example code for this scenario?

**Comment by davidmaxwaterman** [comment]
I am also wondering if the 'leavePartsOnError' could be used for a 'pause/resume' feature?

**Comment by chrisradek** [comment]
@davidmaxwaterman 
We can add some documentation on how to use this. I revisited the issue you linked to, and there does appear to be a bug where resuming an aborted upload results in a smaller file being uploaded. In at least some cases, this occurs when all but 1 'part' has been uploaded. The next time the upload is triggered, since there is only 1 part left, it performs a `putObject` request instead of `uploadPart`. I'm working on a fix for that now.

**Comment by ajredniwja** [comment]
Closing this issue since the feature was implemented.
