### ISSUE TITLE
AWS IoT: thingArn not included in listThings response

### ISSUE THREAD

**Issue by arian-kh** [aws/aws-sdk-js#1541]
When using the aws.iot.listThings method, the callback data includes an array of things, as expected. But each Thing hash is missing the thingArn attribute. I noticed however that the actual response for the Get /things request does include thingArn (seen in the network tab of my browser). Seems like the iot wrapper chooses to exclude the thingArn?

**Comment by chrisradek** [comment]
@arian-kh 
It looks like `thingArn` isn't modeled as a response field in our Iot model. I've reached out to the service team about this. Since the models are shared across all SDKs, we can't directly modify these models here.

The SDKs will ignore data that isn't modeled when reading a service's response, which is why you aren't seeing it now. It is possible to get at the raw response by doing something like the following:

```javascript
iot.listThings(function(err, data) {
  var body = this.httpResponse.body;
  // JSON parse body
  var parsedBody = JSON.parse(body.toString());
});
```

However, the SDK does some additional work, such as converting date values to actual Date objects.

I'll update here once I get some more info from the service team.

**Comment by arian-kh** [comment]
Thanks Chris, appreciate it! I didn't know you can access the httpResponse from the 'this' context.

**Comment by srchase** [comment]
@arian-kh 

This has been added to the model by the Service Team.

Closing out this issue.
