### ISSUE TITLE
bug in ECS waitFor(tasksRunning)

### ISSUE THREAD

**Issue by dbook-kkbrandt** [aws/aws-sdk-js#1551]
After calling ECS.startTask, I'm using the ECS.waitFor('tasksRunning') function with the taskArn that startTask returns. The task always starts on the container instance, BUT the waitFor call sometimes (about 1/3 of the time) returns the following error very quickly:

{ [ResourceNotReady: Resource is not in the state tasksRunning] message: 'Resource is not in the state tasksRunning', code: 'ResourceNotReady', retryable: false, time: Fri May 05 2017 02:04:23 GMT+0000 (UTC), statusCode: 200, retryDelay: 6000 }

I unfortunately haven't noticed a pattern to when this happens. It happens when I use runTask instead of startTask, it happens when I'm starting the task on a newly created container instance, it happens when I'm placing the task on a container instance that I just stopped an old task on. (Though again, in all of these cases, it only happens sometimes)

I see no errors in the ECS console. If there is somewhere else I can look for error logs, that would be good to know.

aws-sdk version: ^2.55.0
nodejs version: 4.4.7
OS: Ubuntu:trusty. Using docker image nodesource/trusty:4.4.7 (https://github.com/nodesource/docker-node/tree/master/ubuntu/trusty/node/4.4.7)

**Comment by dbook-kkbrandt** [comment]
Update on this: I hadn't encountered for over a week, and ran into it again last night, after killing the docker image manually (ssh + docker kill), then attempting to call ecs.runTask(). 
I'm guessing this only happens when ECS hasn't fully registered that a change has occurred, so basically if I try to do something too quickly. 
I consider it a bug that the task starts even though the SDK returns an error.
It would also be nice if the error messages were more fine-grained and descriptive.

**Comment by natan-hoppe** [comment]
I'm stumbling upon this problem consistently. A bit of context, though:

Node: 6.10.1
SDK: 2.93.0

First I call SDK's `runTask` with the task definition I want to run and the ECS cluster where to run it.

```
let params = {
  cluster: "XYZ",
  taskDefinition: "MyTask:1"
};

let runTaskPromise = this.ecsSdk.runTask(params).promise();

runTaskPromise.then(data => {
  let params = {
    cluster: this.cluster,
    tasks: [ data.tasks[0].taskArn ]
  };

  this.ecsApi.waitFor('tasksRunning', params).then(err => {
      if (err) {
        console.log(err, err.stack);
      } else {
        return 0;
      }
  });
});
```

Then, when I execute the code and try to run the desired task for the first time, I get the error:
```
{
  "errorMessage": "2017-08-01T16:51:53.599Z <TASK_ID> Task timed out after 3.00 seconds"
}
```

According to the latest JavaScript SDK documentation, [AWS.ECS](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#waitFor-property): 
> Waits for the `tasksRunning` state by periodically calling the underlying ECS.describeTasks() operation every 6 seconds (at most 100 times).

Which raises the following questions:
1) Why the method request is failing in 3 seconds if the documentation says 6 seconds? 
2) If the `waitFor` timeout is 600 seconds, why it fails in the first request?

**Comment by dbook-kkbrandt** [comment]
@natan-hoppe 
To be sure, does your task stay running after you get that error? Is there any more information that comes with that errorMessage?
The code you've posted wouldn't quite work.
What you would want is something like:
`
...
return this.ecsSdk.waitFor('tasksRunning', params).promise().then(data => 0).catch(e => console.error(e, e.stack);
`

**Comment by natan-hoppe** [comment]
@dbook-kkbrandt Thanks for the feedback, I'll update the code. Now, addressing the questions...

> To be sure, does your task stay running after you get that error?

Yes. The task stays running as intended although the method seems to fail before. I even created a Docker image using these lines just to make sure this was at the SDK level:
```
FROM buildpack-deps:jessie-curl
CMD ["/bin/bash", "-c", "while :; do echo 'Infinite Loop - Hit CTRL+C to exit.'; sleep 1; done"] 
```

> Is there any more information that comes with that errorMessage?

No extra information. Although in a moment of clarity I realized what went wrong in my case. I was running the Node.JS code using AWS Lambda. The problem was: AWS Lambda has a default 3 second timeout, while my debugging task, the one running the Docker image mentioned above, took _more_ than the Lambda default timeout to start. So, I got it working in my case.

Regarding your issue specifically, this isn't a solution, but it helps to debug (aside of being a good practice with containers too):
1) Make sure the application running in the container is [logging _everything_ to the `stdout`](https://12factor.net/logs)
2) Create a Cloudwatch Log Group for the logging
3) Update your task definition to use an IAM role with CloudWatch Logs permissions:

![screen shot 2017-08-01 at 1 05 36 pm](https://user-images.githubusercontent.com/18559172/28844643-35128578-76ba-11e7-9b17-52240a666b35.png)
 
4) Update the container definition inside the task definition you're trying to run to use `awslogs` and point it to the log group created in step 2:

![screen shot 2017-08-01 at 12 54 48 pm](https://user-images.githubusercontent.com/18559172/28844541-cf6ca92e-76b9-11e7-8913-2a6c0c348638.png)

Doing this, you'll be able to see the output at the container level and pinpoint if it's the container causing problems.

**Comment by frankjl** [comment]
Any updates to this? We are also getting this error about 1/3rd of the time. Most of the time, simply retrying the step allows it to succeed. We are sure it's not the container causing issues because the we can see in the logs that our task is running; it just seems to be a bug in the `ecs.waitFor` implementation.

This is a simplified version of what we are doing:

```
ecs.runTask({
  taskDefinition: taskDefinitionId,
  cluster: 'ECSCluster'
}).promise().then((result) => {
  const taskArn = result.tasks[0].taskArn;
  console.info(`Checking to make sure task arn ${taskArn} is RUNNING..`);
  ecs.waitFor('tasksRunning', {
    tasks: [ taskArn ],
    cluster: 'ECSCluster'
  }).promise();
})
```

And sporadically we'll see the following errors:

```
Failed { ResourceNotReady: Resource is not in the state tasksRunning
at constructor.setError (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
at Request.CHECK_ACCEPTORS (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
message: 'Resource is not in the state tasksRunning',
code: 'ResourceNotReady',
retryable: false,
time: 2018-10-19T19:56:50.153Z,
statusCode: 200,
retryDelay: 6000 }
```

**Comment by baszczewski** [comment]
In my opinion there is something wrong in promise like response. For example this methods works correctly for me when I am use callback API. My TypeScript sample:
```typescript
ecs.waitFor("tasksRunning", {
    cluster: AWS_CLUSTER,
    tasks,
    $waiter: {
        delay: 1,
        maxAttempts: 100,
    },
}, (err: AWS_SDK.AWSError, data: AWS_SDK.ECS.Types.DescribeTasksResponse) => {
    if (err) {
        reject(err.message);
    } else {
        resolve(data);
    }
});
```

**Comment by ajredniwja** [comment]
Closing this issue for now because of inactivity, please re-open and reach out if you have any additional questions.
