### ISSUE TITLE
IE 10 JS SDK not working. buf.write is undefined

### ISSUE THREAD

**Issue by wytlytningNZ** [aws/aws-sdk-js#1565]
When trying to authenticate using JS SDK clientside in IE 10, we are receiving an error in the console saying the buf.write is undefined.

I believe it has something to do with the fact IE10 doesn't allow you to assign to the prototype, but in the `dist/aws-sdk.js` file there are two `createBuffer` functions being defined; one that checks `TYPED_ARRAY_SUPPORT` and one that doesn't

1. Line 111334
```
function createBuffer (that, length) {
  if (kMaxLength() < length) {
    throw new RangeError('Invalid typed array length')
  }
  if (Buffer.TYPED_ARRAY_SUPPORT) {   //<-- Checks for support (IE10) before trying to set proto, which is good.
    that = new Uint8Array(length)
    that.__proto__ = Buffer.prototype
  } else {
    if (that === null) {
      that = new Buffer(length)
    }
    that.length = length
  }

  return that
}
```

2. Line 112985
```
function createBuffer (length) {
  if (length > K_MAX_LENGTH) {
    throw new RangeError('Invalid typed array length')
  }
  var buf = new Uint8Array(length)
  buf.__proto__ = Buffer.prototype //<- cannot do this in ie10, and because this function is defined after the first one, this is the implementation that runs.
  return buf
}
```

**Comment by chrisradek** [comment]
@wytlytningNZ 
It looks like there are 2 issues here. First, Buffer is getting pulled in twice because the SDK requires v5, and browserify (used to generate the browser distributable) uses v4. Updating browserify to the latest fixes the Buffer duplication problem.

However, the other issue is that Buffer v5 appears to drop support for IE 10. We can't roll Buffer back to v4, because then we also drop support for android 4.4 devices.

It looks like we'll need to provide a pollyfill for Uint8Array.prototype.fill. That may be something you can include for IE 10 clients today as well.
