### ISSUE TITLE
Upgrade to signatureVersion v4 breaks uploads

### ISSUE THREAD

**Issue by raytiley** [aws/aws-sdk-js#1569]
Our CI recently failed and I tracked it down to this commit in aws-sdk: https://github.com/aws/aws-sdk-js/commit/7b281055ef71f74250c5b1b3733fdce1c338c7ce

Our bucket names use forward slashes to mimic nested directories which I think is fairly common. For now using `signatureVersion: v2` fixes our immediate problem, but was wondering why this validation became necessary and what is the best way going forward to mimic uploading items to locations containing forward slashes.

Thanks

**Comment by KafaltiyaMahesh** [comment]
I am facing same issue while fetching an object but upload working fine with forward slashes in bucket Name 'a/b/c'

**Comment by chrisradek** [comment]
@raytiley 
S3 bucket names aren't allowed to contain forward slashes. Anything after the first forward slash in your bucket name would have actually been considered part of an object's key. 

For example, if you have a bucket, `foo`, and want to upload an object `test.txt` to the directory `bar/baz`, the object's full key would be `bar/baz/test.txt`.

One of the reasons a bucket name can't contain forward slashes is it leads to ambiguity. Are you trying to access the bucket foo/bar, or the object 'bar' within 'foo'?

Using signatureVersion v2, rather than throw an error, S3 appears to treat anything before the first slash as the bucket name. Using signatureVersion v4, the separation between bucket and keys caused an error to be thrown. Going forward, directories should be included as part of an object's key. While you can continue to use signature version 2 to get around this behavior, new regions only support signature version 4, where slashes in bucket names won't work at all.

**Comment by chrisradek** [comment]
#1587 will allow using forward slashes in the `Bucket` field when using signatureVersion 4. This change was made for backwards compatibility, but will be removed when we do a major version bump. New code should instead include 'directories' as part of either the `Prefix` or `Key`, depending what the operation calls for.

See https://github.com/aws/aws-sdk-js/issues/1572#issuecomment-309869153 for more details.
