### ISSUE TITLE
How do I query sets in DynamoDB?

### ISSUE THREAD

**Issue by benishak** [aws/aws-sdk-js#1571]
I have many Items in this form and structure

```
{
  "_created_at": "2017-06-09T18:49:04.079Z",
  "_hashed_password": "$2a$10$........",
  "_id": "2LynMtzC1Z",
  "_pk_className": "_User",
  "_rperm": [
    "*",
    "2LynMtzC1Z"
  ],
  "_updated_at": "2017-06-09T18:49:04.079Z",
  "_wperm": [
    "2LynMtzC1Z"
  ],
  "email": "test@test.org",
  "username": "test"
}
```

I want to find all items by `_rperm`, it should
- not exists
- or includes *

here is my query params

```
{ TableName: 'ap-server',
  KeyConditionExpression: '#className = :className',
  Select: 'ALL_ATTRIBUTES',
  ExpressionAttributeNames: { '#rperm': '_rperm', '#className': '_pk_className' },
  ExpressionAttributeValues: { ':rperm_0': '*', ':className': 'User' },
  Limit: 100,
  FilterExpression: '( #rperm = :rperm_0 OR attribute_not_exists(#rperm) )' }
```

But the query doesn't retrieve anything for me, why?

**Comment by jeskew** [comment]
Hi @benishak,

`#rperm = :rperm_0` checks for equality, whereas you want to know if `#rperm` contains a value. 

If `_rperm` is a string set, you can use the `contains` [filter expression function](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html), as in `( contains(#rperm, :rperm_0) OR attribute_not_exists(#rperm) )`. 

If `_rperm` is a list, you will need to apply the filter manually on the values you receive from DynamoDB (as described [here](https://github.com/awslabs/dynamodb-document-js-sdk/issues/33#issuecomment-110121328)). Since consumed capacity is evaluated before the filter expression is applied, filtering the query results in your application will not result in increased costs from DynamoDB.

**Comment by benishak** [comment]
@jeskew thats true, it was my mistake actually what I was looking for is to use the IN operator just like in MongoDB with `$in` 

Another things why does the following query not work when applied on a set/list ?

Suppose I have an Item with Attribute as array

{
   myList : [1,2,3,4]
}

When I try to find this Item using this query

```
FilterExpression : "#mylist = :list"
ExpressionAttributeValues: { ":list" : [3,4,1,2] }
```

In MongoDB same query will return that Item

{ myList : [3,4,1,2] }
or
{ myLIst : { $all : [3,4,1,2] }

but in DynamoDB in order that this work they must be in the same order so the following will be working just fine

```
FilterExpression : "#mylist = :list"
ExpressionAttributeValues: { ":list" : [1,2,3,4] }
```

as workaround for now, before inserting I check for possible List attributes, sort them, and query them with the a sorted array, so if my query included the list [3,4,1,2] I will make it look like this [1,2,3,4] to match the element in the array.

**Comment by jeskew** [comment]
I think right now you would need apply the filter after getting the results back from DynamoDB. Since Dynamo calculates consumed capacity and limits result size *before* applying any filter expressions, you wouldn't get charged any more if the query filters out fewer results before returning them back to you. You might want to ask this same question on the [DynamoDB developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=131) in case the service team (or developers who write in another language) has any different ideas.

Just FYI, the API version is an identifier that doesn't necessarily represent the last time a service was updated. The last time the API itself was updated was [when time-to-live was added to DynamoDB and DynamoDB streams earlier this year](https://github.com/aws/aws-sdk-js/commit/bc5aab63f0d52bf95f53887d0cdd6ccb5ac52e4c), and the service has recently launched server-side features like VPC and AutoScaling support.
