### ISSUE TITLE
Typescript: Interfaces have method overloads that are not valid requests

### ISSUE THREAD

**Issue by ajmath** [aws/aws-sdk-js#1575]
Currently hitting issues trying to override s3.getObject. According to the type defs there are two overloads of this method.

```
getObject(params: S3.Types.GetObjectRequest, callback?: (err: AWSError, data: S3.Types.GetObjectOutput) => void): Request<S3.Types.GetObjectOutput, AWSError>;
getObject(callback?: (err: AWSError, data: S3.Types.GetObjectOutput) => void): Request<S3.Types.GetObjectOutput, AWSError>;
```
The version that only has the optional callback is not valid per the API docs.

Trying to override this like so:

```
  s3.getObject = (params: GetObjectRequest, callback?: (error: AWSError, output: GetObjectOutput) => void) => {
    return {} as Request<GetObjectOutput, AWSError>;
  };
```
gives a compiler error like this:

```
Error:(22, 3) TS2322:Type '(params: GetObjectRequest, callback?: (error: AWSError, output: GetObjectOutput) => void) => Requ...' is not assignable to type '{ (params: GetObjectRequest, callback?: (err: AWSError, data: GetObjectOutput) => void): Request<...'.
  Types of parameters 'params' and 'callback' are incompatible.
    Type '(err: AWSError, data: GetObjectOutput) => void' is not assignable to type 'GetObjectRequest'.
      Property 'Bucket' is missing in type '(err: AWSError, data: GetObjectOutput) => void'.
```

This is one example of many.  Most seem to stem from allowing APIs to be called with only the callback and no request parameters.

**Comment by jeskew** [comment]
I'm going to reclassify this as a "documentation" issue rather than a "typings" issue, as the type definitions are correct. You can create a client in the SDK with "bound parameters" that will be applied to every request made with that client. See [our developer guide](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/creating-and-calling-service-objects.html#specifying-service-object-parameters) for a discussion of how to use service clients in this way.

The parameters passed to an operation will be merged with the client's bound parameters, so if you've already bound a `Bucket` and `Key` parameter, calling `s3.getObject()` or `s3.getObject((err, data) => { ... })` is allowed.

**Comment by flock-machine-user** [comment]
I am trying to use the `s3.getObject({Bucket: 'bucket', Key:'key}).createReadStream()` using Typescript is throwing an error because there is not a definition for this type `getObject` call.  I am getting error:

```
error TS2345: Argument of type '{ Bucket: String; Key: String; }' is not assignable to parameter of type '(err: AWSError, data: GetObjectOutput) => void'.
  Type '{ Bucket: String; Key: String; }' provides no match for the signature '(err: AWSError, data: GetObjectOutput): void'.

12         s3.getObject(params)
```

What can i do to get this function call to compile?

**Comment by anton-107** [comment]
@flock-machine-user I don't get this specific error. But with one of other methods from aws-sdk, type casting the first parameter helped me solve the transpiler error. In your case it would look like this:

```
s3.getObject({Bucket: 'bucket', Key:'key'} as GetObjectRequest).createReadStream();
```

**Comment by ggutenberg** [comment]
@anton-107 's method worked for me, but I needed to specify the full path to the type.  Ex:

```
s3.createBucket({ Bucket: 'bucket' } as AWS.S3.CreateBucketRequest).promise(),
```

**Comment by MichaelHindley** [comment]
@jeskew I'm not sure what sentiment is implied here. I feel any developer would expect this to work, but it fails with TS2345 Bucket does not exist on Type:

![image](https://user-images.githubusercontent.com/1016639/56811663-837de000-6839-11e9-8090-0d6c412c10d7.png)

The input to deleteObjects clearly accepts a Bucket parameter. Both VSCode and Intellij suggest it, and so do the docs.
![image](https://user-images.githubusercontent.com/1016639/56811750-bd4ee680-6839-11e9-9ea5-98814ce85bd5.png)

The mental gymnastics required to get this working are not so straight forward either, you can't just specify the type of the object you are working with either, this still fails:
![image](https://user-images.githubusercontent.com/1016639/56812098-84634180-683a-11e9-8549-456de2d78627.png)

You need to specify the full import path to the type:

![image](https://user-images.githubusercontent.com/1016639/56812189-aceb3b80-683a-11e9-9b98-3ccf41cf9dba.png)


I can't think of any other library the past few years of using Typescript that has this behavior, it's surely not intuitive.  It impacts the whole development flow, this is how it looks like when you start defining import parameters to almost any aws-sdk function using Typescript:
![image](https://user-images.githubusercontent.com/1016639/56812397-166b4a00-683b-11e9-8631-be44f3ef192a.png)

In the above example, the actual error is completely hidden, the fact that there are missing required parameters is completely unkown to the developer since TS compiler, VSCode language service, and Intellijs implementation of how it handles Typescript can't handle the funky typing of the aws-sdk. 

I'm not saying what's wrong or right from a technical or academic best practice point of view, but I feel like the developer experience and productivity of Typescript with aws-sdk suffers tremendously due to the strategy chosen for the typings.

**Comment by megakoresh** [comment]
Confirm this bug also exists on
- `AWS.IAM.attachGroupPolicy`
- `AWS.Organizations.moveAccount`
