### ISSUE TITLE
testing with DynamoDBLocal and Mocha

### ISSUE THREAD

**Issue by benishak** [aws/aws-sdk-js#1581]
I'm trying to run multiple test suites, it is required that all data in the table must be removed after a test suite finish

in the mocha `beforeEach` hook I have the following function that describe the table, if it exists it delete it and create a new table, if it doesn't exists it create a new table

```
drop() : Promise {
        // only for test
        const params = {
            AttributeDefinitions: [
                {
                    AttributeName: "partition_id", 
                    AttributeType: "S"
                }, 
                {
                    AttributeName: "item_id", 
                    AttributeType: "S"
                }
            ], 
            KeySchema: [
                {
                    AttributeName: "partition_id", 
                    KeyType: "HASH"
                }, 
                {
                    AttributeName: "item_id", 
                    KeyType: "RANGE"
                }
            ],
            ProvisionedThroughput: {
                ReadCapacityUnits: 5,
                WriteCapacityUnits: 5
            }, 
            TableName: this.database
        };

        return new Promise((resolve, reject) => {
            this.service.describeTable({ TableName : this.database }, (err, data) => {
                let promise;

                if (err) {
                    promise = Promise.resolve();
                } else {
                    promise = this.service.deleteTable({ TableName : this.database }).promise();
                }

                promise.then(() => {
                    return Promise.delay(100);
                }).catch(() => {
                    return Promise.resolve();
                }).then(() => {
                    return this.service.createTable(params, (err, data) => {
                        if (err) {
                            reject()
                        } else {
                            Promise.delay(100).then(() => {
                                resolve();
                            });
                        }
                    });
                });
            });
        });
    }
```

However sometimes my tests fails with **ResourceNotFoundException** coming from different commands like `getItem, putItem ...` or **ResourceInUseException** from `createTable` from the code above.

How can I achieve this?, I tried setting delay period to give DynamoDB to ensure that the table is ready to use, it works but it also fails if my tests were short and running quick

Yes I set `{ endpoint : "http://localhost:8000" }` otherwise my tests all be failing and timing out

**Comment by benishak** [comment]
I created a shell-script

```
aws dynamodb deleteTable .... /dev/null && aws dynamodb createTable > /dev/null
```

and use it like this `execSync('/drop.sh`)`

It did the purpose but it makes the test slow

**Comment by jeskew** [comment]
If an asynchronous (i.e., one that accepts a `done` callback) hook is invoked before each test is run, mocha may be invoking some tests while waiting for others' `beforeEach` hooks to finish. Since all tests look like they're using the same table name, that would explain why you're seeing `ResourceNotFoundException`s, which would occur when an operation attempts to write to a table that another tests `beforeEach` hook has just deleted, and `ResourceInUseException`s, which would occur when one `beforeEach` hook is trying to create a table that another hook has just finished creating.

You wouldn't see this behavior with the shell script you mentioned, since `execSync` will block JS's event loop until the underlying process completes.

Would it be possible to create the table once at the start of the test suite and then tear it down afterwards? (Essentially, just replace `beforeEach` and `afterEach` with `beforeAll` and `afterAll`.)

**Comment by benishak** [comment]
that's an issue, I do use also `afterAll` and `beforeAll` but every test step defined under `it('....')` needs a clean table.

The tests aren't written by me so I can't change it, I'm just implementing a adapter to use it within a bigger and running the module's tests after embedding my module ...

**Comment by jeskew** [comment]
Since you need to "stop the world" and prevent `beforeEach` hooks from trampling on each others' state, it sounds like using `execSync` in a synchronous mocha hook (as you've done with a shell script) will eliminate the issue encountered.

As a longer term fix, you might want to revisit how the tests are manipulating shared global state like a single table in a remote database. If all tests require an empty table, each test could use a table whose name is suffixed with a nonce or some unique identifier for the individual test; making this change would also allow you to run tests in parallel if you wanted to.

Closing, as this is a usage question about Mocha and DynamoDB local rather than an SDK issue, but please feel free to reopen if you have any questions or concerns.

**Comment by benishak** [comment]
yes I do have question, what is the best way to do delete all data in a table without deleting the table using the SDK or CLI ?

**Comment by jeskew** [comment]
To keep the same synchronous semantics as dropping and recreating the table via the CLI, you probably want to continue using `execSync` but modify the script to delete all keys. [This gist](https://gist.github.com/k3karthic/4bc929885eef40dbe010) seems like a good starting point, though you would need to modify it to use DynamoDB Local.
