### ISSUE TITLE
My sub domain not getting propagated immedialty.

### ISSUE THREAD

**Issue by medaamarnadh** [aws/aws-sdk-js#1590]
Hi Team,

I am using route53 api from AWS-SDK. My problem is, 
I am creating records by using  ``changeResourceRecordSets`` method. 
 Subdomains creating successfully but I am always getting PENDING status. And those subdomains also not getting propagating immediately. They are taking minimum one minute. 
Is there any way to resolve it?

Regards,
Amar.

**Comment by jeskew** [comment]
Hi @medaamarnadh,

Because the changes requested in a `ChangeResourceRecordSets` operation must be propagated to authoritative Route53 DNS servers in order to take effect, the operation is asynchronous. The service has more extensive documentation on why that is [in their developer guide](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html).

You can use the [`resourceRecordSetsChanged` waiter](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#waitFor-property) on an  SDK Route53 client to register a callback to be invoked when the change has been propagated.
