### ISSUE TITLE
Contributing to the documentation

### ISSUE THREAD

**Issue by adamatan** [aws/aws-sdk-js#1622]
Hi,

I would like to contribute to the documentation, following what I believe to be an error (https://twitter.com/adam_matan/status/884731527933939712). 
Where is the documentation stored? Are there any published contribution guidelines?

Best,
Adam

**Comment by chrisradek** [comment]
@adamatan 
We appreciate you wanting to contribute to the documentation! The API documentation is generated from the source code/api models, but it looks like you'd want to contribute to the developer guide. 

The developer guide was moved out of this repo last year, and I don't think it has been put on GitHub yet. I'll reach out internally to find out how contributions can be made.

I noticed that in your example, you were updating the global configuration after instantiating your service client:

```javascript
var AWS = require('aws-sdk');

var cloudwatchlogs = new AWS.CloudWatchLogs();

console.log(AWS.config.region)              // Undefined

AWS.config.region = 'eu-central-1'          // Define the region with dot notation
console.log(AWS.config.region) .            // eu-central-1
```

The reason the above doesn't work is because the configuration passed to service clients is considered immutable. If updating the global configuration affected already created service clients, then it would be easy to accidentally mutate them by changing the region, credentials, etc.
If you moved 
```javascript
AWS.config.region = 'eu-central-1'
```
 above 
```javascript
var cloudwatchlogs = new AWS.CloudWatchLogs();
```
then you'd see your expected behavior. This is because when a service client is instantiated, the configuration passed in is merged on top of a copy of the global configuration.

There is documentation on the global configuration and service clients here: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html
Admittedly this can be hard to find unless you know exactly what you're looking for. We can add a link to this page so it appears in the API reference docs with each service constructor, and do a better job of calling out how the different configuration sources get merged.

**Comment by Trii** [comment]
This documentation issue persists across the SDK. See:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudSearch.html#constructor-property 

It should be noted somewhere that region needs to be provided either by environment, credentials, config, or the constructor itself.

**Comment by adamatan** [comment]
@chrisradek Thanks for the reply! How should we move forward with changing the documentation?
