### ISSUE TITLE
correctClockSkew should default to True

### ISSUE THREAD

**Issue by varenc** [aws/aws-sdk-js#1632]
Every app with users in the wild will eventually run into users that have a slightly out of date clock.  TLS/SSL has no problem working with clients with a current time that's a couple days wrong, but AWS/S3 does.

`correctClockSkew` should default to True to fix this issue that virtually every AWS user with customers in the wild will eventually run in to.  The one possible caveat should be that if systemClockOffset isn't set to "0" then the correctClockSkew is ignored.

An issue that briefly discusses this for reference: #527 
The pull request that added this feature: #706

**Comment by onassar** [comment]
Which version of the SDK supports this?
I'm using AWS.S3 and AWS.S3.ManagedUpload, and passing in true for the config option doesn't seem to fix the issue.

**Comment by julien-von-oetinger** [comment]
I'm also using AWS.S3 and AWS.S3.ManagedUpload but correctClockSkew just make the api to retry the upload instead of failing right away.

**Comment by onassar** [comment]
This ended up working for me:
`AWS.config.correctClockSkew = true;`

**Comment by varenc** [comment]
@jeskew any idea where this fits on to the AWS SDK's roadmap?  As I said in another issue:
Having it default to false is like embedding a non-deterministic bug that'll cause problems for ~0.1% of users in everyone's AWS implementation. Any site with lots of diverse users will eventually have to deal with this likely after their implementation has gone into production.

**Comment by jeskew** [comment]
@varenc I don't believe changing the default behavior would be backwards compatible. The current major version of the JS SDK did not launch with any mechanism for automatic clock skew correction, so some users may have written workarounds to handle clock skew. Enabling clock skew correction by default could cause working code that relies on external workarounds to begin failing.

**Comment by varenc** [comment]
what about defaulting to true if "systemClockOffset" still has the default, 0, value?  Are there any workarounds in place that wouldn't be using systemClockOffset?  If there's a chance there are some, then yes I agree it'd need to be part of a new major version for backward compatibility.

In the meantime, perhaps having the JS SDK docs mention "correctClockSkew" anywhere at all would be helpful.  (but I'm sure changing documentation is a whole other process)

**Comment by jeskew** [comment]
`systemClockOffset` was introduced at the same time as `correctClockSkew`, and its value is updated when an operation encounters a clock skew error and compares the service's response against the client clock. There's still a chance defaulting `correctClockSkew` to true in an environment with unrelated clock skew correction would end up double-correcting the clock.

The `correctClockSkew` property is documented on [service constructors](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) and on [`AWS.config`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property), but I don't think we have anything in the developer guide. That's something we could address without a major version bump. :)

**Comment by etiennemunnich** [comment]
There are 2x different approaches to try:

AWS.S3 Object option:

"correctClockSkew (Boolean) — whether to apply a clock skew correction and retry requests that fail because of an skewed client clock. Defaults to false."
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor_details

AWS.Config Class option:
"(Boolean) correctClockSkew (readwrite)
Returns whether to apply a clock skew correction and retry requests that fail because of an skewed client clock. Defaults to false.

Returns: (Boolean) — whether to apply a clock skew correction and retry requests that fail because of an skewed client clock. Defaults to false."
 http://docs.amazonaws.cn/en_us/AWSJavaScriptSDK/latest/AWS/Config.html

**Comment by ajredniwja** [comment]
@varenc this is not set to true by default because there might be customers that may be using ```AWS.config.systemClockOffset``` property to apply clock skew in their respective codes. 

Implementing this feature will be a breaking change for many.

However, I see that there is an open [pull request](https://github.com/aws/aws-sdk-js-v3/pull/459) for this feature which looks it will be merged in [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which is under developer preview right now, you are welcomed to try that and give your feedbacks.

Will be closing this issue for now since, I believe this feature wont be implemented in the V2.

Please reach out if you have any additional questions.
