### ISSUE TITLE
[CognitoIdentityCredentials] set RoleSessionName to be IdentityId or enable setting it after getId and before getCredentialsFromSTS

### ISSUE THREAD

**Issue by borisirota** [aws/aws-sdk-js#1659]
Hi,

I'll explain my scenario:

I was using cognito's getCredentialsForIdentity functionality for a while until recently when I needed to add support for 2 features which isn't supported when using this method:

1. Log getCredentialsForIdentity with CloudTrail - no such functionality.
2. S3 Server Access Logging - be able to know which user (IdentityId) calls the api - [The requester is the role and no IdentityId granularity](http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html).

Switching to the getCredentialsFromSTS functionality ([using the Basic Flow instead of the Enhanced Flow](https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-authentication-part-4-enhanced-flow/)) achieves both goals:

1. Achieved because [cloudtrail supports STS assumeRoleWithWebIdentity](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html#STS-API-SAML-WIF).  
2. Can be achieved if the RoleSessionName is used as the user identifier as explained in [How to Easily Identify Your Federated Users by Using AWS CloudTrail](https://aws.amazon.com/blogs/security/how-to-easily-identify-your-federated-users-by-using-aws-cloudtrail/) and in [Tracking Federated User Access to Amazon S3 and Best Practices for Protecting Log Data](https://aws.amazon.com/blogs/security/tracking-federated-user-access-to-amazon-s3-and-best-practices-for-protecting-log-data/) (both blog posts uses the AssumeRoleWithSAML call but it the same as assumeRoleWithWebIdentity)

Now, in order to achieve the second goal I need to set the RoleSessionName to be the IdentityId but this is known only after the [getId call](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js#L164) and no option to set it from the outside so currently I'm pretty much copy-paste the current `refresh` implementation and calling private methods myself in order to set RoleSessionName to be the IdentityId.

1. Is it make sense to support setting the RoleSessionName in the way my use case needs as part of the official SDK ?
2. Any idea if `CloudTrail` will support getCredentialsForIdentity so it will be possible to use simplified flow without giving up on logging ?

Thanks !

**Comment by DaWyz** [comment]
I encountered the same issue in the last few days.

1. It would definitely be helpful to add a `RoleSessionName` parameter when calling `getCredentialsForIdentity`. This way, the CloudTrail logs would reference the AssumedRole as `arn:aws:sts::294050392401:assumed-role/RoleToAssume/MyCustomRoleSessionName` instead of `arn:aws:sts::123456789012:assumed-role/RoleToAssume/CognitoIdentityCredentials`.
2. It seems `getCredentialsForIdentity` is calling `AssumeRoleWithWebIdentity` under the hood so you can track that in CloudTrail if necessary.

Also, you cannot use the Basic Flow when using RoleMapping (roles included in the Id Token). In this case, `getCredentialsForIdentity` is the only choice.
