### ISSUE TITLE
CloudFront.updateDistribution() documentation incorrectly refers to XML configuration

### ISSUE THREAD

**Issue by tvald** [aws/aws-sdk-js#1668]
The [JavaScript SDK documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront.html#updateDistribution-property) for `CloudFront.updateDistribution()` describes the CloudFront configuration as an XML document in several places:

> Update the XML document that was returned...

> In the request body, include the XML document that you updated...

> ...we made substantial changes to the format of the XML document that you include...

The `CloudFront.getDistribution()` returns a JSON object of which conforms to `AWS.CloudFront.Types.Distribution`. This object should be modified and provided to `CloudFront.updateDistribution()`. No XML is involved.

**Comment by jeskew** [comment]
Hi @tvald,

The [AWS SDK for JavaScript API documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html) for service clients is largely derived from the service's API documentation, which means that the docs sometimes describe the on-the-wire format of data rather than the data expected by the SDK. (Note the similarity between the linked document and https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_UpdateDistribution.html.)

As you point out, the SDK expects to receive (and will return) JavaScript types rather than XML. I'll reach out to the service team to ask them to update the documentation.
