### ISSUE TITLE
CognitoIdentityServiceProvider.globalSignOut() is unable to revoke IdToken 

### ISSUE THREAD

**Issue by KMNowak** [aws/aws-sdk-js#1687]
Function `CognitoIdentityServiceProvider.globalSignOut({AccessToken})` revokes all tokens **except for** `IdToken`. 

Shouldn't it be revoked too? 

The `IdToken` is commonly used in `ApiGateway` `Cognito User Pool Authorizer`. Revoking it with remaining tokens would make it much easier to block access to resources with this token after user signs out.

**Comment by AllanFly120** [comment]
Hi, 
Because `IdToken` is represented as a [JSON Web Key Token](https://tools.ietf.org/html/rfc7519), it's signed with a secret or private/public key pairs, which means even if you revoke the IdToken, there is no way to revoke the distributed public key. And IdToken has a short life span, it will expire in a short time.

**Comment by KMNowak** [comment]
Thank you @AllanFly120 for very useful answer. According to it, would you please suggest best way to block/allow access to resources on the level of `API Gateway` with use of `access token`?

**Comment by AllanFly120** [comment]
Frankly, I'm not sure what is the best practice for the circumstance you are referring to:)
But you can go to developer forum (https://forums.aws.amazon.com/forum.jspa?forumID=199&start=0).
