### ISSUE TITLE
aws-sdk adminCreateUser

### ISSUE THREAD

**Issue by OpenxcellOmTeam** [aws/aws-sdk-js#1693]
Using the adminCreateUser method, even on passing email id as the username parameter, the aws console shows the username as the sub id generated by cognito. Is there a way to set email as username on adding email in adminCreateUser?

```
import AWS from 'aws-sdk';
const admin = new AWS.CognitoIdentityServiceProvider();

admin.adminCreateUser({
    UserPoolId: patientConfig.UserPoolId,
    Username: req.body.email,
    ForceAliasCreation: true,
    UserAttributes: attributeList,
    DesiredDeliveryMediums: ['EMAIL']
  }, (err, data) => {
    if(err) return next(err);
    res.sendStatus(200);
  });
```

**Comment by chrisradek** [comment]
@OpenxcellOmTeam 
Since this question is related to how a service API works, can you post your question to the [`Amazon Cognito forums`](https://forums.aws.amazon.com/forum.jspa?forumID=173)? The service team will be better equipped to answer questions related to the API.

If it is determined there is an issue with the SDK, please feel free to re-open this issue or create a new one.
