### ISSUE TITLE
getting the objects within a folders / subfolders

### ISSUE THREAD

**Issue by seaBass3** [aws/aws-sdk-js#1700]
Hello - I understand that S3 buckets use a flat file systems and that folders are really nothing more than a prefix to a key.  Something like if a object's key is "Untitled-10.jpg" and was located in a subfolder of "NFB" folder called "IH-6210-JA"; the actual key name would be "NFB/IH-6210-JA/Untitled-10.jpg" (if I understand this concept correctly).  [I have studied the example located here.](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html?shortFooter=true); specically the listAlbums function.  

The problem I'm having is listAlbums function will only show the root folders.  How would you allow it to show subfolders of a parent folder.  I would ultimately just like to be able to have a function that would return the objects in a subfolder.  Is this possible?  I've spent hours looking for an example how to do this.  Could someone please help clarify this or possibly provide an example.  I'm using this SDK in the browser only.

Thanks in advance for any help.

**Comment by chrisradek** [comment]
@seaBass3 
The listAlbums code you looked at is a good starting point.

Right now the SDK doesn't have a built-in way to distinguish folders from files, but here's what you could do:

1. Call `s3.listObjects` with a `Delimiter` set to `/`. 
This will cause S3 to return any objects that do not contain `/` and that start with the current `Prefix` (empty unless you specify it). This effectively gives you all the 'files' in a given folder. This also gives you any object that contains a '/' in the `CommonPrefixes` array. Generally, you can treat these prefixes as subfolders.
2. Call `s3.listObjects` with a `Delimiter` set to `/` and a `Prefix` set to a `CommonPrefix` found in an earlier step.
Since the CommonPrefixes you found in step 1 should represent sub-folders in your S3 bucket, when you set `Prefix` to one of these with the `Delimiter` still set to `/`, S3 will effectively return a list of objects in the 'folder' defined by `Prefix`.

You can add extra checks to ensure that your 'folders' aren't actually objects that contain data, though the above strategy should work otherwise. You can also add metadata to folders to make those checks easier.

I'm going to mark this as a feature request since this sounds like a useful feature to bake into the SDK as well. Let me know if my response doesn't make sense.

**Comment by seaBass3** [comment]
Thanks again for your help.  I was able to take your advice and figure this out.  I have everything working the way I need it.  I love the fact that I can work directly with the S3 from the browser and not have to go through a PHP server!  Have a great day!
