### ISSUE TITLE
AWS.config.setPromisesDependency(Bluebird) is not Bluebird-y

### ISSUE THREAD

**Issue by jeffbyrnes** [aws/aws-sdk-js#1714]
Given this:

```javascript
const Bluebird = require('bluebird')
const AWS = require('aws-sdk')
const s3 = new AWS.S3()

s3.config.setPromisesDependency(Bluebird)
```

If I then try this:

```javascript
const findLatestRemoteTimestamp = Bluebird.coroutine(function * () {
  const now = Date.now() / 1000
  let timestamp = Math.ceil(now / 600) * 600

  while (timestamp > now - 3600) {
    try {
      // let imageHeadObject = yield headObject(s3Params(timestamp))
      let imageHeadObject = yield s3.headObject(s3Params(timestamp)).promise()

      if (!isValidPNG(imageHeadObject)) {
        throw new Error('We have asked for a PNG that is not a PNG')
      }

      log.info('Found a PNG, syncing this timestamp: %d', timestamp)
      return timestamp.toString()
    } catch (err) {
      if (err.code === 'NotFound') {
        log.info('No tiles found for timestamp %d, continuing', timestamp)
        timestamp -= 600
      } else {
        throw err
      }
    }
  }
```

I end up with a number of these warnings if `NODE_ENV=development`:

```
Warning: a promise was rejected with a non-error: [object Error]
```

Which appear to emanate from `yield s3.headObject().promise()`.

If, instead, I do:

```javascript
const headObject = Bluebird.promisify((params, callback) => s3.headObject(params, callback))

# [snip]

let imageHeadObject = yield headObject(s3Params(timestamp))
```

No warnings are emitted.

Seems like something’s awry.

**Comment by chrisradek** [comment]
@jeffbyrnes 
It looks like Bluebird does a few checks on the `error` object that is rejected and then logs this warning itself. They have an explanation about the warning [here](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error).

Some of the errors received from services don't contain message data, so in those cases, the `error.message` field is `null`. Bluebird specifically checks for a `message` field and logs that warning if it isn't available. Native promises allow for this behavior, but Bluebird is being stricter in this case.

I don't know the internals of Bluebird that well, but it looks like they go down a different code path when you use `Bluebird.promisify`, so that warning isn't logged even though the `error.message` field is still null.

We could update our logic so that we set the message to an empty string if we can't otherwise determine the error message from what the service sends us. This would satisfy Bluebird.

**Comment by jeffbyrnes** [comment]
Thanks for spotting that, @chrisradek; I totally missed their explanation while diving into this.

Interesting that `Bluebird.promisify` doesn’t log that warning, even though `error.message` is the same `null` value. `¯\_(ツ)_/¯`

It feels kinda gross to set the message to an empty string when it is nonexistent (and thus, `null` is, to my mind, the correct value).

I’ll defer to you!

**Comment by chrisradek** [comment]
Agreed. An empty string message doesn't provide any additional info. Closing!
