### ISSUE TITLE
Missing TypeScript Definitions

### ISSUE THREAD

**Issue by sgtoj** [aws/aws-sdk-js#1729]
Missing:
- `AWS.NodeHttpClient()`
- `AWS.Signers`
- `AWS.HttpRequest()`
  - First parameter should be an URI (string) 
  - Currently no parameters are allowed

Example of a current hack, with TS strict mode enabled, to bypass these missing definitions:
```
let client = new (AWS as any).NodeHttpClient()
```

**Comment by jeskew** [comment]
Hi @sgtoj,

The classes and namespace you mention are considered an implementation detail of the SDK. We generally only provide typings for the files that are part of the SDK's public-facing interface.

**Comment by alex-birch** [comment]
Hi @jeskew ,

I think I just encountered the same issue with the util library.

This library is referenced in the [AWS IoT documentation](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html#mqtt).

In order to use it I had to cast as well:
```
import * as AWSx from 'aws-sdk';
...
        var AWS = AWSx as any; 
        var kDate = AWS.util.crypto.hmac('AWS4' + key, date, 'buffer');
```
Should the util library be included in the typings as it's referenced in the public facing docs, or am I doing something wrong?

Thanks

**Comment by atraver** [comment]
Similarly, when reading about how to implement alerting for ElasticSearch, both `NodeHttpClient` and `Signers` are used in the example code: https://aws.amazon.com/blogs/database/implementing-alerting-on-amazon-elasticsearch-data/

Are these classes truly "implementation details," and if so, what are the alternatives (especially since AWS's blogs/docs are suggesting their use)?

**Comment by ArnfinnA** [comment]
Hello 

Sounds like good plan. I like it. Hi hi 

Mvh Arnfinn Aursøy

**Comment by adcreare** [comment]
I think its fairly clear that this isn't a "private" part of the SDK. 
Use of these methods ss all over the aws sample code and documentation.

**Comment by caki0915** [comment]
+1 For this one
`AWS.HttpClient` is missing types as well. 
It is used together with `AWS.Signers` in [AWS Elastic Search Node Documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node)

**Comment by srchase** [comment]
Hello,

I'm opting to close this issue.

Check out SignatureV4 in [v3](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/signature-v4-node) of the SDK. It was purpose built to be public and supported.  v3 is in preview, but would be a good solution once it's ready for production use.

**Comment by dashmug** [comment]
@srchase Because of the missing Typescript definitions, we can't utilise what's shown in the ElasticSearch documentation here: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node

**Comment by rabbitXIII** [comment]
@srchase is there any update here?  It has been 8 months, and the documentation for elasticsearch remains the same, referring users to rely on AWS.HttpClient.
