### ISSUE TITLE
"getLoadBalancers" is missing

### ISSUE THREAD

**Issue by christian-bromann** [aws/aws-sdk-js#1760]
It looks like that `elbV2.GetLoadBalancers` can not get accessed via JS API. It seems to be available in the Java client though: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/autoscaling/model/DescribeLoadBalancersResult.html#getLoadBalancers--

**Comment by jeskew** [comment]
Hi @christian-bromann,

The AWS SDK for JS returns regular JS objects as operation results, so you would just access `result.LoadBalancers` rather than calling a `result.GetLoadBalancers` method.

Please see http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELBv2.html#describeLoadBalancers-property for an example of how to use the `elbv2.describeLoadBalancers` operation.

**Comment by christian-bromann** [comment]
Hi @jeskew,
thanks for your quick response. I missed that the `elbv2.describeLoadBalancers` params are optional filters. Thanks!
