### ISSUE TITLE
TypeError: self.body.read is not a function in managed_upload

### ISSUE THREAD

**Issue by againer** [aws/aws-sdk-js#1761]
Seeing the following error:
TypeError: self.body.read is not a function --
https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L414

From --
https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L182

My aws-sdk version is v2.135.0 and node version is 6.10.0.

This issue occurs when using S3.upload where the `Body` is of type `Stream`.

**Comment by AllanFly120** [comment]
Hey @againer,
Sorry I cannot reproduce the issue here. It's probably because your stream class doesn't support read(). Would you mind sharing your code snippet here?

**Comment by againer** [comment]
Sure thing -- https://github.com/oohnoitz/node-gifsicle-stream/blob/master/lib/Gifsicle.js#L72.

**Comment by againer** [comment]
@AllanFly120 -- https://github.com/aws/aws-sdk-js/pull/1762.

**Comment by AllanFly120** [comment]
Thank you for contribution. We will review it later.

**Comment by mikermcneil** [comment]
@AllanFly120 @againer Seeing this error in the Readable stream produced by the `request` package.  As far as I can tell, it's because `request` is using the `.body` property -- a passthrough stream is a decent workaround for this.  But it doesn't solve the big issue:

The main problem is that, regardless of the problematic nature of the inbound stream, since aws-sdk throws in an asynchronous callback in this case, this error crashes the process, and there's not a good solution to work around it in userland.

Specifically, I've seen this pop up in `aws-sdk@2.265.1`.  (Tried recently upgrading to `2.391.0` and hoping that prevents the crashing issue-- haven't been able to determine whether or not upgrading fixes it yet, but wanted to share my findings in case it helps anyone else out)

**Comment by mikermcneil** [comment]
see also https://github.com/aws/aws-sdk-js/issues/2100
