### ISSUE TITLE
Memory leak with dynamodb putItem

### ISSUE THREAD

**Issue by aniketdd** [aws/aws-sdk-js#1777]
Facing a memory leak problem with continuos dynamodb putItem calls.
my code is:
```javascript
const parsedData = nmeaParser.parse(packet);
if (parsedData) {
  const convertedDataArray = convertGpsData(parsedData);
  convertedDataArray.forEach(dataToSend => this.dynamoDB.putItem(dataToSend));
}
```

Above code is called whenever a gps device sends its location coordinates which need to be updated in  dynamodb. There are currently 100 devices sending their data every minute.
Over a period of a day , memory grows beyond 1.5gb until app crashes due to memory crunches.
I have tried using callbacks, promises and documentClient api. All method leads to extensive memory use over time.
Also tried manually calling global.gc() every minute after exposing garbage collector  for the node app. still facing the same issue. On commenting putItem call, memory does not grow beyong 60mb.

Any help is appreciated.
Thanks.

**Comment by chrisradek** [comment]
@aniketdd 
Do you have an idea of how many putItem calls you're making per minute?

Usually when we see this sort of behavior, it's due to a larger number of requests being submitted than can be processed, over an extended period of time. 

The SDK by default sets the max number of sockets per host to 50, so once you have more than 50 requests in-flight at a time, they are queued until a request completes and frees up it's connection for another request. If over a long period of time more requests are created than can be completed, that queue increases, taking up additional memory.

There are a couple changes you could make to impact this.
1. Batch DynamoDB writes instead of calling multiple putItem calls. This should significantly reduce the number of requests you make. See [batchWriteItem](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#batchWriteItem-property).
2. Increase the maximum number of sockets. See docs [here](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-maxsockets.html). This will require some experimentation to find the optimal value for your use case.

If you create a custom agent (configuring max sockets provides an example), you can also monitor the number of requests that are queued to verify that this is indeed what's happening. You may need to look at some private fields on the agent to get at this info.

**Comment by aniketdd** [comment]
Currently i am making close to 600 calls per minute.
i dont see any call being delayed/queued as receiving response for the all calls immediately.
I will get back with the result of using batchWriteItem.
Thanks
