### ISSUE TITLE
Questions: how to add encryption to millions of files already uploaded to S3 bucket?

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1778]
Hi, 
My service already uploaded millions of files to an bucket and new requirement is to enable server side encryption on all those files. I only found out per object level enable but not bucket level. Is there an efficient way to enable aes256 on all files already there?

Thanks,
Amy

**Comment by chrisradek** [comment]
@testtshoretel 
The quickest way to enable aes256 encryption on your files already stored in S3 is going to involve listing all your objects in your bucket, checking which ones already have `ServerSideEncryption`, and copying the ones that aren't encrypted, this time with encryption.

Fortunately, you don't have to copy all your files locally first. Once you have your list of objects to copy, you can call [`s3.copyObject`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) so that S3 handles the copy for you.

For example, if your bucket is called `BUCKET` and one of your object keys is `SoonToBeEncrypted.txt`, you could do the following:
```javascript
// prove that the object isn't currently encrypted
async function example() {
  let headData = await s3.headObject({
    Bucket: 'BUCKET',
    Key: 'SoonToBeEncrypted.txt'
  }).promise();
  console.log(`File is encrypted? ${!!headData.ServerSideEncryption}`);

  // copy file, this time with encryption
  await s3.copyObject({
    Bucket: 'BUCKET',
    CopySource: '/BUCKET/SoonToBeEncrypted.txt',
    ServerSideEncryption: 'AES256'
  }).promise();

  // verify file is now encrypted server-side
  let headData = await s3.headObject({
    Bucket: 'BUCKET',
    Key: 'SoonToBeEncrypted.txt'
  }).promise();
  console.log(`File is encrypted? ${!!headData.ServerSideEncryption}`);
}
```

Side-note: If you want to make sure all new objects are encrypted, you can also create a Lambda function that is triggered anytime an object is written to your S3 bucket, check if it has server-side encryption, and do the same copy if it isn't.
