### ISSUE TITLE
retryDelayOptions vs UnprocessedItems

### ISSUE THREAD

**Issue by JoshuaWise** [aws/aws-sdk-js#1784]
The [documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#batchWriteItem-property) for `batchWriteItem()` describes the `UnprocessedItems` field, and says we should use `batchWriteItem()` in a loop to retry any `UnprocessedItems` that are returned.

If I use `retryDelayOptions`, which is supposed to cause automatic retrying, do I still need to implement `batchWriteItem()` in a loop?

**Comment by chrisradek** [comment]
@JoshuaWise 
You would still need to implement `batchWriteItem` in a loop.

The SDK retries will retry a request if DynamoDB throttled your request, and for a [few other error types](https://github.com/aws/aws-sdk-js/blob/v2.141.0/lib/service.js#L356-L362).

That's a different type of request failure than having `UnprocessedItems`, which may require intervention from the user to determine what to do.

**Comment by JoshuaWise** [comment]
Ahh, so `UnprocessedItems` is for items that were formatted incorrectly, or something similar? In other words, I should not just blindly retry those items without modification?

**Comment by jeskew** [comment]
`UnprocessedItems` is for writes that could not be performed due to write capacity.

`batchWriteItem` will consume the same amount of write capacity as executing each write using individual `putItem` or `deleteItem` operations. If at least one write can be performed out of the batch, DynamoDB will return a successful response because your request was partially fulfilled. If any of the requested write operations are not valid, the entire request will be rejected. So you can retry the `UnprocessedItems` without modification, though DynamoDB recommends that you use an exponential backoff strategy when doing so. [The DynamoDB Developer Guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#BatchOperations) has a bit more detail on this.

**Comment by JoshuaWise** [comment]
Ahh okay, I think I understand. There are two different types of throttling. One type of throttling is *unrelated* to write capacity, and `retryDelayOptions` handles that. The other type of throttling is related to write capacity, and we need to handle that ourselves.

Is that correct?

**Comment by jeskew** [comment]
There’s only one type of throttling, but batchWriteItem will manifest differently depending on *how much* of the batch was throttled. Imagine, for example, that you have a table with 100 provisioned write capacity and that, within the same throttling window, you send three requests with 60 writes each. The first should return a `200` status code and an empty `UnprocessedItems` array. The second should also return a `200` status code, but it should return an `UnprocessedItems` array with 20 elements, as you only had enough capacity remaining to perform 40 writes. The third request should be rejected with a throttling error, as there would be no remaining write capacity. The SDK would automatically retry the third request.

**Comment by JoshuaWise** [comment]
Ahh okay that clears it up. Thanks. It probably goes without saying but adding these specific workflow details to the documentation could be helpful to people in the future.

Thanks for the quick responses.
