### ISSUE TITLE
Confusing error message when missing region config

### ISSUE THREAD

**Issue by villelahdenvuo** [aws/aws-sdk-js#1786]
Assume the following code:

```js
this.s3 = new S3({
    apiVersion: '2006-03-01',
    region: 'eu-west-1',
    credentials: new CognitoIdentityCredentials({
        IdentityPoolId: environment.cognito.identityPoolId
    })
});
```

It will fail with a weird error:
![pasted image at 2017_10_31 09_46 am](https://user-images.githubusercontent.com/633524/32214977-e1058f6c-be20-11e7-99dd-531d37cd775c.png)

After some head banging you realize you're missing the region from CognitoIdentityCredentials, but the error message is not very helpful, you need to look at the traceback.

It would be great if the error message would be missing region and not missing credentials.

**Comment by davidmaxwaterman** [comment]
I *do* get an error regarding `region`, but I don't have a 'CognitoIdentityCredentials'. My code just has `AWS.Credentials` and `AWS.Config`. I've tried the former because it sounds like `CognitoIdentityCredentials`, but it turned to be in the latter, `AWS.Config`, that I had to add `region: 'eu-west-1',`, which kind of seems to contradict @villelahdenvuo's observation.

FWIW, the error response I had was:

```
<Error>
  <Code>AuthorizationHeaderMalformed</Code>
  <Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message>
  <Region>eu-west-1</Region>
  <RequestId>snip</RequestId>
  <HostId>snip</HostId>
</Error>
```

I didn't know what the `authorization header` was...so had to resort to trial and error.

NB, my code previously worked fine in 2.67.0, from which I had recently upgraded due to having to make a new clone (and this a new 'bower install').

**Comment by srchase** [comment]
There's a note in the documentation regarding including the region in the global AWS.config, or in clientConfig: [CognitoIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html).  Between the note and the trace, I'm opting to close this issue.
