### ISSUE TITLE
Searching uploaded files by tag

### ISSUE THREAD

**Issue by samayo** [aws/aws-sdk-js#1798]
I have about 10k images in my amazon aws bucket. Sadly when I fetch images I can only get all of them at once, I'm sure there is an option to search by tags as all images have `x-amz-tagging` ex: ... bills, photos, documents ... 

So, is there any option to search/fetch by tags?

**Comment by chrisradek** [comment]
@samayo 
Based on the S3 documentation on [object tagging](http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html), it doesn't look like filtering objects via `listObjects` with tags is currently supported.

Since this feature would need to be implemented on S3's end, please create a feature request post on the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) so they can collect your feedback.
