### ISSUE TITLE
Is there a way to capture all error responses?

### ISSUE THREAD

**Issue by bootrino** [aws/aws-sdk-js#1826]
I want to log all errors received from AWS JavaScript SDK in my application.

Ideally at one single place.  Is this possible?

thanks

**Comment by chrisradek** [comment]
@bootrino 
You can provide a `logger` to the global config, which will log data on all requests:
```javascript
AWS.config.udpate({
  logger: console
});
```

We don't provide a public method for adding event listeners to all requests today. There is a private method that accomplishes this, but it could change in any update since it is not something we currently expose through docs or typings.
```javascript
AWS.EventListeners.Core.on('error', function(err) {
    console.log(err);
});
```
