### ISSUE TITLE
"Access Denied" message with multiple credentials running in parallel

### ISSUE THREAD

**Issue by nodriza-io** [aws/aws-sdk-js#1834]
Hello, I'm having problems when I use multiple credentials in parallel... seams like one credential overlap the other one, is possible use the SDK running with multiple credentials at same time in parallel or the only way is en series and swap accounts.

Here is an example code:

```typescript
async.timesLimit(awsAccounts.length, 10, (i, callback) => {

	let awsAccount = awsAccounts[i]

	const AWS = require('aws-sdk')

	let config = {
		accessKeyId: awsAccount.awsAccessKey,
		secretAccessKey: u.decrypt(awsAccount.awsSecretAccessKey),
		region: awsAccount.region
	}

	AWS.config.update(config)

	const tasks = {
		task1: (callback) => {
			// s3.getObject -> Return Random 403, Access Denied
			callback()
		},
		task2: (callback) => {
			// s3.getObject -> Return Random 403, Access Denied
			callback()
		},
		task3: (callback) => {
			// s3.getObject -> Return Random 403, Access Denied
			callback()
		}		
	}
	async.series(tasks, (err, _results) => {
		if (err) return callback(err)
		callback()
	})

}, (err) => {
	if (err) return callback(err)
	callback()
})
```

**Comment by jeskew** [comment]
Configuration is immutable once a client has been instantiated, but you will need to create a client for the current state of `AWS.config` to be captured. It's a global object, so capturing the return of `require('aws-sdk') with a block-scoped variable will not isolate their configuration. Rather than passing configuration to `AWS.config.update` in one scope and then creating S3 clients in another, you could try passing that configuration to the S3 client constructor and allowing the tasks defined to close over that client:

```
const s3 = new AWS.S3({
    accessKeyId: awsAccount.awsAccessKey,
    secretAccessKey: u.decrypt(awsAccount.awsSecretAccessKey),
    region: awsAccount.region
});
const tasks = {
    task1: (callback) => {
        // s3 is available from the parent scope
        callback()
    },
    // etc
};
```

**Comment by nodriza-io** [comment]
Jonathan thank you for your quick help, the solution worked for me.

**Comment by jeskew** [comment]
Glad to hear it!
