### ISSUE TITLE
is there a way that url never expires?

### ISSUE THREAD

**Issue by ashrafmangalore** [aws/aws-sdk-js#1844]
Hi
I am using `aws-sdk` in node.js
    `const params = {
                Bucket: config.AMAZON_S3_BUCKET,
                Key: key
            };`             
    
    s3.getSignedUrl('getObject', params, (error, resp) => {
                if (err) {
                    console.log('s3 getSignedUrl err: ', error);
                } else {
                    console.log('displayed url from s3: ', resp);
                }
    });`
to get the image URL from s3 bucket. But the url is expires after 15 minutes. so how can we make that it never expires?

**Comment by chrisradek** [comment]
@ashrafmangalore 
As far as I know, there isn't a way to create a presigned url for S3 that lasts forever. There's a good explanation on [StackOverflow](https://stackoverflow.com/a/35487677) on how long urls can last for.

The gist is, a presigned URL can only last as long as the credentials used to generate them, or 7 days (when using signature version v4), whichever is shorter.

If you don't care about who can see the URL, you can set it to be [public readable ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObjectAcl-property), otherwise you'd need to regenerate the URL.
