### ISSUE TITLE
Wrong d.ts file for HttpRequest

### ISSUE THREAD

**Issue by slawiko** [aws/aws-sdk-js#1847]
[Here](https://github.com/aws/aws-sdk-js/blob/master/lib/http.js#L95) in constructor we have two arguments:

```ts
constructor: function HttpRequest(endpoint, region) {
    endpoint = new AWS.Endpoint(endpoint);
    ...
    this.region = region;
    ...
  },
...
```

but in [typings](https://github.com/aws/aws-sdk-js/blob/master/lib/http_request.d.ts) there is no constructor.

I suggest to add something like:

```ts
    /**
     * Constructs HttpRequest object with provided endpoint and region
     */
    constructor(endpoint: Endpoint, region: string);
```

**Comment by chrisradek** [comment]
@slawiko 
The typings are meant to match the publicly documented APIs of the SDK. The `HttpRequest` class shouldn't be instantiated directly, but is generated by the SDK and is a member of `AWS.Request` objects. It probably should have just been defined as an interface on the Request object directly.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/HttpRequest.html

Can you share what your use case is for using `AWS.HttpRequest` directly? Right now since the constructor is marked as private, we could change it, but if there's a legitimate reason for using it directly we could expose it as a public API.

**Comment by slawiko** [comment]
@chrisradek ok, here is my use case:

I would like to embed kibana (ES) dashboards in my web-application. I need authorize request on kibana for that. So I have created route `/kibana` and proxy, which just authorizes request:

```ts
(proxyReq: ClientRequest, req: IncomingMessage, res: ServerResponse, options: ServerOptions): void => {
  const endpoint = new Endpoint(kibanaHost);
  // Here I'm instantiating HttpRequest and filling it with authorization headers etc.
  const request = new HttpRequest(endpoint, AWS_REGION);
  request.method = req.method || '';
  request.path = req.url || '';
  if (Buffer.isBuffer(req.body)) {
    request.body = req.body;
  }
  request.headers.Host = kibanaHost;

  const sign = new SignerV4(request, 'es');
  sign.addAuthorization(credentials, new Date());

  proxyReq.setHeader('Host', request.headers.Host);
  proxyReq.setHeader('X-Amz-Date', request.headers['X-Amz-Date']);
  proxyReq.setHeader('Authorization', request.headers.Authorization);
  if (request.headers['x-amz-security-token']) {
    proxyReq.setHeader('x-amz-security-token', request.headers['x-amz-security-token']);
  }
}
```

Maybe this way isn't nice, could you suggest something else?
