### ISSUE TITLE
AWS S3 AccessDenied

### ISSUE THREAD

**Issue by michaelyfan** [aws/aws-sdk-js#1872]
Hello,

I'm having trouble accessing S3 programmatically. I'm using federated identities to get temporary credentials to access other AWS services, which works as expected with DynamoDB. However with S3, I get the error AccessDenied. Here is my code:

```
app.post('/api/getfiles', function(req, res) {
  var AWS = require('aws-sdk');
  var s3 = new AWS.S3({apiVersion: '2006-03-01'});
  AWS.config.update({
    region: 'us-east-1',
    accessKeyId: req.body.accessKeyId,
    secretAccessKey: req.body.secretAccessKey,
    sessionToken: req.body.sessionToken
  });
  s3.listBuckets(function(err, data) { // for example
    if (err) {
      console.log(err, err.stack);
    } else {
      console.log(data);
      res.send(/* blah blah */);
    }
  });
})
```

**Comment by AllanFly120** [comment]
The code looks fine. I think the reason for this issue is the permission setting. One thing you can check is whether permission to S3 has been added to the IAM role you are using for federated identities. The permission policy should contain something like:

```json
{
  "Effect": "Allow",
  "Action": [
    "s3:*"
  ],
  "Resource": [
     "*"
  ]
},
```
This statement grant permission to ervery operation in S3 from any resources

**Comment by srchase** [comment]
As there has been no followup, I'm assuming this has been resolved.  Let us know if it needs re-opened.
