### ISSUE TITLE
AWS SDK TRANSLATE Service not working correct from EN(english) to FR (franch)

### ISSUE THREAD

**Issue by odykyi** [aws/aws-sdk-js#1873]
*Actual Result:*
Text EN "Hello world" -> FR "Hello world" 
It's not correct

*Expected Result: *
Text EN "Hello world" -> FR "Bonjour le monde" 

*AWS Translate Service*
*AWS region us-east-1*
*node module version aws-sdk@2.180.0*
*console AWS*: https://console.aws.amazon.com/translate/home?region=us-east-1#explorer
*screenshot*: https://imgur.com/a/EwEQU

Thanks!

**Comment by odykyi** [comment]
@lsegal @konklone @corymsmith @ericb @ColmHally Please

**Comment by jeskew** [comment]
I can forward this question on to the service team, but the fastest way to get an answer would be [to open a ticket with AWS support](https://console.aws.amazon.com/support/home#/case/create?issueType=customer-service).

Just to rule out any client side issues, could you post a code snippet so that I can attempt to reproduce the issue and make sure the request being sent is well-formed?

**Comment by jeskew** [comment]
According to the service team, this issue has been resolved. Please feel free to reopen if you have any questions or concerns.

**Comment by odykyi** [comment]
@jeskew , thanks, issue fixed
