### ISSUE TITLE
[AWS.SES] Retry mechanism on response parse failure results in multiple mails sent

### ISSUE THREAD

**Issue by vinay20045** [aws/aws-sdk-js#1913]
**Issue**: 
When sending emails with the SDK, if for any reason there is an error while parsing the XML response from the API call, the retry mechanism causes the API call to be executed multiple times (1 + 3 in my case) even though the initial call was successful. 
I came across this issue when trying to send emails through the SDK in a web worker by faking DOMParser.

**Steps to Reproduce**: 
Invalidate the DOMParser (Ex: window.DOMParser = true;) and try to send an email.

**Reference**:
1. Code block - line 11,419 to 11,455
2. Code block - line 945 to 951

**Environment**:
AWS SDK 2.188.0 | Chrome 63.0.3239.132

**Comment by chrisradek** [comment]
@vinay20045 
We know that in some cases, the SDK will receive a successful response but receive malformed XML, which is why this check is in place. We might be able to be a little smarter about how we handle this though.

However, in the short term, you can remove the [data extraction](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#extractData-event) part of a request lifecycle so that the XML response body isn't parsed. That might be more applicable in your case since you don't have an XML parser available.

Example:
```javascript
const request = ses.sendEmail(/* params */);
request.removeAllListeners('extractData');

// send with callback
request.send((err, data) => {});
// or use promise
request.promise().then(() => {}).catch(() => {})
```

**Comment by vinay20045** [comment]
@chrisradek Thanks for suggestion. I've implemented an alternate for now, but, I will try this later and let you know.

Now coming to the actual issue, are you saying that the API sends malformed XML at times? However, in my tests, the API was sending back the **correct XML** but the **parser was not available**.

Though i'm not in a position to comment how to handle this as I do not fully understand the flow, in my view there are a couple of problems here...
1. The error message thrown says "Parse error in document" event though the Parser itself was not available and the XML itself might have been correct. This must be enhanced.

2. When the execution enters this code block, the assumption is that the request went through therefore "retryable" must be false while still throwing an error. This way the user can catch it and handle however it is appropriate. For example, look up the message execution status again using the message id etc.

Please let me know if my understanding is wrong anywhere.
