### ISSUE TITLE
AWS.SNS APNs and p8 cert + teamId

### ISSUE THREAD

**Issue by akaNightmare** [aws/aws-sdk-js#1914]
Hello,

trying to setup SNS for mobile app (APN & GCM) and APN requires p12 cert, private and public key, but according to http://help.apple.com/xcode/mac/current/#/dev11b059073 APN provides p8 file, teamId, keyId.

How to create AWS SNS with p8 file?

**Comment by chrisradek** [comment]
@akaNightmare 
Did you already attempt the instructions from the SNS docs [here](https://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html)?

If that doesn't help, please create an issue on the [SNS forums](https://forums.aws.amazon.com/forum.jspa?forumID=72). The SNS team will be able to provide better support for this since it's specifically around using their service/API.
