### ISSUE TITLE
Missing region in config when using Lambda and config file

### ISSUE THREAD

**Issue by LinusU** [aws/aws-sdk-js#1921]
I'm getting the following error when trying to run `lambda.listFunctions()`:

```text
ConfigError: Missing region in config
```

The region is set in the config file, and was added there by the `aws configure` command.

My environment:

```text
AWS_PROFILE=myprofilename
```

My `~/.aws/credentials` file:

```text
[myprofilename]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
```

My `~/.aws/config` file:

```text
[profile myprofilename]
region = us-west-2
```

**Comment by albinekb** [comment]
I also have the same problem, but without profiles:

My `~/.aws/credentials` file:
```
[default]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
```

My `~/.aws/config` file:
```
[default]
region = eu-central-1
output = json
```

It works with other aws-sdk functions, but it seems like the lambda functions aren't reading the config correctly

**Comment by LinusU** [comment]
> It works with other aws-sdk functions, [...]

Yeah, I should add that I also tested a call to S3, and that went thru without issues...

**Comment by jeskew** [comment]
The config file is only loaded if the `AWS_SDK_LOAD_CONFIG` environment variable is set to a truthy value. Since this feature was not present in version 2.0.0 and could affect the runtime characteristics of applications running in environments already configured for the AWS CLI, config loading was introduced as an opt-in feature.

**Comment by albinekb** [comment]
Yes, we later found that! Perhaps it could be mentioned in the docs of aws-cli where AWS.config, it would be nice if it stated that the flag must be set if you want to load the config from the environment. 

This is very useful when making custom CLIs like HTTPS://github.com/linusu/scandium, since it will load the config in the same way as the regular awscli, making it easy to use for the end user :)

**Comment by LinusU** [comment]
Yes, that was it 😄 

Would love for the "Using a Shared Config File" section to get a little note about that here:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html

Thanks for the help!
