### ISSUE TITLE
CloudSearchDomain Search properties are always returned as an array

### ISSUE THREAD

**Issue by tbo** [aws/aws-sdk-js#1941]
I have defined an index in AWS CloudSearch, that contains a mixture of primitive types and arrays. But if I execute a search via CloudSearchDomain, then all properties are returned as an array. The test search in the web dashboard returns the correct format. The same holds true for direct API calls:

```
curl "https://endpoint/2013-01-01/search?q=foo&cursor=initial&size=10"
```

This is likely a duplicate of #791, which was closed for reasons, that I cannot comprehend.

**Comment by AllanFly120** [comment]
As it's mentioned in #791, the request query is a bit different like [here](https://github.com/aws/aws-sdk-js/blob/880dec7910972f7c0f4449ddb31d2f80acc06f59/apis/cloudsearchdomain-2013-01-01.min.json#L17). The service team specifies in the model that the query must contain `format=sdk`. I think maybe they believe return everything in the array would reduce the complexity to determine whether the response is an array. Since it's not a bug, we cannot update it.
