### ISSUE TITLE
s3 headobject executes multiple times skipping for loop

### ISSUE THREAD

**Issue by Babloo18v** [aws/aws-sdk-js#1950]
I have Multiple Buckets Stored With Multiple Files.. For Suppose I have I have a filenames with Testing_rquil , Tester_qwsw , Tested_wsews stored in Bucket1 , Bucket2 , Bucket3

Testing_rquil - Bucket1 Tester_qwsw - Bucket2 Tested_wsews - Bucket3

when i click download button i get the filename in Eval..

var dataArray = {Bucket1,Bucket2,Bucket3}

// this function is called on download click

   function Getfilefromamazon (s3filename){

            for (var i = 0 ; i < dataArray.length; i++) {

                    var params = {
                        Bucket: dataArray[i],
                        Key: s3filename  // example Testing_rquil
                    };

 s3.headObject(params).on('success', function (response) {
                        console.log("Key was", response.request.params.Key);

                    }).on('error', function (error) {

                        //    //error return a object with status code 404
                    }).send();

}
}

This is my function to download the file from amazon , i need to search the file , and where it is present in amazon s3.. I used for loop to check where it is present but the headobject is getting the file but returns me the last bucket in dataArray which is of no use.

i am trying to catch the file and skip the for loop execution soon after i get the file but its not working..

Please do help.. i need to search the file in multiple buckets using javascript..if i found skip the for loop and comeout of it..

**Comment by chrisradek** [comment]
@Babloo18v 
Whenever you make a request to a service, that request happens asynchronously. This means that the JavaScript event loop does not pause while it waits for a response to come back from the server (S3 in this case). 

Instead, your for loop is going to create and send N requests immediately, not wait for any responses.

There are a lot of tutorials out there on how to handle asynchronous flow in JavaScript, but the easiest (in my opinion) is to use [`async/await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

Here's an example:
```javascript
async function getFile(key) {
  for (let i = 0; i < buckets.length; i++) {
    try {
      const params = {
        Bucket: buckets[i],
        Key: key
      };
      const result = await s3.headObject(params).promise();
      // found file, do stuff
    } catch (err) {
      // error received, do stuff
    }
  }
}
```

I'm going to close this issue since it's a more general JS question, where stackoverflow would better serve you. If you do encounter an issue with the SDK, please feel free to reply or open a new issue.
