### ISSUE TITLE
Extending service classes

### ISSUE THREAD

**Issue by ncave** [aws/aws-sdk-js#2006]
If one is to try extending one of the service classes (S3, SSM, DocumentClient, etc.) like that:

```
class MyS3 extends AWS.S3 { }
var s3 = new MyS3();
```

that results in a run-rime error on construction right about [here](https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L30).
Is that the expected behavior?

**Comment by AllanFly120** [comment]
Hi @ncave,
It's generally not advisable to `extend` from client classes, because they are not written in normal javascript class. Extending from them may not be able to inheritate the correct constructor. But I still haven't find which difference results to the error. I will reply here after more investigation.

**Comment by srchase** [comment]
I'm opting to close this issue.  As @AllanFly120 mentioned, it is not recommended to extend from client classes.
