### ISSUE TITLE
Problem deleting message from SQS FIFO queue:

### ISSUE THREAD

**Issue by taju20910** [aws/aws-sdk-js#2010]
Team,
I have set visibility timeout as 90 seconds and I am trying to delete the message within this time range only. Still message in SQS is not getting deleted most of the times . Also when I call message_obj.delete() func it kind of gets stuck there for sometime ( I have a log next which is not getting printed).
Can this in anyway be related to network issue ?
Or is there anything else I am missing out on .

**Comment by AllanFly120** [comment]
Hey @taju20910 
Can you open the logger(for example: `var sqs = new AWS.SQS({logger: console});`) to confirm whether the request retries when the operation is 'stuck there'? If it is an issue from SQS service instead of SDK itself, [AWS SQS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=12) may be a better place to turn to. You can provide the request id and the service time can access the log to confirm the issue.
