### ISSUE TITLE
DynamoDB documentation is different than this module's actual behavior

### ISSUE THREAD

**Issue by aviggiano** [aws/aws-sdk-js#2018]
Hello,

The current documentation on DynamoDB methods is different than this module's actual implementation. 

First of all, the function names are not the same between the tho resources. On the JavaScript SDK documentation website, the [`UpdateItem`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) action is called [`updateItem`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#updateItem-property), but this module calls it just [`update`](https://github.com/aws/aws-sdk-js/blob/master/clients/dynamodb.d.ts#L243).

Secondly, the request parameters on the AWS documentation says that values to be marshalled objects, while the JS module expects [normal javascript objects](https://stackoverflow.com/a/33534945/1849920). It seems that this difference is going on [for a long time](https://forums.aws.amazon.com/thread.jspa?threadID=208820). I haven't tried using other methods, but I believe they might have the same problem.

Just as a side node (perhaps this should be on another issue I think), the error message doesn't help either:
```
{
    "errorMessage": "The provided key element does not match the schema",
    "errorType": "ValidationException",
    "stackTrace": [
        "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
    ]
}
```

**Comment by chrisradek** [comment]
@aviggiano 
I think you're confusing the low-level [DynamoDB API client](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html) with the [DynamoDB Document Client](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html).

You can instantiate the low-level DynamoDB API client by writing:
```javascript
const DynamoDB = require('aws-sdk/clients/dynamodb');
const client = new DynamoDB({/*params */});
// call updateItem
client.updateItem({/*params*/}, function(err, data){});
```
Documentation for `updateItem` is [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#updateItem-property), and the typings you shared points to this as well.

Then there is also the Document Client, which allows you to pass JSON objects directly instead of having to work with DynamoDB AttributeValues.

You can create a document client by writing:
```javascript
const DynamoDB = require('aws-sdk/clients/dynamodb');
const client = new DynamoDB.DocumentClient({/*params*/});
// call update, which works with JSON objects
client.update({/*params*/}, function(err, data){});
```

Documentation for `update` is [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#update-property).

All of the AWS SDKs have support for the low-level DynamoDB APIs, and that's what DynamoDB will also document. The DocumentClient is a higher-level abstraction that this SDK also provides.

Let me know if that helps!

**Comment by aviggiano** [comment]
@chrisradek You are right, I was looking at the wrong documentation.
From the stackoverflow question and AWS forum, it seems this is a common mistake :thinking: 

I'll close the issue. Thanks!
