### ISSUE TITLE
ETag missing from Cloudfront.getDistributionConfig when running on client

### ISSUE THREAD

**Issue by dennererthal01** [aws/aws-sdk-js#2040]
I have a test script which runs the method CloudFront.getDistributionConfig:

`CloudFront.getDistributionConfig(id, function (err, data) {
  })`

But on the response data, the ETag entry is missing, only the DistributionConfig entry is returned.
If I run this code on Node, then the ETag entry is correctly returned, but when running on the client (on browser) it doesn't.

It's necessary a configuration on the Distribution to allow returning ETag to client that I'm not aware of? 

Thanks!

**Comment by AllanFly120** [comment]
Hey @dennererthal01 ,
In browsers, because of the restriction of CORS, the browsers can only read the headers that exposed to them. It's likely that your CloudFront service doesn't expose ETag header to browsers, this is defined in the service. I'm not very familiar with CloudFront service whether you are able to set the expose headers. You can bring this question to the CloudFront service team in [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=46), they will be happy to answer your question.

**Comment by dennererthal01** [comment]
Thanks @AllanFly120, I'll close this issue as it's not related to the sdk itself.
