### ISSUE TITLE
"new AWS.Batch" is not a constructor

### ISSUE THREAD

**Issue by bosborne** [aws/aws-sdk-js#2048]
I'm currently developing a Vue Web application and I'm using https://sdk.amazonaws.com/js/aws-sdk-2.235.1.min.js. I'm not able to get an AWS Batch instance. Currently getting the following error in the browser:

_undefined is not a constructor (evaluating 'new AWS.Batch()')_

I'm able to instantiate using other classes, like AWS.S3

**Comment by AllanFly120** [comment]
Hi @bosborne,
This is similar to #2041. `AWS.Batch` service is not available in browsers by default because it doesn't support CORS. You can refer to [this file](https://github.com/aws/aws-sdk-js/blob/2b84fb51bbbb54430cc6b44d7761f0f9c65cc8ac/apis/metadata.json#L22). If the service supports CORS, it will have a `"cors": true` entry. 
You can also call for CORS support on [AWS Batch forum](https://forums.aws.amazon.com/forum.jspa?forumID=240).
