### ISSUE TITLE
MetadataService `.promise()`?

### ISSUE THREAD

**Issue by Misiur** [aws/aws-sdk-js#2062]
It seems `MetadataService#request` does not support `.promise()`. Did I miss something?

**Comment by chrisradek** [comment]
@Misiur 
Nope, you're right, it doesn't currently support promise, but it could. Since it doesn't currently return anything, we could probably just make it return a promise directly if no callback is provided, and continue to return undefined either. Marking as a feature request, but if you feel inclined would be happy to review a PR for this!

**Comment by ArnfinnA** [comment]
Can everyone please try to help me keep the information from the hackers. 

Thanks from me. 

Mvh Arnfinn Aursøy
