### ISSUE TITLE
How to upload apk file for device farm?

### ISSUE THREAD

**Issue by Luckstai** [aws/aws-sdk-js#2063]
I did not check the documentation how to upload the apk file through some api, I was able to upload the tests and a response is an s3 url.

I would like to know the right flow to follow to run the automated tests, for example:

Create project
Create Device Pool
Upload Tests
Upload APK
Create Run

**Comment by AllanFly120** [comment]
Hey @Luckstai,
Sorry for the delayed reply, have you figured out the usage of device farm? If you still have any questions, you can bring them to [developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=193). Since this is not about the usage issue of SDK, I will close this issue. Feel free to comment here if you run into any SDK issues.

**Comment by Luckstai** [comment]
Thank you very much, but I managed to solve the problem yes, see you later
