### ISSUE TITLE
Support for Custom Domain Names in Cognito

### ISSUE THREAD

**Issue by cwardcode** [aws/aws-sdk-js#2094]
A couple weeks or so ago, the option of creating Custom Domains was added to the AWS Console, along with the following documentation:
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html

We would like to link a Custom Domain with our user pool during our CI/CD process, but it doesn't look like the javascript SDK supports adding Custom Domains at this time. 

Is support for Custom Domains on any release roadmap?

**Comment by AllanFly120** [comment]
Hi @cwardcode, I think this issue is more of the service feature request. Unfortunately, we don't have extra information on each service roadmap. You can directly communicate with service team on [Cognito Forum](https://forums.aws.amazon.com/forum.jspa?forumID=173). They will be happy to answer your questions.

**Comment by cwardcode** [comment]
@AllanFly120 Cognito added the feature to their service a couple weeks ago, I was just wondering if the SDK support for the feature was on the aws-sdk-js roadmap. I thought that the SDK team would handle the integration, but if it's the service team I can definitely create a topic in the forum!  I just want to make sure I'm posting in the correct place.

**Comment by ajredniwja** [comment]
Hey @cwardcode, 

Is this still an issue, I think it should be implemented by the SDK. Closing this issue now, please reach out if you continue to see the problem.
