### ISSUE TITLE
The role of stream Passthrough In S3 Upload?

### ISSUE THREAD

**Issue by steveLuo1** [aws/aws-sdk-js#2100]
Hello,

I am trying to upload a mp3 file from a website directly to S3.
when I use   request.get(options) in uploadParams's body as follow
Method1 
 const options = {
            'url': url,
            'headers': {
                'Authorization': authorization,
            },
            'forever': true,
            'encoding': null
        };

        const uploadParams = {
            'Bucket': bucketName,
            'Key': path.basename(fileName),
            'Body':  request.get(options)
        };

        try {
            const result: ManagedUpload.SendData = await s3Client.upload(uploadParams).promise();
....
It does not work!
the error message is as follow:
 ...../node_modules/aws-sdk/lib/s3/managed_upload.js:414
    var buf = self.body.read(self.partSize - self.partBufferLength) ||
                        ^
TypeError: self.body.read is not a function
    at ManagedUpload.fillStream (/Users/mm87550/project/hit-hub-zendesk/node_modules/aws-sdk/lib/s3/managed_upload.js:414:25)
    at Request.<anonymous> (/Users/mm87550/project/hit-hub-zendesk/node_modules/aws-sdk/lib/s3/managed_upload.js:190:28)
 

But when I add Passthrough stream, then upload works! (see below), I would like to know why? 

  const options = {
            'url': url,
            'headers': {
                'Authorization': authorization,
            },
            'forever': true,
            'encoding': null
        };

        const passthrough = new stream.PassThrough();
        request.get(options).pipe(passthrough);

        const uploadParams = {
            'Bucket': bucketName,
            'Key': path.basename(fileName),
            'Body':  passthrough
        };

        try {
            const result: ManagedUpload.SendData = await s3Client.upload(uploadParams).promise();
....

**Comment by steveLuo1** [comment]
I am using  "aws-sdk": "2.224.1"

**Comment by chrisradek** [comment]
@steveLuo1 
The S3 managed upload (`s3.upload`) requires a readable stream for the `Body` field as input (when the input is a stream). Internally, the SDK will call [read](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_readable_read_size) on the the stream that's passed in so it can control how quickly to read data. It needs to do this so that it can control how many `uploadPart` requests to make at a time (this enables controlling the number of parallel requests to have at a time as well as retrying individual parts without storing the entire object in memory).

Calling `request().get()` doesn't provide a true readable stream. Instead, the object returned inherits from the Nodejs [Stream](https://github.com/request/request/blob/536f0e76b249e4545c3ba2ac75e643146ebf3824/request.js#L130) class, and then implements methods like [write](https://github.com/request/request/blob/536f0e76b249e4545c3ba2ac75e643146ebf3824/request.js#L1487). While it supports the common [flowing mode](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_two_modes) operation with `pipe` and listening for `data` events, it does not support `paused` more with `read()` since `read` is not implemented by request.

You actually figured out a work-around by piping the stream from request into a PassThrough stream. Since PassThrough streams extend Readable streams, they have the `read` method defined and can operate fully in paused mode.

Hope my response wasn't too long-winded!

**Comment by steveLuo1** [comment]
Hi Chris,

Thanks a lot for quick and great reply!

Regards,
Steve

On Tue, Jun 19, 2018 at 4:29 PM, Christopher Radek <notifications@github.com

**Comment by steveLuo1** [comment]
Hi Chris,

Do you know any better ways,. or right ways to do this?

Thanks a lot.
Steve

**Comment by mikermcneil** [comment]
@steveLuo1 I like your PassThrough approach a lot, and I think it solves a lot of problems.  Thinking of emulating that in skipper-s3/sails-hook-uploads, only problem is I'm not sure when it was added to Node off the top of my head.  will post back if I find out

**Comment by mikermcneil** [comment]
@steveLuo1 @chrisradek just verified you can use PassThrough as early as Node 8.0.0 (and probably earlier, judging by the date on [this issue](https://github.com/nodejs/readable-stream/issues/92))

![image](https://user-images.githubusercontent.com/618009/44557835-3d9ad600-a706-11e8-9269-349279ecab90.png)
