### ISSUE TITLE
Bug LEX: deleteIntent does not provide ResourceInUseException information

### ISSUE THREAD

**Issue by Nop0x** [aws/aws-sdk-js#2102]
Hey there!

Basic Info:
- AWS SDK version: aws-sdk@2.259.1
- node version: v8.11.2

Bug: 
As stated in the [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/LexModelBuildingService.html#deleteIntent-property), lexmodelbuildingservice.deleteIntent is supposed to provide information on the referenced resource, when a ResourceInUseException is thrown. However, this is not happening. The exception gets thrown, but the message is null.

Expected outcome:
The ResourceInUseException should return a reference where the intent is in use.

Thanks in advance,

Marvin

**Comment by chrisradek** [comment]
@Nop0x 
Thanks for reporting this issue.

This is currently a limitation in the JavaScript SDK due to how we remove exceptions from our service models, so the SDK doesn't know how to parse the response body to provide additional details. Now that additional details are returned in error messages by some services, we'll have to revisit that decision.

As a work-around, you can parse the response message:

```javascript
const request = client.deleteIntent(/* params */);
// send request using .send or .promise
request.send((err, data) => {
  if (err) {
    switch (err.name) {
      case 'ResourceInUseException':
        // JSON parse string to get additional details, or log it
        console.error(request.response.httpResponse.body.toString());
        return;
      default:
        console.error(err);
        return;
    }
  }
});
```

We may be able to do something similar if we can tell `message` is `null`.

**Comment by Nop0x** [comment]
@chrisradek Thanks for updating me on that issue!

Another question concerning this error: Is there any way to lower the required delay between requests? After I get the error and remove the Intent from my bot (via the API as well), I have to wait approx. 50+ seconds before I go ahead and retry the intent deletion.
I would suggest removing or lowering the delay after a successful request.

**Comment by srchase** [comment]
Hi @Nop0x,

It looks like your questions have been answered. I'm going to close this issue soon unless there's anything further.
