### ISSUE TITLE
AWS S3 on abort removes stream 'end' listeners which it shouldn't remove

### ISSUE THREAD

**Issue by equinox7** [aws/aws-sdk-js#2107]
Hi all, I am using busboy on the server side to receive files from the browser and I upload them to AWS S3. Sometimes the file is too big and the event `limit` is emitted on the stream. When this happens I `.abort()` the started upload.

On abort a `cleanup` method of the [`managedUpload`](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js) is called which does this:
```javascript
if (typeof self.body.removeAllListeners === 'function' &&
    typeof self.body.resume === 'function') {
    self.body.removeAllListeners('readable');
    self.body.removeAllListeners('end');
    self.body.resume();
}
```

So it clears **ALL** the `end` listeners including the one which was assigned by busboy. This causes the busboy's `finish` event never to be called. Since I am sending a response to the client side on busboy's `finish` — it means that I don't send any response in this case.

**I think `managedUpload` should remove only listeners assigned by AWS SDK and not all listeners.**

Here is the simplified version of my code:
```javascript
function parseForm (req, res, next) {
    
    const busboy = new Busboy({
        header: req.headers,
        limits: {
            filesSize: 1024 * 1024
        }
    });

    const s3 = new AWS.S3(/* ... */);
    
    busboy.on('file', (fieldName, fileStream, fileName, encoding, mimeType) => {
        const s3Upload = s3.upload({
            Body: fileStream,
            // ...
        });
        
        fileStream.on('limit', () => {
            s3Upload.abort();
        });
        
    });
    
    // This listener is never being called if the `limit` event was emitted on `fileStream`
    busboy.on('finish', res.json({ success: 1 }));
    
    req.pipe(busboy);
    
}
```

**OS**: Mac OS High Sierra 10.13.4
**Node.JS**: v8.2.1
**aws-sdk**: 2.263.1
**busboy**: 0.2.14

**Comment by AllanFly120** [comment]
Hey @equinox7 
Sorry for the delayed response. I agree that removing the listeners on body stream is not a good idea. Not only this, the resuming stream is not an expected behavior either:
https://github.com/aws/aws-sdk-js/blob/bd6d814c209ff1cf7f566d344873fe287f84dacc/lib/s3/managed_upload.js#L591
Thank you for bringing this to us! This unexpected behavior needs to be fixed, but currently I will do more investigation on whether the fix will effect the performance(memory usage).

However in this case, according to [Node stream doc](https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_event_end), the `end` event won't be emitted unless all the content has been consumed. So here if the request is aborted, the `end` event should not emit based on node stream convention.

**Comment by equinox7** [comment]
Thank you for you response @AllanFly120

Not resuming a stream on the SDK's side is fine for me as I can `.resume()` it myself. So I will get an `end` event eventually. Not sure though if the stream is even being paused in my case.

**Comment by equinox7** [comment]
Hi @AllanFly120, is there any progress regarding the investigation?

**Comment by ajredniwja** [comment]
Hey @equinox7,

Apologies for the late reply, are you still facing the issue?
