### ISSUE TITLE
S3 passing redundant params 

### ISSUE THREAD

**Issue by ninthz** [aws/aws-sdk-js#2123]
Hey guys,
This is my simple code. 

```
import dotenv = require('dotenv');
dotenv.config();

import AWS = require('aws-sdk');
import { S3 } from 'aws-sdk';

export default class AwsS3
{
    protected s3: S3;

    protected uploadDir: S3.StartAfter = 'upload/';
    protected archivedDir: S3.StartAfter = 'archived/';
    
    constructor()
    {
        this.s3 = new AWS.S3({
            region: process.env.AWS_REGION,
            params: {Bucket: process.env.AWS_BUCKET}
        })
    }

    listObject()
    {
        let params: S3.Types.ListObjectsV2Request = {StartAfter: this.uploadDir};
        return this.s3.listObjectsV2(params).promise();
    }
}
```

I'm using Typescript to implement wrap s3. For easily to using and these code should be work but when run compile. I got error like this:
```
error TS2322: Property 'Bucket' is missing.
```
I know this required Bucket but i did pass in constructor already :(

**Comment by chrisradek** [comment]
@ninthz 
Unfortunately this is one of our [known limitations](https://github.com/aws/aws-sdk-js#known-limitations) regarding the TypeScript definitions we generate.

I'm not sure if there's a great way to solve this in the SDK, since we do want the parameters for each operation to indicate which fields are required.

A possible work-around on your end would be to do something like:
```typescript
let params: Partial<S3.Types.ListObjectsV2Request> = {StartAfter: this.uploadDir};
return this.s3.listObjectsV2(params as any).promise();
```
This would give you some type-safety when you're assigning to your `params` object.

**Comment by srchase** [comment]
This is a known limitation.  Closing out this issue as we've done our best to document this in the README.
