### ISSUE TITLE
The correct way to use new DocumentClient()

### ISSUE THREAD

**Issue by enGMzizo** [aws/aws-sdk-js#2131]
I see the following error occasionally in my ec2 instance that uses DynamoDB  heavily and I guess I am not implementing it correctly 
```
{ message: 'Could not load credentials from any providers',
code: 'CredentialsError',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '169.254.169.254',
port: 80,
time: 2018-07-05T10:02:37.690Z,
originalError: 
{ code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '169.254.169.254',
port: 80,
message: 'connect ECONNREFUSED 169.254.169.254:80' } } }
```

The way I am using the AWS sdk to connect and get data from DynamoDB is like the following 

```js
'use strict'
const BluebirdPromise = require('bluebird')
AWS.config.setPromisesDependency(BluebirdPromise)
const DocumentClient = AWS.DynamoDB.DocumentClient

class DynamoOne {

  get({
    key
  }) {
    return new DocumentClient().get({ // creating new instance every time i want to get Item
        Key: key,
        TableName: 'TABLE_NAME',
        ConsistentRead: consistent,
      })
      .promise()
      .catch(e => console.trace(key, e))
  }
}

new DynamoOne.get({
  id: 1
}).then((item) => {
  console.log(1, item)
})
```

Is this the correct way to use it ? or I should create ``new DocumentClient()`` once and use it all over , like the following code 

```js
'use strict'
const BluebirdPromise = require('bluebird')
AWS.config.setPromisesDependency(BluebirdPromise)
const DocumentClient = new AWS.DynamoDB.DocumentClient() // creating new instance once

class DynamoTwo {

  get({
    key
  }) {
    return DocumentClient.get({ // reuse DocumentClient
        Key: key,
        TableName: 'TABLE_NAME',
        ConsistentRead: consistent,
      })
      .promise()
      .catch(e => console.trace(key, e))
  }

}


new DynamoTwo.get({
  id: 1
}).then((item) => {
  console.log(1, item)
})


```

Which one is the correct one DynamoOne or DynamoTwo ?

**Comment by chrisradek** [comment]
@enGMzizo 
Since you're using the default credential provider to retrieve EC2 Metadata Credentials, and each instance of a service client has its own copy of configuration, your first sample would lead to more calls to the EC2 metadata service.

Assuming that each call your wrapper class makes to the document client should have the same configuration (region/credentials/etc), it makes sense to instantiate your DocumentClient once per instance so you aren't duplicating work.

If you wanted to use separate DocumentClients for each call (this would be needed if each one had to be configured differently, e.g. to support different regions with the same instance of your wrapper class), you could also instantiate an EC2MetadataCredentials provider explicitly and pass that into your DocumentClient when you instantiate it:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2MetadataCredentials.html

**Comment by enGMzizo** [comment]
Thanks @chrisradek  , I used DynamoTwo and I don't see this error anymore
