### ISSUE TITLE
Lambda.invoke's `error` callback argument is never populated

### ISSUE THREAD

**Issue by ronjouch** [aws/aws-sdk-js#2134]
I have a Node 8.10 Lambda that errors (either by `throw`ing or calling the `callback` with a first-argument error), following [Lambda function handler (Node.js) docs](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html):

```js
exports.handler = async (event, context, callback) => {
  throw new Error('error using throw');
  // can also be expressed as:
  // callback('error using callback');
};
```

I invoke it programatically, following [Lambda.invoke docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property):

```js
import * as aws from 'aws-sdk';
const myLambda = new aws.Lambda();

myLambda.invoke(
  { FunctionName: "MyFunctionName", Payload: "{}" },
  (error, data) => {
    // Here I'd expect `error` to contain an error.    
    // But instead, `error` is always `null`!
    // The only way to check for an error in the lambda I found is:
    if (data.Payload && data.Payload.errorMessage) {
      console.log('error in lambda', data.Payload);
    }
  });
```

See the comments above:

- Why is `error` always `null`? Shouldn't it be populated with my lambda-thrown error?
- Does checking for `data.Payload.errorMessage` make sense?

---

This is a followup to [someone else's StackOverflow question](https://stackoverflow.com/questions/42672023/aws-lambda-error-processing).

**Comment by AllanFly120** [comment]
Hi @ronjouch 
In a word, the `error` will only be set when the request has failed. It can either because of the response status code 4XX / 5XX or the request isn't sent or parsed properly by SDK. In this case, your lambda function is successfully invoked and response status code is 200 so the error shouldn't be set. Yes checking the `data.Payload.errorMessage` is what supposed to do here.
