### ISSUE TITLE
S3 .putObject() failed when Body is a stream of a small file (1MB or less)

### ISSUE THREAD

**Issue by cronvel** [aws/aws-sdk-js#2147]
I'm using the SDK with some S3 compatible services (like Digital Ocean's Space, etc).

For some strange reasons, the following code always fail when the file is around 1MB or less:
```js
var fileStream = fs.createReadStream( filePath ) ;
s3.putObject( { Key: fileName , Body: fileStream } , results => {
    // some code
} ) ;
```
The callback is called after 2 minutes with an 'Unknown error', and no other clue.
Instead, I must do something like this:
```js
content = fs.readFileSync( filePath ) ;
s3.putObject( { Key: fileName , Body: content } , results => {
    // some code
} ) ;
```
Since there is no way to debug raw request I heard of, I'm a bit confused... 
BTW I can't always predict the size of the data, and cannot retain GB of data in memory...

**Comment by AllanFly120** [comment]
I'm not very familiar with DO service but usually, when you see this error message it means the service returns 4XX / 5XX but the SDK cannot parse the response message. This make sense because the SDK may look for `amz-X` headers to parse the error message. Can you show the raw HTTP response you get?

**Comment by cronvel** [comment]
@AllanFly120 Thanks for the reply.

It returns an error 500, with a valid XML, telling "Unknown error". It works when I craft the request all by myself, and I don't know what headers are sent by the SDK, or if the request is chunked, etc...
If there is a simple way to debug the SDK request, I would appreciate it! ;)

**Comment by chrisradek** [comment]
@cronvel 

At least with S3, the length of the object is required to be known. The SDK can calculate that if it's given a filestream, or a non-streaming body, but won't be able to determine what it is for a `putObject` request otherwise.

If you need to work with streams where the content-length is unknown, you can also use the [s3.upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) method. That method will perform a multi-part upload (so DO would need to support that functionality) and buffer 5MB (configurable, that's the default value) chunks of your stream to perform the upload.

If you want to get the raw response from the server, you can access that in your first example by doing something like:
```javascript
s3.putObject({/** params **/, function(err, data) {
  // 'this' is the AWS Response object
  // (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html)
  if (err) {
    console.log(this.httpResponse.body.toString());
    console.log(this.httpResponse.headers);
  }
});
```

I'm going to close this for now since this seems like an issue when interacting with DO, but if you do encounter this issue when using S3 please open another issue!
