### ISSUE TITLE
Update item in dynamoDB

### ISSUE THREAD

**Issue by naveenp77** [aws/aws-sdk-js#2149]
I want to update multiple item without primary key(Key)
How to achieve?

**Comment by AllanFly120** [comment]
Can you elaborate the question? Usually if you use the `putItem()` or `updateItem` the old item will be updated if they have the same key, otherwise new item will be put into table. Without knowing the primary key the first question is to find what items you want to update. You can add secondary key to the attribute you want to index with. Or you can use [scan operation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#scan-property). But this is generally not advisable because it may possibly traverse the whole table and it's slow. After I found the items you can update them with `updateItem` or `putItem`

**Comment by naveenp77** [comment]
Thanks,
What is the best practice to update multiple items?
