### ISSUE TITLE
Add support for streaming v4 uploads

### ISSUE THREAD

**Issue by sashakorman** [aws/aws-sdk-js#2150]
When uploading an object to S3, a hash of the entire content will be calculated for the signature.
This is a problem for resource limited hosts uploading huge files (5TB in our case - so the part is 500MB), as the entire part must be buffered first, the SHA256 computed, and then submitted to S3.
In our case this limitation does not allow to perform parallel uploads.
AWS S3 supports streaming uploads with v4 signer (http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html)
There is no way to opt into the streaming v4 upload in the JS SDK - as far as I know - this feature is implemented in Java SDK and boto.
It'd be great to expose streaming v4 uploads to the consumers of JS SDK.

**Comment by AllanFly120** [comment]
Hi @sashakorman By default, our SDK calculates the content hash for putObject. For big files, using `upload` of SDK is more preferable than `putObject`. I'm not sure why you mentioned the 500MB part, but the `upload` will automatically upload the object in 5 MB chunk by default and you will have lower memory load and even quicker rate because you can make 4(or more) parts upload parallelly. 

Alternatively, you can turn content hashing off by setting config `computeChecksums` to false: 
```javascript
s3.config.computeChecksums = false;
```

**Comment by AllanFly120** [comment]
Hey @sashakorman  sorry, I misunderstood in my last reply. You set the big part size because you hit the part number limit. Currently, the multipart uploader will buffer the part so that it can be retried. It's a nice thing to have if we don't need to buffer the part. This is definitely a feature request. Thank you for bringing this up to us. Just by curiosity, is the stream you are trying to upload always be an fs stream or it can be any stream?

**Comment by sashakorman** [comment]
Hey @AllanFly120. Exactly, we are hitting 500MB part size. Currently the incoming stream is always fs stream and the size of the stream is known. Generally speaking the incoming stream can be any stream, for example, streaming from Azure blob to S3 object.

**Comment by AllanFly120** [comment]
@sashakorman actually, I find even the stream signing will not help with this situation since the SDK will try to retry the parts so it will always put at least one part in memory. Unless you ensure the input stream is an fs stream so that it's possible that SDK can chop the chunks by byte range.

**Comment by sashakorman** [comment]
@AllanFly120 make sense. We can ensure the input stream is a fs stream.

**Comment by ajredniwja** [comment]
Closing this now, please reach out if you have additional questions.
