### ISSUE TITLE
MediaConvert NameModifier

### ISSUE THREAD

**Issue by riteshapatel** [aws/aws-sdk-js#2162]
How do you use NameModifier? Docs say you should be able to use $Number$ or $Time$. When run the job with these as NameModifier, it simply appends $Number$ or $Time$ to the output file name. Some more examples would be helpful.

Thx,

Ritesh

**Comment by AllanFly120** [comment]
Hi @riteshapatel, Can you share which documentation you are referring to?

**Comment by riteshapatel** [comment]
```https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MediaConvert.html```

**Comment by AllanFly120** [comment]
Hey @riteshapatel Since this is not an SDK issue / question, you can bring the question to [the forum](https://forums.aws.amazon.com/thread.jspa?threadID=268221). The service teams are happy to answer you questions. I will close this issue now but feel free to comment here is you have more questions.
