### ISSUE TITLE
AWS.SharedIniFileCredentials loadRoleProfile using non existent options

### ISSUE THREAD

**Issue by dpmallinger** [aws/aws-sdk-js#2197]
this code:
var sourceCredentials = new AWS.SharedIniFileCredentials(
      AWS.util.merge(this.options || {}, {
        profile: sourceProfileName,
        preferStaticCredentials: true
      })
    );

is broken because this.options is null because its not saved in the constructor.  This causes filename to be null and thus the code defaults to ~/.aws/credentials instead of process.env.AWS_SHARED_CREDENTIALS_FILE ( or whatever was passed into the original constructor call)

In addition; the constructor filename does not default per the documentation.
this.filename = options.filename
should be
this.filename = options.filename || process.env.AWS_SHARED_CREDENTIALS_FILE
to match this documentation:
  * @option options filename [String] ('~/.aws/credentials' or defined by
   *   AWS_SHARED_CREDENTIALS_FILE process env var)
   *   the filename to use when loading credentials.

**Comment by chrisradek** [comment]
@dpmallinger 
The behavior you're seeing is expected. In order to maintain backwards-compatibility for users that use more than one SDK/tool, when we added support for the `AWS_SHARED_CREDENTIALS_FILE`, we put it behind the `AWS_SDK_LOAD_CONFIG` environment variable. See [here](https://github.com/aws/aws-sdk-js/pull/1391#issue-109380362) for more info on that change.

This is absolutely something we are changing when we do a major version bump, but couldn't be done at the time we added it without potentially breaking users.

**Comment by dpmallinger** [comment]
@chrisradek 
I updated the pull request to just be the fix for this.options

**Comment by sturdiva** [comment]
+1 to this, We are also unable to use credentials across assumeRole calls with a non-standard credential file due to the `options` variable not being saved in the constructor.

```
    var credentials = new AWS.SharedIniFileCredentials ({
        'filename': '/path/to/credentials',
        'profile':  'remote-role',
    });

    AWS.config.credentials = credentials;
```

```
[static-role]
aws_access_key_id = AK1234
aws_secret_access_key = secret

[remote-role]
role_arn = arn:aws:iam::123456789012:role/foo
source_profile = static-role
```
