### ISSUE TITLE
TypeError: AWS.SageMaker is not a constructor

### ISSUE THREAD

**Issue by paulfryer** [aws/aws-sdk-js#2231]
How can I add the SageMaker client SDK to my Node project? I'm using the default "npm install aws-sdk", but it looks like that doesn't include the SageMaker client library. How can I add that with Node?

**Comment by srchase** [comment]
@paulfryer 

SageMaker is included in the current SDK.

The documentation can be found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SageMaker.html)

Which version of the SDK are you using?

**Comment by paulfryer** [comment]
Hi @srchase I'm using the latest version of the SDK. 
I can see the AWS.SageMaker documentation shows an example of how to use the API, for example:
`var sagemaker = new AWS.SageMaker();`
However when I do that with the default `npm install aws-sdk` I get the error in the title of this post. I've been trying to find the source code of the SageMaker node client and somehow build a custom version of the aws-sdk. I see I can do that with browserify like this:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html#using-command-line-tools

However what I really want to do is browserify ALL my node packages together, not just the aws-sdk.

**Comment by paulfryer** [comment]
I figured it out, I had to make an explicit reference to the sagemaker client library from my JS file, like this:
`require('../../node_modules/aws-sdk/clients/sagemaker')`
How the browserify step will pull in this sagemaker code, since it's using code reflection to determine what to include.

**Comment by chrisradek** [comment]
@paulfryer 
Are you using browserify to create a node.js bundle, or a browser bundle?

The SDK uses the `browser` field in `package.json` to inform tools that respect it (such as browserify/webpack) which modules to use when creating a browser bundle. Sagemaker is included in the node.js version of the SDK, but not the browser version since it's unknown if it supports CORS:
https://github.com/aws/aws-sdk-js/blob/master/clients/browser_default.js

If you want to pull in SageMaker for a browser bundle, you can also import it via `require('aws-sdk/clients/sagemaker')`:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html#webpack-importing-services

**Comment by paulfryer** [comment]
![9-4-2018 12-28-44](https://user-images.githubusercontent.com/472725/45053191-1b765180-b03e-11e8-95e7-bb8c81f38696.png)
@chrisradek thanks for that, and Yes SageMaker does support CORS (see attached screenshot), seems to be working fine from my browser based application.
