### ISSUE TITLE
AWS.MediaConvert is not a constructor

### ISSUE THREAD

**Issue by abidingotter** [aws/aws-sdk-js#2242]
I'm creating a typescript application using the latest AWS SDK (2.310.0) installed from NPM. 

I can make calls using the AWS.S3 object fine, but am unable to use the AWS.MediaConvert:

```
var endpointPromise = new AWS.MediaConvert({apiVersion: '2017-08-29'})
    .describeEndpoints(params)
    .promise();
```

The error I receive at runtime is "TypeError: AWS.MediaConvert is not a constructor". I can inspect the AWS object and can see a lot of properties, but MediaConvert is not one of them.

According to SERVICES.md https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md   "all services are supported in the browser version of the SDK"

If I have to build my own SDK, how can I mix and match the typings from the NPM module with the built version of the SDK?

Probably similar to https://github.com/aws/aws-sdk-js/issues/2232

**Comment by chrisradek** [comment]
@abidingotter 
SERVICES.md actually mentions that not all services are available in the default hosted build:
> Although all services are supported in the browser version of the SDK, not all of the services are available in the default hosted build (using the script tag provided above).

Are you using a tool like browserify or webpack for your project? If so, you can import the service you want directly:
```typescript
import * as MediaConvert from 'aws-sdk/clients/mediaconvert';
```
This will also result in a smaller bundle size for your app because you won't need to include every service in your app, just the ones you actually import.
