### ISSUE TITLE
list-buckets aws-sdk API is not showing my bucket creation date?

### ISSUE THREAD

**Issue by Yaswanth-C** [aws/aws-sdk-js#2266]
I want to get my `s3` bucket creation dates using `list-buckets` API . But it is not showing the creation date that it is showing in aws console.  

When i tried with `aws-sdk API` the output is like this 

```
const aws = require('aws-sdk');
const s3 = new aws.S3({region: "ap-south-1",apiVersion: '2006-03-01'});
    // TODO implement
const params= {};
 s3.listBuckets(params, Bucketlist);
 function Bucketlist(err, data) {
 if (err) console.log(err, err.stack); // an error occurred
 else   
 {   
  console.log(data)
 }
}
```

Output 

```
{
        "Buckets": [
            {
                "CreationDate": "2018-09-12T11:32:04.000Z",
                "Name": "campaign-app-api-prod-serverlessdeploymentbucket-"
            },
            {
                "CreationDate": "2018-09-12T10:06:44.000Z",
                "Name": "s3-api-log-events"
            }
        ]
    }
```

In console

[![this is the my aws console][1]][1]

Why am i getting different dates in `s3api`. Is my `CreationDate` interpretation is wrong ?

Any help is appreciated.

Thanks 

  [1]: https://i.stack.imgur.com/siJup.png

**Comment by srchase** [comment]
@Yaswanth-C 

Thanks for submitting this issue.

I see that you've submitted a post on AWS Forums.  There's nothing to indicate that this is an issue with the SDK.  If you run ```aws s3 ls``` with the AWS CLI, you'll get the same (incorrect) timestamps.

Since this isn't an issue with the SDK, I'm going to close out this issue and allow it to be resolved by the service team via the AWS Forums.  If you or they have followup questions pertaining to the SDK, let us know.
