### ISSUE TITLE
How to resume from break point？

### ISSUE THREAD

**Issue by Yijx** [aws/aws-sdk-js#2381]
I ues aws-sdk.js with Chrome,If I use upload API 
```
let s3 = new AWS.S3({
      accessKeyId: files.uploadOptions.accessKeyId,
      secretAccessKey: files.uploadOptions.accessKeySecret,
      sessionToken: files.uploadOptions.sessionToken,
      region: files.uploadOptions.region
})
let upload = s3.upload({
      Bucket: files.uploadOptions.bucket,
      Key: files.uploadOptions.key,
      Body: files
})
upload.send((err, data) => {...})
```
I use abort() to stop uploading
```
upload.abort()
```
When I use upload.abort(), It is a DELETE xhr,I can't use upload.send() again(404 Error).
I  can restart this upload,but It is not a good way.
How can I resume upload? Should I use abort() to stop uploading?
Sorry I am not good at English,thanks for everybody who can help me. /(ㄒoㄒ)/~~

**Comment by srchase** [comment]
@Yijx 

Are you wanting to pause the upload?

Abort() will clean up the multipart upload, which is why it cannot be restarted with send().

**Comment by Yijx** [comment]
> @Yijx
> 
> Are you wanting to pause the upload?
> 
> Abort() will clean up the multipart upload, which is why it cannot be restarted with send().

I use
``` 
leavePartsOnError: true
```
then when I abort() uploading, no error appear.If I use send() aging upload will restart from break point...
Is it a right way to stop uploading? or Is there any other way to stop the breakpoint sequel?
Thank you O(∩_∩)O~~

**Comment by srchase** [comment]
```leavePartsOnError: true``` is the correct way to be able to resume a managed upload.

**Comment by AllanFly120** [comment]
Hi @Yijx,

Just add some details to @srchase. Currently `upload()` method doesn't come with the ability to resume aborted upload. If you config `leavePartsOnError: true` and abort the the upload, the uploaded parts will be saved in the S3 invisibly(and you will be charged for those parts. Have a look at [this doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config) to save your expense) and you can resume the upload by only uploading the missing parts. But within the `MultipartUpload` request object, all the internal state will be [reset](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L614~L620). So if you call `send()` again it will try to start from beginning. You will see error because you would re-upload the same part.

To resume the upload from some of parts already being uploaded, you need to handle the upload by your self instead of using `upload()`. How to do it depends on your use case, but you can refer to [S3 multipart upload documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html) for more information, which is also what SDK does under the hood.

I haven't used any but there might be some NPM packages that could help with the use case, you can have a look at there.

**Comment by Yijx** [comment]
@AllanFly120 
Thanks for helping me!
I will try to use basic api to refactoring my code.

**Comment by srchase** [comment]
I'll close this issue for now.  We're happy to re-open if you have additional questions.
