### ISSUE TITLE
strange behavior when destructing method from aws.S3

### ISSUE THREAD

**Issue by jsphweid** [aws/aws-sdk-js#2384]
Is it a bug that this succeeds:
```
import { S3 } from 'aws-sdk'
const s3 = new S3()
s3.getObject({ Bucket: 'myBucket', Key: 'myKey' }, (err, data) => {
	console.log(err, data)
})
```

while this fails?:
```
import { S3 } from 'aws-sdk'
const { getObject } = new S3()
getObject({ Bucket: 'myBucket', Key: 'myKey' }, (err, data) => {
	console.log(err, data)
})
```

`this.makeRequest is not a function` at `aws-sdk/lib/service.js:653:23`

Looks like it is losing a `this` reference but it wasn't immediately clear to me that it was because the way I initialized S3.

**Comment by srchase** [comment]
@jsphweid 

Thanks for opening this issue. 

This is the expected behavior for v2.  Because operations are generated dynamically, it is not possible to destructure a single operation.

However, this is possible in [v3](https://github.com/aws/aws-sdk-js-v3).  There's an open PR to update the README with an example of this: https://github.com/aws/aws-sdk-js-v3/pull/121/files

With v3, you can do this:

```const { getObject } = require('@aws/sdk-s3-node/commands/GetObjectCommand')```

Let us know if you have further questions and we can re-open.
