### ISSUE TITLE
"CredentialsError: Missing credentials in config" with ECS task role after upgrade from 2.338.0 to 2.377.0

### ISSUE THREAD

**Issue by OscarBarrett** [aws/aws-sdk-js#2433]
We have a scheduled ECS task with a task role that grants permissions to upload files to S3. It has been working fine, however after upgrading `aws-sdk` from 2.338.0 to 2.377.0 it fails with `CredentialsError: Missing credentials in config` and the following stack trace:

```bash
TypeError: Cannot read property 'accessKeyId' of null
at features.constructor.apiAttemptEvent (/app/node_modules/aws-sdk/lib/service.js:338:42)
at Request.API_CALL_ATTEMPT (/app/node_modules/aws-sdk/lib/service.js:392:34)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at SyncProcess.uploadImages (/app/src/syncImages.js:145:13)
```

Relevant code in our `syncImages.js`:
```javascript
    this.s3 = new AWS.S3({
      apiVersion: '2006-03-01',
      params: { Bucket: S3_BUCKET }
    });

    ...

    const list = this.s3.listObjectsV2({ Prefix: prefix }).promise(); // Causes the error
```

We've since locked `aws-sdk` to 2.338.0 in a new revision and our task does not fail.
I've had a look through the changelog but didn't see anything that stood out as a potentional cause of this.

ECS details:
- Agent version 1.22.0
- Our task is run as a scheduled task, EC2 launch type.
- We do not override the task role on the schedule target. It is only set on the task definition.
- We do not set any AWS-related environment variables.

**Comment by AllanFly120** [comment]
Hi @OscarBarrett 
which credential provider are you using? Can you log the request credentials using 2.338.0?(you can omit the values, just share the keys) You can try like this:

```javascript
const request = this.s3.listObjectsV2({ Prefix: prefix });
const list = await request.promise();
console.log(request.service.config.credentials);
```

**Comment by OscarBarrett** [comment]
It's using `RemoteCredentials`

```
RemoteCredentials {
  expired: false,
  expireTime: 2018-12-18T08:01:13.000Z,
  accessKeyId: '...',
  sessionToken: '...',
  httpOptions: { timeout: 1000 }
}
```

**Comment by AllanFly120** [comment]
The issue comes from here: https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L338, where `request.service.config.credentials` is `null`. But it looks like the `request.service.config.credentials` is defined eventially. I'm wondering why it's the case. What's your `request.service.config.credentials` and `AWS.config.credentials` looks like before making any calls? Do you also see request failed because of missing credentials in config?

**Comment by jstewmon** [comment]
It seems like the CredentialProviderChain must be resolving to `null` without an error being passed to the callback. I don't see how that's possible for RemoteCredentials if the requisite env vars are set.

@OscarBarrett can you confirm that `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` or `AWS_CONTAINER_CREDENTIALS_FULL_URI` env vars are visible to the container?

**Comment by OscarBarrett** [comment]
I've spent some more time debugging this. I created a simple test file and ran it with both versions:

```js
const AWS = require('aws-sdk');

console.log(`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: ${process.env.AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}`);
console.log(`AWS_CONTAINER_CREDENTIALS_FULL_URI: ${process.env.AWS_CONTAINER_CREDENTIALS_FULL_URI}`);

const run = async () => {
  console.log('AWS.config.credentials:', AWS.config.credentials);
  const s3 = new AWS.S3({
    apiVersion: '2006-03-01',
    params: { Bucket: '...' }
  });

  const request = s3.listObjectsV2({ Prefix: '...' });
  console.log('request.service.config.credentials:', request.service.config.credentials);

  const list = await request.promise();
  console.log('list:', list);
};

run();
```

Output:
```
Version 2.338.0
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /v2/credentials/...
AWS_CONTAINER_CREDENTIALS_FULL_URI: undefined
AWS.config.credentials: null
request.service.config.credentials: null
list: { IsTruncated: false,
  Contents: [...],
  ... }

Version 2.377.0
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /v2/credentials/...
AWS_CONTAINER_CREDENTIALS_FULL_URI: undefined
AWS.config.credentials: null
request.service.config.credentials: null
list: { IsTruncated: false,
  Contents: [...],
  ... }
```

Interestingly this did not fail on `2.377.0`.

Our code that triggered this error is a bit more complex - something like this, where there are several thousand items that it loops over.
```js
await Promise.all(items.map(async (item) => {
  let list;
  try {
    list = await this.s3.listObjectsV2({ Prefix: item.prefix }).promise();
  } catch (err) {
    throw new Error(`Failed to list images for ${item.prefix}. Error: ${err}`);
  }

  const uploadedImages = list.Contents.map(i => i.Key.split('/')[1]);
  const missingImages = item.images.filter(
    i => !uploadedImages.includes(this.constructor.imageNameFor(i))
  );

  if (missingImages.length) {
    for (const image of missingImages) {
      // ...queue image sync
    }
  }
}));
```

This consistently fails with `2.377.0`. I've checked the number of calls and 5 out of 5 tries it failed on the 2030th call to `listObjectsV2`. Our items array is still larger than this. Failure happens about 5s after the script starts.

I'll try and come up with a reproducible test case in the next couple of days :confused:

**Comment by OscarBarrett** [comment]
This fails for `2.377.0`:

```js
const AWS = require('aws-sdk');

class Test {
  constructor() {
    this.s3 = new AWS.S3({
      apiVersion: '2006-03-01',
      params: { Bucket: process.env.S3_BUCKET }
    });
  }

  async run() {
    try {
      await Promise.all(Array(100).fill(0).map(async () => {
        let list;
        try {
          list = await this.s3.listObjectsV2().promise();
        } catch (err) {
          console.log(`Failed to list images. Error: ${err}`);
          process.exit(1);
        }
      }));
    } catch (e) {
      console.log(e);
      process.exit(1);
    }

    console.log('done');
  }
}

const test = new Test();
test.run();
```

Output:
```
Version 2.338.0
done

Version 2.377.0
Failed to list images. Error: CredentialsError: Missing credentials in config
```

**Comment by jstewmon** [comment]
I think I've got a lead on this issue...

Recently, the behavior of RemoteCredential changed from using a global refresh queue for all class instances for a queue per RemoteCredentials instance.

In your case, the S3 instance is using the CredentialProviderChain to resolve the credentials. When you concurrently dispatch a large group of requests through a service instance that has not yet loaded credentials, the credentialProvider on the service instance will create a new RemoteCredentials instance per service request, which in turn generate a http request for the ECS credentials per service request.

I suspect that this is overloading the RemoteCredential http endpoint, leading to the issue you're seeing. But, I don't know how we ended up getting the original error you reported, which I'd classify as undefined behavior since it shouldn't be possible. So, there may be some issue where the SDK is not handling an error correctly.

Can you try adding this line to your solution to see if it resolves the problem?

```js
this.s3.config.credentials = await this.s3.config.credentialProvider.resolvePromise();
await Promise.all([]);
```

@AllanFly120 I think we want `CredentialProviderChain.resolve` to coalesce calls to avoid the stampede on constructing new instances of Credentials (of any type) in a scenario like this. What do you think?

**Comment by jstewmon** [comment]
I now see why the strange TypeError was thrown... When `config.getCredentials` is called concurrently with a `credentialProvider` that hasn't resolved, each request that successfully resolved will continue with `config.credentials` set, but when a later resolution fails, the callback will set `config.credentials` to `null` before passing the error to its callback: https://github.com/aws/aws-sdk-js/blob/master/lib/config.js#L385-L390

So, I think the fix I added for #2451 fully addresses this problem.

**Comment by AllanFly120** [comment]
@jstewmon 
Thank a lot for your thorough investigation. I see where the credentials could be set to null. The idea of making `CredentialProviderChain.resolve()` coalesce make much sense. I also need to update the `service.js` not to assume credentials always exists and resolved.

@OscarBarrett 
Thanks a lot reporting this issue. We will make the fix into SDK shortly.

**Comment by jstewmon** [comment]
@AllanFly120, I'm not sure how conducive the current code it to what I'm about to suggest, but instead of checking that the service config credentials are valid every time they're accessed, I think it would be better if we could bind the credentials to the request once the validate event has fired, so that we are sure the validated credentials are used to make the request, since the value of config.credentials could be modified after validate runs. In other words, once we validate the object, use that object without referencing it through the config property which could be reassigned.

**Comment by AllanFly120** [comment]
I agree with the direction of the suggestion. Instead of maintaining reference from each request to Credentials, we should make credentals classes as factories for resolved credential object. So that requests won't share the credentials reference. 

You should check out the [JS SDK V3](https://github.com/aws/aws-sdk-js-v3) we are working on. It's still in early stage, but we got rid of the centralized the credentials provider. The idea is that credentials will only be resolved at service client instantiation time, making operation calls will not try to fetch credentials any more and they don't have reference to credentials resolver. Thus we won't have problems of overriding the credentials in concurrent calls

**Comment by srchase** [comment]
This issue was resolved in https://github.com/aws/aws-sdk-js/pull/2451.

See https://github.com/aws/aws-sdk-js/issues/2455, which has also been merged and is pending release.
