### ISSUE TITLE
DocumentClient with Transactions

### ISSUE THREAD

**Issue by dehli** [aws/aws-sdk-js#2435]
Hi, I'm working through adding DynamoDB transactions with the DocumentClient and I'm seeing some unexpected behavior.

```
const client = new AWS.DynamoDB.DocumentClient({ 
  params: { TableName: "table-name" }
});

client.transactWrite({
  TransactItems: [{ Put: { Item { id: "id" }} }]
});

Error MissingRequiredParameter: Missing required key 'TableName' in params.TransactItems[0].Put
```

I would assume that the params passed into the `DocumentClient` would be passed to each of the transactions. Is this a correct assumption?

Thanks!

**Comment by AllanFly120** [comment]
Hey @dehli,

If you look into the [api reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#transactWriteItems-property), you will find the `TableName` member is actually set in each transaction item object. So that you can make tranactions between different tables. The way of setting params in your example will  set the table name outside the transaction items.

The idea of document client is binding the JS data type with DDB data type. It doesn't do further altering to the parameters other than merging the parameters from operation parameters and service parameters.

**Comment by dehli** [comment]
Thanks @AllanFly120! I had seen that, but was hoping that the parameters from the document client would be merged into each request and behave like calling the request regularly (like when you call `client.put()`). Thanks for the guidance though! Cheers!
