### ISSUE TITLE
EC2 Credentials are set not expired even when it's not the case 

### ISSUE THREAD

**Issue by sargun** [aws/aws-sdk-js#2440]
In the case where the IMDS serves up expired credentials, the `EC2MetadataCredentials.expired` is set to false. I think that's because expired is blindly set to false: https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/ec2_metadata_credentials.js#L77

**Comment by jstewmon** [comment]
@sargun according to AWS the IMDS should always provide credentials that are valid for at [least 5 minutes](https://aws.amazon.com/iam/faqs/#How_do_i_get_started_with_IAM_roles_for_EC2_instances).

Can you elaborate on the behavior you're observing and how it differs from what you expect to happen?

If the metadata service is actually serving expired credentials, resulting in a failed service call using those credentials, what do you think the SDK should do? Try calling the metadata service again? Pass an error to the refresh callback?

**Comment by sargun** [comment]
@jstewmon That's not always true. If the IMDS has failures, it wont show creds in 5m. If you have access to the ticket database, you can see customer case 5574322451 for more info. 

We hit the IMDS credentials endpoint, and it returns an expiration which has already past. I think we should compare the current time on the instance (ideally via [adjtimex](http://man7.org/linux/man-pages/man2/adjtimex.2.html)) and compare that to the timestamp and use that to set expired. Perhaps, it should also create an AWSError.

**Comment by jstewmon** [comment]
The expired flag is just used to control when refresh is called, so I think its value is incidental to your scenario, since it's being set during a refresh.

So, the current behavior is that the credentials are fetched successfully, but that they may already be expired, which results in the service call that triggered the refresh to fail with expired credentials. But, you'd prefer that the expiration of the retrieved credentials be checked against the current time and have refresh fail with an error if the expiration is less than the current time.

The outcome will be the same (failed service request), but you'd get an error that indicates that the failure is due to the the refreshed credentials already being expired.

Is that right?

**Comment by sargun** [comment]
Correct, and in addition, and we could check that the credentials.expired != false before making the request, so we don't make an errant request which will fail no matter what.

**Comment by jstewmon** [comment]
The expired property is checked for every service request in Credentials.prototype.needsRefresh. I created a PR with the proposed change to fail the refresh if the metadata service provides expired credentials.
