### ISSUE TITLE
Step Functions Intermittently returning null output

### ISSUE THREAD

**Issue by andrewryan1906** [aws/aws-sdk-js#2462]
I've observed this issue now for some time, as I have an application that makes heavy use of step functions across a number of services, and do nightly builds across all of my services. Every now and then - I'd say 1 in 100 - the result of a **describeExecution** call contains status SUCCEEDED but no output - even when there's an output. This causes my nightly builds to be brittle, to break intermittently and then succeed upon a rebuild. Can you provide any assistance on why this is happening?

If you consider this workflow:

![image](https://user-images.githubusercontent.com/37671394/50485971-997faf00-09c5-11e9-99d8-334d17ed7b1c.png)

As you can see, it finished, and had an output... but look at my build logs:

![image](https://user-images.githubusercontent.com/37671394/50485996-ae5c4280-09c5-11e9-96b5-254a59217ca5.png)

No output.

Thanks!
Andrew

**Comment by srchase** [comment]
@andrewryan1906  (Andrew),

Could you provide an example of the ```describeExecution``` call you are making?

Is the actual response from the StepFunction API empty?  Or does it appear that the SDK itself is causing the issue?

**Comment by andrewryan1906** [comment]
The call is as follows:

```
  do {
                    await sleep(1000);

                    executionDescription = await stepFunctions.describeExecution({executionArn: executionInfo.executionArn}).promise();
                    console.log('Received status: ' + JSON.stringify(executionDescription.status));

                } while (executionDescription.status === 'RUNNING');
```

I don't know if it's the SDK or the API - the only way I interact with the API is through the SDK, and since it's intermittent, I can't try to replicate once it's observed. I do know, however, that the step function IS in fact returning an output.

**Comment by srchase** [comment]
You can use the follow the example on [Using a Request Object Event Listener](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-a-response-event-handler.html) in order to inspect the httpResponse:

```
var req = stepFunctions.describeExecution({executionArn: executionInfo.executionArn})
req.on('error', (resp) => { console.log(err) });
req.on('success', (resp) => {
  console.log(resp.httpResponse.body.toString());
});
req.send();
```

I suspect that the output would also be empty in the raw response, but it would be helpful to confirm.

**Comment by nocoli** [comment]
I have the same issue. My application relies heavily on step functions and uses the .NET SDK for AWS step functions. This issue is occurring intermittently where the result from the `DescribeExecutionAsync` method is returning with an `ExecutionStatus` of SUCCEEDED but the Output is null. I have a try catch block handling this and retrying the request a couple of seconds later which is returning the expected output. 

Not sure if this has anything to do with the SDK or not, but @andrewryan1906 you are not alone.

I'm currently running the AWSSDK.StepFunctions version 3.3.2.27 nuget package.

**Comment by srchase** [comment]
@nocoli,

Are you using the JavaScript SDK?  It looks like you need to refer to the .NET SDK instead.
