### ISSUE TITLE
Catching error exception if S3 getObject can't find requested object in the bucket

### ISSUE THREAD

**Issue by Mohan1996** [aws/aws-sdk-js#2508]
I'm trying to use a try-catch to find any errors S3 GetObject returns in the scenario that the requested object doesn't exist in the bucket. What error message does AWS return specifically if it can't find the object in the bucket?

try {
const temp = s3.getObject({ Bucket: 'xxx', Key: 'xxx')}.promise();

} catch {e} {
// should be the message AWS returns if it can't find the object
if (e.message === ' ') {     

} else {
throw e;
}

**Comment by srchase** [comment]
It will likely be easier to rely on the error code instead of the message.

The list of S3 Error Codes can be found here: [ErrorCodeList](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList)

In this case, you would receive a ```NoSuchKey``` error code if there is no key in the bucket you've specified.
