### ISSUE TITLE
aws s3 upload content type issue

### ISSUE THREAD

**Issue by piyumi25** [aws/aws-sdk-js#2510]
I am trying to upload files to aws s3 bucket using react app. This is the code I have used to upload.

![image](https://user-images.githubusercontent.com/33615108/52054092-5f379d80-2581-11e9-8ff6-2a31d2483e10.png)

after uploading it shows the content type as "application/octet-stream; charset=UTF-8" and unable to open the file after downloading.

**Comment by piyumi25** [comment]
Thank you. But I tried this way by putting ContentType:image/png
but is s3 it shows as image/png; charset=UTF-8. what should be the reason for that?

**Comment by windmemory** [comment]
@piyumi25 I noticed that this piece of code did the logic to add `charset=UTF-8` into the ContentType, and seems to be a bug because it adds the `charset` to image content.

https://github.com/aws/aws-sdk-js/blob/d78f694cd52e23409d9f679cc021bb4379ed2202/lib/services/s3.js#L286-L289

@srchase Could you please take a look at this?
I encountered similar issues that when I am uploading a image file with multipart upload, the sdk will add the `; charset=UTF-8` automatically to the `ContentType`, which breaks the logic in our system.

**Comment by AllanFly120** [comment]
Hi @elorzafe, @windmemory  We added this logic for browser environment because some browsers may append `charset` to `Content-Type` headers automatically and hence break our request signature(see #244 #245 for more information). So we added a default value to `charset`. To get around it you can set the `ContentType` key explicitly to the appropriate type. SDK won't try to append the `charset` then.

**Comment by trivikr** [comment]
As explained by @AllanFly120, the get around is to append the `charset` to the `ContentType` key explicitly.
