### ISSUE TITLE
DocumentClient saves Number 0 as Null type

### ISSUE THREAD

**Issue by nakulp007** [aws/aws-sdk-js#2513]
The following params should set value of **test** to **Number type 0**. 
However it saves it as **Null type set to true**. This if for both put and update operation.

```
const params = {
      TableName: "TABLE",
      Item: {
        id: "some-id",
        test: 0
      }
}
```

**All other numbers besides 0 are marshalled correctly.**

This is only and issue when using DocumentClient. 0 is a valid value for Number type in DynamoDB and can be set manually using console.

I tried wrapping the it in javascript Number(0) with no luck. 

Until this issue is fixed, is there a way to manually specify the dynamodb type to convert to in DocumentClient?

I am using aws-sdk 2.286.2 .

Thanks for your help.

**Comment by klaytaybai** [comment]
@nakulp007, I wasn't able to reproduce this with 2.286.2 or 2.395.0.  I'm not sure why you are seeing this, but I would try updating your SDK since it is quite outdated.  Please let me know if that fixes the issue for you.  I would also be interested to know if you have had this occur multiple times.

**Comment by nakulp007** [comment]
@klaytaybai thanks for your response. I was able to reproduce it at will the day I posted the question. But for some reason, it is working as expected now. No change to deployed function. Maybe some temporary problem on the database side. Thanks.

This can be closed.
