### ISSUE TITLE
MediaConvert API does not support the new Rotate parameter

### ISSUE THREAD

**Issue by laynemoseley** [aws/aws-sdk-js#2553]
I am getting the following error when trying to use the new `Rotate` param:

```
Unexpected key 'Rotate' found in params.Settings.Inputs[0].VideoSelector
```

According to this documentation, Rotate is now supported: https://docs.aws.amazon.com/mediaconvert/latest/ug/manually-specified-rotation.html

I have also successfully added a Rotate in the web interface, and the JSON from their includes that param. However, when I used that exactly JSON in the javascript SDK, I get these errors.

See also: https://docs.aws.amazon.com/mediaconvert/latest/ug/automatic-rotation.html, https://docs.aws.amazon.com/mediaconvert/latest/ug/auto-rotate.html

**Comment by srchase** [comment]
@laynemoseley 

Thanks for opening this issue.  I've escalated this to MediaConvert team to make that new parameter available via the SDKs.

Once the MediaConvert team makes their update, the SDKs will include that change in the next release.

**Comment by laynemoseley** [comment]
Thank you!

Any idea on timeframe?

**Comment by srchase** [comment]
Not at this time. 

I'll update this issue when there is an update I can share.

**Comment by laynemoseley** [comment]
perfect. Thank you for the help!

**Comment by srchase** [comment]
@laynemoseley 

v2.411.0 is out with 7729619134b77729cfa34db047aa72e39caf8bbe

It includes the new Rotate parameter.

**Comment by laynemoseley** [comment]
thank you!

**Comment by tijanirf** [comment]
I tried to create MediaConvert job in lambda function, but i still having same problem like @laynemoseley. The error code is still the same (Unexpected key 'Rotate' found in params.Settings.Inputs[0].VideoSelector) even though i specified the api version using apiVersion `AWS.config.apiVersion = {mediaconvert: '2017-08-29'}`

Is it because i specify wrong api version? Any hint would helping me a lot, i tried to solve this error for 2 days but still no result. Thanks

**Comment by srchase** [comment]
@tijanirf 

Are you supplying your own version of the SDK?  Or using the SDK supplied by Lambda?

The version supplied by Lambda is 2.290.0 and does not include the update that added the Rotate option.

**Comment by hamid09430** [comment]
Hi @srchase 
i am getting this Error when lambda function trigger by S3 Put item Trigger.

Exception: Parameter validation failed:
Unknown parameter in Settings.Inputs[0].VideoSelector: "Rotate", must be one of: ColorSpace, ColorSpaceUsage, Hdr10Metadata, Pid, ProgramNumber

i have added this stuff in job.json file to keep the input video file Orientation as it is

"VideoSelector": {
          "ColorSpace": "FOLLOW",
          "Rotate": "AUTO"
        },


Any Help will highly appreciated
Thanks

**Comment by arivera-skycred** [comment]
@srchase Same issue here. Using the Video on Demand workflow for media conversion. Added the `Rotate` param to the json within the media convert job creation lambda function and getting the error. Is there any way to add this to lambda?

**Comment by arivera-skycred** [comment]
@hamid09430 and any others having this issue, you can manually get Lamda to run with the latest version of `aws-sdk` but following this guide:
https://medium.com/@anjanava.biswas/nodejs-runtime-environment-with-aws-lambda-layers-f3914613e20e

Also, see this SO post for more info.
https://stackoverflow.com/questions/53782484/is-it-possible-to-use-a-newer-version-of-the-aws-sdk-than-provided-in-aws-lambda

Worked for me.

**Comment by trivikr** [comment]
Locking this thread as the issue can be fixed by using latest version of `aws-sdk` as explained in https://github.com/aws/aws-sdk-js/issues/2553#issuecomment-497357617
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
