### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by gramakri** [aws/aws-sdk-js#26]
Allow the API to be used with  HTTP and Socks Proxies.

**Comment by yamsellem** [comment]
Using `https-proxy-agent` worked for me.

```
var ProxyAgent = require('https-proxy-agent');

var options = {
  accessKeyId: '..', 
  secretAccessKey: '..',
  httpOptions: {agent: new ProxyAgent({host, port})}
};
client = s3.createClient({s3Options: options});
```

**Comment by restebanez** [comment]
http://blogs.aws.amazon.com/javascript/post/Tx3CV0OSVN2TBPS/Using-the-AWS-SDK-for-JavaScript-from-Behind-a-Proxy

**Comment by ivarrian** [comment]
@yamsellem This is the solution that helped me! Thanks.

**Comment by license2e** [comment]
@yamsellem Thank you! This helped me as well...

**Comment by alain-odea-vgh** [comment]
Got hit by this too.  My Squid proxy was refusing access, returning HTTP 403 itself, and presenting a user-facing access denied HTML page.  Not sure if there's a reliable way to differentiate that from a AWS API error. The Content-Type is text/html regardless of Accept headers, but I suppose that isn't enforceable for S3 since each Object can have a custom Content-Type including text/html.
