### ISSUE TITLE
S3 upload does not call callback for large data (size >= queueSize*partSize) when using streams in object mode

### ISSUE THREAD

**Issue by ramaguruprakash** [aws/aws-sdk-js#2615]
When I run the below command for the script the callback is not called at the end of s3.upload (I have attached the test file to this issue):
`node s3UploadIssue.js uploadToS3 -b <dest_bucket> -k <folder> -f ./test.txt`
```
const uploadToS3Command = require('commander');
const fs = require('fs');
const aws = require('aws-sdk');
const stream = require('stream');
const uploadToS3 = (commandArgs) => {
  let {
    filePath,
    bucket,
    key
  } = commandArgs;


  let s3 = new aws.S3();
  let count = 0;
  let passThrough = new stream.Readable({
    objectMode: true
  });
  passThrough._read = function () {};

  let dataStream = fs.createReadStream(filePath);
  dataStream.on('readable', () => {
    let buf = dataStream.read(512);
    while (buf !== null) {
      count++;
      console.log('Reading from file chunk Number: ', count);
      passThrough.push(Buffer.from(`${buf.toString('utf8')}:${count}`));
      buf = dataStream.read(512);
    }
  }).on('end', () => {
    console.log('Reading done ended');
    passThrough.push(null);
  });

  let options = {
    queueSize: 1
  };

  let uploadParams = {
    Bucket: bucket,
    Key: key,
    Body: passThrough
  };

  s3.upload(uploadParams, options, (err, data) => {
    if (err) {
      console.log('Upload failed with ', err);
      return;
    };
    console.log('Data returned', JSON.stringify(data));
    return;
  }).on('httpUploadProgress', (httpUploadProgress) => {
    console.log('https ', httpUploadProgress);
  });
};
uploadToS3Command
  .command('uploadToS3')
  .description('upload to s3')
  .option('-f, --filePath <filePath>', 'Path of the file to be uploaded')
  .option('-b, --bucket <bucket>', 'The destination bucket')
  .option('-k, --key <key>', 'The file name to upload')
  .action(uploadToS3);
uploadToS3Command.parse(process.argv);
```
[test.txt](https://github.com/aws/aws-sdk-js/files/3058246/test.txt)

**Comment by nepomozhets-el-ma** [comment]
Same issue 👍

**Comment by AllanFly120** [comment]
Hey @ramaguruprakash 

Seems like the 'end' event in PassThrough is never triggered. If you emit the 'end' event on to `passThrough` explicitly on `dataStream`'s 'end' event, you should be able to complete the upload.

**Comment by ramaguruprakash** [comment]
@AllanFly120  thanks for the response.

1. ```).on('end', () => {
    console.log('Reading done ended');
    passThrough.push(null);});
If you look at the above code, on the end of dataStream I am pushing a null indicating the end of stream.

2. This script works when you remove the `objectMode: true` which I think indicates that end of the stream is reached.

3. My Hypothesis of the issue (Maybe wrong because I don't completely understand SDK code.):
    a) Whenever there is data push to passThrough stream there is a `readable` event emitted in `aws-sdk/lib/s3/managed_upload.js`,.
    b)When the limit is reached for upload(queueSize*pageSize), it stops receiving the event (not sure why maybe the thread is busy or something) and once the upload is done it resumes back.
     c) By that time all the events are pushed to passThrough stream and only a single readable event is emitted in  `aws-sdk/lib/s3/managed_upload.js`. If this would have been a string the entire data in the passThrough stream is read but since it is an object only 1 record is read. Which means that the upload process is completed before completely reading the stream. Therefore, the end event is not emitted.
     d) ```A Readable stream in object mode will always return a single item from a call to stream.read(size), regardless of what the size argument is.... No streams in Node core are object mode streams. This pattern is only used by userland streaming libraries.``` in this link https://www.bennadel.com/blog/2878-should-the-relationship-between-object-mode-and-read-size-be-symmetric-in-node-js-streams.htm

**Comment by ramaguruprakash** [comment]
Hi, Any update on this? This is impacting our customers so clarity on this issue will help us a lot!!.

**Comment by ramaguruprakash** [comment]
Hi, Any update please ?

**Comment by AllanFly120** [comment]
Hey, @ramaguruprakash 

I will investigate the root cause, but I don't think your hypothesis is the case. When the date source ended, I don't think even 'passThrough' gets the `end` event. Have test with the `pipe()`?

**Comment by ramaguruprakash** [comment]
@AllanFly120 ,

passThrough gets the end event I have listened to the event and printed it if that is what you are taking about.  But if your hypothesis is right then it should not work for the regular mode also right (the non-object mode). It clearly works for it.

But yea thanks for trying to help me with the route cause.  Looking forward to hearing from you soon.

**Comment by ramaguruprakash** [comment]
@AllanFly120 ,
  Its been 10 days from the last update. I just want to understand the timeline of the resolution. It will help us plan on whether we have to look for some alternate solutions if the object mode is not supported or not used in the right way

**Comment by AllanFly120** [comment]
Hey @ramaguruprakash Unfortunately I haven't got time to look back to it recently, but I will take it up. Just to make sure: does sending `end` event fix the issue? I hope you can use it as a contemporary work around.

**Comment by ramaguruprakash** [comment]
@AllanFly120 , There is an end event, But aws-sdk is reading using readable which reads only 1 object per read. even when I add an end, it does not reach aws-sdk

**Comment by ramaguruprakash** [comment]
Hi @AllanFly120 , Its been a month, is it possible for you to investigate further, It will be really helpful.

**Comment by ramaguruprakash** [comment]
Update:
I just added a passThrough2 stream to the earlier script and it uploads because this passThrough2 is an non-object mode stream. So there definitely is a problem in s3 upload when we use the stream in the object mode.

```
const uploadToS3Command = require('commander');
const fs = require('fs');
const aws = require('aws-sdk');
const stream = require('stream');
const uploadToS3 = (commandArgs) => {
  let {
    filePath,
    bucket,
    key
  } = commandArgs;


  let s3 = new aws.S3();
  let count = 0;
  let passThrough = new stream.Readable({
    objectMode: true
  });
  passThrough._read = function () {};

  let passThrough2 = new stream.Readable({
    objectMode: true
  });
  passThrough2._read = function () {};

  let dataStream = fs.createReadStream(filePath);
  dataStream.on('readable', () => {
    let buf = dataStream.read(512);
    while (buf !== null) {
      count++;
      console.log('Reading from file chunk Number: ', count);
      passThrough.push(Buffer.from(`${buf.toString('utf8')}:${count}`));
      buf = dataStream.read(512);
    }
  }).on('end', () => {
    console.log('Reading done ended');
    passThrough.push(null);
  });

  passThrough.on('data', (data) => {
    console.log('passThrough data ', typeof data);
    passThrough2.push(data.toString());
  }).on('end', () => {
    console.log('pushed null here too');
    passThrough2.push(null);
  });
  let options = {
    queueSize: 1
  };

  let uploadParams = {
    Bucket: bucket,
    Key: key,
    Body: passThrough2
  };

  s3.upload(uploadParams, options, (err, data) => {
    if (err) {
      console.log('Upload failed with ', err);
      return;
    };
    console.log('Data returned', JSON.stringify(data));
    return;
  }).on('httpUploadProgress', (httpUploadProgress) => {
    console.log('https ', httpUploadProgress);
  });
};
uploadToS3Command
  .command('uploadToS3')
  .description('upload to s3')
  .option('-f, --filePath <filePath>', 'Path of the file to be uploaded')
  .option('-b, --bucket <bucket>', 'The destination bucket')
  .option('-k, --key <key>', 'The file name to upload')
  .action(uploadToS3);
uploadToS3Command.parse(process.argv);
```

**Comment by AllanFly120** [comment]
Hey @ramaguruprakash 

I haven't found the root cause but I think I have figure out the 'superficial cause'. Put the conclusion first: object mode stream isn't compatible with `ManagedUpload` in *most* cases. I use you original code snippet to illustrate my point.

1. When you read data from disk, and call the `Readable.prototype.push()` on your `passThrough` stream, you just shove the data(in this example it's ~512 byte length buffers) into the stream regardless of the back pressure. When `Readable.prototype.push()` returns `false`, the data is buffered in the `passThrough` stream. 

1. Everytime when `passThrough` emits `readable` event, `ManagedUpload` will try to read the chunk. [Here](https://github.com/aws/aws-sdk-js/blob/2212c8f7e2981a43c8ecc272d2b3a7dc7b35e1bd/lib/s3/managed_upload.js#L420~L421) the `ManagedUpload` assumes the stream is in buffer mode and try to read the specified slice of the chunk. However, since the stream is in object mode, the `ManagedUpload` can actually only read one object, in this case it's a ~512 byte buffer. In this case, the other buffered object remains unread in `passThrough`.

1. When file stream reaches the end, you push `null` to `passThrough`. You expect `passThrough` emits `end` event. But in fact `end` event will not emit unless the buffered data is completely consumed([reference](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_event_end)).

As it's descripted above, you can only trigger the `end` event when you have 0 buffered data. 

I don't think it is a bug if we really think of the meaning of supplying object stream to S3. Somewhere down the hood, the SDK will eventually serialize the objects into binary data. If we think of these JavaScript objects, SDK either lacks the information of how to serialize them or would have to make assumption on data serialization(JSON.stringify?). On the other hand, I cannot think of a use case that requires you to supply an object stream, maybe I'm wrong here.

I will update the API reference to make clear that object stream should be used with care.

**Comment by ramaguruprakash** [comment]
@AllanFly120 Thanks a lot for your detailed reply. 

I have 1 question -
1. Why does it happen only when size is greater that queueSize*partSize ? 
I see that for every object pushed there is a readable event in `managedUpload` till the size is less that queueSize*partSize. As soon as the size limit is reached there is a pause in the readable events even though the passThrough stream is getting data.
2. I think `managedUpload`  has some mechanism to serialize the objects because it's been working for us for so long till the size limit is reached. Please correct me if I am wrong. The only problem is we can only read one object at a time which is causing this issue.

The takeaways for me -
1. So is it good to assume that `managedUpload` MUST be provided with buffer stream? As I mentioned in a workaround, I am just adding another passThrough stream which is a non-object stream and it works., so is that the solution if we some reason have object streams.

**Comment by AllanFly120** [comment]
@ramaguruprakash 
I don't think the limit you mentioned has anything to do with the `queueSize * partSize`, you can try adjusting the `queueSize` or `partSize` to see if the limit changes accordingly(SDK's default `partSize` is 5 MB).

I suspect the `size limit` you observed is`sizeOfObject * queueSize`. When your file size is smaller than this limit, usually it's also small enough to be read in 1 chunk. When the chunk arrives, the `readable` event emitted. Then the [fillStream function](https://github.com/aws/aws-sdk-js/blob/2212c8f7e2981a43c8ecc272d2b3a7dc7b35e1bd/lib/s3/managed_upload.js#L416) will be called to fill in the `queueSize`. For example, if the `queueSize` is set to 4, the `fillStream()` will be called 4 times. In each invoke, the function will read in an object(it is expected to read a `partSize`). If your data size is smaller than the `limit`, all the data will be completely consumed in a single `readable` event. Then the `end` event can make through and trigger the upload to complete.

If your data is bigger than `sizeOfObject * queueSize`, the situation is different according to whether the data is bigger than 1 chunk. If the data is bigger than `sizeOfObject * queueSize` but smaller than 1 chunk, when you push `null`, there is still data in stream not consumed, so you won't get complete the upload. Note that `sizeOfObject * queueSize` is the biggest size you can upload by a single `readable event` in `object mode`. 

When you data is bigger than 1 chunk, not only does your `end` event cannot make through, but also any further chunk can only be uploaded the first `sizeOfObject * queueSize` slice of data. And since there is no `end` event, your upload cannot be completed.

**Comment by AllanFly120** [comment]
@ramaguruprakash 

> So is it good to assume that managedUpload MUST be provided with buffer stream?

You should supply buffer stream. If object stream works previously, it's only because the data is completely consumed with luck. I will update the API reference to mention this.

**Comment by ramaguruprakash** [comment]
Thanks, @AllanFly120  for all the support
