### ISSUE TITLE
Official/native support for dynamodb-data-mapper

### ISSUE THREAD

**Issue by ajhool** [aws/aws-sdk-js#2637]
There is an aws project called DynamoDB Data Mapper JS (https://github.com/awslabs/dynamodb-data-mapper-js). It's been very useful for interfacing between javascript and dynamo. It sits at 11,500 weekly downloads. However, it looks like the repo is not being adequately maintained and some breaking issues are starting to emerge. There is a popular, unanswered issue asking if the repo is dead: https://github.com/awslabs/dynamodb-data-mapper-js/issues/138

Could the package be moved into the official aws-sdk instead of residing in a separate repo? I'm not sure why it was placed in a separate repo to begin with as it is an incredibly simple way to interface between javascript and Dynamo. The separate annotations package is also fantastic.

**Comment by AllanFly120** [comment]
Hey @ajhool,

The `awslabs` org is used for projects that are less 'prime-support'. We just got the ownership for that library recently. We will start to look into highly requested bug report because of the our limited bandwidth. 

> Could the package be moved into the official aws-sdk instead of residing in a separate repo?
Yes, we have plan to move the library to [V3](https://github.com/aws/aws-sdk-js-v3) after it comes to offictial.

**Comment by ajhool** [comment]
Thank you for your response and that is great news about v3!
