### ISSUE TITLE
aws_sdk__WEBPACK_IMPORTED_MODULE_0___default.a.Textract is not a constructor

### ISSUE THREAD

**Issue by Kojji** [aws/aws-sdk-js#2657]
Hi, i've been trying to use Textract with VueJs, and i get an error that i don't know how to solve... "aws_sdk__WEBPACK_IMPORTED_MODULE_0___default.a.Textract is not a constructor" from the following command, `var textract = new AWS.Textract();`, before that i imported and configured it with and account approved for the preview of textract,
`import AWS from 'aws-sdk'
AWS.config.update({
  region: 'us-east-1',
  accessKeyId: '<my-access-key>',
  secretAccessKey: '<my-secret-access-key>'
});`
I'm currently using v2.450.0
I had made some tests to see if it was an import error, but using the constructors, `var s3 = new AWS.S3();` and `var Lambda = new AWS.Lambda();` ,it worked and had its configs updated as the configuration abobe, in nodeJs it worked as well, but when i use in vue it returns the error.
I was thinking on sending a request diretly to the endpoint as a work around, but if it has a direct fix it would be nice.

**Comment by AllanFly120** [comment]
Hi @Kojji,

According to the [SDK setting](https://github.com/aws/aws-sdk-js/blob/master/clients/browser_default.js), the `Testract` service is not available in your browser SDK. There are only a subset of AWS services available in SDK browser build mainly because not all the AWS services support CORS. But this list is not always up-to-date. If you are sure that the service works in browser environment, you can get around it by importing the client explicitly in your code before bundling like:

```javascript
const Trestract = require('aws-sdk/clients/textract')
```

Or you can use your [browser builder](https://sdk.amazonaws.com/builder/js/) to build the SDK with the service you selected.

**Comment by Kojji** [comment]
yeah, it looks like it isn't supposed to work in the browser environment, i tried to import the client explicitly, as you said, and with the latest version as well, i'll work with it in another way, thanks, i'm closing this issue.
