### ISSUE TITLE
putItem don't recognize AttributeValue in Node.js

### ISSUE THREAD

**Issue by gustavosatheler** [aws/aws-sdk-js#2672]
Error:
**One or more parameter values were invalid: Type mismatch for key user_id expected: S actual: M**

Runtime: Node.js 8.10 and Node.js 10.x

Follow the object I want to put
```javascript
const user = {
    cpf: "12332112345",
    fullname: "Josevaldo",
    password: "secret",
    phone: "555533221100"
}

const Item = {
    "user_id": {
        "S": user.cpf
    },
    "cpf": {
        "N": user.cpf
    },
    "fullname": {
        "S": user.fullname
    },
    "password": {
        "S": user.password
    },
    "phone": {
        "S": user.phone
    }
}

```

How to put
```javascript
const docClient = new AWS.DynamoDB.DocumentClient(config)
docClient.put({
    'users',
    Item,
    'attribute_not_exists(user_id)'
}).promise()
```

**Comment by trivikr** [comment]
From [documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-example-document-client.html): The DynamoDB document client simplifies working with items by abstracting the notion of attribute values 
The value is passed directly instead of creating an Object.

In Item object, making the following change for all params should fix your issue:
```
    "user_id": {
        "S": user.cpf
    }
```
to
```
    "user_id": user.cpf
```

Closing this issue, please reopen if you still have questions.
