### ISSUE TITLE
ChainableTemporaryCredentials cannot be used for non-default regions

### ISSUE THREAD

**Issue by tjunnone** [aws/aws-sdk-js#2673]
With the introduction of the Hong Kong region, there is now the concept of "opt-in" regions (Hong Kong) and "enabled by default" regions (every other region so far). STS has an interesting behavior where you can either request a token from a regional endpoint which will be valid in all regions, or you can use the default global endpoint and the token will only be valid in the "enabled by default" regions. There is an AWS account-wide way to opt-in to a larger token issued by the global STS endpoint, but not everyone can or want to do that.

The problem comes when you're trying to use ChainableTemporaryCredentials (or the older TemporaryCredentials for that matter) in your config for role-based authentication. There doesn't seem to be a way to specify that the credentials provider should use a regional STS endpoint, and therefore it doesn't appear to be possible to get temporary credentials for the Hong Kong region at this time using the SDK. I think perhaps the addition of a region or endpoint param to ChainableTemporaryCredentials would be the most straightforward way.

I also considered setting the global AWS.Config.sts.endpoint, but a) this doesn't seem to help b) you can't use a global config in any type of server where you need to concurrently directly requests to multiple regions, everything has to be configured per-request and per-AWS service.

**Comment by workeitel** [comment]
The `param`-parameter for `ChainableTemporaryCredentials` constructor is forwarded to the STS client so in theory this should set the endpoint: `new ChainableTemporaryCredentials({endpoint: ".."})`.

https://github.com/aws/aws-sdk-js/blob/cb1604ca89a077ffdb86127884292d3b18c8b4df/lib/credentials/chainable_temporary_credentials.js#L121-L125

But passing STS Client options in the constructor is not allowed by the typings: https://github.com/aws/aws-sdk-js/blob/c175cb2b89576f01c08ebf39b232584e4fa2c0e0/lib/credentials/chainable_temporary_credentials.d.ts#L25

One workaround is setting the endpoint afterwards:

```javascript
const credentials = new AWS.ChainableTemporaryCredentials();
credentials.service.config.endpoint = "https://sts.us-east-1.amazonaws.com";
```

Which works for `ChainableTemporaryCredentials` but not `TemporaryCredentials` since the STS client is build on demand for `TemporaryCredentials`:

https://github.com/aws/aws-sdk-js/blob/cb1604ca89a077ffdb86127884292d3b18c8b4df/lib/credentials/temporary_credentials.js#L125-L127
