### ISSUE TITLE
JS SDK - getCostAndUsage ValidationException: end date past the beginning of next month

### ISSUE THREAD

**Issue by sjriddle** [aws/aws-sdk-js#2732]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I'm using the Javascript AWS SDK to get cost and usage for billing. The date range that is being used in the method are `2019-06-18` through `2019-07-03`. When this is run, I get a validation exception: 
```
 message: 'end date past the beginning of next month',
  code: 'ValidationException',
  time: 2019-06-20T16:36:26.382Z,
  requestId: '8cd4e923-9379-11e9-b60e-0f6c84c39e7b',
  statusCode: 400,
  retryable: false,

```

I've read the documentation and understand the end date is exclusive for the `getCostAndUsage` method. If I change the end date to the 1st, it will get the data (as specified in `http://docs.amazonaws.cn/en_us/AWSJavaScriptSDK/latest/AWS/CostExplorer.html` Do you know of any workaround or fix to this specific problem? Is there something I'm missing?

**Comment by AllanFly120** [comment]
Hey @sjriddle,

According to the error message, my understanding is that you cannot make a request period later than `2019-07-01`. I assume the purpose of it is to prohibit queries with the time range later than current date. I'm not so sure of the rationale of this behavior. To workaround this issue, can you validate the date range to make sure you are not querying the future month's usage?

Since this is not an SDK issue, I will close it. If you have more questions, feel free to reach out to the service team on the [forum](https://forums.aws.amazon.com/thread.jspa?threadID=279084) or comment below.
