### ISSUE TITLE
Backlog of issues

### ISSUE THREAD

**Issue by ajhool** [aws/aws-sdk-js#2733]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

There are multiple issues that are still open, appear to have community interest, but have received no comments. I'm sure there are issues that I've missed which have received comments but not from the AWS team. Would AWS please consider addressing/resolving/closing these open issues that have never been addressed?

-- Over a year old, no comments --
#1576
#1583
#1599
#1654
#1659
#1917
#1927
#1932
-- Less than a year old, but more than 3 months old, no comments --
#2511
#2527
#2579
#2637 (Note: this is an issue that I opened)
#2641

I would also note that there are 18 open issues from between 2 to 20 days ago that have not been addressed. `aws-sdk-js` is a critical dependency for almost any app that interfaces with AWS resources, but it is not officially supported by the AWS Support Center and we are told to "post an issue about it on GitHub". The support center offers contractual support within 12-24 hours and it is clear that GitHub issues do not receive nearly the same speed of support and sometimes the support never comes.

It is frustrating that a critical issue that I opened in April has never received comment and that the AWS Support Center also does not provide support for it. I imagine that the other community members whose issues I've linked also share in this frustration.

Furthermore, the longer it takes to address these issues and develop the software, the longer it is before we can spend money on AWS infrastructure, which is something that we all want us to do.

**Comment by ajhool** [comment]
+18 days and counting, lol

**Comment by ajhool** [comment]
+18 days and counting

**Comment by AllanFly120** [comment]
Hey @ajhool,

Apologies for the delayed response.

The majority of the tickets you linked to here are tagged as "feature request". We intentionally leave feature requests open until the features have been implemented.
We plan to implement many of these feature requests in [SDK V3](https://github.com/aws/aws-sdk-js-v3), following a particular process and timeline.

For most of the other issues, we managed to answer questions in time.
In some circumstances, we need to spend time reproducing the issue to understand its root cause.
Beyond that, some issues do slip through. We will review the issues that are not labeled or responded to soon and try to close them if we can.
