### ISSUE TITLE
How to handle _hardError exceptions from s3.copyObject

### ISSUE THREAD

**Issue by Meekohi** [aws/aws-sdk-js#280]
When using `s3.copyObject`, if the original object doesn't exist then `aws-sdk` throws an exception `"NoSuchKey: The specified key does not exist."`. I'd like to handle these gracefully, but try/catch blocks don't work since the the exception is thrown outside the call stack.

Is there a correct way to handle this? Is it required to explicitly check the existence of the source object before calling `s3.copyObject`?

**Comment by seankovacs** [comment]
Why was this closed? aws-sdk is raising an exception bypassing any event emitters or err callbacks if a key doesn't exist. Resorting to a  global "catchall" event seems wrong.

**Comment by jzelenkov** [comment]
I run into the same exact issue.

Trying to download an object from s3 that doesn't exist is a _programmer error_. There is nothing that could be done about it. That's why `aws-sdk` throws an `uncaughtException` at this point.

Network issue would produce an _operational error_ that will be passed to the stream. Then it is up a developer to do something about it:

```js
s3.getObject(params)
      .createReadStream()
      .pipe(file)
      .on('error', (err) => {
        console.log('download failed')
        // download retry logic ?
      })
```

One way to avoid `uncaughtException` is to check if an object exists in s3 bucket before trying to download it.

----

A good article covering errors in NodeJS: [https://www.joyent.com/developers/node/design/errors](https://www.joyent.com/developers/node/design/errors)

**Comment by seankovacs** [comment]
That's odd, fs doesn't crash an app if a file doesn't exist. It actually uses the err in the callback. 
 \_(ツ)_/¯

**Comment by jzelenkov** [comment]
good point. APIs are hard

**Comment by logidelic** [comment]
Is this being looked at? Is there a workaround? To be clear, the problem is that this exception cannot be caught by the client code. This a fatal API bug. No API should throw an exception internally that is not caught internally. This will, at worst, simply crash the node app or, at best, will trigger a global exception handler to allow clean shutdown. Both of these are unacceptable for obvious reasons.

FWIW, I'm getting this issue with s3.getObject when an invalid key name is specified.

**Comment by verveguy** [comment]
@logidelic: I'm with you on this one.

@lsegal this is insane. I'm in lambda using node and cannot catch this exception. S3 is literally killing my function *with no way for me to gracefully recover*.

To the point earlier, fs doesn't crash your app if a file doesn't exist. That's what exceptions are *for*.

**Comment by chrisradek** [comment]
@verveguy 
Can you share your example where an uncatchable error is being thrown?

Looking at @jzelenkov's example, adding an `error` event listener to the read stream would catch errors thrown by the service, such as `NoSuchKey` if trying to download an object that doesn't exist.

**Comment by verveguy** [comment]
@chrisradek sure. 

Note: I now realize that I have *not* explicitly tried to add event handlers to the *read* stream. But here's the thing, I shouldn't have to IMHO. In my case, even more so because I'm trying to use the Promise support offered by the AWS SDK.

So what am I doing?

I'm writing a simple (!) lamdba function in node and using the AWS S3 SDK. 
Since node is all about async, I'm therefore using Promises. I'm also trying to use the stream support to easily get the file content from S3 onto the /tmp filestore. 

What *should* happen *(IMHO) is that by using a Promise, my catch() portion of the promise chain should in fact be invoked with whatever exception is thrown by the machinery underlying S3.getObject . However, that's not the case. S3.getObject() wants to be "special" despite the promise of the promise() support in the AWS SDK. As soon as I call s3.getObject().promise() we're off to the races and the exception is thrown pretty promptly. Note that the promise() is wrapping the AWSRequest, *not* wrapping the readStream as you propose doing with event handlers. 

In the end, I've managed to cobble together a solution that wraps things in a Promise of my own and uses the event handlers on the *output file* at the end of the pipe to invoke the resolve() , reject(). 

However, that's too far down the pipe (so to speak) to catch the errors thrown from the event handlers underlying the S3 request. You're right: perhaps I could use the readStream instead. I might even try that sometime.

But for now, I put calls to headObject in place first to avoid even trying to make a getObject call at all since it was unsafe to do so.

Having read various threads around here in growing frustration, this all appears to boil down to a fundamental philosophical argument about what the behavior of an async operation from S3 should be like vs what other async operations (such as fs calls) are like. The (broken) promise support only makes it even more frustrating. And trying to use promises plus streams is making me insane.

I'd love a clean code example of a properly promisified S3.getObject with streams writing to a local file that works without exception even when the ket doesn't exist.

**Comment by lsegal** [comment]
@verveguy can you show a full example of what you are doing? It's hard to know where a problem might be without knowing how to reproduce the issue.

**Comment by chrisradek** [comment]
How are you attempting to use `s3.getObject` with both promises and streams? The two aren't currently supported together.

Using just promises, the `catch` handler on your promise chain should capture the error.

Part of the underlying problem with combining streams and promises in the same interface is that promises only really care about 2 states: resolve and reject. Streams have more than 2 states though, such as data/readable, as well as error and end.

What we would need to do is wrap the current stream that we return through the SDK with a new type that exposes `promise` methods. We'd still have to deal with the question of whether calling `then` on the stream will pass the full content as a buffer to the resolving function or not. Since streams are often used to pipe data from one source to another in a memory-efficient way, keeping an internal store of all the data so that it can be returned when using promises would be a huge negative for many users.

It seems like converting streams to promises is something that should be handled outside of the SDK as it would be an important choice made by the user. There are 3rd party libraries that will do just that.

As for the argument for not having to add event handlers to catch errors on the readstream, that's how many event emitter-based APIs work in node.js.  Even calling `fs.createReadStream` with an invalid path will throw an uncatchable error if you do a simple try/catch, and requires the user to attach an `error` listener to the stream in order to handle the error. Maybe I'm missing something about this argument, please elaborate if so.

@lsegal beat me to the question. Can you share an example of what you're doing? It could be that there really is something the SDK is doing wrong.

**Comment by lsegal** [comment]
It should also be mentioned, just for clarity, that this *specific* issue regarded an explicit `throw(err)` call from inside a request callback (equivalent to throwing from a `.then()` callback), which is expected to bubble up. The original reported issue was not about errors bubbling out of the SDK's internal handling, which is why it was closed. If you are seeing internal errors bubbling up as thrown errors, it would be great to provide reproduction steps so those scenarios can be looked at.

**Comment by verveguy** [comment]
@lsegal: I'll open a new issue regarding the use of s3.getObject, streams and promises.
