### ISSUE TITLE
S3: Incorrect endpoint when generating presigned url

### ISSUE THREAD

**Issue by aunpongsit** [aws/aws-sdk-js#2802]
**Describe the bug**
I was getting `https://bucket-name.s3.cn-north-1.amazonaws.com.cn` domain all the time when using `getSignedUrl` after `listObjectsV2` of another s3 client on the same bucket name even if the s3 client was created with a region specified.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v8.11.3

**SDK version number**
 aws-sdk@2.505.0

**To Reproduce (observed behavior)**
```
import AWS from 'aws-sdk';

const BUCKET = 'bucket-name';
const KEY = 'path/to/key';

(async function main() {
  const chinaS3 = new AWS.S3({region: 'cn-north-1', credentials: new AWS.SharedIniFileCredentials({profile: 'china'})});
  const s3 = new AWS.S3({region: 'ap-southeast-1', credentials: new AWS.SharedIniFileCredentials({profile: 'default'})});

  console.log(s3.getSignedUrl('getObject', {Bucket: BUCKET, Key: KEY})); // correct, got ap-southeast-1 region
  await chinaS3.listObjectsV2({Bucket: BUCKET}).promise();
  console.log(s3.getSignedUrl('getObject', {Bucket: BUCKET, Key: KEY})); // incorrect, got cn-north-1 region
})();
```
Output:
```
https://bucket-name.s3.ap-southeast-1.amazonaws.com/path/to/key?AWSAccessKeyId=xxx&Expires=xxx&Signature=xxx
https://bucket-name.s3.cn-north-1.amazonaws.com.cn/path/to/key?AWSAccessKeyId=xxx&Expires=xxx&Signature=xxx
```

**Expected behavior**
Output from both `console.log` should be the same

**Additional context**
I also tried using callback in `s3.getSignedUrl` - still the same

**Comment by AllanFly120** [comment]
Hey @aunpongsit 

The `getSignedUrl` functionality in SDK is a client-side function(admittedly it will request for credential token if you are using temporary credentials). This means SDK doesn't have the knowledge of which region the bucket is actually in. So you need to supply the right region.

Fortunately, if the region in your request and the actual region are in the same [partition](https://docs.aws.amazon.com/sdkforruby/api/Aws/Partitions.html), S3 will response the correct region. The S3 client will also cache the correct region so that next time it will override the region to correct one for the following requests. You can grab these correct region by calling `s3.headBucket`.

So, to make sure the region in your url is correct, you should call `s3.headBucket` before calling `s3.getSignedUrl`. For example, if your bucket is in `us-west-2` but your client is configured to region `ap-southeast-1`, after calling `s3.headBucket`(successfully), the s3 client will know the bucket is actually in `us-west-2`. Then you can create correct url with `s3.getSignedUrl`.

But what if the actual region and request region aren't in the same partition?(e.g. `cn-north-1` and `ap-southeast-1`) Your `s3.headBucket` would fail and you will know your s3 client is not configured to the correct region.

**Comment by aunpongsit** [comment]
> But what if the actual region and request region aren't in the same partition?(e.g. cn-north-1 and ap-southeast-1) Your s3.headBucket would fail and you will know your s3 client is not configured to the correct region.

So for this case, how can I make it point to the correct region again? I also tried calling `s3.headBucket` as the code below. It seems like no matter how I call `s3.getSignedUrl` after that it always points to china region.
```
import AWS from 'aws-sdk';

const BUCKET = 'bucket-name';
const KEY = 'path/to/key';

(async function main() {
  const chinaS3 = new AWS.S3({region: 'cn-north-1', credentials: new AWS.SharedIniFileCredentials({profile: 'china'})});
  const s3 = new AWS.S3({region: 'ap-southeast-1', credentials: new AWS.SharedIniFileCredentials({profile: 'default'})});

  console.log(s3.getSignedUrl('getObject', {Bucket: BUCKET, Key: KEY})); // got ap-southeast-1 region
  await chinaS3.listObjectsV2({Bucket: BUCKET}).promise();
  try {
    console.log(await s3.headBucket({Bucket: BUCKET}).promise()); // failed as you said
  } catch (e) {
    console.log(s3.getSignedUrl('getObject', {Bucket: BUCKET, Key: KEY})); // still got cn-north-1 region
  }
})();
```

**Comment by aunpongsit** [comment]
I finally solved it by adding `AWS.config.s3 = {endpoint: s3.config.endpoint};` after any API call to china region to manually override S3 endpoint which might be cached for some reason.

PS. I still believe this is a SDK bug. If the S3 client explicitly specifies a region then the SDK should respect that and not let another S3 client overrides it.
