### ISSUE TITLE
Incomplete documentation of rds.describeDBInstances

### ISSUE THREAD

**Issue by adclark1** [aws/aws-sdk-js#2809]
The documentation here:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html

Under the describeDBInstances method in the Parameters section, two supported filters are listed: db-cluster-id and db-instance-id. dbi-resource-id is also supported, but it is not listed on this page. It is necessary if you need to describe the database instance using the resource ID rather than the other identifiers. It works as expected, it's just not documented on that page.

**Comment by AllanFly120** [comment]
Hey @adclark1 

Thanks you for bring this up. It also affects [other SDKs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#describe_db_instances-instance_method). I believe it's because RDS service team doesn't ship the newest document. I have reached out to them to get it updated.

**Comment by randyurbano** [comment]
I added the filter to the RDS API Reference:

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html

The change will propagate to SDK documentation.

Thanks for your feedback.

**Comment by adclark1** [comment]
Thanks!
