### ISSUE TITLE
Buffer error still present in latest version of SDK

### ISSUE THREAD

**Issue by samparnell** [aws/aws-sdk-js#2812]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am using the latest version of the SDK in Node Lambda functions. 
Still seeing this in the logs when using the Node v10 runtime. 

 [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

This was supposedly fixed in v2.467.0. 
I've tested with with version 2.508.0 and 2.510.0 (confirmed by logging out AWS.VERSION in the Lambda function) and the error is still present. 

**If on Node.js, are you running this on AWS Lambda?**
Yes, using the Node v10 runtime. 

**SDK version number**
v2.508.0 & v2.510.0

**To Reproduce (observed behavior)**
Any lambda function that includes the aws-sdk seems to have this error

**Additional context**
https://github.com/aws/aws-sdk-js/pull/2687
https://github.com/aws/aws-sdk-js/issues/2671
https://github.com/aws/aws-sdk-js/issues/2354
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by AllanFly120** [comment]
Hey @samparnell 

We do keep some old construtors because I thought they won't be imported in Lambda, like here: https://github.com/aws/aws-sdk-js/blob/7e5fa20c97f6ad0eee18d5bd06223ccca5b69f2d/lib/browserSha1.js#L102

It will be helpful if you can provide where is the warning thrown from. In Lambda, you can try attach to the `warning` event on `process`, here's the [doc](https://nodejs.org/docs/latest/api/process.html#process_event_warning). It should give you the warning name and stack trace.

**Comment by samparnell** [comment]
Hi Allan, that was helpful and did in fact expose that the aws-sdk is not the culprit! Sorry for the false alarm.
