### ISSUE TITLE
CORS Support for RDSDataService API (Aurora Serverless Data API)

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-sdk-js#2825]
Hi, 

This request is for CORS support for the RDSDataService API; basically, same issue as described here: 
https://github.com/aws/aws-sdk-js/issues/1967

Understood it lies with the Aurora service team, but like above, wondering if that's a request you can help facilitate?

**Comment by AllanFly120** [comment]
Hi @matwerber1,

We can reach out the to service team internally to bring this issue more observability. To make the issue solved faster, please also reach out to the service team on the [forum](https://forums.aws.amazon.com/forum.jspa?forumID=60)

**Comment by ajredniwja** [comment]
Hi @matwerber1,

 Thank you for your patience.

 It is not recommended for RDS Data API to be called in client-side JavaScript on the browser. This may leak implementation details (SQL, parameters, cluster and secret ARNs, etc...) to the client and be a security issue for the website owner.

The RDS Data service team recommended that the best practice is to call RDS Data Api within a light-weight back-end service (i.e Lambda) and instead of directly from client-side website code. 

If you have any other questions you can bring it to the forum.
