### ISSUE TITLE
`AWS.DynamoDB.DocumentClient.batchWrite` should provide type generic for type safety

### ISSUE THREAD

**Issue by tommedema** [aws/aws-sdk-js#2835]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Currently I'm not getting any type safety when using `batchWrite`:

```
interface IAction {
  viewId: string,
  lastUserEmail?: string,
  actionType: string,
  createdAt: number,
  payload: object
}

const actionItem = {
      viewId
}

const result = await db.batchWrite({
      RequestItems: {
        [tableName]: [{
          PutRequest: {
            Item: actionItem
          }
        }]
      }
    }).promise()
```

This is unsafe, as actionItem could be anything (I want to ensure that it is of type `IAction`). Instead I should be able to define a type generic like `db.batchWrite<IAction>` such that the type of the items I am creating is being checked.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v8.16.0

**SDK version number**
2.512.0

**Comment by AllanFly120** [comment]
Hey @tommedema 

Can you make sure you are using [`Document Client`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) instead of [`regular client`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html)? The type definition equivalent to `batchWrite` in regular client is [`batchWriteItem`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#batchWriteItem-property). 

So you can either call `batchWriteItem` on `AWS.DynamoDB` client or `batchWrite` on `AWS.DynamoDB.DocumentClient` client. You are likely calling `batchWrite` on an `AWS.DynamoDB` client.

**Comment by tommedema** [comment]
@AllanFly120 I am calling `batchWrite` on `AWS.DynamoDB.DocumentClient` (confirmed), and it does not have a type generic as you can see here: https://github.com/aws/aws-sdk-js/blob/a0010e6fde102c86496ecd9683f50554f3493c3f/lib/dynamodb/document_client.d.ts#L32

Therefore there is no way to define the type of the item inserted
