### ISSUE TITLE
AWS.IoTAnalytics in a browser app

### ISSUE THREAD

**Issue by patrick-239** [aws/aws-sdk-js#2897]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I want to use a data from a DataSet in a browser app, but a IotAnalytics not included in file aws-sdk/client/browser_default.js
If I manually add a line "IotAnalytics: require('./iotanalytics')" in file "aws-sdk/client/browser_default.js" everything works perfect. 

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.2

**SDK version number**
2.546.0

**To Reproduce (observed behavior)**
Line 
var iotanalytics = new AWS.IoTAnalytics();
failed with a error
TypeError: undefined is not a constructor (evaluating 'new AWS.IoTAnalytics()')

**Expected behavior**
object AWS.IoTAnalytics  could be created and used in a browser app. 

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @patrick-239,

Thank-you for reaching out, the reason for not having some services included in the browser_default.js is because some services don't support CORS yet.
 I tried using the constructor in the browser, I used [dekstop builder](https://sdk.amazonaws.com/builder/js/) and tried it in the browser console. Can you try using the desktop builder and selecting the services you need.

Please reach out if you have any additional questions.
