### ISSUE TITLE
AWS Lambda exposing secrets to lambda functions

### ISSUE THREAD

**Issue by kailashyogeshwar85** [aws/aws-sdk-js#2937]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
logging process.env inside lambda function print sensitvie keys like aws_accesskey, secret key,aws_session_key. What are those keys and can those keys be used for some kind of hijacking ?

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the Node.js version**

8.14.0

**SDK version number**
2.564.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
create lambda function and return process.env in callback

**Expected behavior**
No secrets should be visible

**Screenshots**
 
Note:

I have not set any env variables for lambda functions this are by default exposed.

**Comment by ajredniwja** [comment]
@kailashyogeshwar85 Thank-you for reaching to us with your issue, I have reached out to the service team internally and will get back to you once I hear from them.

**Comment by ajredniwja** [comment]
Hey @kailashyogeshwar85, 

Thank-you for your patience. This is expected behavior by the service team according to their design. The secrets exposed there are the execution role's secrets. It should be secure to use it as it is. You can create different roles with different permissions. More information found [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html). 

Please reach out if you have any other questions.
