### ISSUE TITLE
Possible to run integration tests with S3 for free

### ISSUE THREAD

**Issue by Borewit** [aws/aws-sdk-js#2974]
I developed a kind of extension to *aws-sdk*, [@music-metadata/s3](https://github.com/Borewit/music-metadata-s3), which is able to retrieve metadata from audio files stored in the S3 cloud.
What makes this component special, is that it uses chunked transfer, is very require very little bandwidth to read the metadata. An interesting component to application dealing with audio files, using the S3 as a storage backend.

I would like to get in touch with Amazon to help me to ensure I can keep my integration tests up and running without running into costs.

Can you please help me with that?

**Comment by ajredniwja** [comment]
Hey @Borewit, thank-you for reaching out and for your patience.
You might wanna ask this question using: https://aws.amazon.com/contact-us/
 For pricing calculation and information: https://docs.aws.amazon.com/pricing-calculator/latest/userguide/what-is-pricing-calculator.html

Closing this issue, since it is not related to the functioning of the SDK.
