### ISSUE TITLE
problem saving / reading large numbers from DynamoDB

### ISSUE THREAD

**Issue by thinwhiteduke80** [aws/aws-sdk-js#3126]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Reading large numeric values using AWS.DynamoDB.DocumentClient fails for large numbers, 'n' character is appended to the value.

The problem has been discovered on SDK v2.630.0, the code works fine on 2.486.0, see outputs below.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, but the problem exists also when executing code locally

**Details of the browser/Node.js version**
v12.14.1

**SDK version number**
v2.630.0

**To Reproduce (observed behavior)**

Create table 'Bug' with string hashkey named 'id'.

Run following code

```
const AWS = require('aws-sdk')
const crypto = require('crypto')

const id = crypto.randomBytes(20).toString('hex')
const largeNumber = 4912103092126044000

const put = async () => {
  var params = {
    TableName: 'Bug',
    Item: {
      id,
      NumAttribute: largeNumber
    }
  }

  console.log('writing item', params)
  var documentClient = new AWS.DynamoDB.DocumentClient()
  await documentClient.put(params).promise()
}

const get = async () => {
  var params = {
    TableName: 'Bug',
    Key: {
      id
    }
  }

  var documentClient = new AWS.DynamoDB.DocumentClient()

  const res = await documentClient.get(params).promise()
  console.log('got item', res)
}

const run = async () => {
  await put()
  await get()
}

run()
```

Output on 2.630 (notice 'n' character appended to the NumAttribute)

```
writing item {
  TableName: 'Bug',
  Item: {
    id: '1e29fd53ef9e4d51ba501d0f3d517a1fd3706370',
    NumAttribute: 4912103092126044000
  }
}
got item {
  Item: {
    id: '1e29fd53ef9e4d51ba501d0f3d517a1fd3706370',
    NumAttribute: 4912103092126044000n
  }
}
```

Output on 2.486.0

```
writing item {
  TableName: 'Bug',
  Item: {
    id: 'c8bfd2e8508810459387b30a93250137d913cf86',
    NumAttribute: 4912103092126044000
  }
}
got item {
  Item: {
    id: 'c8bfd2e8508810459387b30a93250137d913cf86',
    NumAttribute: 4912103092126044000
  }
}
```

**Comment by ajredniwja** [comment]
Hey @thinwhiteduke80 thank-you for reaching out to us with your issue. 

This change was introduce in v2.610.0 in order to support BigInt in DynamoDb in the PR: https://github.com/aws/aws-sdk-js/pull/3019. 

Talking about the specifics, when you do a get operation the SDK checks if the number is a [safe integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger) or not, using the JavaScript's isSafeInteger() as can be seen below https://github.com/aws/aws-sdk-js/blob/db4cb0f07c03524d4820c63c2d27396dcbefaab7/lib/dynamodb/converter.js#L231

it gets converted to a bigInt which is literally appending an `n` to the number as described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).

The workaround for this will depend upon your use case, you can customize the SDK or convert back the output after receiving it. Please reach out if you have any other questions.
