### ISSUE TITLE
SDK have some problem with credentials on ECS fargate

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-sdk-js#3176]
when running the following code on Fargate(I am using the `node:10.18.1`  docker image):

```
const verifySession = (username, custom, callback) => {

    const lambda = new AWS.Lambda({region: IPSA_REGION_NAME});
    var params = {
        FunctionName: VERIFY_SESSION_LAMBDA,
        InvocationType: "RequestResponse",
        LogType: "Tail",
        Payload: `{"username": "${username}", "custom": "${custom}"`,
    };
    lambda.invoke(params, function(err, data) {
        if (err) {
		console.log(err, err.stack);
                callback(false);
        } else {
           callback(data.Payload == 'true');
        }
    });
}

```
I receive the following error:

> { TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined

which I believe is related to credentials. Because when running the same code on local, if I do not set the `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY`, I receive the same error. But if I set these variables, the code runs fine on local.

I am sure that the above code was working fine a couple of days ago. But I do not know what has happened.

**Comment by ajredniwja** [comment]
If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Otherwise is it possible for you to provide the complete stack trace?

**Comment by ajredniwja** [comment]
Closing due to lack of inactivity. Please re-open and reach out if you have additional questions.
