### ISSUE TITLE
DynamoDBSet doesn't implement iterator protocol

### ISSUE THREAD

**Issue by clar-cmp** [aws/aws-sdk-js#3214]
The DynamoDBSet class does not implement the iterator protocol, and cannot be used in `for...of` loops. For example, the value `DynamoDB.Converter.unmarshall({ NS: [1, 2, 3] })` will not be iterable, but `DynamoDB.Converter.unmarshall({ NS: [1, 2, 3] }).values` is.

I've checked the code directly on master and this is not the case. Having a `[Symbol.iterator]` property defined will make it easier to check if a returned value is a list/set without having to specifically check for the `values` property. Simply checking  if `[Symbol.iterator]` is defined will work for both.

This applies to the current master, or release 2.656.0.

**Comment by ajredniwja** [comment]
Hey @clar-cmp thank-you for reaching out to us with your issue, this is not a necessarily a bug with the SDK but an enhancement that can be made since the iteration is made possible using how you mentioned `DynamoDB.Converter.unmarshall({ NS: [1, 2, 3] }).values`.
Making the change to ignore `.values` and make `DynamoDB.Converter.unmarshall({ NS: [1, 2, 3] })` will be a breaking change for many customers, do you think it will be a good step to implement that? In my opinion, I believe that it should not be made. 

Please reach out for any other questions that you might have.

**Comment by clar-cmp** [comment]
Hi @ajredniwja, this isn't a breaking change; people would still be able to access via `.values` but also via `[Symbol.iterator]`. The only code that would break is code that uses a check for `[Symbol.iterator]` as a list check instead of `Array.isArray`, which would already be an incorrect implementation.

**Comment by ajredniwja** [comment]
Hey @clar-cmp, can you add code links where [Symbol.iterator] should be added?

We would be also appreciate a PR if you want to work on it.

**Comment by clar-cmp** [comment]
Hi, @ajredniwja, I'll try and get a PR in the next few days. :)
