### ISSUE TITLE
GET_MEDIA_FOR_FRAGMENT_LIST returns status `ok` for fragment not found

### ISSUE THREAD

**Issue by igormq** [aws/aws-sdk-js#3217]
**Describe the bug**
Request to KinesisVideoMediaArchive.getMediaForFragmentList often returns :

```
EߣB��matroskaB��B��S�g�������T�g�ss�g�9E�AWS_KINESISVIDEO_ERROR_CODED�FRAGMENT_NOT_FOUNDg�)E�AWS_KINESISVIDEO_ERROR_IDD�3000g�[E� AWS_KINESISVIDEO_FRAGMENT_NUMBERD�/MY_FRAGMENT_NUMBER
```
and status=200. Shouldn't return an error/reject the promise? 

Also, I am 100% sure that it does exist (my second problem). Then, my lambda fails and retries, and often after the second or third retry it works. How long after the PUT_MEDIA will the fragment be available at GET_MEDIA_FOR_FRAGMENT_LIST? I did not found in the docs.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**SDK version number**
Example: v2.631.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @igormq, thank-you for reaching out to us with your issue, I am not sure if I understand the problem here, you mentioned you often get the error, can you please share the error stack?

Can you provide me with the version of the SDK, printing the output of AWS.VERSION where 
`AWS = require('aws-sdk');`

Can you also make sure you are using the latest version of the SDK with lambda as per the instructions found [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Can you please provide an example of the code snippet to reproduce the error as well?

**Comment by ajredniwja** [comment]
Closing this issue for lack of response, please reach out if you have questions.
