### ISSUE TITLE
Feature: Configure Services' Endpoint URLs via Environment Variables

### ISSUE THREAD

**Issue by mikicho** [aws/aws-sdk-js#3236]
**Is your feature request related to a problem? Please describe.**
I've been looking at the documentation about environment variables and see that you are able to configure credentials, regions, and profiles using environment variables, but I do not see a way to configure the endpoint URL option to point to our internal proxy.

**Describe the solution you'd like**
My suggestion is to configure the endpoint URL if either the AWS_<REGION>_<SERVICE>_ENDPOINT or AWS_<SERVICE>_ENDPOINT (in that order of priority) environment variables are available.

**Describe alternatives you've considered**
Use environment variable in code:
```
  new AWS.Lambda({ endpoint: process.env.AWS_URL })
```

**Additional context**
I need it for localstack :)

**Comment by codyhazelwood** [comment]
+1

This would be very helpful for pointing at MinIO on our local dev machines (so we can still dev on an airplane, bad connection, etc), but then easily default back to S3 in production.

If implemented, it would be helpful to be per-service (like `AWS_S3_ENDPOINT`).  For example - we might want Lambda to point at local SAM, but S3 to point at local MinIO.

There's an easy work around here, but it would still be nice to have.

**Comment by kellertk** [comment]
Thank you for posting your feedback here, and our apologies that we’ve been thinking this over for a long time without much forward motion. There are similar requests to implement this feature in a few of the AWS SDKs and the AWS CLI, so in order to coordinate those teams - and hopefully make the discussions a little easier to follow - we’ve created a new issue in aws/aws-sdk here: https://github.com/aws/aws-sdk/issues/229

**Comment by kellertk** [comment]
Please see https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html
