### ISSUE TITLE
elbv2 registerTargets not working

### ISSUE THREAD

**Issue by federicofrade** [aws/aws-sdk-js#3257]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to register a target on an existing target group using as target a running ec2 instance but despite it don't throw any error it never appear even as pending.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.15.0

**SDK version number**
2.678.0

**To Reproduce (observed behavior)**
```javascript
const elbv2 = new AWS.ELBv2();
const registerTargetParams: RegisterTargetsInput = {
  TargetGroupArn: 'Pre-created-target-group-arn',
  Targets: [
    {
      Id: 'Pre-created-instance-with-running-status',
    }
  ],
};
await elbv2.registerTargets(registerTargetParams);
```

**Expected behavior**
Target is visible from aws console frontend as initial (or even healthy or unhealthy, but to appear)

**Additional context**
I try with version 2.610 before and compared parametrization with http request from frontend with both new and old frontend. I also use this browser extension, that show all the actions from console and how to make them with different sdks:
chrome://extensions/?id=ganlhgooidfbijjidcpkeaohjnkeicba
Then i use the same parametrization the extension shows but with no lucky.

**Comment by philipwigg** [comment]
Take a look at the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELBv2.html#registerTargets-property) for `AWS.registerTargets`.

"If a callback is not supplied, you must call AWS.Request.send() on the returned request object to initiate the request."

You're not supplying a callback so the code is probably returning an `AWS.Request` object without actually sending it. From the code example you gave, you're not catching any errors either so it might be that there's an error instead. Something like this would let us find out:-

```
elbv2.registerTargets(registerTargetParams, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else console.log(data)})
```
If you really need to use `await` instead of a callback then you need `registerTargets` to return a promise. That means [you need to chain](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html) ```.promise()``` to the end of your method call so it would look something like this instead.

```
  try {
    result = await elbv2.registerTargets(registerTargetParams).promise()
    console.log(result)
  } catch (error) {
    console.log(error)
  }
```

Hope that helps!
