### ISSUE TITLE
SharedIniFileCredentials doesntwith profile/source profile for mfa

### ISSUE THREAD

**Issue by AndreasEK** [aws/aws-sdk-js#3317]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I need to include `role_arn`, `source_profile` and `mfa_serial` in ~/.aws/credentials in order to get mfa to work from within the SDK, despite the [documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html) tells that these settings should only exist in ~/.aws/config and not in the credentials. Maybe some tutorial / better documentation about how to use MFA in conjuction with the AWS SDK is all that is needed. 

This is a follow up of #2887.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
❯ node -v
v12.9.0

**SDK version number**
aws-sdk@2.698.0

**To Reproduce (observed behavior)**
This code should use the profile `admin` and ask the user for the MFA code from tokenCodeFn, but the function is never invoked. 

### JS
```
const awsConfigPromise = new Promise((resolve, reject) => {
  tokenCodeFn = (serial, cb) => {
    this.tokenBlock = true;
    const resp = inquirer
      .prompt({
        name: 'token',
        type: 'input',
        default: '',
        message: `MFA token for ${serial}:`,
      })
      .then(r => {
        cb(null, r.token);
        resolve();
      })
      .catch(e => {
        cb(e);
        reject();
      });
  };
  const awsConfigWithCredentials = {
    ...awsConfig,
    credentials: new AWS.SharedIniFileCredentials({
      tokenCodeFn,
      profile: 'admin',
    }),
  };

  AWS.config.update(awsConfigWithCredentials);
});
```
### ~/.aws/config
```
[profile andreas]
region = eu-central-1
output = json

[profile admin]
region = eu-central-1
role_arn= arn:aws:iam::xxx:role/admin
role_session_name = Andreas_Ebbert_Karroum
source_profile = andreas
mfa_serial = arn:aws:iam::xxx:mfa/andreas
```
### ~/.aws/credentials
```
[andreas]
aws_access_key_id = …
aws_secret_access_key = …

[admin]
aws_access_key_id = …
aws_secret_access_key = …
#role_arn = arn:aws:iam::xxx:role/admin
#source_profile = andreas
#mfa_serial = arn:aws:iam::xxx:mfa/andreas
```

**Expected behavior**
To my understanding the last three lines in `~/.aws/credentials` should not be necessary, but the token function will not be called, if they are not present.

**Comment by ajredniwja** [comment]
Hey @AndreasEK Thank-you for sharing this, I can reach out to the docs team to request additional information with the docs.

This is not mentioned in https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-mfa_serial.html

Which would need some change as well. 

Have you tried setting AWS_SDK_LOAD_CONFIG=1 ?

**Comment by jvaldesmartini** [comment]
> Have you tried setting AWS_SDK_LOAD_CONFIG=1 ?

Did that too, nothing. 

AWS.SharedIniFileCredentials does not work with any profile based on a source

`const credentials = new AWS.SharedIniFileCredentials({ profile: 'some-profile-with-source' });`

`accessKeyId `is `undefined`, see below SharedIniFileCredentials dump


```json
 {
  expired: false,
  expireTime: null,
  refreshCallbacks: [ [Function (anonymous)] ],
  accessKeyId: undefined,
  sessionToken: undefined,
  filename: undefined,
  profile: 'some-profile-with-source',
  disableAssumeRole: false,
  preferStaticCredentials: false,
  tokenCodeFn: null,
  httpOptions: null,
  roleArn: 'arn:aws:iam::XXXXXXX:role/XXXXXRole'
}
```

**Comment by gabegorelick** [comment]
I also experienced this (using v2.802.0), but setting `AWS_SDK_LOAD_CONFIG=1` fixed it.

Some relevant code for anyone else that's trying to understand the JS SDK's behavior here:

`SharedIniFileCredentials` loads profiles here: https://github.com/aws/aws-sdk-js/blob/332573f1882799c5dfea3ab34d871a515d60079a/lib/credentials/shared_ini_file_credentials.js#L98

Most of the time, that will end up calling this: https://github.com/aws/aws-sdk-js/blob/332573f1882799c5dfea3ab34d871a515d60079a/lib/util.js#L971-L974

`loadFrom` takes an option `isConfig` that indicates whether to read from config file or credentials file. It defaults to the credentials file, since `isConfig` is undefined:

https://github.com/aws/aws-sdk-js/blob/332573f1882799c5dfea3ab34d871a515d60079a/lib/shared-ini/ini-loader.js#L38-L60

To @ajredniwja's point, if you set `AWS_SDK_LOAD_CONFIG`, `isConfig: true` should be set: https://github.com/aws/aws-sdk-js/blob/332573f1882799c5dfea3ab34d871a515d60079a/lib/util.js#L963-L968



This behavior does seem to be documented in https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-configured-credential-process.html:

> You can source credentials by using a method that isn't built into the SDK. To do this, specify a credential process in the shared AWS conﬁg file or the shared credentials file. If the AWS_SDK_LOAD_CONFIG environment variable is set to a truthy value, the SDK will prefer the process specified in the config file over the process specified in the credentials file (if any).
