### ISSUE TITLE
s3.getObject() does not throw any error. Causes fatal exit in Lambda.

### ISSUE THREAD

**Issue by PierrickI3** [aws/aws-sdk-js#3367]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
`await s3.getObject(params).promise()` does not throw error

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**SDK version number**
2.718.0

**To Reproduce (observed behavior)**

This is the function that calls `s3.getObject()`:

```
async function getObjectFromBucket(_bucket, _path, _body) {
  logger.info(`getObjectFromBucket(). Bucket: ${_bucket}, path: ${_path}`);
  try {
    const params = {
      Bucket: _bucket,
      Key: _path,
    };
    logger.info('get object');
    const data = await s3.getObject(params).promise();
    logger.info('get object returned');
    return data.Body.toString();
  } catch (error) {
    logger.error(error);
    throw error;
  }
}
```

This is called using (in a try/catch block):

```
logger.info('Getting data from S3: ' + dataFilePath);
let conversationsFileData = await getObjectFromBucket(customerInsightsWorkerResultsBucket, dataFilePath);
logger.info('conversations file data getObjectFromBucket returned');
```

The logs in CloudWatch show this:

```
2020-07-23 14:36:11: INFO: Process all data with interval from worker: 2020-07-21T22:00:00Z/2020-07-22T21:59:59Z, where startDate is 2020-07-21T22:00:00.000Z and endDate is 2020-07-22T21:59:59.000Z
2020-07-23 14:36:11: INFO: Getting data from S3: 99acba40-ccf1-11ea-8c43-c1794d6e279a/9c10e900-ccf1-11ea-94d1-79617617f2c7.json
2020-07-23 14:36:11: INFO: getObjectFromBucket(). Bucket: qa-customerinsights-workers-results, path: 99acba40-ccf1-11ea-8c43-c1794d6e279a/9c10e900-ccf1-11ea-94d1-79617617f2c7.json
2020-07-23 14:36:11: INFO: get object
END RequestId: ca0c3298-46d5-499a-af49-d55d92b534b1
REPORT RequestId: ca0c3298-46d5-499a-af49-d55d92b534b1  Duration: 48.04 ms      Billed Duration: 100 ms Memory Size: 1024 MB    Max Memory Used: 123 MB
XRAY TraceId: 1-5f19a05b-08cd11104173d32ea5bc24ca       SegmentId: 3eeb8b5f170bc0d5     Sampled: true
```

I have verified that the file exists and I can use it with my own account

**Expected behavior**
`s3.getObject()` should download the file or throw an error if there is an issue.

**Additional context**
S3 bucket is set to allow all principals with all permissions (`s3:*`)

**Comment by PierrickI3** [comment]
Can this be due to a permission issue? I was hoping to have at least some error.

**Comment by ajredniwja** [comment]
Hey @PierrickI3 Thank-you for reaching out to us with your issue. 

I am not able to reproduce this and I don't believe this is a permissions issue. 

Have you followed [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies)?

**Comment by PierrickI3** [comment]
Thanks @ajredniwja. We use the serverless framework to upload our functions.

Since we could not fix it and this is a long running process, we decided to move to ECR so I can no longer troubleshoot this. Closing.

**Comment by JonasMS** [comment]
I'm experiencing the same symptoms.

Uploaded a container image to ECR, deploying a Lambda fxn off of that.

**Code below is silently failing:**
```
exports.fetchMessage = function (data) {
  data.log({
    level: "info",
    message:
      "Fetching email at s3://" +
      data.config.emailBucket +
      "/" +
      data.config.emailKeyPrefix +
      data.email.messageId,
  });

  return new Promise(function (resolve, reject) {
    // Load the raw email from S3
    data.s3.getObject(
      {
        Bucket: data.config.emailBucket,
        Key: data.config.emailKeyPrefix + data.email.messageId,
      },
      function (err, result) {
        if (err) {
          data.log({
            level: "error",
            message: "getObject() returned error:",
            error: err,
            stack: err.stack,
          });
          return reject(
            new Error("Error: Failed to load message body from S3.")
          );
        }

        data.log({
          level: "info",
          message: "Email successfully retrieved.",
        });

        data.emailData = result.Body.toString();
        return resolve(data);
      }
    );
  });
};
```

**Logs:**
2023-10-17T05:40:10.118Z	538e882a-3589-4bd0-999e-f8e49aff06f5	INFO	{
  level: 'info',
  message: 'Fetching email at s3://moondip.xyz.mailbox/5n32kdhd3kf32n6fed387s9s4b1n9hpa6eeguc81'
}
END RequestId: 538e882a-3589-4bd0-999e-f8e49aff06f5
REPORT RequestId: 538e882a-3589-4bd0-999e-f8e49aff06f5	Duration: 303.94 ms	Billed Duration: 1128 ms	Memory Size: 256 MB	Max Memory Used: 97 MB	Init Duration: 823.16 ms	


1. Code runs fine locally
2. Running the image locally also fails
  - emits this log: Starting runtime without AWS_SESSION_TOKEN , Expected?: false
  - emits incomplete stack trace that's not logged in CloudWatch: 
<img width="753" alt="image" src="https://github.com/aws/aws-sdk-js/assets/8249197/5cd317ac-b479-4c48-8e54-56dbf602fc72">
3. This snippet of code is working in another Lambda fxn which is hosted via a .zip file as opposed to an image (I just pasted code into the code editor).

I tried uploading this failing Lambda fxn via .zip but this caused one of the dependencies to fail -- I expect because it was built on a diff architecture.

Do you guys have clues on what may be causing this or thoughts on how I can get better reporting on what's going on?
