### ISSUE TITLE
How to access an S3 bucket from another account using aws-sdk for node.js?

### ISSUE THREAD

**Issue by SuvabBaral** [aws/aws-sdk-js#3409]
It seems we can allow access to an S3 bucket to a user in another account. But once that is done, how can we access the S3 bucket belonging to a different account using this 'aws-sdk' from a node.js program?

`const AWS = require('aws-sdk');
const s3 =  AWS.S3();`

This only has access to the S3 bucket in the same account. If we are to access an S3 bucket belonging to a different account, how can we do it?
Do we add parameters to the 'S3()' method? If Yes, what are the parameters that we must add?

**Comment by philipwigg** [comment]
Can you give more detail about what you're trying to do?

If you're trying to list all the buckets you have access to in another account then [that will not work](https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-cross-account-access/). You can only list buckets in your own account. That's true even if you have access to buckets in a different account.

You should be able to get and put objects, etc. using specific buckets in different accounts though by just using the bucket name as you would normally because bucket names are globally unique.

Hope that helps.
