### ISSUE TITLE
IncompleteBody Exception

### ISSUE THREAD

**Issue by ollieSayer** [aws/aws-sdk-js#3424]
Some of our users are experiencing IncompleteBody exceptions when uploading through our application to an S3 bucket via the JS SDK (aws-sdk-2.574.0). We are using the upload() method with 10mb partSize and a queue of 10. This exception does not affect all our users and does seem to be a select few at the moment.

Looking at the changelogs for 2.683.0 I can see "S3: throw an exception when incomplete body is returned from CopyObject, UploadPartCopy, and CompleteMultipartUpload" would this also affect upload()? And is this a known problem and if so under what circumstances is it known to occur?

**Comment by ajredniwja** [comment]
@ollieSayer Thanks for reaching out to us with your issue. Apologies for a late reply, https://github.com/aws/aws-sdk-js/pull/3259 suggests it happens for those 3 operations and moreover when S3 returns 200 status code with empty or incomplete body. Which would mean it can affect the `upload`. That will be because of CompleteMultipartUpload being used in a private API from the SDK. 

Depending on your application you can check for empty or incomplete body with status code `200`. 

Let me know if you have any other questions.
