### ISSUE TITLE
disableAssumeRole should be default false

### ISSUE THREAD

**Issue by c19** [aws/aws-sdk-js#3448]
https://github.com/aws/aws-sdk-js/blob/f1c689ffbca0d21d7bd359d5d4a5f1bd2b498a8b/lib/node_loader.js#L79

This is causing assume role fails when refreshing. meanwhile same config and tokens aws cli works fine.

**Comment by ajredniwja** [comment]
Hey @c19 Many of the customers currently rely on SDK credential resolution to be synchronous thats because we would not expect them to make asynchronous assume role calls. 

The workaround would be to use the `SharedIniFileCredentials ` directly. 

Reference: https://github.com/aws/aws-sdk-js/pull/926#discussion_r58608047

Closing this issue now, please feel free to reach out if you have any other questions or comments.
