### ISSUE TITLE
Missing Typescript Definition for HttpClient

### ISSUE THREAD

**Issue by rabbitXIII** [aws/aws-sdk-js#3450]
There are missing typescript definitions that conflict with official documentation when using Typescript.  This issue has been brought up multiple times in the past without response.

- AWS.NodeHttpClient
- AWS.Signers
- AWS.HttpRequest
- AWS.HttpClient

In previous threads ( [#1729](https://github.com/aws/aws-sdk-js/issues/1729), #1278 ), users were informed these were implementation details, and should not be used, however they are used in official aws documentation (see [#1729](https://github.com/aws/aws-sdk-js/issues/1729). From the docs: [Signing Requests to Elasticsearch](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node)).
```
...
 var client = new AWS.HttpClient();
  client.handleRequest(request, null, function(response) {
...
```

Has there been any change here, or a different recommendation?

**Comment by reddy-s** [comment]
Facing the same issue. It would be good to have these type definitions added

**Comment by rabbitXIII** [comment]
Hello, it has been a month since this issue has been opened, and over four years since the original issue was reported.  

Regardless of the fix ETA, is there any response SLA from AWS for these issues?  
From the README: "There are limited resources available for handling issues and by keeping the list of open issues lean we can respond in a **timely manner**."

**Comment by ajredniwja** [comment]
Hey @rabbitXIII @reddy-s, apologies for the late reply, this issue should have been fixed in V3 of the SDK, can you give it a try. 

The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available. For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/) or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

**Comment by keyboardDrummer** [comment]
I seem to run into this in V3.

**Comment by skyref69** [comment]
It seems there is the same problem with V3.
