### ISSUE TITLE
Removal of endpoints without a major release?

### ISSUE THREAD

**Issue by mattBrzezinski** [aws/aws-sdk-js#3526]
Hi,

I'm the owner of [AWS.jl](https://github.com/JuliaCloud/AWS.jl) which uses this repository to create an interface with AWS in the [Julia](https://julialang.org/) programming language.

I noticed that in [v2.787.0](https://github.com/aws/aws-sdk-js/commit/af5e87da6929cd49e8f875f4f30c8ffbaddc6ae6#diff-0db823a0509ab9e0d93512aae50618b4c2ae30c3578b712b2bded7e9bfb25db5) the `CreatePresignedPortalUrl` endpoint for IoT Sitewise was removed, but no major release was made? I'm not sure if this was intended, but it seems to break backwards compatibility.

**Comment by ajredniwja** [comment]
Hey @mattBrzezinski thanks for opening this issue, the code that code that plays a role here is actually generated code from service team (well, in a way), this feature was implemented across all the SDKs as the service is supported by all the SDKs. 
It can be potentially a breaking change, I have reached out to the team (IoT Sitewise) will update here once I have an update.

**Comment by ajredniwja** [comment]
I was able to confirm that none of the corresponding features of the API were released yet and did not anticipate it to be beneficial. So I believe it should not be a breaking change since the functionality was not launched. 

Will be closing this issue now, please reach out of you have any other questions.
