### ISSUE TITLE
Allow installation of SDK _specific_ to a service

### ISSUE THREAD

**Issue by chainhead** [aws/aws-sdk-js#3569]
**Problem**
Allow installation of SDK _specific_ to a service than the _whole_ SDK.
**Solution**
Instead of `const AWS = require('aws-sdk')`, provide an option as shown below.

```js
const aws-sdk-core = require('aws-sdk-core'); // Common utilities
const aws-sdk-rds = require('aws-sdk-rds');  // Only RDS specific CLI
const aws-sdk-sns = require('aws-sdk-sns); // Only SNS specific CLI
```

**Describe alternatives you've considered**
Can't think of.

**Additional context**
An `npm i` inside a `Dockerfile` will install the _entire_ SDK in the current packaging of the SDK. Whereas, my project maybe limited to a handful of services. A limited SDK will reduce the container image size due to smaller `node_modules_ folder thereby, increasing pod density.

**Comment by ajredniwja** [comment]
Hey @chainhead thanks for opening this issue: 

In V2 you can do something like: 

```
const DynamoDB = require("aws-sdk/clients/dynamodb");
const client = new DynamoDB({ region: "us-west-2" });
const request = client.putItem({
  TableName: "FakeName",
  Item: {
    Foo: { S: "Foo" },
  },
});
request.send((err, data) => {
  console.log(err);
});
```

It makes use of the specific client which partially solves the problem.

This issue is completely addressed in [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3)

You can install and use specific clients and commands. You can find more about it [here](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/). 

Closing this issue now, please reach out if you have any other questions.

**Comment by chainhead** [comment]
But, the `npm install` will still pull the entire SDK, right? I was hoping we can pull in _only_ say, `aws-sdk-dynamodb`, etc.

**Comment by ajredniwja** [comment]
With V3 you can do some thing like `npm i @aws-sdk/client-dynamodb`

You can check clients at https://www.npmjs.com/package/@aws-sdk/client-dynamodb
