### ISSUE TITLE
API endpoint to fetch all the available regions for API Gateway

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3625]
Confirm by changing [ ] to [x] below:
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)

**Describe the question**

Do we have any **API endpoint to fetch all the available regions** for a particular service like [API Gateway](https://aws.amazon.com/api-gateway/)?

**PS:** Please refer #3623 for more info.

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo, unfortunately, the functionality is not available, I have created an internal ticket for the API gateway team, can update the issue once they implement on it or I hear otherwise from them. 

This might not help but here is a link to listed supported regions for the service:
https://docs.aws.amazon.com/general/latest/gr/apigateway.html

Will be tracked in: https://github.com/aws/aws-sdk-js/issues/3623

So closing this issue.
