### ISSUE TITLE
Incorrect Typescript type for DynamoDB StringSetAttributeValue

### ISSUE THREAD

**Issue by Nevon** [aws/aws-sdk-js#3627]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The Typescript type definition for a StringSetAttributeValue in a DynamoDB response is `string[]`:

https://github.com/aws/aws-sdk-js/blob/140740509d70c45099daf1b1c6c34ab6633b4a09/lib/dynamodb/document_client.d.ts#L2619-L2620

But in reality, it's the [DynamoDBSet type](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/set.js).  

**Is the issue in the browser/Node.js?**
Browser & Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, but it shouldn't matter.

**Details of the browser/Node.js version**
v14.15.1

**SDK version number**
2.580.0

**To Reproduce (observed behavior)**

Just do a get on an item with a StringSet. For example:

```ts
const db = new aws.DynamoDB.DocumentClient();
const params: aws.DynamoDB.DocumentClient.GetItemInput = {
    Key: {
        account_id,
    },
    TableName
};
const result = await db.get(params).promise();
console.log(result?.Item)

// output
{
  approved_usage: Set {
    wrapperName: 'Set',
    values: [ 'performance', 'staging' ],
    type: 'String'
  },
  account_id: '123456789',
}
```

**Expected behavior**

I would expect that the `StringSetAttributeValue` would be something like a `DynamoDBSet<string>`, not a `string[]`. I assume the other set types have the same issue.

**Comment by ajredniwja** [comment]
Hey @Nevon thanks for opening this issue, the Typescript definitions were added late to the SDK, while I am not sure when this will be fixed in this SDK, The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available.
For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/)
or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

The V3 is written in TypeScript to provide type safety, while `documentClient` is not implemented in V3 because of the issues mentioned [here](https://github.com/aws/aws-sdk-js-v3/issues/1223), the [`getItem`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/getitemcommand.html) should work just the same which should solve the problem. 

Please let us know you feel about using V3 for your application.

**Comment by Nevon** [comment]
> The V3 is written in TypeScript to provide type safety, while documentClient is not implemented in V3 because of the issues mentioned here, the getItem should work just the same which should solve the problem.

This is true, but migrating from aws-sdk v2 to v3 is unfortunately not as simple as a single method call for non-trivial systems. Eventually we will of course migrate over, but seeing as how v2 is still supported and even baked into the NodeJS lambda runtimes by default, it doesn't seem like too much to ask that the Typescript types be updated to be correct.

**Comment by ajredniwja** [comment]
@Nevon apologies for late reply here V3 was able to have the full implementation of all the DynamoDb functions, with that being said, I believe you are right but since its already fixed in V3 of the SDK it takes less of a priority. We welcome PRs in case you wanna open one but I am not sure about the priority for this mostly because V3 was intended to solve this problem.

**Comment by Nevon** [comment]
This is still an issue
