### ISSUE TITLE
HttpRequest headers.Content-Length has incorrect type in Typescript

### ISSUE THREAD

**Issue by magdalenalipka** [aws/aws-sdk-js#3638]
**Describe the bug**
HttpRequest class (lib/http_request.d.ts) is typed to contain headers: 
```
headers: {
        [key: string]: string;
    }
```
but `Content-Length` header should be number type.

**Expected behavior**
Type of headers should be something like:
```
headers: {
    [key: string]: string;
  } & { "Content-Length": number };
```

**Comment by magdalenalipka** [comment]
`Max-Forwards` also should be number type.

**Comment by ajredniwja** [comment]
hey @magdalenalipka thanks for opening this issue, originally types were not described in the V2 of the SDK. 

This problem has been fixed in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3)

Also worth a read https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/
