### ISSUE TITLE
Issue with aws sns sms service. 

### ISSUE THREAD

**Issue by dilip-987** [aws/aws-sdk-js#3711]
#  checked cloudwatch logs for the issue "providerResponse": "Blocked as spam by phone carrier", found what could be better solution for the above questions

**Comment by ajredniwja** [comment]
Hi @dilip-987, I'd have to close this issue, since it does not have sufficient information for me to triage this. Can you please follow the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=guidance%2C+needs-triage&template=---questions---help.md&title=) for me to help you better. Thank you
