### ISSUE TITLE
DynamoDB DocumentClient typescript definitions seem to be incorrect

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js#3719]
Same issue as here https://github.com/aws/aws-sdk-js/issues/2367

It was never resolved, and instead locked automatically.

This is still an issue when using DocumentClient, that the TS definition expect an AttributeValue, ather than a simple stringfor example.

**Comment by ajredniwja** [comment]
@paul-uz thanks for opening this issue, the typings were not added in the V2 of the SDK from the start but added later thats why there are some inconsistencies. For that reasons it was fixed in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3). Can you please check it out? If that doesnt fit your use case please let us know.
