### ISSUE TITLE
Cloudwatchlogs not behaving as documentation states

### ISSUE THREAD

**Issue by calixtoyg** [aws/aws-sdk-js#3768]
The [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#filterLogEvents-property) states that for this function "filterLogEvents" if you don't state the startTime you should get the logs from the most recent events but I am getting them from oldest to new which is the other way around

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Locally

**Details of the browser/Node.js version**
v16.0.0

**SDK version number**
2.602.0

**Expected behavior**
Should get the logs from most recent to least recent.

**Comment by ajredniwja** [comment]
Hey @calixtoyg I am a little confused as well, let me check with the cloudWatch team how it should be.

**Comment by ajredniwja** [comment]
Can you also share the code that you are using?

**Comment by calixtoyg** [comment]
`    it('should have logs from most recent to least recent', async (done) => {
        const cloudwatchlogs = new AWS.CloudWatchLogs();
        const params = {
            logGroupName: LOG_GROUP_NAME
        };
        const logs = await cloudwatchlogs.filterLogEvents(params).promise();
        console.log(logs)
    });
   `

This should return from most recent to least recent that is what the documentation says
![image](https://user-images.githubusercontent.com/38393309/118778776-b7962480-b88a-11eb-9818-67cafaf9aec2.png)

**Comment by calixtoyg** [comment]
Further more and this probably needs a separate issue if you don't specify the "**logGroupNames**" and only **startTime** it is not able to find the logs from that startTime onward even though they are there.

**Comment by ajredniwja** [comment]
I have contacted the Cloudwatch team for the same. I'll get back to you once I hear back from them.

**Comment by ajredniwja** [comment]
Word from the team that: There was an issue in FilterLogEvents in IAD/us-east-1 which could've caused recent events to not have been returned when --start-time and --end-time are not provided, but it has now been resolved. Please let us know if you still see the issue. 

Also, please provide the following information where the issue was found if it still exists and you need us to investigate further 

* AWS Account Number
* Region(s)
* LogGroups and LogStreams
* GetLogEvents request/response
* Approx time (in UTC) when you made the request and saw missing logs

Please note that GetLogEvents/FilterLogEvents are paginated APIs. To get all the events, you will have to make subsequent calls with nextForwardToken or nextBackwardToken that you receive in the response.

**Comment by calixtoyg** [comment]
it has been really long I don't have the exact request that I made, the region was eu-west-1 and I can't really provide the account number here, is not my account. the time was around when I made the issue in github.
