### ISSUE TITLE
s3.uploadPart not returning eTag (or any other data)

### ISSUE THREAD

**Issue by 5inline** [aws/aws-sdk-js#384]
When using the s3.uploadPart() function, the return data is empty. There is no error response, but also no data. Currently using aws-sdk-js#2.0.19. It was working previously, but no longer. Is there a way to calculate the ETag without the response? The s3.completeMultipartUpload() function fails without the eTags.

**Comment by AReallyGoodName** [comment]
OK I have a problem with how this all works. I had the same issue. BUT... I was still getting the ETag back in the header from the remote side if i read the header manually without the Amazon SDK. 

Incorrect CORS configuration merely seems to change what the SDK sees. If you do a manual request without the Amazon SDKs uploadPart function you can see the ETag regardless of that particular setting.

Which raises the question. Why require this ExposeHeader option in CORS? It doesn't change what gets sent to the user at all. It just changes what the SDK library will output.

**Comment by lsegal** [comment]
@AReallyGoodName 

> Which raises the question. Why require this ExposeHeader option in CORS?

Amazon S3 is exposing the direct CORS configuration parameters as described by the [CORS specification](http://www.w3.org/TR/cors/), in this case, the `Access-Control-Expose-Headers` option. In other words, it is required because it is part of the CORS specification, and is required there. The CORS spec dictates that any response header not listed in the above "expose headers" rule should not be programmatically accessible via JavaScript. S3 is simply responding to the browser's OPTIONS request with the exact configuration you've set on your bucket, which allows you full customizability of your CORS setup.

Now, there is something to be said about whether this customizability should be necessary, or if at the very least S3 should be providing some useful defaults. Unfortunately, any update to the way CORS configurations work would have to be made in the S3 service itself, not the SDK, so I would recommend opening a thread on the [Amazon S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) and making a feature request there if you think this would be a useful addition to the service.

Hope that helps!
