### ISSUE TITLE
How to check if an AWS IAM Role has an `ExternalID` configured or not?

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3870]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Is there a way to check if an AWS IAM role has an `ExternalId` restriction while making the [AssumeRole](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRole-property) API call? 

- It doesn't throw an error when the `ExternalId` is passed in the case of an IAM role that doesn't have an external ID configured.
- It throws an error when an invalid `ExternalId` is passed for an IAM role with external ID restriction.

Please refer #3869

**Comment by aldegoeij** [comment]
As experienced AWS dude I can tell you this is extremely unlikely to ever be supported as it would mean you can discover TrustPolicy configs.

The `Externald` field is frankly nothing more than a normal conditional field, with some magic on the CLI / SDK side to allow you to easily send it in a AssumeRole request. Hence its ignored if you send something, because the specific condition is missing on the TrustPolicy. If you have `sts:TagSession` on your TrustPolicy, you can send any tag you like...

You will only ever get back a success or failure of the IAM API call, for reasons stated above.
