### ISSUE TITLE
Add environment variable to override endpoint_url

### ISSUE THREAD

**Issue by pedrocaseiro** [aws/aws-sdk-js#3999]
- [x] This is a feature with version 2.x of the SDK

With [boto3](https://github.com/boto/boto3/pull/2746/files) it's possible to specify an `AWS_ENDPOINT_URL` to override the default one. Wondering if it would be possible to have the same in aws-sdk-js.

**Comment by kellertk** [comment]
Thank you for posting your feedback here, and our apologies that we’ve been thinking this over for a long time without much forward motion. There are similar requests to implement this feature in a few of the AWS SDKs and the AWS CLI, so in order to coordinate those teams - and hopefully make the discussions a little easier to follow - we’ve created a new issue in aws/aws-sdk here: https://github.com/aws/aws-sdk/issues/229

**Comment by tim-finnigan** [comment]
I'm going to resolve this as a duplicate of https://github.com/aws/aws-sdk-js/issues/3236. As mentioned above there is also an issue in the aws-sdk repository for tracking this feature request at a cross-sdk level.
