### ISSUE TITLE
Typings is broken for client-route-53

### ISSUE THREAD

**Issue by xonuzofa** [aws/aws-sdk-js#4009]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ ] This is an issue with version 2.x of the SDK

**Describe the bug**
node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts(97,5): [39merror TS1005: '}' expected.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v3.46.0

**To Reproduce (observed behavior)**
Download via NPM - "@aws-sdk/client-route-53": "3.46.0"

**Expected behavior**
No issues with typings

**Comment by nlang** [comment]
This issue still exists in version 3.51.0
The typings file `Route53.d.ts` is truncated at line 97 
![image](https://user-images.githubusercontent.com/1759992/154082831-28ad818a-7cb1-4b07-b78b-f6685bb11477.png)

The typings for `Route53Client` are odd as well, the Route53Client has no `send()` method defined in is therefor pretty useless at the moment.

**Comment by ajredniwja** [comment]
@xonuzofa thanks for opening this issue, originally typings were not added to V2 at all and some of it was added later. The problem was solved in [V3](https://github.com/aws/aws-sdk-js-v3) of the SDK which provides first class typescript support.

**Comment by zshzbh** [comment]
Hey @xonuzofa , 

As we are approaching the [maintenance mode ](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/)for AWS JS V2, AWS will limit SDK releases to address critical bug fixes and security issues only.  As the problem was solved in [V3](https://github.com/aws/aws-sdk-js-v3) of the SDK, we recommend that you update to [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html). AWS SDK for JavaScript v3 provides improved features, enhanced performance, and continued support from AWS. To ease your migration, we provide an [automated migration tool](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html#using-codemod).


Thanks! 
Maggie
