### ISSUE TITLE
Documentation shows this to now be optional?

### ISSUE THREAD

**Issue by tnoskilz** [aws/aws-sdk-js#4053]
in s3control CreateJobRequest, the ClientRequestToken is marked as required.  The [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3Control.html) is conflicting, marking it both as Required in the example and then stating this:
"If a token is not provided, the SDK will use a version 4 UUID."
Others have pointed to this no longer being required for services such as chime due to the above.

Can the [CreateJobRequest type definition](https://github.com/aws/aws-sdk-js/blob/d05708ee0b52974be66b185410fde1900ee9a1c0/clients/s3control.d.ts#L764) be updated to reflect this now being optional?

**Comment by ajredniwja** [comment]
Hi there, the docs reflect `ClientRequestToken` required because it is required by the [CreateJob API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_CreateJob.html#API_control_CreateJob_RequestSyntax).
I think its an add on that the SDK generates a token when its needed, instead of breaking the request. 

https://github.com/aws/aws-sdk-js/commit/a984c93b9943b241fb6b040003ed562231ef22ad
