### ISSUE TITLE
AWS-Batch listJobs response is partial for jobs in 'RUNNABLE' state and does not include attributes as per the API documentation

### ISSUE THREAD

**Issue by srakshe** [aws/aws-sdk-js#4193]
### Describe the bug

For a job in 'RUNNABLE' state, the API returns only the following attributes.
```
  {
    jobArn: 'STRING_VALUE',
    jobId: 'STRING_VALUE',
    jobName: 'STRING_VALUE',
    createdAt: 'NUMBER_VALUE',
    status: 'RUNNABLE'
  }
  ```

### Expected Behavior

The response expected as per the API specification
https://docs.aws.amazon.com/batch/latest/APIReference/API_JobSummary.html

jobDefinition is missing. It is is applicable to all job states.

### Current Behavior

jobDefinition property is not returned for 'RUNNABLE' jobs as per the API specification

### Reproduction Steps

```
const AWS = require('aws-sdk');

AWS.config.update({accessKeyId:aws_access_key_id,secretAccessKey:aws_secret_access_key,region:aws_region,sessionToken:aws_session_token})

var batch = new AWS.Batch();

var params = {
    jobQueue: "arn:aws:batch:eu-west-2:XXXX:job-queue/XXXX",
    jobStatus:  "RUNNABLE",
    maxResults: 100
};

async function listhandler(err, data) {
    if (err)
    {
        console.log(err, err.stack); // an error occurred
    }
    else{
        console.log(data.jobSummaryList)
    }
}

batch.listJobs(params,listhandler);
```

### SDK version used

2.1203.0

### Environment details (OS name and version, etc.)

Linux

**Comment by ajredniwja** [comment]
Hey @srakshe thanks for opening this issue, I was able to get similar results where all the required fields are returned too. There might be special cases when this is not returned but since the SDK doesn't do any customization with AWS batch responses, I have reached out to the team to have more insight.

**Comment by aBurmeseDev** [comment]
HI there - sorry for the long wait. I was able to confirm that this needs to be addressed by service team AWS Batch and out of SDK control. 

Since there are no pending action items for the SDK team, and we aim to dedicate this repository solely for SDK-related issues, I will proceed with closing this case. Please feel free to reach out directly to the service team via [AWS Support](https://aws.amazon.com/contact-us/) for further updates.
