### ISSUE TITLE
EventBridge - Rule - Parameter ScheduleExpression is not valid

### ISSUE THREAD

**Issue by hanoj-budime** [aws/aws-sdk-js#4212]
### Describe the bug

why this "CRON" Expression is not supported ?

`cron(*/60 * * * ? *)`

Error
![image](https://user-images.githubusercontent.com/53425981/191253103-9b71de20-b0fd-4eac-b3fa-7153e64838b6.png)

### Expected Behavior

Every one hour -> event rule

### Current Behavior

Error

### Reproduction Steps

Create rule with this value

`cron(*/60 * * * ? *)`

### SDK version used

2.1069.0

### Environment details (OS name and version, etc.)

Windows 10

**Comment by ajredniwja** [comment]
Hey @HanojHanu thanks for opening this issue, can you please share the code that you are using to create the rule?

**Comment by HanojHanu** [comment]
```js
const params = {
    Name: /* some thing */,
    Description: /* some thing */,
    State: /* some thing */,
    ScheduleExpression: /* cron expression */,
    Tags: /* some thing ARN */,
  };
const data = await eventBridgeClient.putRule(params).promise();
```

**Comment by HanojHanu** [comment]
Hey @ajredniwja,

Any fix ?

**Comment by aBurmeseDev** [comment]
Hi @hanoj-budime - apologies for the long silence here. I'd like to address this in case you're still blocked by this. 

The cron expression cron(*/60 * * * ? *) is not supported because it contains an invalid value for the minutes field. In cron expressions, the minutes field should be a value between 0 and 59, or a wildcard character (*).

To create a rule that runs every hour, you should use the cron expression cron(0 * ? * * *). This expression means "every hour at minute 0" (at the start of every hour).

Let me know if that makes sense.
Best,
John
