### ISSUE TITLE
No AWS.Signers.V4 in aws-sdk

### ISSUE THREAD

**Issue by wong2** [aws/aws-sdk-js#4214]
### Describe the bug

```
const signer = new AWS.Signers.V4(req, "managedblockchain")
```

Gives `Property 'Signers' does not exist on type 'typeof import`

### Expected Behavior

Should just work.

### Current Behavior

`Property 'Signers' does not exist on type 'typeof import`

### Reproduction Steps

Code above

### Possible Solution

Add missing types.

### SDK version used

2.1221.0

### Environment details (OS name and version, etc.)

Node.js 16

**Comment by ajredniwja** [comment]
Hey @wong2 thanks for opening this issue, V2 was initially written with no types but were added later. This problem is solved in [V3 of the SDK](https://github.com/aws/aws-sdk-js) which has [first-class TypeScript support](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/).

**Comment by wong2** [comment]
Great!
