### ISSUE TITLE
Expose what IoT limit was breached (Throttles)

### ISSUE THREAD

**Issue by icsaba** [aws/aws-sdk-js#4223]
### Describe the feature

Expose the exact IoT quota that was breached when raising `ThrottleException: Rate exceeded`.

### Use Case

Generally, if we get a `ThrottleException: Rate exceeded` we have no clue what iot limit is breached, hence it's so hard to debug, and solve bottlenecks in our applications. 

### Proposed Solution

Exception message should be more descriptive, for example

```
ThrottlingException: Rate exceeded (Requests per second per thing)
   ...
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2.1011.0

### Environment details (OS name and version, etc.)

linux

**Comment by RanVaknin** [comment]
Hi @icsaba ,

Sorry for the late response. The error you are seeing is coming from the service itself, not from the SDK. The SDK just deserializes the raw response as it is sent from the service itself. 

You can try to submit an internal feature request to the service team by requesting support in your AWS console.
Since this is not actionable by the SDK team, I feel confident we can close this.

All the best,
Ran~
