### ISSUE TITLE
Send invite email on user creation through IdentityStore (SSO)

### ISSUE THREAD

**Issue by benmurden** [aws/aws-sdk-js#4226]
### Describe the feature

When creating a user on IAM Identity Center (successor to AWS Single Sign-On) console, the user can be sent an invite email immediately upon creation, with instructions on where to log in and what to do next. It seems when users are created through the SDK, there is no email sent with these instructions. Perhaps I have missed it, but I cannot see a way to make sure this email is sent with the current SDK.

### Use Case

When creating users for IAM Identity Center (successor to AWS Single Sign-On), we always need to tell those users where to sign in and what to do next. It would be good if sending this invite email could be integrated into the SDK and AWS API.

### Proposed Solution

Either one of or both:

- An option in the existing IdentityStore CreateUser interface that sends an invite email upon creation, or;
- An API to send said email to a given IdentityStore user.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v2.1231.0

### Environment details (OS name and version, etc.)

Linux

**Comment by semanur-prenuvo** [comment]
Not clear how to trigger this email but needed for automation of users 👍

**Comment by RanVaknin** [comment]
Hi @benmurden @semanur-prenuvo ,

This sounds like a service side limitation, and not a functionality that the SDK can add.
The SDKs are code generated from the API models of each service. In this case `identitystore` client is generated from [this API ](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference).

Unfortunately I don't see any service operation in that API that allows you to send invite email programatically.

Since this would be a service side feature request, and not actionable by the SDK team, I'm going to close this.

Thank you for your patience,
Ran~

**Comment by benmurden** [comment]
I agree, it really does need to be addressed at the AWS API side of things. Do you have any suggestions about where users could request such changes be made?
