### ISSUE TITLE
Error: unable to get local issuer certificate -- AWS Secrets Manager

### ISSUE THREAD

**Issue by SaitejaChavva** [aws/aws-sdk-js#4233]
### Describe the bug
```
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'secretsmanager.us-east-1.amazonaws.com',
  retryable: true,
  time: 2022-10-13T06:40:29.115Z
}
```

I'm getting above issue, while accessing the AWS Secrets Manager. Below is my code
```js
import { Handler, APIGatewayEvent } from 'aws-lambda'; 
import { globalJsonResponse } from "@claims/schema"; 
import { SecretsManager } from 'aws-sdk'; 

const client = new SecretsManager({ 
    region : process.env.REGION, 
    accessKeyId: process.env.ACCESS_KEY_SM, 
    secretAccessKey: process.env.SECRET_KEY_SM 
}); 

export const handler: Handler = async (event: APIGatewayEvent) => { 
    const functionName = 'SM'; 
    console.log("inside the handler"); 
    const secretName = "ClaimSuperSecret1"; 
    try { 
        const res = await client.getSecretValue({ SecretId: secretName }).promise(); 
        console.log("updateTableRes", res) 
        return globalJsonResponse(200, { status: 200, res, message: 'Secrets reteived successfully' }, functionName); 

    } catch (error) { 
        console.log("err", error); 
        return globalJsonResponse(error.statusCode, { status: error.statusCode, message: error.code }, functionName); 
    } 
};
```

### Expected Behavior

N/A

### Current Behavior

N?A

### Reproduction Steps

N/A

### SDK version used

2.1201.0

### Environment details (OS name and version, etc.)

windows

**Comment by SaitejaChavva** [comment]
Hey, anyone please help me to fix the issue..
Kindly do the needful

**Comment by ajredniwja** [comment]
@SaitejaChavva thanks for opening this issue, the issue seems to be not coming from the SDK. 
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-registering-certs.html

Network connectivity errors can result from issues with your VPC's routing configuration, security group rules, AWS Identity and Access Management (IAM) role permissions, or network address translation (NAT), or from the availability of resources such as IP addresses or network interfaces. Depending on the issue, you might see a specific error or timeout if a request can't reach its destination.

The default lambda ships version 2.1083.0 of the SDK, can you make sure you are using a lambda layer to import latest version of the SDK. 
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by SaitejaChavva** [comment]
@ajredniwja Thanks for the reply

But DynamoDB connection was working fine. Only I'm getting error while accessing Secrets Manager. 

Yes I'm using lambda layer to import latest version of the SDK.

**Comment by aBurmeseDev** [comment]
HI @SaitejaChavva - sorry for the long delay here. 

This type of error typically occurs when the client is unable to verify the SSL/TLS certificate presented by the server. This can happen due to several reasons such as missing root certificates, network configuration issues, or issues with the SSL/TLS implementation.

In the context of AWS Lambda functions, this error can occur due to the lack of root certificates in the Lambda execution environment. By default, AWS Lambda uses the Amazon Trust Services root certificates which may not include the necessary certificates for some AWS services or endpoints.

Since this's unrelated to SDK and no action item for the team, I'm going to close this.
