### ISSUE TITLE
ECMAScript module (ESM) bundle

### ISSUE THREAD

**Issue by Grishpan** [aws/aws-sdk-js#4302]
### Describe the feature

Working with angular, in my typescript file I'm adding:
`import * as AWS from 'aws-sdk';` and `import * as S3 from 'aws-sdk/clients/s3';`
and during build time I'm getting this warning:

`Warning: ... depends on 'aws-sdk'/'aws-sdk/clients/s3'. CommonJS or AMD dependencies can cause optimization bailouts.`

I know that I can add it to `allowedCommonJsDependencies` in `angular.json` to suppress the issue but am still wondering if this dependency can be packaged with ECMAScript for better optimization and overall bundle size.

### Use Case

Better optimization of dependency bundle. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2.1277.0

### Environment details (OS name and version, etc.)

Windows 10 Enterprise

**Comment by RanVaknin** [comment]
Hi @Grishpan,

Maybe I'm misunderstanding you, but what you are proposing already exists in our V3 SDK 

In v3 each service client is modularized. You can npm install each client, and import them independently, significantly reducing the bundle size.

For example, instead of:

```js
import S3 from 'aws-sdk/clients/s3';
```

it would be

```js
import { S3Client } from '@aws-sdk/client-s3';
```

Please check out the [migration guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md). 

Thanks,
Ran
