### ISSUE TITLE
ssm.getParameter crashes with error that has `null` message

### ISSUE THREAD

**Issue by medikoo** [aws/aws-sdk-js#4330]
### Describe the bug

If I attempt to get not existing parameter, SDK crashes with an error that has a `null` message.

### Expected Behavior

The error should have a meaningful message

### Current Behavior

The error message is `null`

### Reproduction Steps

```javascript
const AWS = require("aws-sdk");
const ssm = new SSM();
ssm.getParameter({ Name: "/not/existing" }).promise().catch(error => {
  console.log(error.message); // null
});
```

### SDK version used

2.1304.0

### Environment details (OS name and version, etc.)

macOS 12.6

**Comment by RanVaknin** [comment]
Hi @medikoo,

When you import the entire SDK you need to construct the SSM client from the SDK object:
```js
const AWS = require("aws-sdk");
const ssmClient = new AWS.SSM();
```
_**Or**_, you can import that ssm module on its own:
```js
const SSM = require("aws-sdk/clients/ssm");
const ssm = new SSM();
```

Regarding error handling, we suggest this paradigm:

```js
const SSM = require("aws-sdk/clients/ssm");
const ssm = new SSM({ region: 'us-east-1' });

ssm.getParameter({Name: "/not/existing"}, (err,data)=>{
    if (err) {
        // error handling code
        console.log(err);
    } else {
        // data handling code
        console.log(data);
    }
})
```
output:
```console
-- REDACTED INFORMATION --
...
...
  code: 'ParameterNotFound',
  time: 2023-01-30T19:00:40.323Z,
  requestId: 'REDACTED',
  statusCode: 400,
  retryable: false,
  retryDelay: 38.43549644787767
}
```

**Comment by medikoo** [comment]
@RanVaknin  There's no problem with API usage, I'm reporting that when error is expected, the weird instance (with `null` as message) surfaces

**Comment by RanVaknin** [comment]
Hi @medikoo ,

I see what you are saying, however `message` field here is not guaranteed. That field is serialized based on the response from the SSM service. If the service is not returning an error message in the raw response HTTP body, then the SDK wont have anything to serialize and the `message` field will be null. In this particular case the response is:

```
{"__type":"ParameterNotFound"}
```

I'm not exactly sure why this is a problem since the error name is very self explanatory.
Additionally, we recommend you use the `name` field instead for error handling, as recommended in our [developer guide](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/)

Since this isn't an issue with the SDK, and there is no action we can take here, I feel confident we can close this issue. 
If you are running into any other problems you are welcome to open an additional issue.

Thanks,
Ran~

**Comment by medikoo** [comment]
> I'm not exactly sure why this is a problem since the error name is very self explanatory.

We are working on instrumentation that observes AWS SDK requests, and we treated error message as something guaranteed. 

Also, it's quite surprising to have a JavaScript `Error` instance with `null` as a message. Per JS spec it's always a _string_ (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message) and it's the first time in my coding history that I've approached a utility that produces an error instance with `null` message.

If the intention is to follow good JS practices here, it'll definitely be good to fix that. Also, AWS SDK v3 doesn't share this issue (which is a relief :)
