### ISSUE TITLE
fetching assets uploaded using signed URL but fetched using signed cookies

### ISSUE THREAD

**Issue by kushalarvind** [aws/aws-sdk-js#4337]
### Describe the feature

hi, our s3 bucket was made private recently so to fetch assets we were using signed cookies and to upload we were using signed url. but we tried to fetch asset that is uploaded using signed url the out is of buffer, is there a way to upload such that while fetching we get the normal image in output

### Use Case

i can't convert buffer to base64 since we are calling assets directly in UI, it would be helpfull if you can suggest an alternative way

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

2.0.5

### Environment details (OS name and version, etc.)

windows, 11

**Comment by yenfryherrerafeliz** [comment]
Hi @kushalarvind, thanks for opening this feature request. Could you please elaborate more what your request is?, could you provide some sample data and code that I can use to better understand your feature request and see what we can suggest from a SDK perspective?, because as far as I know, when fetching a file from a signed url, even when this signed URL was generated through the SDK, the implementation for this operation is responsibility of the client, which means is an operation out of the SDK scope.

For example, lets say I have the following signed URL:
```console
https://BUCKET.s3.REGION.amazonaws.com/KEY?....
```
Then, if using JavaScript I would do the following:
```js
const response = await fetch({
    method: 'GET',
    headers: {
    },
    url: 'https://BUCKET.s3.REGION.amazonaws.com/KEY?....'
})
const data = response.data;
// Manipulate the data after this
.....
```

Thanks!
