### ISSUE TITLE
headObject does not return `ObjectLockMode` and `ObjectLockRetainUntilDate`

### ISSUE THREAD

**Issue by votdev** [aws/aws-sdk-js#4362]
### Describe the bug

Calling the [headObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property) function the returned `AWS.S3.Types.HeadObjectOutput` response does not contain the properties `ObjectLockMode` and `ObjectLockRetainUntilDate` even if the headers `x-amz-object-lock-mode` and `x-amz-object-lock-retain-until-date` exists.

### Expected Behavior

I expect that the properties `ObjectLockMode` and `ObjectLockRetainUntilDate` are filled with the data delivered via the `x-amz-object-lock-mode` and `x-amz-object-lock-retain-until-date` headers.

### Current Behavior

The properties `ObjectLockMode` and `ObjectLockRetainUntilDate` are not populated.

![Bildschirmfoto vom 2023-03-07 11-32-23](https://user-images.githubusercontent.com/1897962/223400533-dfa22105-05e8-4b47-8ed7-95ba28bbf74b.png)

![Bildschirmfoto vom 2023-03-07 11-36-05](https://user-images.githubusercontent.com/1897962/223400547-b15dd926-1d8c-4f61-849d-11a87b4f7b1a.png)

### Reproduction Steps

n/a

### SDK version used

2.1329.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by RanVaknin** [comment]
Hi @votdev ,

Since the request is being sent and returned correctly, my guess is that you have a CORS configuration on your bucket that is preventing from the headers from being piped to the response. You need to list the headers you want under "AllowedHeaders". 

Please check out this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html)

Let me know if you need anything else.
Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @votdev ,

I can see that the response you get from the firefox dev tools is showing the correct headers being returned from the service. Initially, I thought this might be a serialization error with the SDK, but when running a similar program from a Node.js environment I can see that the headers are in fact returned and serialized correctly:

```js
const AWS = require('aws-sdk');

const client = new AWS.S3()

const params = {
    Bucket: "foo-bucket",
    Key: "bar.txt",
}

client.headObject(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

Output:
```
{
  AcceptRanges: 'bytes',
  LastModified: 2023-03-14T01:03:44.000Z,
  ContentLength: 3,
  ETag: '"REDACTED"',
  VersionId: 'REDACTED',
  ContentType: 'application/octet-stream',
  ServerSideEncryption: 'AES256',
  Metadata: {},
  ObjectLockMode: 'COMPLIANCE',
  ObjectLockRetainUntilDate: 2023-04-04T18:47:36.000Z
}
```

You are using Angular with RxJS, since I dont have experience with either one, its hard to diagnose. I suggest you first try to run the request from Node locally,  and only then run it from web environment. Perhaps one of those two libraries is the culprit.

Thanks,
Ran~
