### ISSUE TITLE
httpUploadProgress Not Work As Expected

### ISSUE THREAD

**Issue by ehabAbdelMawla** [aws/aws-sdk-js#4363]
### Describe the bug

```
return await s3.upload(params).on('httpUploadProgress',({loaded,total})=>{
       console.log(Math.floor((loaded/total)*100))
}).promise()
```

### Expected Behavior

1
2
3
..
100

### Current Behavior

15
80
100

### Reproduction Steps

-

### SDK version used

2.1318

### Environment details (OS name and version, etc.)

Windows

**Comment by yenfryherrerafeliz** [comment]
Hi @ehabAbdelMawla, thanks for opening this issue. Could you please elaborate more in what the issue is here?, basically the upload progress event will notify you every time a chunk of data is uploaded, and the size for that portion of data uploaded will be equals to the minimum part size, which by default is 5 MB, so that the value for loaded will be 5 MB in each event, except for the last part which size will be whatever is remaining to send in that specific part.

So, could you please also provide a more detailed code snippet where we can see how you initialize the clients and parameters?

Note: Please make sure you redact any sensitive information.

Thanks!
