### ISSUE TITLE
Lambda invoked multiple times even for successful response

### ISSUE THREAD

**Issue by sisir-hellosivi** [aws/aws-sdk-js#4367]
### Describe the bug

- I have a mutation with a Lambda resolver in Appsync that invokes (synchronous) another Lambda (Lets call this LambdaExternal).
- The mutation however is not made to wait for the invoked LambdaExternal to return back the response (Notice no `await` on `lambdaUtil.invokeFunction`) because AppSync mutations' have a 30 sec timeout.
- The LambdaExternal that is invoked runs for at least 1.5 minutes before returning the result. The result of LambdaExternal is sent back to the client using an AppSync subscription. LambdaExternal calls an AppSync mutation called notifyClient which sends the response to the client via subscription.

Code sample:
```js

const AWS = require('aws-sdk');
const lambda = new AWS.Lambda({
    region: 'my-region'
});

const lambdaUtil = {
  invokeFunction: function(name, payload = {}) {
    const params = {
        FunctionName: name,
        Payload: JSON.stringify(payload)
    }

    return new Promise(resolve => {
        lambda.invoke(params, function(err, data) {
          if(err) {
              resolve(err);
          } else {
              resolve(data);
          }
        });
    });
  }
};

//This runs in the AppSync mutation Lambda resolver
const myMutationHandler = async (event) => {
  console.log("myMutationHandler started")
  lambdaUtil.invokeFunction('LambdaExternal',  event.data);
  return {
    status: 'ok',
    data: {
      message: 'Done',
    }
  }
}

```

Library versions:
aws-sdk: 2.1158.0

### Expected Behavior

The AppSync mutation invokes LambdaExternal once and just ends returning status 'ok'. LambdaExternal after finishing, calls the AppSync mutation that is linked with a subscription to send the response back to the client

### Current Behavior

The expected flow works but sometimes after about a 2 minutes or so, LambdaExternal is invoked again automatically. Log wise I cannot the "myMutationHandler started" (from the sample code provided) in AppSync CloudWatch logs but in LambdaExternal's CloudWatch logs I can see that for the same request parameters it was invoked more than once. Which means the mutation didn't run again but LambdaExternal did.

This could possibly be because of AppSync hitting 30 seconds timeout which closes the connection and aws-sdk or Lambda doing a retry because of the lost connection. I've now changed the whole setup to follow a complete async pattern using SQS to solve this problem (still testing) but still curious to know why this could've happened. Will update details of my findings as I debug more.

### Reproduction Steps

I'll try with a smaller sample code and update here.

### SDK version used

aws-sdk 2.1158.0

### Environment details (OS name and version, etc.)

Lambda node 12.x

**Comment by RanVaknin** [comment]
Hi @sisir-hellosivi ,

Thanks for the detailed explanation. Since you ruled out the mutation happening twice, You lambda getting invoked twice sounds like a triggered retry on the invocation level. This [doc](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html) talks about it more in detail. 

I would try to read the logs before the second triggered of lambda and see if there are any errors from an SDK standpoint in order to rule that out (for example a 400, or any transient errors like connection issues that the SDK retries by default) or maybe a runtime error. If you are able to spot one you might want to handle it with an appropriate retry strategy.

Let me know what you are able to find,
Thanks,
Ran~
