### ISSUE TITLE
aws-rekognition(cannot searchFaceByImage with multiple faces image)

### ISSUE THREAD

**Issue by zivserphos** [aws/aws-sdk-js#4383]
### Describe the feature

Hey , Im currently working and using your service of aws sdk rekognition (nodejs).

Im trying to take an existing image from an s3 bucket which contains more than one face and then using your method searchFacesByImage , the problem is that currently the function only supports one face for the checking and not multiple , the result is that when im trying to search face by image with more than one face the most clear face will be checked but the other wont , please if you can provide a feature that will return an array of object that stores the faces that were detected as a key and a face id from the collection as a value.

Thanks in advance , Ziv Serphos

### Use Case

because currently I need to crop each image to faces and than send request for each face , which is also more expensive both in time and money

### Proposed Solution

rekognition.searchMultipleFaceByImage(multipleSearchParams) method 

### Acknowledgements

- [x] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

2.1288.0

### Environment details (OS name and version, etc.)

macos macbook pro 2021  12.0.1 nodejs v16.16.0

**Comment by RanVaknin** [comment]
Hi @zivserphos ,

From what I can see in the [docs](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_SearchFacesByImage.html) `searchFacesByImage` does support multiple faces. From the doc:
>**searchFacesByImage**
For a given input image, first detects the largest face in the image, and then searches the specified collection for matching faces. The operation compares the features of the input face with faces in the specified collection.

>Note
To search for all faces in an input image, you might first call the [IndexFaces](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_IndexFaces.html) operation, and then use the face IDs returned in subsequent calls to the [SearchFaces](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_SearchFaces.html) operation.
You can also call the DetectFaces operation and use the bounding boxes in the response to make face crops, which then you can pass in to the SearchFacesByImage operation.

In terms of changing any existing functionality of rekognition, this is a service functionality, and not something we on the SDK side can provide. 
The SDK is a thin wrapper meant to abstract and simplify calls to the various AWS services, we don't control the results that are returned from the service.

You might want to look at the docs for the specific operation more closely since it sounds like what you are looking for is already supported. 

Thanks,
Ran~

**Comment by zivserphos** [comment]
Well , I also saw the docs and the quote you shared is indeed a possible solution , but , I have written this issue after I saw this docs because I still believe that this possible solution might cause problem in run time and somehow is threshold for unexpected behavior. 

I would be more than happy to provide a solution with searchImageByFace which I think will be more accurate than the current situation for now...

**Comment by RanVaknin** [comment]
Hi @zivserphos ,

> this possible solution might cause problem in run time and somehow is threshold for unexpected behavior.

Can you elaborate on what you mean? why would there be a problem with the runtime?
Without seeing a code snippet that reproduces the issue I don't have enough context. 

> would be more than happy to provide a solution with searchImageByFace which I think will be more accurate than the current situation for now...

I'll reinforce what I said earlier. The functionality and data of how and what data is returned from the Rekognition service is not something the SDK can change. If you see in a documentation gap where the docs say X, and is returning Y then either there's a documentation discrepancy or there is a bug in the service. Both of which need to be upstreamed and solved by the service team. 

Thanks,
Ran~
