### ISSUE TITLE
Limit on how many objects I can upload to s3 in parallel

### ISSUE THREAD

**Issue by nesbtesh** [aws/aws-sdk-js#4397]
### Describe the bug

Our app allows hundreds of users to upload thousands of items to s3 in parallel. However, we've identified a bug in the system where the AWS s3 SDK returns a successful response even when the object hasn't been inserted in the bucket. This usually occurs when there are thousands of objects being uploaded simultaneously.

Does AWS imposes some limits on the number of parallel uploads that can be made using signed URLs? How can this happen?

### Expected Behavior

We expect that our app can handle high volumes of parallel uploads without encountering any issues, as this is a critical feature for our users.

### Current Behavior

When there are thousands of objects being uploaded simultaneously to the AWS s3 bucket using signed URLs, the AWS s3 SDK returns a successful response, but the object never gets inserted in the bucket. 

### Reproduction Steps

Create thousands of signed urls at the same time and use them to upload files to s3 bucket

### SDK version used

2.1354.0

### Environment details (OS name and version, etc.)

WEB, Edge, Chrome

**Comment by RanVaknin** [comment]
Hi @nesbtesh,

I'm not aware of any limitations that could lead to this false positive status because of workloads. This sounds like an issue with the S3 server. Since you are generating presigned URLs for uploads, the actual PUT request is generated by the browser(I assume?) from your customer's machine, so it might be caused by some headers getting re-written or some other edge case that I can't think of.

I can upstream your request to the team, but if you have a Technical Account Manager assigned to your company I encourage you to open the ticket through them and link this Github issue. 

Since you know you are getting a successful status, I assume you have access to the response logs, in those response logs there should be an `x-amz-request-id` header returned with the response.
Something like this:

```
HTTP/1.1 200 OK
x-amz-id-2: LriYPLdmOdAiIfgSm/F1YsViT1LW94/xUQxMsF7xiEb1a0wiIOIxl+zbwZ163pt7
x-amz-request-id: 0A49CE4060975EAC
Date: Wed, 12 Oct 2009 17:50:00 GMT
ETag: "1b2cf535f27731c974343645a3985328"
Content-Length: 0
Connection: close
Server: AmazonS3
```

The S3 service team will need that to root cause the issue you are experiencing.
Please ask the account manager to CC me on the internal ticket so I can weigh in from an SDK standpoint. 
If you don't have an account manager please let me know and I can try to upstream it to the service team on your behalf.

Thanks,
Ran~
