### ISSUE TITLE
misleading error message on timed out SSO session: Error: connect EHOSTDOWN 169.254.169.254:80

### ISSUE THREAD

**Issue by marc-guenther** [aws/aws-sdk-js#4413]
### Describe the bug

When I use a profile that is configured for SSO, and the session has timed out, and I use the sdk (eg. `s3.listBuckets()`), I get this very confusing error message: `Error: connect EHOSTDOWN 169.254.169.254:80`

As I just now had problems with my VPN connection, I lost considerable time running in the wrong direction.

As it turns out, this has NOTHING to do with the network at all, and the fix is to run `aws sso login` again.

### Expected Behavior

A useful error message, like for example: "Your SSO session has timed out, please run "aws sso login" to renew it" or something like that.

Yes, there is this info hidden in there: `'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1'`, but I have never heard of `AWS_CONFIG_FILE` or `AWS_SDK_LOAD_CONFIG` and most certainly it was not needed to fiddle with those.

### Current Behavior

Calling for example `s3.listBuckets()` results in:
```
Error: Error: connect EHOSTDOWN 169.254.169.254:80 - Local (192.168.50.148:51732)
    at internalConnect (node:net:1036:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:466:18)
    at node:net:1139:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  message: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',
  errno: -64,
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2023-05-05T08:33:14.306Z,
  originalError: {
    message: 'Could not load credentials from any providers',
    errno: -64,
    code: 'CredentialsError',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80,
    time: 2023-05-05T08:33:14.306Z,
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      errno: -64,
      code: 'EHOSTDOWN',
      syscall: 'connect',
      address: '169.254.169.254',
      port: 80,
      time: 2023-05-05T08:33:14.305Z,
      originalError: [Object]
    }
  }
}
```

This is extremely misleading. Why would missing credentials result in a EHOSTDOWN network error?

### Reproduction Steps

- use a profile which is configured with SSO
- make sure you are not logged in: `aws sso logout`
- run for example this code:
    ```node
    var AWS = require('aws-sdk');
    var s3 = new AWS.S3();

    s3.listBuckets(function(err, data) {
      if (err) { console.log("Error:", err); }
      else {
        for (var index in data.Buckets) {
          var bucket = data.Buckets[index];
          console.log("Bucket: ", bucket.Name, ' : ', bucket.CreationDate);
        }
      }
    });
    ```

### SDK version used

2.1372.0

### Environment details (OS name and version, etc.)

MacOS 10.15.7

**Comment by RanVaknin** [comment]
Hi @marc-guenther ,

`EHOSTDOWN` is a Node.js error code, not an SDK error code. 

The SDK looks for credentials in something called "the credential chain", it looks at environment variables, hardcoded credentials, shared config file (AWS_CONFIG_FILE), SSO token, EC2 metadata (IMDS)

Since your sso token was expired, the credential chain looked for credentials in all those places, and ended up at the last place it checks for credentials (ec2) which got rejected because you are not running your code from an EC2 instance context. The SDK tried calling the IMDS endpoint at 169.254.169.254 and failed to connect, thats why Node surfaced that EHOSTDOWN, indicating that the host is unreachable. 

>A useful error message, like for example: "Your SSO session has timed out, please run "aws sso login" to renew it" or something like that.

I wholeheartedly agree with you, and in fact there is explicit code in the v2 sdk that should surface just that:
https://github.com/aws/aws-sdk-js/blob/0112e502d794724e2d9c6d17bc8018efd2e8cd63/lib/credentials/sso_credentials.js#LL99C16-L99C16

Maybe the error is truncated on your end, or simply gets swallowed. I'll have to do some investigation to see why this is happening. 

Will keep you posted.
Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @marc-guenther ,

In the last part of that error trace, you can see that the last `originalError` is [Object], this means Javascript truncated the object representation when printing to the console.

For example:
```console
$ const nestedObj = {one: {two: {three: { four: {}}}}};
$ console.log(nestedObj);
{ one: { two: { three: [Object] } } }

$ JSON.stringify(nestedObj);
'{"one":{"two":{"three":{"four":{}}}}}'
```
The solution is to use JSON stringify to display the entire error trace.

You can argue that we can surface all the errors on the same level, but since JS SDK v2 is going into maintenance mode we are shifting focus onto enhancing v3 instead. I suggest that you move to using JS SDK v3 as well.

Thanks,
Ran~

**Comment by devnulled** [comment]
Thanks @marc-guenther; you filing this issue helped me track down a similar problem I was having with this library underneath the covers of a node app that looked like some sort of weird network issue.

In case someone else runs into this same issue and needs to fix it: 

At least for me, it was a combination of two different things:

1. I always name my AWS profiles that I use with the `aws` cli, so I never have any profiles named default.
2. The environment variable that you use to set the profile,`AWS_DEFAULT_PROFILE`, is no longer used. 
 Instead, use the env variable `AWS_PROFILE` now instead.   E.g.:

`export AWS_PROFILE=mycompany-us-west-2`

I still have the `AWS_DEFAULT_PROFILE` defined as the same value, just in case.  But now the app using this library now works for me.

**Comment by marc-guenther** [comment]
Yea, it's a pity that @RanVaknin first wrote "I wholeheartedly agree", and then closed the ticket es "not planned". Although it seems to be quite an easy fix, and is very very confusing for everyone. Just because "v2 is going into maintenance mode" doesn't mean that tons of people are still using it, and waste time figuring this out... Oh well...
