### ISSUE TITLE
ec2.send(new RunInstancesCommand(params)) doesnt timeout.

### ISSUE THREAD

**Issue by mgara** [aws/aws-sdk-js#4448]
### Describe the bug

Using   "@aws-sdk/client-ec2": "^3.301.0": 
Sending a     `RunInstancesCommand` doesnt timeout
I'm seeing this problem when I try to spawn `g5.12xlarge` and it is not available.

So I 2 cases, I usually get the error : 
```
We currently do not have sufficient g5.12xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get g5.12xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1f.
```
which I'm completely fine with it, and I can handle it properly.
but sometimes, which is **more problematic**,  I get no response whatsoever from the API call.

### Expected Behavior

the RunInstancesCommand should either: 
1. return an instance 
2. Return an error (out of capacity error or invalid ami for example)

### Current Behavior

the RunInstancesCommand  has 3 outcomes
1. Creates an instance as expected
2. Return an error (out of capacity error or invalid ami for example)
3. No response and no timing out.  <--- that is the problem

### Reproduction Steps

It's completly random but happens mostly when there is no g5 instances available. 
It can be the root cause or can be something else.
knowing that I'm running this piece of code into a scheduler that keeps retrying.

### SDK version used

3.301.0

### Environment details (OS name and version, etc.)

ECS

**Comment by RanVaknin** [comment]
Hi @mgara ,

You are using a version that is about 600 commits behind main. As a first step I would advise updating the SDK and see if this solves anything. We have pushed changes that fixed some socket related behavior.

From the sounds of it, your socket / connection might be timing out before the server responds. Unfortunately this is kind of hard to diagnose because the SDK does not log low level wire logs. 

You can try to force the socket to stay open for longer. For example 90 seconds:

```js
const client = new EC2Client({
  region: "us-east-1",
  requestHandler: new NodeHttpHandler({
    connectionTimeout: 90000, 
    socketTimeout: 90000     
  })
});
```

Let us know how it goes.

Thanks,
Ran~
