### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by jockiech** [aws/aws-sdk-js#4449]
### Describe the bug

I found a bug in **aws-sdk** which is so weird. Here is the case: I import the **aws-sdk** in my project and use **Vite** to build it into production, when I want to run the production, the program no longer running.

### Expected Behavior

I hope when I use **Vite** to build **aws-sdk**, it no longer report the error, and block normal program execution

### Current Behavior

Here is the error: 
[https://ask.csdn.net/questions/7773827](url)

### Reproduction Steps

Here is the error: 
[https://ask.csdn.net/questions/7773827](url)

### SDK version used

all sdk versions

### Environment details (OS name and version, etc.)

MacOS

**Comment by RanVaknin** [comment]
Hi @jockiech 

Thanks for opening this issue. Unfortunately I cannot read anything from the link you have provided since I don't read Chinese. 

From the description of this issue its not clear what the issue is. If there is an error thrown and what it is. 
Which version of the SDK are you using? Which version of vite? 

We would need to see your application code, and since you are using Vite it means going through your project structure. Please create a small github repository and add the minimal code needed to reproduce this. 

Thanks,
Ran~
Thanks,
Ran?

**Comment by jockiech** [comment]
Using vite+vue3+ts to upload files to Tianyi Cloud OSS through AWS, all functions were tested successfully in the development environment. However, after packaging and compiling, errors occur. 
![dummy](https://github.com/aws/aws-sdk-js/assets/38551182/c75a6ad8-244b-41c9-89d7-4e278e246409)
![dummy](https://github.com/aws/aws-sdk-js/assets/38551182/1519819f-1b46-4f8f-9d8d-a2b8cc89508d)
![dummy](https://github.com/aws/aws-sdk-js/assets/38551182/ce2ac9c4-fbb2-48e9-bcc2-bf07ae7e00bd)

**Comment by jockiech** [comment]
the version of aws-sdk I use is v2.1356.0
the version of vite I use is v4.2.0

**Comment by RanVaknin** [comment]
Hi @jockiech ,

The pictures you are adding are very hard to read, aside from the error message, this is impossible to read.
Without seeing you actual code repo I cannot really debug this.

My suggestion is to use JS SDK v3 and see if it solves your issue.

Thanks,
Ran~
