### ISSUE TITLE
Angular 7 - CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

### ISSUE THREAD

**Issue by ss94866** [aws/aws-sdk-js#4450]
### Describe the bug

I am getting credentials error. I don't want to hardcode accesskeyid and secretaccesskey in the code. I want to use aws config file (.aws/credentials). The lib asks to set AWS_SDK_LOAD_CONFIG=1 in the .env file of the project. But, in angular we have environment files instead of .env. So, is there any other way to set AWS_SDK_LOAD_CONFIG=1.

Please give some other way.

Thank you.

![image](https://github.com/aws/aws-sdk-js/assets/68229944/831d5fc6-120b-49bc-93ae-207000203f66)

### Expected Behavior

Get credentials from AWS_CONFIG_FILE in angular7

### Current Behavior

Getting error 
![image](https://github.com/aws/aws-sdk-js/assets/68229944/c59b8e81-f0cb-4e0e-a325-a634d366600d)

### Reproduction Steps

1. Create angular project 
2. install aws-sdk
3. Try to use the lib without hardcoding the credentials in the code.

### SDK version used

latest

### Environment details (OS name and version, etc.)

windows

**Comment by RanVaknin** [comment]
Hi @ss94866 ,

You can add those env variables into your `environment.ts` file for angular. Just bear in mind that effectively there is no difference between that and hard coding your credentials. When bundling your application this code will be exposed on the front end. 

I'm not sure what your use case is, but if you have a backend, the SDK calls should be made there rather than the front end, that way you can take advantage of credentials loading on the server side which is less likely to get compromised. 
If you are building only on the client side, you can use [Cognito identity pools](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html) to get a temporary credentials to use on the front end. 

Let us know if you have any other questions. 
Thanks,
Ran~
