### ISSUE TITLE
Pinpoint api to get all sms channel detail

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-sdk-js#4490]
### Describe the feature

We are in search of api which can tell us the all detail of a sms channel for a particular pinpoint application.
i.e. Current Spend Limit, Max Limit, current monthly spend out of current spend limit.

I checked and see that we have on SpendLimit api but it is not giving us current monthly spend in response.

### Use Case

Get current monthly spend of a sms channel of a pinpoint application.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.405.0

### Environment details (OS name and version, etc.)

Windows

**Comment by ajredniwja** [comment]
Hi @devendra-kumar1, thanks for opening this request, not a PinPoint expert, did you use [describeSpendLimits](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/PinpointSMSVoiceV2.html#describeSpendLimits-property)? which provides with monthly spend limit. 
 
The [describeAccountLimits](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/PinpointSMSVoiceV2.html#describeAccountLimits-property) has a `Used` field which mentions the current amount spent. 

I also see [getSmsChannel](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#getSmsChannel-property) which gives out information about SMS channel for an application but doesnt mention anything about spend limits. 

If this is not what you are looking for can you please mention the API you are using and what additional fields you are looking for? Thanks

**Comment by devendra-kumar1** [comment]
> Hi @devendra-kumar1, thanks for opening this request, not a PinPoint expert, did you use [describeSpendLimits](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/PinpointSMSVoiceV2.html#describeSpendLimits-property)? which provides with monthly spend limit.
> 
> The [describeAccountLimits](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/PinpointSMSVoiceV2.html#describeAccountLimits-property) has a `Used` field which mentions the current amount spent.
> 
> I also see [getSmsChannel](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#getSmsChannel-property) which gives out information about SMS channel for an application but doesnt mention anything about spend limits.
> 
> If this is not what you are looking for can you please mention the API you are using and what additional fields you are looking for? Thanks

@ajredniwja Thanks for reply. I used these two mentioned method but none of them are providing me the used amount so far.
I checked a way when i logged in to aws console and navigate to pinpoint dashboard and select pinpoint app. 
I checked network tab of chrome browser and see one api is getting called for getting data of sms channel of that pinpoint app. Adding sample request and response FYI.

API: https://ap-south-1.console.aws.amazon.com/pinpoint/api/account/settings/sms?appId=<app_id>
Response: 
{"data":{"publishesPerSecond":"20","**currentMonthlySpend**":"2.276","monthlySpendLimit":"40","maxLengthOfWhitelistedMessageText":"30","shortcodes":[],"appSenderId":"","whitelistedMessagesPerShortCodeMap":"27","accountTier":"Production","senderId":"AegonL","messageType":"Transactional","sanctionedMonthlySpendLimit":"120","defaultGlobalMonthlySpendLimit":"1","currentRemainingSpendQuota":"40.0"}}


In the above response you can see it has one field cuurentMonthlySpend which tell us how much amount i have spent so far.

So if we have any such method which can tell us the monthly spend ?

**Comment by RanVaknin** [comment]
Hi @devendra-kumar1 ,

Looking at the API model for pinpoint, I don't see a modeled operation that returns the fields `currentMonthlySpend` or `monthlySpendLimit`. 

Notice the URL has a `.console.aws.amazon.com`, This inidicates this is a console utility. What I'm guessing is happening, is that Pinpoint has service side support for getting account usage (probably leveraging cost explorer api under the hood) without that API method actually being published in their model. Since all the AWS SDK's are code-generated from the published API models of each AWS service, the SDK will only reflect what the model has.

I tried using cost explorer to find a solution for you, but to get individual usage for an application CE uses resource tags, and as far as I can tell, tags are not supported for Pinpoint applications. 

As of now this issue is not actionable by the SDK team and I don't see a direct workaround. The best course of action for you would be to use the AWS console to open a support ticket and engage with the pinpoint service team asking for a feature request to add that operation to their model and add sigv4 support for it. 

Apologies for the inconvenience. 
Ran
