### ISSUE TITLE
AWS Credential Error in Runtime using JavaScript AWS SDK v2.784.0

### ISSUE THREAD

**Issue by KrishankantFromCambium** [aws/aws-sdk-js#4505]
### Describe the bug

On an EC2 instance, I encountered a credential error when attempting to upload a file to an S3 bucket. It's worth noting that this issue arose unexpectedly since the process worked without errors both before and after a retry attempt.

### Expected Behavior

In any number of attempts, there should be no occurrence of a credential error.

### Current Behavior

Error: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1 Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

### Reproduction Steps

It's important to note that this issue is not consistently reproducible, but here are the steps that trigger the problem:

1. Create an S3 stream to upload a file using the `s3:upload` API.
2. Continuously write content to the stream for approximately 30-40 minutes.
3. Attempt to close the stream to create a file on S3, which occasionally throws the error mentioned above.

Strangely, on subsequent retry attempts, the operation works fine without any credential issues.

I appreciate any insights or guidance on how to resolve this intermittent AWS credential error when using the `aws-sdk` for JavaScript.

In EC2 instance throws a Credential error on attempting to upload file to s3 but It was working fine before and after a retry

### Additional Information/Context

**Infrastructure:** My code is deployed to an EC2 instance, and it's expected to load credentials from an IAM Role and no accessKeyId, secretAccessKey and sessionToken are passed.

### SDK version used

 v2.784.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04.5 LTS

**Comment by RanVaknin** [comment]
Hi @KrishankantFromCambium ,

This smells like a credential expiration window issue, especially considering the intermittent nature of the problem during uploads lasting 30-40 minutes. This duration likely coincides with the credential expiration window. The SDK typically checks expiration and refreshes credentials if needed before each API call, but this process can't occur during a single, long-running upload call. This also explains why the issue is resolved on retry as the SDK will check for credentials again.

The way the flow works "under the hood", is that the SDK's [IMDS provider](https://github.com/aws/aws-sdk-js/blob/master/lib/metadata_service.js) will make a call to the IMDS endpoint to request a token (valid for a maximum of 6 hours), and with that token the SDK then will call to get the role session. 

Based on the description, it sounds completely possible that during that 6 hour credential validity window, one of your long-running upload streams will run over that 6 hour mark and will have to retry. Can you try to adjust the partSize parameter in your uploader to something smaller?

Thanks,
Ran~
