### ISSUE TITLE
sqs.sendMessage is sometimes very slow or fails

### ISSUE THREAD

**Issue by kim-sung-jee** [aws/aws-sdk-js#4537]
### Describe the bug

 even after exceeding the default time of 2 minutes and the default retry of 2 attempts
sqs.sendMessage is sometimes very slow or fails

"The problematic queue is using a standard queue."

### Expected Behavior

Initially, I thought the issue was with the default settings of the SDK. Therefore, I added the following code to inject into the SQS client:

```javascript
const agent = new https.Agent({
  maxSockets: 256,
  keepAlive: true,
  rejectUnauthorized: true,
});

export const sqs = new AWS.SQS({
  region: constants.AwsRegion,
  httpOptions: { agent }
});
```

However, I am still experiencing errors with `sqs.sendMessage`. These errors occur when there is a moderate level of traffic using the `sqs.sendMessage()` function, but not at the times of peak traffic. Each time this issue happens, multiple failure logs are recorded within a minute.

### Current Behavior

Here is a picture displaying the errors that occurred throughout the day, including failures after the default timeout of 2 minutes and the standard 2 retries.

(While the content below shows up to 1 minute, upon checking the actual span, it fails after a delay of 4 minutes as shown in the picture.)

<img width="407" alt="스크린샷 2023-11-26 18 13 48" src="https://github.com/aws/aws-sdk-js/assets/85841791/46e7a81f-f6ac-4b34-bc85-38f6cb7da6fb">

| Time              | Duration   |
|-------------------|------------|
| Nov 26 05:25:04.286 | 1 min 0 s |
| Nov 26 05:25:32.450 | 60.0 s    |
| Nov 26 05:29:24.507 | 60.0 s    |
| Nov 26 11:50:17.943 | 60.0 s    |
| Nov 26 11:51:16.185 | 1 min 0 s |
| Nov 26 11:51:49.479 | 60.0 s    |
| Nov 26 11:52:03.622 | 1 min 0 s |
| Nov 26 11:52:07.623 | 1 min 0 s |
| Nov 26 11:52:13.153 | 1 min 0 s |
| Nov 26 11:52:23.986 | 1 min 0 s |
| Nov 26 11:52:36.693 | 60.0 s    |

As mentioned earlier, the times when these issues occur are not periods of sudden spikes in traffic for `sqs.sendMessage`.

### Reproduction Steps

I apologize for not being able to provide a detailed explanation of the reproduction process. However, the same issue occurred with both five `await sqs.sendMessage` calls and processing within a `Promise.allSettled` with five promises.

### SDK version used

2.1230.0

### Environment details (OS name and version, etc.)

node: 16.20.2

**Comment by RanVaknin** [comment]
Hi @kim-sung-jee ,

The image you added just shows an output from a monitoring tool. I don't see a specific error thrown even though you mentioned that there is an error:
>_"Here is a picture displaying the errors that occurred throughout the day"_

Since there are retries kicking in, there must be some explicit errors thrown that cause the retries to trigger. 
If you can share those errors with us we will be able to get a better idea on how to assist you.

Since your code is incomplete it's hard to see how you are making the request, but given that you mentioned Promise.allSettled, **I'm guessing** that you are firing all the sendMessage commands concurrently and are getting a throttling error from the service. If you are getting a throttling error you can do one of two things:

1. Setup a retry strategy with an exponential backoff with jitter to help space out your concurrent requests.
2. Open a support ticket in the AWS console, and ask to get a throttling limit increase.

How are you running your code? Is this firing through lambda? in an EC2 instance inside of a VPC? local node.js environment?

Thanks,
Ran~
