### ISSUE TITLE
RequestTimeout during upload 

### ISSUE THREAD

**Issue by gsphanikumar** [aws/aws-sdk-js#454]
Using aws-sdk some of my uploads are failing once in a while with the below stacktrace. Retries doesnt help in this case. Is this related to https://github.com/aws/aws-sdk-js/issues/281 ?

```
2014-12-31 00:12:22,395 - info: Error uploading file:RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
    at Request.extractError (node_modules/aws-sdk/lib/services/s3.js:283:35)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:114:20)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:16)
    at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (node_modules/aws-sdk/lib/request.js:593:14)
    at Request.transition (node_modules/aws-sdk/lib/request.js:24:12)
    at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
    at node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:31:9)
    at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:595:12)
2014-12-31 00:12:22,395 - error:  message=Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed., code=RequestTimeout, time=Wed Dec 31 2014 00:12:22 GMT-0800 (PST), statusCode=400, retryable=true
```

I am using the below code to upload

```javascript
 var stream = fs.createReadStream(filePath);
var params = {
  Bucket: awsBucketName,
  Key: awsFilename,
  Body: stream
};
s3.putObject(params, function(err, data) {
   if (err) {
      logger.info("Error uploading file:" + err.stack);
      fn(err);
} });
```

node version  -  v0.10.33
aws-sdk - 2.0.1

**Comment by lsegal** [comment]
I'm going to mark this as closed since there hasn't been any response and I wasn't able to reproduce this on my end. If you can provide more information on the latest version (now 2.1.5), feel free to reopen!

**Comment by gsphanikumar** [comment]
Got the below error couple of times with the 2.1.4 sdk. 
Saw a upload issue where 10 retries did not help. Upload eventually succeeded after retrying after a couple of hours. Am using the npm retry module for retries.

```
	var stream = fs.createReadStream(filePath);
	var params = {
			Bucket: awsBucketName,
			Key: awsFilename,
			Body: stream
			};
     stream.on('open',function() {
         s3.putObject(params, function(err, data) {
             if (operation.retry(err)) {
                 logger.error("Error during upload:" + err.stack);
                 logger.error("Retrying uploading file " + path);
                 return;
             }
             if (err) {
                 logger.error("Error uploading file:" + err.stack);
             } 
         });
     });

```

```
2015-1-27 22:09:45,872 - error: Error during upload:RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
    at Request.extractError (/node_modules/aws-sdk/lib/services/s3.js:358:35)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

**Comment by gsphanikumar** [comment]
@lsegal Can you please re-open this issue

**Comment by lsegal** [comment]
@gsphanikumar I'm still unable to reproduce the issue with the information provided. A timeout error implies that the data isn't being sent to S3 by your socket, or it's not sending the amount of bytes specified by the Content-Length header in the request.

Is there any other information relevant to your environment? Are you by any chance using a proxy either with the Node process or globally on your system?

**Comment by gsphanikumar** [comment]
@lsegal  We are not using a proxy but it turned out to be our Ec2 Nat instance capacity issue.

**Comment by ronyrun** [comment]
Hello, 

I encounter the same error when upgrading from version 
v2.0.0-rc.19 to v2.4.7

I have no errors with v2.0.0-rc.19
I'm gonna try to detail more on which version this is not working anymore

```javascript
 var option = {
                    Bucket: bucket,
                    Key: upload.dest,
                    Body: fs.createReadStream(path.normalize(output + '/' + upload.orig)),
                    ContentType: upload.contentType
                };
                
                s3.putObject(option, function (err) {
                    if (err) {
                        console.error(JSON.parse(JSON.stringify(err)));
                        return cb(err);
                    } 
                    cb();
                });
```

**Comment by mjurincic** [comment]
@ronyrun Any updates on this I'm having the same, almost exact same code,  aws-sdk v2.4.4, it  just happens sporadically

**Comment by lsegal** [comment]
@ronyrun @mjurincic if this is sporadic and you cannot reproduce it on the same exact body contents multiple times in a row, it is more than likely a networking issue. All the SDK is doing is putting your body in a HTTP PUT request with some custom headers and sending it using the standard HTTP client routines, so there is nothing different about 'putObject' from any other of the SDK's methods (and this includes *all* service operations, not just S3).

A RequestTimeout error happens if S3 receives no data during a period of time. The only way the SDK is doing something wrong here would be if it sent the wrong Content-Length for your body, which would mean S3 would be waiting for more bytes that would never be sent. If this were the case, though, you would be able to reproduce it every time with the same exact data. You can also verify this yourself by inspecting data across the wire and checking that your Content-Length header is correct.

If the Content-Length is correct, and given the non-deterministic behavior, the issue is probably outside of the SDK and somewhere in Node.js itself or down your networking stack. As a user pointed out above, there are many moving parts to this error, even EC2 NAT instance capacity issues can cause this error-- something that you may not yet have ruled out. If your instance is sending a lot of bytes across the wire, it's entirely possible that you may be getting throttled somewhere along the way. It might even just be a temporal / random corruption issue, which happens from time to time, especially over the course of sending a lot of data.

Either way, you should probably be using the [managed s3.upload() method](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) for all uploads anyway, since it parallelizes the data and uploads in chunks so retries can happen in a more granular fashion. This method was added after the 2.0.0 rc releases. Sending a single large body payload is a very unreliable operation, and you're seeing that in the code above. You're still not guaranteed to have no networking errors (you may still have timeouts internally), but the managed uploader should be able to recover from them more easily.

That said, if you *can* in fact reproduce this reliably on a single body payload, feel free to post those reproduction steps so the SDK maintainers can fix that specific issue.

**Comment by ronyrun** [comment]
Thank you @lsegal 

I found which version cause the issue 

"aws-sdk": "2.4.0", => Working
"aws-sdk": "2.4.1", => not Working

I'm gonna test the managed s3.upload() method you provided.

**Comment by chrisradek** [comment]
@lsegal 
Thank you for your explanation.
@ronyrun 
Were your errors in `2.4.1` sporadic or consistent? Let us know if you have better results using `s3.upload()`!

**Comment by ronyrun** [comment]
Hi, my error is consistent.

**Comment by ronyrun** [comment]
My bad it's sporadic, I have the issue now with a previous version.

**Comment by FouadWahabi** [comment]
Hello,
Please any solution or a workaround for this issue, I encountered it with the latest version

**Comment by huesforalice** [comment]
Switching to 'upload' instead of 'putObject' solved this issue for me.

**Comment by sseetal** [comment]
Can confirm that 'upload' also works for me

**Comment by deliverymanager** [comment]
+1

**Comment by junajan** [comment]
We encountered the exact same problem when upgrading from v2.5.0 to v2.82.0

Our code:
```js

const params = {
  Bucket: bucket,
  Key: folder + objectName,
  Body: fs.createReadStream(localFile),
  ContentType: 'text/csv',
  ACL: 'public-read'
}

return this.s3Client.putObject(params)
  .promise()
  .then(data => {
    this.logger.info('FileContent was uploaded with etag %s', data.ETag)
  })
```

**Comment by junajan** [comment]
I tried different versions and this error started appearing with this commit: https://github.com/aws/aws-sdk-js/commit/37f8596926dc0736d4e3e5021872fa981a305067

Also, it looks like it works when changing `putObject` to `upload`.
