### ISSUE TITLE
AWS S3 InvalidRequest (400 Bad Request) SOAP requests must be made over an HTTPS connection.

### ISSUE THREAD

**Issue by 3y3** [aws/aws-sdk-js#458]
Hello, I use aws-sdk as part of [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) package to autopublish prebuild binaries from TravicCI and AppVeyor. I publish succesefully from AppVeyor, but my travis config dosen't work - I receive error
`400 BadRequest`. In S3 logs I see verbose information:
```
5a2b5e5d590abed41d07774d8746a82b637b04c6640553bb755c7eff90d8ca42 node-inspector 
[08/Jan/2015:14:27:59 +0000] 199.182.120.18 - 9B9ADFABBF38468B 
REST.HEAD.OBJECT debug/v0.3.2/node-v11-linux-x64.tar.gz 
"HEAD /debug/v0.3.2/node-v11-linux-x64.tar.gz HTTP/1.1" 
400 InvalidRequest 324 - 4 - "-" "aws-sdk-nodejs/2.1.4 linux/v0.10.35" -
```

Is there any reasons why this error happens only on Travis but not on AppVeyor.
Related node-pre-gyp issue https://github.com/mapbox/node-pre-gyp/issues/131

**Comment by lsegal** [comment]
I see the SDK info in the stack trace, but I'm not sure where that code is coming from. Can you explain how you are using the SDK here?

**Comment by 3y3** [comment]
The error starts [here](https://github.com/mapbox/node-pre-gyp/blob/master/lib/publish.js#L36)
I'm not a developer of node-pre-gyp, but I can provide more info.

Now I updated to latest node-pre-gyp version to have more verbose log:
```bash
1.49s$ if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package testpackage publish --verbose; fi;
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'node',
node-pre-gyp verb cli   '/home/travis/build/3y3/v8-debug/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'package',
node-pre-gyp verb cli   'testpackage',
node-pre-gyp verb cli   'publish',
node-pre-gyp verb cli   '--verbose' ]
node-pre-gyp info using node-pre-gyp@0.6.1
node-pre-gyp info using node@0.10.35 | linux | x64
node-pre-gyp verb command package []
node-pre-gyp info package packing /home/travis/build/3y3/v8-debug/build/debug/v0.3.2/node-v11-linux-x64
node-pre-gyp info package packing /home/travis/build/3y3/v8-debug/build/debug/v0.3.2/node-v11-linux-x64/debug.node
node-pre-gyp info package Binary staged at "build/stage/debug/v0.3.2/node-v11-linux-x64.tar.gz"
node-pre-gyp verb command testpackage []
node-pre-gyp info install unpacking debug.node
node-pre-gyp info validate Running test command: '/home/travis/.nvm/v0.10.35/bin/node --eval require('/home/travis/build/3y3/v8-debug/build/debug/v0.3.2/node-v11-linux-x64/debug.node')'
[v8-debug] Package appears valid
node-pre-gyp verb command publish []
node-pre-gyp info publish Detecting s3 credentials
node-pre-gyp info publish Authenticating with s3
node-pre-gyp info publish Checking for existing binary at https://node-inspector.s3.amazonaws.com/debug/v0.3.2/node-v11-linux-x64.tar.gz
node-pre-gyp info publish s3 headObject error: "BadRequest: null"
node-pre-gyp ERR! publish error 
node-pre-gyp ERR! stack BadRequest: null
node-pre-gyp ERR! stack     at Request.extractError (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/services/s3.js:352:35)
node-pre-gyp ERR! stack     at Request.callListeners (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
node-pre-gyp ERR! stack     at Request.emit (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
node-pre-gyp ERR! stack     at Request.emit (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:604:14)
node-pre-gyp ERR! stack     at Request.transition (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:21:12)
node-pre-gyp ERR! stack     at AcceptorStateMachine.runTo (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/state_machine.js:14:12)
node-pre-gyp ERR! stack     at /home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/state_machine.js:26:10
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:22:9)
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:606:12)
node-pre-gyp ERR! stack     at Request.callListeners (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/3y3/v8-debug/node_modules/.bin/node-pre-gyp" "package" "testpackage" "publish" "--verbose"
node-pre-gyp ERR! cwd /home/travis/build/3y3/v8-debug
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
null
The command "if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package testpackage publish --verbose; fi;" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by lsegal** [comment]
Ah, looking at your configuration it looks like you're trying to push to an [eu-central-1 bucket](https://github.com/node-inspector/v8-debug/blob/master/appveyor.yml#L6)? This error is showing up because the SDK has the default 'us-east-1' region configured but is trying to upload to an 'eu-central-1' bucket.

It looks like you correctly *attempted* to configure the region, which is the right thing to do, but my guess is `node-pre-gyp` does not actually support configuring the region through the `node_pre_gyp_region` environment variable (i.e. it's not passing through). I bet if you printed the `s3.config` options in that code you would see region misconfigured.

Reading through the [`node-pre-gyp` README](https://github.com/mapbox/node-pre-gyp#3-configure-aws-credentials), it's a little unclear about how to configure the region-- but I think they mean you can configure region only through the rc file format, not environment. You might want to ask on mapbox/node-pre-gyp#131 about the correct way to configure a region through environment variables.

Note that if node-pre-gyp doesn't have a way to do it, I think you can work around it by setting the `AWS_REGION` environment variable directly, which the SDK will use to configure your region-- or should, anyway. You can give that a shot.

**Comment by 3y3** [comment]
Oh! Really thanks and sorry for this issue. I can't understand how I missed this difference in `appveyor.yml` and `.travis.yml`

Now I added `node_pre_gyp_region="eu-central-1"` to my `.travis.yml` and all works fine!
