### ISSUE TITLE
Error in AWS SDK and Usage Guide for Content Moderation version 7

### ISSUE THREAD

**Issue by seantsangmk** [aws/aws-sdk-js#4589]
### Describe the bug

I followed the instructions provided in the guide (https://docs.aws.amazon.com/rekognition/latest/dg/procedure-moderate-images.html#moderation-labels-update-sdk) to update the label mappings for Versions 6.1 to 7. However, this result in an error being displayed in CloudWatch.

### Expected Behavior

interface DetectModerationLabelsRequest should include RequestedModelVersion

### Current Behavior

cloudwatch log shows errors with `UnexpectedParameter: Unexpected key 'RequestedModelVersion' found in params`

### Reproduction Steps

use sample code in https://d1m67pwji3rslw.cloudfront.net/guide/Guide_JavaScriptV2.pdf with aws-sdk@2.1563.0

### SDK version used

2.1563.0

### Environment details (OS name and version, etc.)

Windows 10 Version 22H2 (OS Build 19045.3930)

**Comment by tpneumat** [comment]
Same issue -- aws-sdk version-- 2.264.1

**Comment by hjst** [comment]
@seantsangmk @tpneumat The `RequestedModelVersion` param isn't in the public SDK (and I suspect it never will be). [The instructions say to download the SDK version linked on that page](https://docs.aws.amazon.com/rekognition/latest/dg/procedure-moderate-images.html#moderation-labels-update-sdk) and use that instead of the public SDK in NPM.

We vendored this "private" SDK into our repo (using it only for Rekognition) and sure enough, the `RequestedModelVersion` param is there and it works as documented.

**Comment by RanVaknin** [comment]
Hi all,

@hjst seems to be correct. Additionally the doc you linked mentions:

>Your account will remain on version 6.1 until March 4, 2024. If you wish to use version 6.1 beyond March 4, 2024, contact the[AWS Support team](https://aws.amazon.com/support) by March 1, 2024 to request for an extension. We can extend your account to remain on version 6.1 until April 2, 2024. If we do not hear from you by March 1, 2024, your account will be automatically migrated to version 7.0 between March 4, 2024 and March 26, 2024.

Since we are past this date I assume the upstream service automatically applies content moderation v7. 

This is a service related request and is not not something the AWS SDK team can address.
If there are any other questions please let us know.

Thanks,
Ran~
