### ISSUE TITLE
issue in installing aws-sdk@2.1572.0

### ISSUE THREAD

**Issue by nishikant-rsystems** [aws/aws-sdk-js#4602]
### Describe the bug

> aws-sdk@2.1572.0 postinstall /mnt/ebs/codeVKAPIs/vk-api-webservices/routes/vk-api-early_checkin/node_modules/aws-sdk
> node scripts/warn-maintenance-mode.js

sh: node: command not found

### Expected Behavior

it should install the version properly

### Current Behavior

Giving node command not found error

### Reproduction Steps

RUN npm i aws-sdk

while installing the package it gave an error for the latest aws-sdk version.

### SDK version used

2.1572.0

### Environment details (OS name and version, etc.)

linux

**Comment by BenHwem** [comment]
We had the same issue, in our case we found a workaround by making sure that Node is available to all users on the system, as Node was only available to the root user. We are using an elastic beanstalk environment and a post deploy script to install Node using NVM. Happy to share the workaround if this scenario is the same for you?

**Comment by aBurmeseDev** [comment]
Hi @nishikant-rsystems - thanks for reaching out.
As mentioned by previous comment, it could be because Node is only available to root users and not to non-root users. I would also make sure npm file is in appropriate path/folder. 

You can verify if node is installed on current user by running `node -v` in your terminal. Here's one resource I found that might be useful as there are many suggestions for your reference: https://stackoverflow.com/questions/31472755/sudo-npm-command-not-found 

Hope it helps,
John
