### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by scott-threet-konecranes** [aws/aws-sdk-js#4606]
### Describe the feature

variables providing payload size limits for various supported services (especially lambdas)

### Use Case

keeping lambda responses below the payload limitations (Here I am specifically interested in the 6MB (seems to actually be 6291556 bytes (https://zaccharles.medium.com/deep-dive-lambdas-response-payload-size-limit-8aedba9530ed, confirmed with own testing) )) for synchronous requests/responses from https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html), but I think having the other limits available could also be useful

### Proposed Solution

just some constant variables somewhere, something like Number.MAX_SAFE_INTEGER

### Other Information

of course I can do these kind of constant variables locally, but seems like it could be useful thing also for other people

I've specified the one I need to use, but of course other limits would be equally useful to have available

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

^2.1392.0

### Environment details (OS name and version, etc.)

serverless ^3.32.2

**Comment by RanVaknin** [comment]
Hi @scott-threet-konecranes ,

It's not clear what the actual request from the SDK team is. 
The Lambda request and response payload limit is not something that is related to the SDK, it is related to a limitation of Lambda as a service.

>just some constant variables somewhere, something like Number.MAX_SAFE_INTEGER

It's not clear what you are asking for here. A variable that can adjust the max payload size? 

If you didn't know, all of the AWS SDKs (and the AWS CLI) are all code generated from the API models of each service. Because of this, the SDK team cannot add any parameters or configurations that are not specified in the model, because each one of those resources represent a tie to a backend functionality.

Since your request is more geared towards Lambda as a service, and not actionable by the SDK team, I'm going to go ahead and close this.

Thanks again,
Ran~

**Comment by scott-threet-konecranes** [comment]
First, to be clear, I'm not asking for anything that can be adjusted. I was asking only for the size limit to be programmatically available.

Anyway, it sounds like it would instead be a feature request towards that api model, which I was not aware of. Is there any documentation about that? My google skills are only finding things about models from api gateway.

Thanks for clarification about how sdk's are developed.
