### ISSUE TITLE
Service: AmazonSimpleEmailService; Status Code: 403

### ISSUE THREAD

**Issue by SreedharLilly** [aws/aws-sdk-js#4610]
### Describe the bug

"Message": "Error sending email: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonSimpleEmailService; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3488a0f7-3c13-4125-9939-0a99032255be; Proxy: null)"

### Expected Behavior

It need to send an email through the AmazonSimpleEmailService

### Current Behavior

"Message": "Error sending email: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonSimpleEmailService; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3488a0f7-3c13-4125-9939-0a99032255be; Proxy: null)"

### Reproduction Steps

"Message": "Error sending email: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonSimpleEmailService; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3488a0f7-3c13-4125-9939-0a99032255be; Proxy: null)"

### SDK version used

1.12.674

### Environment details (OS name and version, etc.)

Windows

**Comment by aBurmeseDev** [comment]
Hi @SreedharLilly - thanks for reaching out. 

The error you're seeing is due to the signature mismatch where the signature value in your request to the AWS didn't match the signature that service calculated. How are you [signing API requests](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-signing.html)? Can you provide a minimal reproducible code that would give me more insights on understanding the issue to offer guidance?

**Comment by ikechiU** [comment]
@aBurmeseDev
