### ISSUE TITLE
I want to use Lambda with the event sources SQS & API Gateway with SDKv3 and without a SDKv2 dependency

### ISSUE THREAD

**Issue by ehuebner** [aws/aws-sdk-js#4616]
### Describe the bug

I want to use Lambda in my Typescript / NodeJs application. I am using SQS and API Gateway as event sources.
As the [documentation mentions](https://docs.aws.amazon.com/lambda/latest/dg/typescript-handler.html), I need to install `aws-lambda` to get the type definitions for `APIGatewayProxyEvent`, `APIGatewayProxyResult`, `SQSEvent` & `SQSRecord`.
`aws-lambda` has dependency to the SDKv2 and as a result I have the 100 mb SDKv2 in my dependencies only because I need the 4 type definitions. With a 256mb layer size and dependencies I need for my use case, I exceed the 256mb.

### Expected Behavior

Have type definitions of all Lambda event sources available without a dependency to SDKv2.

### Current Behavior

Lambda event source type definitions have a dependency to SDKv2.

### Reproduction Steps

npm install aws-lambda
Check your `package-lock.json` or your `node_modules` directory for `aws-sdk`.

### Possible Solution

Provide the interfaces in the SDKv3.

### SDK version used

v3 & forced to use v2

### Environment details (OS name and version, etc.)

MacOS

**Comment by RanVaknin** [comment]
Hi @ehuebner ,

Thanks for reaching out.

Despite its name, `aws-lambda` is not a tool owned by AWS. This is a community driven repo, and we don't control it. 

I do see that you can install the [types themselves](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda): `npm install --save @types/aws-lambda`, or your other option is to create those interfaces yourself in your lambda function. 

Since this is not actionable by the AWS SDK team, I'm going to go ahead and close this.

Thanks again,
Ran~

**Comment by rupertlssmith** [comment]
Weird that the tutorial in AWS official docs even says to use aws-lambda to get the types when it is not an AWS package.
