### ISSUE TITLE
Cannot call s3.getBucketLocation on non us-east-1 buckets when sending signature v4 requests to us-east-1

### ISSUE THREAD

**Issue by e-gineer** [aws/aws-sdk-js#462]
When connecting to S3 using signature v4, I'm seeing correct behaviour from all regions EXCEPT us-east-1. Specifically, requests to us-east-1 for getBucketLocation of buckets in other regions fail when using signature v4.

To reproduce, please create buckets in a few regions, and use the code snippet below with different settings for the connectRegion.

Please let me know if you have trouble reproducing, or if I'm doing something wrong in working with buckets across regions... Thanks!

```
aws = require 'aws-sdk'

#connectRegion = 'eu-central-1' # works
#connectRegion = 'eu-west-1' # works
#connectRegion = 'us-west-2' # works                                                                                                                  
connectRegion = 'us-east-1' # fails

accessKeyId = 'SECRET'
secretAccessKey = 'SECRET'

regionalBuckets = [
  'your-us-east-1-bucket'
  'your-eu-west-1-bucket'
  'your-us-west-2-bucket'
  'your-eu-central-1-bucket'
]

console.log "== Results for #{connectRegion} ================"

conn = new aws.S3
  accessKeyId: accessKeyId
  secretAccessKey: secretAccessKey
  signatureVersion: 'v4'
  region: connectRegion

conn.listBuckets (err, buckets) -> console.log err, buckets

for bucket in regionalBuckets
  conn.getBucketLocation {Bucket: bucket}, (err, location) ->
    console.log "\n#{bucket} location is:", err, location
```

**Comment by AdityaManohar** [comment]
@e-gineer This is expected behavior. If you are using signature v4, then requests made to an endpoint will have to be signed with the same region as that endpoint.

For instance,  if you are making a `getBucketLocation` request for a bucket in `us-west-2` then the request will have to be signed with `region: 'us-west-2'`. Typically, if you are using signature v4, you should already know the region your bucket is in.

To get around this, you can force path style bucket addressing when constructing an S3 service object.

```javascript
var s3 = new AWS.S3({
  signatureVersion: 'v4', 
  region: 'us-east-1', 
  s3ForcePathStyle: true
});

// This will now work
s3.getBucketLocation({Bucket: 'not-us-east-1-bucket'}, callback);

``` 

Hope this helps!

**Comment by e-gineer** [comment]
Thanks @AdityaManohar, my testing shows that s3ForcePathStyle resolves the issue per your example.

But, I'm still confused as to why this operation succeeds when calls are made to any region other than us-east-1? If I understood your answer correctly, then I'd expect the sample script to fail in all regions, not just us-east-1...

For example, this non-s3ForcePathStyle code works in us-west-2:
```
AWS = require('aws-sdk');                                                                                                                             

var s3 = new AWS.S3({
  accessKeyId: 'SECRET',
  secretAccessKey: 'SECRET',
  signatureVersion: 'v4',
  region: 'us-west-2'
});

s3.getBucketLocation({Bucket: 'not-us-west-2-bucket'}, function (err, result) {
  console.log(err);
  console.log(result)
});
```

but the same code called from us-east-1 fails:
```
AWS = require('aws-sdk');                                                                                  

var s3 = new AWS.S3({
  accessKeyId: 'SECRET',
  secretAccessKey: 'SECRET',
  signatureVersion: 'v4',
  region: 'us-east-1'
});

s3.getBucketLocation({Bucket: 'not-us-east-1-bucket'}, function (err, result) {
  console.log(err);
  console.log(result)
});
```

Thoughts? Is the expected behavior that us-east-1 is a special case?

**Comment by AdityaManohar** [comment]
When you sign a request with `us-east-1`, the request is routed to `s3.amazonaws.com` which then does some DNS magic to route you to where your bucket actually is. This fails if the bucket is not in `us-east-1`, because the request is now actually hitting another region, but being signed with `us-east-1`.

When you sign a request with a region other than `us-east-1`, there is no DNS magic happening. A request is made to the correct endpoint, which will return the location of the bucket irrespective of where the bucket actually is (this is only true for `getBucketLocation`, other operations will have to be signed with the correct region).

So you can also do:

```javascript
var s3 = new AWS.S3({
  signatureVersion: 'v4', 
  region: 'us-west-2' // Any region except us-east-1 
});

// This will now work
// Location is empty for a bucket in us-east-1
s3.getBucketLocation({Bucket: 'any-location-bucket'}, callback);

```

**Comment by e-gineer** [comment]
Thanks, this clarifies things completely ... us-east-1 really is a special case for S3.
