### ISSUE TITLE
pre-signed S3 putObject URLs don't allow tags

### ISSUE THREAD

**Issue by RingOfStorms** [aws/aws-sdk-js#4620]
**Is your feature request related to a problem? Please describe.**
Essentially reopening this issue because it is not solved: https://github.com/aws/aws-sdk-js/issues/1313

Summary:
It is impossible to enforce Tags and their value with just a signed url. The only thing that you can do is _allow_ a client to provide headers. This is not usable when you do not have control over the client and still want tags to be set.

**Describe the solution you'd like**

I'd like the S3.getSignedUrl method to allow an additional param: `TagSet` which matches other TagSet params throughout the API. This would result in a signed url that can have data put to it and the resulting S3 object will have the tags defined in the getSignedUrl params.

```
s3.getSignedUrl('putObject', {
    Bucket: bucket,
    Key: key,
    Expires: 60, // seconds
    Metadata: {
      testMetaKey: 'test meta value'
    },
    TagSet: [
      { Key: 'testTagKey1', Value: 'test1' }
    ]
  });

// PUT into signed url

const { TagSet } = s3.getObjectTagging({ Key: key, Bucket: bucket });

assert(TagSet, [{ Key: 'testTagKey1', Value: 'test1' }]) // should be true
```

**Comment by aBurmeseDev** [comment]
Thanks for reaching out and sorry for the long wait.  

During my investigation, I found out that there might be ongoing bug on service S3 side that affects across-SDKs but the expected behavior here is to include `x-amz-tagging` header when sending your request. It is also noted in the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property) as
>.....Tagging must be provided as headers when sending a request. If you are using pre-signed URLs to upload from a browser and need to use these fields, see createPresignedPost().

Here are some resources that I found indicates the known issue on the service side:
- https://github.com/aws/aws-sdk-ruby/issues/2762
- https://github.com/aws/aws-sdk-ruby/issues/2919

Let us know if issue persists with `x-amz-tagging` as header.
