### ISSUE TITLE
Ipv6 address treated as hostnamem `getaddrinfo ENOTFOUND [fd00:ec2::23]`

### ISSUE THREAD

**Issue by Defman** [aws/aws-sdk-js#4684]
### Describe the bug

When using podidentity with eks the ip `[fd00:ec2::23]` is treated as a hostname.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Should not try to resolve the ip via dns.

### Current Behavior

Tries to resolve `[fd00:ec2::23]` via dns

### Reproduction Steps

EKS Cluster running ipv6

### SDK version used

3.654.0

### Environment details (OS name and version, etc.)

EKS ipv6

**Comment by aBurmeseDev** [comment]
Hi @Defman - thanks for reaching out. 

The AWS SDK for JavaScript v2 is now in maintenance mode, as announced in [this blog post](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/). This means that only critical bug fixes and security issues will be addressed. Since this isn't considered a critical bug or security vulnerability, I will be closing this issue. 

However, if you believe this issue should be considered critical or a security concern, please let me know, and I will re-evaluate it.
