### ISSUE TITLE
installing AWS-SDK @ "2.1692.0" is returning npm Err, BAD ARCHIVE 

### ISSUE THREAD

**Issue by CLIMEUP-AYYAPPA** [aws/aws-sdk-js#4690]
### Describe the bug

The code pipeline failed this morning with aws-sdk install in package lock.json but is working fine locally.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

It should install aws-sdk

### Current Behavior

It is returning npm BAD ARCHIVE

### Reproduction Steps

Installing AWS-SDK in code pipelnieis failing

### SDK version used

2.169.0

### Environment details (OS name and version, etc.)

AWS Code pipeline

**Comment by aBurmeseDev** [comment]
Hi @CLIMEUP-AYYAPPA - thanks for reaching out.

Could you provide more details on your workflow, code example and changes that was made before encountering this?

It's worth noting that there haven't been any major changes in recent major versions of AWS SDK JavaScript v2 since we announced the maintenance mode: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/

Have you also considered migrating to [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3)?
