### ISSUE TITLE
sqs.sendMessage: HTTP content length exceeded 1662976 bytes.

### ISSUE THREAD

**Issue by Amir-61** [aws/aws-sdk-js#479]
Hi there,

If the response for `sqs.sendMessage` is too large, we are getting the following error "HTTP content length exceeded 1662976 bytes." and since it expects a valid XML response it says:

{
       "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: H",
       "code": "XMLParserError",
       "time": "2015-01-22T23:38:13.320Z",
       "statusCode": 413,
       "retryable": false
} 

Thanks,
Amir

**Comment by lsegal** [comment]
@Amir-61 thanks for reporting. I'm looking into this. It looks like this only triggers if you send a very large payload (over 1.5mb). The actual max size for SQS is much smaller (~256kb), so this error should typically not occur. That said, I've reached out to the SQS team to see if we can make this error more user friendly.

**Comment by AdityaManohar** [comment]
I'm marking this as closed because there is not much else that we can do from the SDK side of things. Feel free to reopen this issue or another issue if you have any questions.

**Comment by kilaka** [comment]
We had this issue recently and after we restarted the java client, the message receive worked.
This is quite strange, because we poll for only 10 messages and when looking at the queue using Amazon's UI, the biggest message was 7KB.
We have a suspicion that something got corrupted in the client SDK code, causing trying to poll a larger chunk of data.
