### ISSUE TITLE
API for validating operation params without making request

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js#488]
Is there any way to use the operation param validation that appears to be part of the SDK on it's own? My interests are in making a mock of the SDK to enable easier development of our applications without necessarily needing to take real actions in AWS. My team builds automation tools to orchestrate AWS and we have had to each basically have a real AWS account setup to our specifications in order to develop. I understand that a mock of the behavior will not represent the actual behavior on the backend of AWS by any means, but the param validation that is part of the SDK would go a long way.

If I can find a way to make this aws-sdk mock library, it would enable more advanced automated testing of our software which is virtually impossible to accomplish today as the thing I am trying to test may be long running operations within AWS. If I could get param validation, mock the response and maybe track some state of the resources created/modified/deleted it would be very valuable. 

For example, I could create a mock of a rds.createDBInstance that runs through your validation, then I could store the state in memory that an RDS instance was created with the params passed. Then I could have a mock of rds.describeDBInstances that again runs through your validation, reads the state from memory and returns the result as if the RDS instance were actually complete, without waiting minutes for it to happen in the real world.

**Comment by lsegal** [comment]
@chadwintzer this is a great question! Here are a couple of suggestions:

1. You don't have to use param validation as a separate module, you can instead just use the aws-sdk as is and build a request without sending it. There are a couple of ways to do this, the easiest is to just use the `request.build()` method, which runs all lifecycle events up to `'send'`. Technically, `build()` is a private method, but if there is interest here, I wouldn't be opposed to opening it up. The alternate public API version would be to remove all events associated with the `send` and beyond [lifecycle events](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html) (`request.removeAllListeners('send')`) and then call `request.send()`, which would do everything but hit the network. More on this below.

2. Ideally you're not just running param validation, but also validating responses. It sounds like the issue here is that you don't want to hit the AWS network, rightly so. In this case, the SDK request/response architecture can be mocked out to not hit the network when testing. We use this for our own functional tests, you can see a simple mocking implementation here:

https://github.com/aws/aws-sdk-js/blob/master/test/helpers.coffee#L167-L195

This small set of helpers takes a request object and throws out all the event handlers that hit network / parse server responses and instead just return pre-canned response object data. For example:

```js
var req = mockResponse({data: {Foo: 1}, error: null});
req.send(function(err, data) {
  console.log(err); // null
  console.log(data); // {Foo: 1}
});
```

Or the `mockResponses` method, which mocks a sequence of requests (good for testing sequential interactions).

3. Alternatively, you can use something like [nock](https://github.com/pgte/nock) which mocks out your HTTP client and allows you to build pre-canned data responses, or, more interestingly, [record live data](https://github.com/pgte/nock#recording) off the wire and replay it later. This is actually a really useful strategy that we use when testing the AWS SDK for Ruby v2 with a lot of success. I wrote about this a while ago on the [Ruby blog here](http://ruby.awsblog.com/post/Tx116N5YWW4WJ8I/Faster-AWS-Tests-with-VCR)-- it talks specifically about Ruby but the concepts should transfer over. The advantage of this one is that you can run your initial tests with accurate fixtures directly from a real service response, and then play it back multiple times without the extra network / resource costs. The other big win is that if you ever want to check if your tests "still work in the real world", you can just toggle off the "run locally" check (clear your local cache) and your tests will record new live data again. This is what I would do if I were in your shoes-- it's way easier than setting up fixtures manually. We've been looking at using this methodology for testing the JS SDK going forward.

Hope that helps!

**Comment by AdityaManohar** [comment]
Closing this out since the OP seems to have left the conversation.

**Comment by arbitrarytech** [comment]
@lsegal Thanks for the info! I have started mocking out the calls to the SDK that I am using and it is very successful so far. I now have functional mocks of an SQS queue as well as some of the EC2 calls I am making. In each of my mocks I now basically have something like this:
```
var AWS = require('aws-sdk'),
  sqs = new AWS.SQS();

...

var build = sqs.sendMessage(params).build();
if (build.response.error) return cb(build.response.error);
```
With this, I get the the validation you guys provide in the SDK and I can mock the backend behavior myself. If it turns out decently, I would be happy to release my "mock-aws-sdk" open source. Thanks for the help.

p.s. I consolidated my GitHub accounts which is why I turned to a "ghost".
