### ISSUE TITLE
Add structure to some errors

### ISSUE THREAD

**Issue by ide** [aws/aws-sdk-js#499]
Currently there's some important info in errors that needs to be grepped for in the error message. All the info is there but it would be even better if there were more structure. For example this is an error I got back from SNS:

```
{ [InvalidParameter: Invalid parameter: TargetArn Reason: No endpoint found for the target arn specified]
  [stack]: [Getter/Setter],
  message: 'Invalid parameter: TargetArn Reason: No endpoint found for the target arn specified',
  code: 'InvalidParameter',
  [name]: 'InvalidParameter',
  time: Fri Feb 06 2015 17:59:11 GMT-0800 (PST),
  statusCode: 400,
  retryable: false,
  retryDelay: 30,
  [isOperational]: true,
  __stackCleaned__: true }
```

I can see from the message that the TargetArn is the invalid parameter but currently I have to write a small regex / indexOf check. Something like `err.Info.InvalidParameter` would be less fragile to have.

**Comment by AdityaManohar** [comment]
@ide 
There is some flexibility in error messages returned by both the SDK and services, and parsing the error message to glean information from it does not scale well because of the variety in error messages.

You can rely on `error.code` across service operations. I'd be interested to know more about how/why you are using this parsed information.

CC: @lsegal

**Comment by ide** [comment]
@AdityaManohar: here are two examples I've encountered (both with SNS).

One is if you call `sns.createPlatformEndpoint` with a token that has already been registered, you get back an error with the code "InvalidParameter" and the endpoint ARN is part of the error message. To my knowledge, this is the only way to get the endpoint ARN for a single token that you've previously registered. So currently, I grep `error.message` for the endpoint ARN with a little regex.

The other case is if you call `sns.publish` with TargetArn value that is well-formed but doesn't exist. The resulting error has the code "InvalidParameter" and the error message says that TargetArn was the invalid parameter and that "No endpoint found for the target arn specified". So, to make sure that the problem is because of an unregistered endpoint ARN, I need to grep the error message for the invalid parameter name and the reason.

**Comment by AdityaManohar** [comment]
>To my knowledge, this is the only way to get the endpoint ARN for a single token that you've previously registered.

From the documentation: 
> The `CreatePlatformEndpoint` action is idempotent, so if the requester already owns an endpoint with the same device token and attributes, that endpoint's ARN is returned without creating a new endpoint.

If you are using the same token to create a new endpoint on the same application, you should see the `EndpointArn` in your data. I'm not sure why you are getting an error. Is your `Attributes` map identical across requests? Also, it may be a good idea to cache the `EndpointArn` locally.

I was able to create an application and an application endpoint. Multiple `CreatePlatformEndpoint` calls with the *same* parameters returned the same response:

```javascript
{ ResponseMetadata: { RequestId: '2a1bc3bb-6e6e-514e-b332-8ef48ebf78fd' },
  EndpointArn: 'arn:aws:sns:us-west-2:123456789012:endpoint/ADM/sampleapp/ea45d12d-1e2d-3ac7-8337-06c2a0aa4567' }
```

>So, to make sure that the problem is because of an unregistered endpoint ARN, I need to grep the error message for the invalid parameter name and the reason.

There are 2 scenarios here:
1. If you are publishing directly to an application `EndpointArn`, then it is best to cache this `EndpointArn` locally in your application instead of making a no-op request.
2. If you are publishing to an application `EndpointArn` that has been subscribed to a topic, then you can make a `listSubscriptions` call and get the `Endpoint` from the response. Even in this scenario, it might be favorable to cache this information locally and iterate over your local cache to implement your conditional logic.

I hope this helps!

**Comment by lsegal** [comment]
> I can see from the message that the TargetArn is the invalid parameter but currently I have to write a small regex / indexOf check. Something like err.Info.InvalidParameter would be less fragile to have.

Unfortunately having the `InvalidParameter` name specified in the error as a structured response would be no less fragile, because the SDK would have to write the same regex / indexOf check that you are writing, and our code would be just as susceptible to changes in error message content.

I would recommend following @AdityaManohar's advice of getting the correct ARN from a list or describe call against the service. This is always better than trying to process errors for response data when possible.

**Comment by ide** [comment]
>If you are using the same token to create a new endpoint on the same application, you should see the EndpointArn in your data. I'm not sure why you are getting an error. Is your Attributes map identical across requests? Also, it may be a good idea to cache the EndpointArn locally.

We do cache the EndpointArn in a Postgres RDS table but want to handle potential data loss if the table is unavailable or we lose rows for some reason. In this scenario all I have is the device token (don't have the attributes of the endpoint either) so it is possible that my code would try to re-register a device token with different attributes than the ones stored in SNS. I'll keep the little regex check for now since it's easy to verify with an integration test, and only pops up when our own data is temporarily unavailable (hopefully never!).

BTW thanks for the thoughtful suggestions @AdityaManohar and @lsegal. Really appreciate it.
