### ISSUE TITLE
Inconsistent timeouts when using s3.upload

### ISSUE THREAD

**Issue by jpfranco** [aws/aws-sdk-js#514]
Hey guys. I'm not sure if I'm testing this properly, but I just wanted to confirm what the expected behavior should be in this case. I've been noticing that when using ```s3.upload``` the time it takes for the ```NetworkingError: Network Failure``` error to be raised after a connection is dropped is a bit inconsistent. I've set the following config options:

```
AWS.config.httpOptions.timeout = 120000
AWS.config.maxRetries = 1
```

I'm testing this by starting an upload and then turning off my computer's wifi. Usually it takes about 1.5-2 minutes for the error to show up, but sometimes it takes as little as 20 seconds. I would've expected the error to show up after the first of the current part requests times out (2 minutes after the connection is dropped plus another 2 minutes since I've configured an extra retry). Is this assumption correct? Thanks

Here is an example of a part being dropped early:
```
[AWS s3 undefined 22.064s 1 retries] uploadPart({ Body: { type: '', size: 6291456 },
  ContentLength: 6291456,
  PartNumber: 17,
  Bucket: 'foo',
  Key: 'bar',
  UploadId: 'r_IXmUQyF2sqpjSd_YaaZdO5WZYlML6YwNqNGkgflk07UZo8f2fMASk3r2HvypteyGlIpPJUM7QYjR8tnuOmnYZ.koPKIJdZ6U.FvUvguC6ss6UGhy2IS.B50PrOtNw2' })
```

**Comment by AdityaManohar** [comment]
@jpfranco 
Pulling out the network cable doesn't simulate a connection timeout. The SDK will retry the error though because you have configured it to retry once.

If you are using an OSX install you can use the [Network Link Conditioner](https://developer.apple.com/downloads/index.action?q=Network%20Link%20Conditioner#) to simulate a slow connection. There should be other alternatives depending on the platform you are using.

I was able to set my timeout to 2000ms and simulate timeout errors
```
{ [TimeoutError: Connection timed out after 2000ms]
  message: 'Connection timed out after 2000ms',
  code: 'NetworkingError',
  time: Wed Feb 18 2015 14:46:39 GMT-0800 (PST),
  region: 'us-west-2',
  hostname: 'testbucket.s3-us-west-2.amazonaws.com',
  retryable: true }
```
Let me know if this helps.

**Comment by jpfranco** [comment]
Thanks. You're right, I'm able to get consistent results with Network Link Conditioner, sorry about that.

**Comment by AdityaManohar** [comment]
@jpfranco any time!
