### ISSUE TITLE
AWS object has no Glacier component?

### ISSUE THREAD

**Issue by blzabub** [aws/aws-sdk-js#522]
I'm working with the browser sdk, trying to interact with Glacier, just trying to instantiate a Glacier service interface object per the documentation:

``` javascript
 var glacier = new AWS.Glacier();
```
Getting the following error:

```
TypeError: undefined is not a constructor (evaluating 'new AWS.Glacier()')
```

In the Chrome console:

``` javascript
AWS
=> Object {util: Object, VERSION: "2.1.15", Signers: Object, Protocol: Object, XML: Object…}
AWS.S3
=> function (){return e!==Object?e.apply(this,arguments):void 0}
AWS.Glacier
=> undefined
```

**Comment by lsegal** [comment]
The hosted version of the SDK is only built to support services that work with [CORS](http://www.w3.org/TR/cors/). This list of services is documented in the [browser guide](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html) and does not include Glacier. You can [build your own version](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html) of the SDK with Glacier, but note that I do not believe Glacier supports CORS, so you would need to use an environment that disables CORS restrictions (a Chrome or Firefox extension, for example). Also note that due to the heavy use of SHA256 hashing in Glacier, performance will likely be significantly impacted in the browser.

Hope that helps.

**Comment by blzabub** [comment]
Ah yes, I did see that list of 11 services which does not include Glacier, but when I saw Glacier in the javascript documentation I thought otherwise. Thanks for the explanation.

**Comment by lsegal** [comment]
I am going to mark this as closed, but feel free to open new ones if you do end up generating a client with Glacier and run into any issues!

**Comment by blzabub** [comment]
Thanks @lsegal, am going to consider implementing an S3 client instead and just moving files from S3 to Glacier, or maybe send chunks to my web host and have the host send the chunk to Glacier and then delete the chunk on success. My web host has about 20GB total storage and these archives I'm moving are hundreds of GB in size. Cheers!
