### ISSUE TITLE
CDN URL for Newest Patch Version

### ISSUE THREAD

**Issue by cancan101** [aws/aws-sdk-js#535]
Some CDN URL that can be used which always provides the newest (patch) version

Something like:
https://sdk.amazonaws.com/js/aws-sdk-2.1.x.min.js
or
https://sdk.amazonaws.com/js/aws-sdk-2.1.min.js

**Comment by lsegal** [comment]
Thanks for the suggestion, Alex. This has come up before. One of the biggest concerns with automatically sending updates of the SDK into user applications is that we do not want to promote the practice of using untested version dependencies in downstream consumer applications. 

We do try very hard to maintain backwards compatibility across patchlevels, but there is always a risk associated with pulling in new versions of a library. Even legitimate bugfixes can potentially break downstream consumers across patchlevels if users are making incorrect assumptions, used a private API, or if the behavior itself was not well defined. This is uncommon, but it can and has happened before, and not just with the SDK.

Ideally, you should be testing that your application works with *any* library updates (big or small) prior to switching over to that new version in your codebase. If we had the URL being proposed, it's very likely we would discourage users from using it and recommend testing locally with new versions prior to deploying code to production instead. For that reason, I'm not sure that it makes sense to add behavior that we explicitly discourage (deprecate) immediately out of the gate. 

Note that the SDK currently follows the same best-practice in this regard as other large libraries like jQuery, for instance, which lists the latest versions but does not offer any CDN link support using this pattern. In fact, jQuery [explicitly moved away from this proposed model](http://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/) a while ago for the same reasons. It makes sense for us to follow the lead of other tried-and-tested libraries like jQuery here.

If you really do want to go down this route, it would not be too difficult to host the SDK in a location of your own. You could poll on our [GitHub releases Atom feed](https://github.com/aws/aws-sdk-js/releases.atom) or just npm/GitHub itself to find new versions and update your CDN with these versions. I would definitely advise caution with this practice for the reasons state above, though.

Hope that helps to explain a little about why this behavior is not currently available in our hosted build. I'm going to mark this issue as closed because this is a practice that is discouraged by other large libraries, and they have the battle scars to prove why it does not work well. That said, feel free to raise any questions/concerns here, I'd be glad to answer anything about this topic and even provide better alternatives.
