### ISSUE TITLE
getSignedUrl for putObject does not respect ContentDisposition

### ISSUE THREAD

**Issue by spazard1** [aws/aws-sdk-js#542]
I am calling s3.getSignedUrl('putObject', config, calback) with the following config:

var awsUploadConfigs = {
                Bucket: mybucket,
                Key: mykey,
                Expires: 3600,
                ContentType: myFileType,
                ACL: "private,
                ContentDisposition: 'attachment;filename="steven"'
            };

The resulting URL generated is: https://mybucketandkey?AWSAccessKeyId=mykey&Content-Disposition=attachment%3Bfilename%3D%22steven%22&Content-Type=application%2Fpdf&Expires=1427218287&Signature=sig&x-amz-acl=private

The resulting object in S3 doesn't have the Content-Disposition metadata set.

I have tried instead using Metadata: {"Content-Disposition": 'attachment;filename="steven"'} and when attempting to use the resulting URL, the request was rejected with a 403 saying that my signature didn't match the URL.

It seems that the sdk isn't sending the Content-Disposition information in a way that the REST endpoint for S3 understands.

I'm using the latest 2.1.18 version of the sdk and node 0.10.36.

**Comment by lsegal** [comment]
Hi @spazard1,

> It seems that the sdk isn't sending the Content-Disposition information in a way that the REST endpoint for S3 understands.

When using pre-signed URLs, the SDK is not responsible for sending the request to S3, it is only responsible for generating a URL. When using pre-signing, you must ensure that you are passing any headers through to your request, as this information is not passed through to the S3 API in the URL. In the case of ContentDisposition, this is actually passed through as the `Content-Disposition` header.

Let me know if that helps.

**Comment by spazard1** [comment]
Yes that makes sense. I thought that since the URL that is given back had the ContentDisposition inside it, that the AWS endpoint would read that information accordingly. Thanks for your answer.

**Comment by lsegal** [comment]
@spazard1 the ContentDisposition parameter is thrown into the URL as a side-effect of the way the SDK generates URLs. Currently we just generate everything in the URL, since we don't know at build time which parameters S3 will parse out of the URL. Ultimately, you don't need to be passing this parameter to the SDK, as it's not actually part of the URL and is not signed as part of the request, so ignoring it would work the same. As a sidenote, however, I agree it would be useful if S3 was able to parse some of these headers from the URL-- I would suggest opening an issue on the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) to request this functionality, as that would definitely simplify usage for many users.
