### ISSUE TITLE
sync lstat call in s3.uploadPart

### ISSUE THREAD

**Issue by juliangruber** [aws/aws-sdk-js#560]
if pass a read stream to `s3.uploadPart`, a sync lstat call will be performed here

- https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L172
- in https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L238

and more. If this file doesn't exist, the lstat call will throw, instead of calling the callback with the error.

**Comment by lsegal** [comment]
Can you explain a little bit more about the issue you're running into? Is the readable stream you're providing a file stream via `fs.createReadStream()`? If so, is the file being removed after the upload starts? 

Also are you sure an error is being thrown? Based on the codepath you provided, it actually looks like the error would just get swallowed and explicitly not thrown.

If we could get more information about the scenario, it would help to diagnose the problem. Thanks!

**Comment by juliangruber** [comment]
Yeah, it's from a `fs.createReadStream()`. The original source of error is that the file doesn't exist in the first place. However the sync lstat call is reached first before the fs module's internal `fs.open(...)` reaches disk, so it's not the stream emitting an error.

Hm you're right that it can't be this codepath, I'll find the real one causing this.

**Comment by juliangruber** [comment]
- https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L325
- https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L331
- https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L412

Those look not be be caught by any try/catch. I susped it's the last one, I'll try to come up with a stack trace.

**Comment by juliangruber** [comment]
```
Error: ENOENT: no such file or directory, lstat './data/1428314400000-1428316142276-30875.txt'
    at Error (native)
    at Object.fs.lstatSync (fs.js:838:18)
    at Object.byteLength (XXX/node_modules/aws-sdk/lib/util.js:172:39)
    at Request.SET_CONTENT_LENGTH XXX/node_modules/aws-sdk/lib/event_listeners.js:93:38)
    at Request.callListeners (XXX/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (XXX/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (XXX/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (XXX/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (XXX/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at XXX/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (XXX/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (XXX/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (XXX/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
    at callNextListener (XXX/node_modules/aws-sdk/lib/sequential_executor.js:90:14)
    at Request.computeSha256 (XXX/node_modules/aws-sdk/lib/services/s3.js:230:7)
    at Request.callListeners (XXX/node_modules/aws-sdk/lib/sequential_executor.js:97:18)
```

**Comment by lsegal** [comment]
> The original source of error is that the file doesn't exist in the first place.

Can you explain how the file does not exist if you are using `fs.createReadStream()`? It seems reasonable for the SDK to throw an exception if it can't stat the file, since it would need that file to exist in order to upload it. If you use `fs.createReadStream()`, the SDK expects for the file to be present so we can get the content length (and also the bytes). Are you mocking the fs call or something?

FWIW you can do a couple of things to work around this:

1. You can do `delete stream.path` so the SDK doesn't think it's a file stream.
2. If you can get the content length on your own, you can either set ContentLength in your upload or set `stream.length` or `stream.size` on the stream with the actual length. This will short-circuit the stat check.

I would suggest the above two workarounds for your case where the file does not exist on disk, though I am curious how you are coming upon this scenario. If we can understand the use case we might be able to support it.

**Comment by juliangruber** [comment]
This is due to a race condition. So yeah initially it's a problem on my side, but a function taking a callback should always

- report errors only to that callback
- do only async work, no *Sync calls

If you want I can get into why I think those points are important.

For now I'll set `stream.length` on my own, but I still consider this unexpected behavior, so I'm leaving this open for you to decide.

**Comment by lsegal** [comment]
I agree with one of your points but not both:

> * report errors only to that callback

I mostly agree with this. We do make a best-effort to catch possible errors and return them in the callback, but I will point out that this is not a guarantee. If there is a scenario that puts a library in an inconsistent state for undefined behavior, it seems reasonable to have an uncaught error in that case. For example, we currently have no guards on Buffer creation-- if heap memory was ever fully consumed and a `new Buffer` raised an out of memory exception, we would not be handling this case either; realistically we wouldn't want to anyway. Typically you would expect unrecoverable errors to hard-throw. This is currently undefined behavior (the SDK does not know how to handle streams that are not available on disk)-- that said, we can certainly look at handling this case specially, but there's an argument to be made that this might be an unrecoverable error.

> * do only async work, no *Sync calls

I'm not sure I agree with this one. An async call does not imply that *only* async work is being done. In fact, that's actually not possible. A `new Buffer`, or, frankly, any new memory allocation, for example, is itself a synchronous I/O operation (that can fail and `throw`), though arguably a much faster one than a file stat. Also, practically speaking, any time we call out to any library, function, or code path, that code path might be a black box that we have no control over (this is especially the case for a third-party library). By the above standard, it would be impossible for any asynchronous library to call on any other third-party code and still meet this bar, because that third-party code could be performing any number of synchronous I/O operations. From the perspective of having "small modular functions", which Node.js is really good at exposing, if asynchronous function A calls asynchronous function B, it should not be the concern of function A if fn B decides to call synchronous functions C and D-- that is solely the decision of fn B. From our own modular organization, we treat our util functions as separate black box functions that should not leak their abstractions into the SDK functions that rely on them. We could potentially refactor `byteLength` to run asynchronously, but this would only be for performance reasons, not for functional purity. Realistically, we only see negligible (if that) performance gains by switching to async stat, since this code path is only a very tiny part of the overall request cycle.

I think we both generally agree that knowable exceptions should be caught in functions that accept an err-data callback, and I agree that we could be doing a better job here. That said, looking at the code, it would probably require quite a bit of extra code complexity to handle this edge case, so we'll have to do some more investigation to see if it's worth taking this on.

Thanks for bringing this to our attention, though!

**Comment by lsegal** [comment]
I'm going to mark this as closed since this is a fairly specific edge case that has undefined behavior (when you delete a file being streamed out from under the SDK). We have issues open to improve the general error handling in the SDK that may make some of these errors bubble up in the callback instead of getting thrown, but there is no guarantee that all errors can always be caught in this way (especially for critical errors like these).
