### ISSUE TITLE
error: [InvalidParameterType: Expected params.count to be a string] when using s3.upload

### ISSUE THREAD

**Issue by MohsenElgendy** [aws/aws-sdk-js#575]
I have a very simple content of a file and when i apply the following code to add the file to a bucket, it gives me a strange error about a param named "count". here is my code

```javascript
var params = {Bucket: 'bucket', Key: 'key', Body: stream};
s3.upload(params, function(err, data) {
  console.log(err, data);
});
```

and here is the error
```
{ [InvalidParameterType: Expected params.count to be a string]
  message: 'Expected params.count to be a string',
  code: 'InvalidParameterType',
  time: Tue Apr 14 2015 12:56:42 GMT-0400 (EDT) }
```

**Comment by AdityaManohar** [comment]
Which version of the SDK and Node.js are you using?

**Comment by MohsenElgendy** [comment]
node@v0.12.2
npm@2.7.4
aws-sdk@2.1.23

**Comment by MohsenElgendy** [comment]
I had a workaround for the issue for now, but i do not recommend it.
What i did was that i changed my S3 configure array, to this 

```
new AWS.S3({params: {Bucket: 'bucket-name', Key: 'test.txt'}, paramValidation: false})
```

I added the param called "paramValidation" and set it to false, so it stopped the method from validating the issue so the file was uploaded successfully, Now this seems like a very wrong way to work around the issue but since i am in a hurry, i can leave it for now, but i still need an explanation for what is going on.

**Comment by lsegal** [comment]
@MohsenElgendy my guess is you're using a library in your JavaScript environment that is adding properties to the `Object.prototype`, specifically the `.count` property. Unfortunately this will cause interoperability issues with the SDK as well as many other JS libraries. You can verify that this is the case by running:

```js
for (i in params) { console.log(i) }
```

If your environment is clean you should only see "Bucket", "Key", and "Body". If you see "count", this is caused by a third-party library.

Let me know what you find.

**Comment by MohsenElgendy** [comment]
@lsegal Looks like my environment wasn't as clean as i might have thought, I had a method that was added to the ```Object.prototype``` called ```count``` so it affected the whole environment.

```javascript
Object.prototype.count = function () {
    var count = 0;
    for( var prop in this ) {
        count = count + 1;
    }
    return count;
};
```

Thanks for the help.

**Comment by johnpryan** [comment]
@lsegal is there any reason that this causes interoperability issues?  It seems like the AWS SDK should only care about keys on the object, and not on the prototype.  I'm using a compiler that adds  keys to the object's prototype automatically.

**Comment by lsegal** [comment]
@johnpryan not all params arguments are going to be object literals, so this allows complex objects (like objects pulled from another API/library) to be passed in directly. The SDK does standard object enumeration (`for in` loop), so if you want the SDK to skip the key, you should mark it as a [non-enumerable property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) when it's defined so that other libraries won't attempt to enumerate the key either.

**Comment by johnpryan** [comment]
@lsegal thanks for the quick response.  After digging a bit further I think object enumeration works for my use-case.   Full disclosure- I'm using [Dart's JS Package](https://pub.dartlang.org/packages/js) for Dart -> JS interoperability. which adds the prototype fields as non-enumerable properties already.

**Comment by lsegal** [comment]
If it is being added as non-enumerable with `Object.defineProperty`, it should be skipped by a `for ... in` loop. Here's a fiddle demonstrating:

https://jsfiddle.net/9bLyvhpw/

Maybe something else is going on?

**Comment by johnpryan** [comment]
I think I figured it out - I was passing an invalid `params` object to the aws.S3.putObject() function (not properly converted to JS)
