### ISSUE TITLE
SignatureDoesNotMatch with non-alphanumeric characters 

### ISSUE THREAD

**Issue by alexandarp** [aws/aws-sdk-js#578]
Hello,

I am using ```copyObject``` to transfer files from one s3 bucket to another. Half way through the process, I get the following error: 

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method
```

I narrowed down the error, and figured out that ```copyObject``` stops at a file which includes an asian character. 

Here are my params:

```
params =
            Bucket: "backup-#{bucket}"
            CopySource: "#{bucket}/#{image.Key}"
            Key: image.Key
``` 

If I skip over the files with asian characters, everything works fine. Is there something I extra I have to add to the params in order to use these characters?

Thanks,
Alex

**Comment by lsegal** [comment]
Unfortunately, JavaScript strings can only contain UTF-8 characters, so if your keys happen to have non-UTF-8 encodings in them, the AWS SDK for JavaScript currently does not support manipulating these objects. In order to support this, the SDK would need to both accept and return `Buffer` objects instead of strings for any Key / Bucket / CopySource parameter provided, which would be feasible on input but would be a breaking change on output.

That said, even though it's not supported, you can try using a Buffer() to generate the text for the key (`Buffer([byte,codes,here,...]).toString()`) or even one of the [ab2str / fromCharCode tricks](http://stackoverflow.com/questions/6965107/converting-between-strings-and-arraybuffers) to get around these JavaScript limitations. I haven't tried these, so I'm not sure how they will work, but let me know if this does work for you.

**Comment by alexandarp** [comment]
Thanks for the quick reply. I will get back to you with a solution.

**Comment by alexandarp** [comment]
@lsegal I have an update. The solution for me was to uri encode the image key:

```
encode_key = encodeURIComponent(image.Key)
          params =
            Bucket: "backup-#{bucket}-west"
            CopySource: "#{bucket}/#{encode_key}"
            Key: encode_key
```
I can then use ```decodeURIComponent()``` to convert the files to the original characters if I need to. I am not sure if this would be a solution for anyone else experiencing the problem.
