### ISSUE TITLE
Cannot load SDK into Google Apps Script

### ISSUE THREAD

**Issue by clemesha** [aws/aws-sdk-js#620]
Hi,

I'm currently writing a simple service using https://developers.google.com/apps-script/
and I cannot get the SDK to load. I'm currently working with aws-sdk-2.1.32.

I've followed these steps:
http://googleappsdeveloper.blogspot.com/2012/11/using-open-source-libraries-in-apps.html
and still haven't got it to work. 
I have tested the above method to load 'underscore.js', and that is working.

I can provide any other details or run any tests, just let me know.
Thank you.

**Comment by AdityaManohar** [comment]
Can you explain what you are trying to do? I am able to include the SDK as a script tag directly on a html partial and use it in that partial page.

![screen shot 2015-06-05 at 11 24 12 am](https://cloud.githubusercontent.com/assets/966440/8012324/76cb36de-0b75-11e5-971a-10694206f74b.png)

**Comment by clemesha** [comment]
Hi, thanks for the response. I'm trying to use the AWS SDK as a library. See attached screenshot of using underscore.js and moment.js vs the AWS SDK.
![screen shot 2015-06-05 at 2 52 58 pm](https://cloud.githubusercontent.com/assets/42060/8015988/b38fa6aa-0b92-11e5-8114-3f0d48f508e4.png)

**Comment by AdityaManohar** [comment]
The AWS SDK distributable relies on the existence of the `window` object. As I understand, Google Apps Script explicitly disallows any global access. I would recommend using an HTML partial with script tag. This way, you have access to the Google Apps Script libraries as well as the AWS SDK. You will even be able to pass data from your AWS resources into Google Apps.

Let me know if this helps.

**Comment by clemesha** [comment]
I'm looking to just create a stand-alone Google Apps Script (GAS) that uses the built-in GAS "Time-driven" Events trigger. 
In that stand-alone script I'm reading in emails from Gmail, then I hope to use the AWS SDK to trigger AWS Lambda functions, post data to S3, etc.

Let me know if this is possible, or if there are work-arounds to deal with the lack on the window object.
Thanks again.

**Comment by lsegal** [comment]
> Let me know if this is possible, or if there are work-arounds to deal with the lack on the window object.

It seems like the [article you posted](http://googleappsdeveloper.blogspot.com/2012/11/using-open-source-libraries-in-apps.html) provides a number of workaround to include libraries in your code:

> The simplest way to include the Underscore library in a project would be to paste its source code directly into your script

And also:

> Packaging a JavaScript library like Underscore as an Apps Script library is possible, but requires some helper functions to work correctly.

Did you try either of these methods? Note that loading the AWS SDK should be equivalent to the methodology required to load Underscore that is described in that post. Specifically, both libraries rely on a global variable attached to `window`. Basically, you should be able to use the same logic that got underscore working for you by doing the same for the AWS variable instead of `_`. There should be no fundamental difference between these two libraries from the perspective of GAS.

It's hard for us to know what exactly is not working without seeing code. If you're still having trouble, it would help if you showed the code that you are using to load both Underscore and the AWS SDK in your application.

Hope that helps.

**Comment by lsegal** [comment]
@clemesha I gave this a shot and was able to load the SDK with minimal adjustment to the aws-sdk.js file:

```js
(function(){var window = {};

// PASTE THE AWS SDK CODE HERE

;this.AWS = window.AWS;}).call(this);
```

The `AWS` variable was made available to my script using this method.

Hope that helps!

**Comment by clemesha** [comment]
Ok, thank you for the very helpful updates! I just now tried what you suggested,
and things did get further, but as you also mentioned, there's other dependancies it relies on,
see attached screenshot of current test. Are these unfixable issues? Thanks again.
![screen shot 2015-06-08 at 1 38 00 am](https://cloud.githubusercontent.com/assets/42060/8030911/7d49d0ae-0d7f-11e5-9ce2-09ac7f9e9c0b.png)

**Comment by lsegal** [comment]
Yes, these are unlikely to have a workaround. See the second paragraph in my last response. Most notably, GAS has no native support for XHR, which is integral to the correct functioning of the SDK.

**Comment by clemesha** [comment]
Ok, understood. Thanks again @AdityaManohar and @lsegal !
