### ISSUE TITLE
InstanceType isn't enumerated

### ISSUE THREAD

**Issue by alanmimms** [aws/aws-sdk-js#630]
In the other language SDKs the EC2 service's "enum type" InstanceType has enumerated values in an array or whatever (even in Java's baroque and crappy way of describing such things if you use introspection). But the JavaScript SDK doesn't have, e.g., the string "C4xlarge" anywhere - searching case insensitively. It would be OH so nice if the JavaScript SDK also had an exported array listing the values of "string" properties like EC2's InstanceType as enjoyed by the SDK users of other languages.

**Comment by lsegal** [comment]
@alanmimms you can find the list of enumerated properties in our documentation alongside the parameter you're looking at, i.e., InstanceType: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#runInstances-property

It is "c4.xlarge", by the way, noting the period. Hope that helps!

**Comment by alanmimms** [comment]
Wow! Thanks. I was looking at the Java SDK when I wrote the above and of course the "." is missing from the Java symbol but not the string it's bound to. Thank you for helping me find it.

**Comment by lsegal** [comment]
@alanmimms 

> If you look at the link you gave me, you will not find any definition of the instances property that is COMPUTER READABLE - only strings in documentation.

That's correct, the enumerable values are available in documentation only and are not present in the source. We *could* add enumerable values as an array somewhere inside of the service classes, or even as a set of "constant" properties, but this would not really be all that beneficial in the long run as:

1. You would likely need to visit documentation in order to find what these constants are named, at which point you can see these enumerated values in the operation parameters themselves.

2. Declaring constants would not provide much context on where these enumerated properties are used (like `AWS.EC2.INSTANCE_TYPE_C4XLARGE`), and you would still need to refer to the API documentation to see where they can be passed in. In this case you would actually have to read the operation docs, which already list the valid enumerated values.

The only real benefit to enumerated properties in general is the extra compiler help to avoid typos, but unfortunately in JavaScript there would be no compiler feedback when passing an invalid property name like `AWS.EC2.INSTANCE_TYPE_C99XSMALL`-- the failure case would be the same as passing an invalid string. For this reason, there's little benefit to adding a slew of constants to our documentation, and it would only increase our doc page sizes and code size as well.

You *would* get the benefit of grepping our npm package for these names, but I would argue that's not the best way to discover the enumerable properties-- visiting the API documentation is the preferred approach.

**Comment by alanmimms** [comment]
No, that's precisely the opposite of my point, really. I WANT to be able to do this programmatically so I can present the user with a list of choices in a GUI for orchestrating his application, and along the way I also want to give him the set of tradeoffs for his application based on the strengths and weaknesses of those instance types. I need a way - and would VERY much prefer a web service rather than an SDK API - to enumerate the instance types and get their resource strengths and weaknesses - all programmatically without a developer having to rebuild anything when you guys add new types. It's wonderful that you change so frequently to keep up with the hardware coming available and innovations in your cloud service capabilities. But it's a huge pain for people to release new versions with silly little strings changing all the time just to keep up. Let me write a piece of software that presents the user (whom only I know well enough to do this for - you guys cannot possibly know him that well) the tradeoffs to decide what instance type to deploy on. Then we can all develop things that add value and stop fiddling around with little strings that are hardcoded in various places.

Does that make any sense?

**Comment by lsegal** [comment]
@alanmimms I think that makes sense. Note that although we don't package the full models in the npm package (to preserve space), you can look at including the full EC2 API model definition in your code ([apis/ec2-2015-04-15.normal.json](https://github.com/aws/aws-sdk-js/blob/master/apis/ec2-2015-04-15.normal.json)). All enumerable properties are listed in these definitions and is how we generate our documentation. For example, you can grab the instance type list with:

```js
var api = require('./path/to/ec2-2015-04-15.normal.json');
console.log(api.shapes['InstanceType']['enum']);
```

We can look at including these strings by default as a feature request, but you can use the above code as a workaround for now.

**Comment by alanmimms** [comment]
Thanks! I can now fish on my own. But I do think my proposal of a web service to do all of this and also to allow queries for capabilities of each instance type is the way to go as the instance types change frequently and there are MANY more each time you add some. Your current scheme doesn't scale well as more are added. It's getting out of hand, no?

Thanks very much for the help.

**Comment by lsegal** [comment]
@alanmimms 

> But I do think my proposal of a web service to do all of this and also to allow queries for capabilities of each instance type is the way to go

For this I would recommend starting a forum post on the [Amazon EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) to request this feature. I agree that it would be a useful thing to have in the API!

**Comment by AdityaManohar** [comment]
@alanmimms I'm marking this as closed as you do seem to have a workaround for now. Feel free to reopen this issue or open another issue if you have any questions.
