### ISSUE TITLE
Is there a reason why v4.js Content-Type and User-Agent are ignored from signed headers?

### ISSUE THREAD

**Issue by harshavardhana** [aws/aws-sdk-js#659]
Example 

~~~
2d438433 lib/signers/v4.js (Loren Segal  2014-05-29 00:54:11 -0700 185)   unsignableHeaders: ['authorization', 'content-type', 'content-length',
b1bac923 lib/signers/v4.js (Loren Segal  2014-07-08 15:30:08 -0700 186)                       'user-agent', expiresHeader],
~~~

I couldn't find anything in the commit history regarding why Content-Type, User-Agent and Content-Length were removed from the signed header list , since adding them on the other hand doesn't seem to cause any issues with S3.

**Comment by lsegal** [comment]
@harshavardhana although signing these headers may work in your case, there are many cases where signing these headers causes problems. Here are reasons for each of the named headers:

* **User-Agent**: This is ignored from signing because signing this causes problems with generating pre-signed URLs (that are executed by other agents) or when customers pass requests through proxies, which may modify the user-agent.
* **Content-Length**: This is ignored from signing because generating a pre-signed URL should not provide a content-length constraint, specifically when vending a S3 pre-signed PUT URL. The corollary to this is that when sending regular requests (non-pre-signed), the signature contains a checksum of the body, which implicitly validates the payload length (since changing the number of bytes would change the checksum) and therefore this header is not valuable in the signature.
* **Content-Type**: Signing this header causes quite a number of problems in browser environments, where browsers like to modify and normalize the content-type header in different ways. There is more information on this in #244. Avoiding this field simplifies logic and reduces the possibility of future bugs.

**Comment by harshavardhana** [comment]
Thanks @lsegal this is super helpful

**Comment by tglines** [comment]
@lsegal just to confirm, `Content-Type` validation is not possible with the s3 sdk?  I just opened an issue that's similar here: https://github.com/aws/aws-sdk-js/issues/2212
