### ISSUE TITLE
CodeCommit on AWS-SDK-JS

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#674]
I wanted to be able to use the aws-sdk-js with CodeCommit, is this on the roadmap? If yes when? Best Regards

**Comment by AdityaManohar** [comment]
The SDK already has support for AWS CodeCommit in Node.js. Here is the link to the [API documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeCommit.html).

Are you talking about support for CodeCommit in the browser distributable of the SDK?

**Comment by ramonck** [comment]
I'm talking about browser distribution of the SDK.

**Comment by AdityaManohar** [comment]
@ramonck support for AWS CodeCommit is not included in the default browser distributable of the SDK because the service does not support CORS yet. I would recommend opening an issue on the [AWS CodeCommit Forum](https://forums.aws.amazon.com/forum.jspa?forumID=189) requesting CORS support.

**Comment by AdityaManohar** [comment]
@ramonck I'm marking this as closed because this isn't something that can be solved in the SDK at this time. Like I mentioned earlier, I would recommend opening on the [AWS CodeCommit Forum](https://forums.aws.amazon.com/forum.jspa?forumID=189) to request for CORS support.

Feel free to reopen this issue or open another issue if you have other questions.

**Comment by ramonck** [comment]
I have opened a case there, thanks for the help.

Best Regards,
