### ISSUE TITLE
Allow ECS task definition "CMD" param to be in shell form

### ISSUE THREAD

**Issue by MeanwhileMedia** [aws/aws-sdk-js#691]
I'm registering a task definition and need to supply the command attribute as a string, not an array. The reason I want this is so that I can easily supply a "multiline" command as such:

```
taskDefReg.containerDefinitions[0].command = 'git pull whatever; cd whatever; node whatever; etc'
```

This "shell form" should be valid according to docker docs: https://docs.docker.com/reference/builder/#cmd

However, I get the error msg:
```
message: 'Expected params.containerDefinitions[0].command to be an Array',
```

Any way we can add the ability to define CMD in shell form??

Thanks

**Comment by lsegal** [comment]
I would suggest bringing this up in the [ECS forums](https://forums.aws.amazon.com/forum.jspa?forumID=187), since this is an API issue that cannot be solved in the JS SDK directly (we simply provide an interface to the public API). That said, according to Docker documentation, "exec form" is the preferred form, since it has better support for arguments with spaces.

If you do not have arguments with spaces, you can easily convert to this format with:

```js
var cmd = 'git pull whatever'.split(' ');
taskDefReg.containerDefinitions[0].command = cmd;
```

That should allow you to provide the command in the correct format. 

**Note however** that this won't make multiple commands work, and *this would not work in shell form either*. According to Docker's docs on "shell form": 

> Note: Unlike the shell form, the exec form does not invoke a command shell. This means that normal shell processing does not happen.

Using ";" is an interpolation that happens in the shell, not [exec()](http://linux.die.net/man/3/exec). Providing the original command in Docker's shell form would not actually behave the way you expect, even if this was supported in the API.

Hope that helps.

**Comment by MeanwhileMedia** [comment]
Thanks for the response @lsegal. I'll try to post something in the forums. In the meantime.... I guess I'll have to write an extra build script (then run only that from docker CMD) instead of compressing everything into a multiline cli command. Too bad.

I'm also going to test if I can make exec form work by inserting '/bin/sh -c' in between each seperate 'line' of my command array. Not ideal though...

**Comment by MeanwhileMedia** [comment]
Just tested something like this:
```
["sh", "-c", "git", "clone", "whatever", "sh", "-c", "cd whatever", "sh", "-c", "npm install"]
```
This does not work. Everything after the first executable (git) just gets parsed as arguments to that first executable. Oh well.

**Comment by lsegal** [comment]
@MeanwhileMedia I think it would work if you quoted the shell command. For example:

```js
var cmd = "sh -c 'echo a && echo b'".split(' ');
```

**Comment by MeanwhileMedia** [comment]
Just tried your suggestion, as well as several other variations... turns out you can get it to work simply by doing:

["sh", "-c", "git clone whatever; cd whatever; npm install"]

So if you want to use shell form, you just push your string into array ["sh", "-c"]. Just make sure the entire multi-line command is a single string.

**Comment by lsegal** [comment]
Glad you got it working!

**Comment by MeanwhileMedia** [comment]
Thanks for your help @lsegal
