### ISSUE TITLE
abort method only seems to work on large files

### ISSUE THREAD

**Issue by onassar** [aws/aws-sdk-js#757]
using `abort` on an `AWS.S3.ManagedUpload` instance, and it only seems to work on larger files. I've tested with smaller files (~150kb and 1.7mb), but it was only on a larger one (~5.7mb) whereby abort was adhered to.

In other cases, the upload simply continued.
Is there a way to enforce `abort` on smaller files?

**Comment by chrisradek** [comment]
@onassar 
The reason you're seeing different behavior is due to how the `AWS.S3.ManagedUpload` handles uploading files of different sizes.

The `ManagedUpload` has a minimum part size theshold of 5MB (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#minPartSize-property). If the file being uploaded is below this threshold, then only a single upload operation is performed. 

If the file is above the threshold, then the `ManagedUpload` will instead do a multi-part upload. When `abort` is called, any parts that have not yet been sent to the `S3` bucket will not be sent, and the parts that have already been uploaded will be deleted from the bucket.

Since the smaller files are being uploaded in a single operation, they can't be aborted. Is the goal to remove the file from your bucket when abort is called?

Let me know if this information helps.

**Comment by onassar** [comment]
Thanks for the response @chrisradek 
The intention was to offer the user the option to abort an upload (eg. if they chose the wrong file, they realize their internet connection is too slow and don't want to continue it, etc). I stumbled on the exact scenario you're describing: that when a user triggers the abort method against an `AWS.S3.ManagedUpload` instance, it works as expected if the file is over 5MB

The concern is that it's a bit of a strange UX: the user can only (successfully) abort an upload whereby the file is over 5MB. The way I'm dealing with this is within the UI, I'm only showing the option to abort if the file is greater than the `minPartSize` threshold.

Is it possible to have abort work if/when the file is smaller? I was under the impression the `minPartSize` property needed to be greater than 5MB. If I could have it be arbitrarily low (eg. 100kb), that would be ideal.

**Comment by jeskew** [comment]
Multipart upload parts must be [at least 5 MB](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html), unfortunately.

**Comment by onassar** [comment]
Gotcha okay. Curious: is that a restriction from the browser or the AWS lib?

**Comment by chrisradek** [comment]
@onassar 
This is a restriction set by the S3 service.

**Comment by onassar** [comment]
Gotta. Any chance this can be overridden on a per-bucket basis?

**Comment by chrisradek** [comment]
@onassar 
Sorry for the delayed response.
Since this restriction is set by the S3 service, I'd recommend creating a feature request thread to allow overriding the minimum part-size that can be uploaded on the S3 forums here:
https://forums.aws.amazon.com/forum.jspa?forumID=24

**Comment by onassar** [comment]
Thanks @chrisradek
I'll give that a go. Would be great if I could update that on a per-bucket service
