### ISSUE TITLE
2.2.12 on lambda

### ISSUE THREAD

**Issue by cagataygurturk** [aws/aws-sdk-js#765]
Hi, whem 2.2.12 is added to lambda?

**Comment by chrisradek** [comment]
@cagataygurturk 
I would suggest posting this question to the AWS Lambda service team on the forums:
https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0

They manage updates to the version of the SDK used by Lambda.

Marking as closed since this isn't something controlled by the SDK, but feel free to reopen if you have further questions.

**Comment by chrisradek** [comment]
I would like to add that it is possible to bundle the latest SDK with your code if you wish to use a version other than what's provided by Lambda.

**Comment by cagataygurturk** [comment]
Unfortunately i could not do it. Can you explain how to overwrite the installed sdk please?

**Comment by chrisradek** [comment]
@cagataygurturk 
Take a look at the documentation for creating a deployment package with Node.js:
http://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html

The short version is, you will want to create a zip file that includes the code for your lambda function, as well as the JavaScript SDK. If you create a new directory, you can run `npm install aws-sdk`, create your JavaScript file that contains the code you want to run.  When you `require('aws-sdk') from within your JavaScript file, it should reference the version of the SDK bundled in your zip.

When you create your Lambda function, you'll upload the zip you've created, or upload it to S3 and reference it from there.

Let me know if that helps!

**Comment by cagataygurturk** [comment]
Yes i did like you said and really require() loaded the newer package from zip file. Thanks.
