### ISSUE TITLE
Uploading large file with ContentMD5 gets "confused"

### ISSUE THREAD

**Issue by kyleseely** [aws/aws-sdk-js#774]
When calling upload with a large file and passing the file's md5 hash like below:
```javascript
var params = {Bucket: 'bucket', Key: 'key', Body: largeFile, ContentMD5: 'theFilesMd5Hash'};
s3.upload(params, function(err, data) {
  console.log(err, data);
});
```
you always get a BadDigest error. I believe it's because the sdk is trying to do a multipart upload, but doesn't calculate the md5 for each chunk.

I already know about the `computeChecksums` option in the constructor. I just wanted to bring up this bug so it doesn't get other people.

**Comment by chrisradek** [comment]
@kyleseely 
You are correct.  When using `ManagedUpload`, files that are larger than 5 MB (by default) will automatically be broken up into parts with each part uploaded to S3 individually. The MD5 hash for each part will be different than the one for the entire file, which is why passing in the MD5 to `ManagedUpload` is causing a BadDigest error on large files.

As you've suggested, setting the `computeChecksums` option in the S3 constructor to `true` will cause `ManagedUpload` to automatically calculate the MD5 hash for each part and send it to S3 for validation, so `ContentMD5` does not need to be provided in this scenario.

**Comment by kyleseely** [comment]
Passing the correct md5 of the file to `upload` shouldn't cause a BadDigest error. The sdk should understand that the user wants to pass along the md5 of the file and calculate it correctly for each part that's uploaded. This took me days to figure out what was going on and I don't want that to happen to other users.

**Comment by AdityaManohar** [comment]
@kyleseely 
On a related note there are many features that the SDK provides as a convenience (generating MD5 checksums, S3 object metadata headers, SSE key checksums and so on). 

Even if you passed in a correct MD5 for a large file, this would need to be ignored because an MD5 checksum is generated for the each of the smaller uploaded chunks.

Silently ignoring user provided parameters can be very confusing and lead to other quirky side effects. This is the reason the SDK does not ignore any user provided parameters. 

By default the SDK will compute checksums for the S3 operations that require a `content-md5` header to be set. If you want to pass in your own MD5 checksum, you will need to turn off the `computeChecksums` option in the configuration. This can become much more involved when using `AWS.S3.ManagedUpload` because you will have to provide the MD5 checksum for each of the generated parts. 

I hope this helps clarify things!

**Comment by kyleseely** [comment]
Then perhaps an `InvalidParameter` error should be thrown when providing `ContentMD5` to upload a large file. It drove me nuts that I was getting a `BadDigest` error when the md5 I provided was indeed correct for the file.

**Comment by joshuajabbour** [comment]
:+1: to what @kyleseely says. This is insanely frustrating. `InvalidDigest` is such a confusing error here...

**Comment by chrisradek** [comment]
I've created pull request #786 to address this.  This will update the docs to clarify that ContentMD5 should not be provided when using `ManagedUpload`.  It also updates the message in the error to clarify that the ContentMD5 is invalid for multi-part uploads. I didn't want to change the error code itself because it is possible some users have already coded around the code specifically.

Let me know if you still have any concerns with regards to the changes being made!

**Comment by chrisradek** [comment]
#786 has been merged to address this.  These changes will be available via npm with the next SDK release.  They can also be used now by running npm install on this github repo.
