### ISSUE TITLE
Managed Upload: Resume does not work when body is a stream

### ISSUE THREAD

**Issue by kentor** [aws/aws-sdk-js#777]
Resume (calling `abort()` then `send()` again) works fine when the body is a File or Buffer, but nothing happens when calling `send()` again when the body is a stream. Sample code (node 4):

``` js
const AWS = require('aws-sdk');
const streamifier = require('streamifier');

const credentials = new AWS.Credentials({
  accessKeyId: ...,
  secretAccessKey: ...,
});

const s3 = new AWS.S3({
  credentials,
  params: { Bucket: ...},
  region: ...,
});

const MB = 1024 * 1024;
var body = new Buffer(20 * MB);
body.fill('1', 0, 5 * MB);
body.fill('2', 5 * MB, 10 * MB);
body.fill('3', 10 * MB, 15 * MB);
body.fill('4', 15 * MB);
body = streamifier.createReadStream(body);

const upload = new AWS.S3.ManagedUpload({
  leavePartsOnError: true,
  params: { Body: body, Key: 'test/test' },
  service: s3,
});

upload.on('httpUploadProgress', function(progress) {
  console.log(progress);
});

upload.send(function(err, data) {
  console.log(err, data);
});

setTimeout(function() {
  upload.abort();
  console.log('abort');
  setTimeout(function() {
    upload.send(function(err, data) {
      console.log(err, data);
    });
  }, 1000)
}, 1000);
```

**Comment by chrisradek** [comment]
@kentor 
This is currently a limitation with resuming a managed upload. This limitation exists because once data is read from a stream, it can't be read again, so trying to automatically resume could result in some lost data.

That said, I would like to take a deeper look and see what options there are for us to support resuming on aborted streams.  For now I'm going to mark this as a feature request, and work on updating documentation to specify that resuming when using streams isn't currently supported.

**Comment by kentor** [comment]
I see. I thought it would just keep what its read from the stream into a buffer until that part has uploaded successfully, or else read from the buffer again if the part was aborted and resumed.

**Comment by ajredniwja** [comment]
Closing this issue, since the feature was implemented.
