### ISSUE TITLE
Support content-length-range in s3.getSignedUrl('putObject', ...)

### ISSUE THREAD

**Issue by weiyin** [aws/aws-sdk-js#806]
getSignedUrl is much more convenient to use than creating policy JSONs and the HMAC myself. However, it is does not support content-length-range, which allows me to specify min and max object sizes.

**Comment by chrisradek** [comment]
@weiyin 
The `putObject` operation does not support setting `content-length-range`. See this related issue for more information: #643 

Since the `putObject` operation doesn't support this header, the header won't have an affect when using the presigned url either.

I'm closing this issue since this isn't something the SDK supports, but feel free to comment or re-open if you'd like to discuss further.
