### ISSUE TITLE
Memory leak with DynamoDB scan

### ISSUE THREAD

**Issue by ilanle** [aws/aws-sdk-js#818]
Hi, 
I am getting a serious memory leak when using dynamo.scan using the sdk in node.js environment.
I recursively call an asynchronous function which calls dynamo.scan, and I get a serious memory leak over time, when printing out memory usage, I see that every 5 iterations or so,  heap size jumps by about 1 megabit.
When I omit the Dynamo.scan call and replace it with callback after timeout, I don't get a memory leak.
Not clear why this happens.
Tried to limit the masSockets setting to no avail.
Thanks for your help

here is some of my code (reduced it as much as I can):

```
    myClass.getNextScan = function(lastPosition ,callback) {
        var options = {
            'TableName': params.tableName,
            'Limit':params.scanLimit
        };
        if (params.filterExpression){
            options["FilterExpression"]=params.filterExpression;
            options["ExpressionAttributeValues"]=params.expressionAttributeValues;
        }
        if (lastPosition) {
            options['ExclusiveStartKey'] = lastPosition;
        }
        if (params.ProjectionExpression){
            options['ProjectionExpression']=params.ProjectionExpression;
        }
        Dynamo.scan(options, function(err, data) {
                callback(null,null);
        });
    };

    myClass.getNexScanAndMark=function(lastPosition){
        console.log('memory usage ',process.memoryUsage());
        myClass.getNextScan(params.LastEvaluatedKey,function(err,data){
            myClass.getNexScanAndMark(params.LastEvaluatedKey);
        });
    };
```

**Comment by chrisradek** [comment]
@ilanle 
This isn't really an issue with the SDK, but appears like a memory-leak due to the way garbage collection is handled by the JavaScript engine. Garbage collection isn't always predictable, and sometimes you may have to wait a minute or so before seeing memory being freed. 

If you are using node, you can test this by starting your application with node --expose-gc, and forcing the garbage collector to run. In my quick test based on the code you've written above, I also force the garbage collector to run every minute:

```javascript
setInterval(function(){
    global.gc();
    console.log('Memory usage after gc: ', process.memoryUsage());
}, 60000);
```

After the main code finishes running and one or two garbage collections are forced, the memory usage returns to the originally reported values. 

Beyond that, there could be other issues in the code causing memory to be held on to longer than expected. Based on your example, `myClass.getNexScanAndMark` calls `getNextScan`, and accesses `params` using a closure, and the callback function passed into `getNextScan` also accesses `params` using a closure.

Memory leaks are very tricky to debug, but in this case, it doesn't seem to be an issue with the SDK, since I am able to run a test case and see the memory eventually being released. I'm going to close this issue, but if after more testing you determine there is a leak specific to the SDK, feel free to re-open or create a new issue.

Sorry for the lengthy post, hope this information helps!

**Comment by ilanle** [comment]
Hi,
Actually I already did all of that before posting this issue.
I already did monitor it and did force GC every loop. Whether or not forcing or not forcing GC, in several minutes you see a memory leak that cannot be mistaken.

The reason that I think that Dynamo.scan maybe related is that if I just omit the call to Dynamo.scan, there is no memory leak.

Meaning if I replace the lines:
        Dynamo.scan(options, function(err, data) {
                callback(null,null);
        });

with just

       setTimeout(function(){
       callback(null,null);
       },0);

There is no memory leak.
You could notice that whatever the scan returns, I return callback(null,null) and don't do anything, this is of course just for testing the memory leak.


P.S. another fact that might be a hint, I don't see memory rise on every loop (with GC forced), but rather every several loops/scans.

Thank you

**Comment by ilanle** [comment]
Hi,
Can you refer to my last comment?
thank you

**Comment by chrisradek** [comment]
This may be related to #855. I'll investigate further.

**Comment by srchase** [comment]
@ilanle 

Is this still an open issue for you?  There have been significant updates to the SDK since this was reported, so we're curious so see if you encounter the same issue using the latest version of the SDK.
