### ISSUE TITLE
Where to document peripheral extensions/helpers?

### ISSUE THREAD

**Issue by petemounce** [aws/aws-sdk-js#854]
I've written [es-aws-iam-http-connector](https://www.npmjs.com/package/es-aws-iam-http-connector) which uses IAMv4 to sign requests (made via the [elasticsearch-js](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/index.html) client) that are made against an AWS ES Domain secured with IAM. 

Where is the best place to mention a module that provides add-on or related functionality, from your SDK docs?

**Comment by petemounce** [comment]
I then discovered [TheDeveloper/http-aws-es](https://www.npmjs.com/package/http-aws-es) which does a better job, so I've removed my own module.

**Comment by chrisradek** [comment]
@petemounce 
We don't currently have a location to document extensions/helpers to the SDK. Part of the reason is we don't want to be responsible for maintaining that list as more libraries are created or decay.

However, NPM does maintain a list of projects that depend on the SDK: https://www.npmjs.com/package/aws-sdk
