### ISSUE TITLE
getBucketLocation in browser issues two calls instead of one

### ISSUE THREAD

**Issue by krishnasrinivas** [aws/aws-sdk-js#873]
When I do this on browser:
```js
s3.getBucketLocation(params, function(err, data) {
       if (err) console.log(err, err.stack); // an error occurred
       else     console.log(data);           // successful response
     })
```

I see that there are two calls:
1) First call is signed with 'us-east-1' to which S3 server responds:

`<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region><RequestId>2E1B85EE978E0C0C</RequestId><HostId>2qRIjS6ekuX9C5b91ygYuVsw4KsBbbyO+UANC3FmS8aq1Ojzrhpfo22gnMHDgXITbqKVxaD6OeY=</HostId></Error>`

Now we know the correct region which is eu-west-1

2) Second call is sent again this time signed with `eu-west-1`, now server responds with `200 OK` with the body containing:

`<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">eu-west-1</LocationConstraint>`

Why is the second call necessary when the first call already responds with the correct region in the error XML?

**Comment by AdityaManohar** [comment]
@krishnasrinivas looks like this behavior is related to this change: adf583b

This has the (potentially desirable) side effect of returning correct response data for the [`AWS.S3.getBucketLocation()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property) API operation. 

```javascript
s3.getBucketLocation(params, function(err. data) {
  // use LocationConstraint here
  console.log(data.LocationConstraint);
});
```
To answer your question more specifically, the second call is required because error responses are handled differently by the SDK's request handler chain, and correct response data cannot be trivially populated from error responses (this could also lead to strange side effects). So a request that has resulted in an error is retried to return the correct response data that is then useable by any consumer code.

I hope that helps answer your question. I'm also curious to learn more about your use case? Are you parsing the error response manually?

**Comment by krishnasrinivas** [comment]
We are writing S3 compatible JS client library https://github.com/minio/minio-js I was curious as to how aws-sdk-js does getBucketLocation from the browser i.e how would it signs (V4) the request without knowing the region and saw this behavior. Thanks for your response.
