### ISSUE TITLE
DynamoDB waitFor() with custom interval/max_attempts

### ISSUE THREAD

**Issue by mseiwald** [aws/aws-sdk-js#881]
How would I use waitFor() with a customer interval and/or max_attempts value?

**Comment by chrisradek** [comment]
@mseiwald 
There isn't a publicly available way of modifying the `interval` or `max_attempts` on waiters in the SDK. However, this is something we could support. I'll mark this as a feature request for now.

That said, the `waitFor` method is essentially just calling `describeTable` every 20 seconds, up to 25 times. It would be fairly trivial to write a polling function that does the same in your own code, using parameters you specify.

Thanks for your feedback, let us know if you have any further questions or comments!

**Comment by TamerShlash** [comment]
+1 for this feature request, I had to write a custom polling function and while that's not that hard, it feels unnecessary as there's an existing way to do that.

However, I want to highlight two things:

1. The default `delay` is 20 and `maxAttempts` is 25, that's _too_ much for a default value, and doesn't serve well for testing. Even if there's a way to customize the values, I would suggest to better tune the defaults.
2. Instead of waiting for a fixed duration, I suggest to follow [Incremental Backoff](http://docs.aws.amazon.com/general/latest/gr/api-retries.html).
