### ISSUE TITLE
Dynamodb latency

### ISSUE THREAD

**Issue by davidporter-id-au** [aws/aws-sdk-js#900]
Both in production and in a [simplified test](https://github.com/davidporter-id-au/debugging-node-aws-perf/blob/master/node/test.js) we're seeing typical latency with dynamodb requests at being around ~60 Milliseconds. 

This is certainly higher than what Dynamodb is reporting in its graphs and appears higher than [most other naive implementations](https://github.com/davidporter-id-au/debugging-node-aws-perf). 

Python with the boto library took about ~12ms, making it nearly 6 times faster on average. Are we doing something wildly wrong? 

Testing info: 

```
region: ap-southeast-2
read IOPs were well above the usage (only on request per second).
node version: 5.6 (also tested with 0.12.x, 4x)
AWS sdk version:  2.2.35
```

**Comment by chrisradek** [comment]
@davidporter-id-au 
By default, keepAlive is not enabled in node. Enabling this should speed things up as existing sockets will be reused. Do you mind testing this option out? You can do this by instantiating your `DynamoDB` client with the following options:
```javascript
var dynamo = new AWS.DynamoDB({
  region: "ap-southeast-2",
  httpOptions: {
    agent: new https.Agent({
      rejectUnauthorized: true,
      keepAlive: true
    })
  }
});
```

**Comment by davidporter-id-au** [comment]
So, I've learned a couple of things: 

##### Versions matter: 
1. I was rather wrong when I said it affected 0.12.x to 5.x, it appears to be version specific. Node 0.12.9 exhibits the 60~ millisecond behaviour. We're running node 0.12.9 in production which is why I was originally investigating that specific version. 
2. The performance for node 5.6.0, 4.3.0 and 4.2.0 appears better. Anecdotally it averages around ~15 milliseconds - still not great - but significantly better. However it is also significantly more variable than 0.12.9. 

This is a comparison of the versions: [pretty picture](https://raw.githubusercontent.com/davidporter-id-au/debugging-node-aws-perf-3/master/pretty-graphs.png) and [data](https://github.com/davidporter-id-au/debugging-node-aws-perf-3/blob/master/pretty%20graphs.csv). (Coincidentally, the number of requests between versions is different because node keeps crashing with the keepalive change, particularly on 0.12.9)

##### Keepalive doesn't seem to matter, breaks occasionally

I added the changes as you suggested with keepalive. It appears to make no difference on the performance for any of the versions of node that I've checked. It does now seem to throw the following error intermittently now though: 
```
$ node dynamo.js > results/node-4.2.0.log
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TLSWrap.onread (net.js:544:26)
```

**Comment by davidporter-id-au** [comment]
All tests run within an ec2 under the same conditions as before.

**Comment by davidporter-id-au** [comment]
@chrisradek So I ran the while loop again, both at a ['high'](https://github.com/davidporter-id-au/debugging-node-aws-perf-4/blob/master/high-freq.js) rate of once every 10 ms and a ['low'](https://github.com/davidporter-id-au/debugging-node-aws-perf-4/blob/master/low-freq.js) rate at once every second and did a [flame-graph](http://www.brendangregg.com/flamegraphs.html) of what's going on*.

Graphs for Node 5.7.0: [high freq](https://github.com/davidporter-id-au/debugging-node-aws-perf-4/blob/master/version-5.7.0/high-freq.svg), [low freq](https://github.com/davidporter-id-au/debugging-node-aws-perf-4/blob/master/version-5.7.0/low-freq.svg)

All the results across node versions look similar. The thing that is immediately outstanding to my fairly ignorant perspective, is there is a hell of a lot of CPU time being spent on credentials. The callstack is huge and the % of CPU time spent there is far higher than what I'd expect. Just my 2c, but I'd be slightly concerned that something in the way credentials are being validated, rotated and expired is hurting performance badly.

It's worth noting I'm running this on a Ubuntu Ec2 (standard AMI) with an instance role with permission to access dyanmo, so obviously it's reaching out to the metadata endpoint at some point in the lifecycle to get creds.

`*`I took care to wait 5 seconds into the loop to account for the CPU time spent on `require()` calls, metadata endpoint credential fetches and any other one-time operations at startup which would skew the CPU utilization. [This](https://github.com/davidporter-id-au/debugging-node-aws-perf-4/blob/master/make-graph.sh) is the shell script to make the graph, note 5 second sleep.

**Comment by chrisradek** [comment]
@davidporter-id-au 
Please correct me if I'm misreading the graph, but I don't think it is necessarily showing that a lot of time is spent on retrieving credentials. 

For each operation, the SDK will validate credentials to determine if they should be refreshed, so we would expect a large sample of credential related calls. The SDK also gets credentials when signing the request (this may be able to be optimized), but again, checks if credentials need to be refreshed before actually retrieving them. The graph doesn't seem to show how much CPU time is actually spent on each method call, but rather how many times each method was called.

How long were these tests run for? Since you're grabbing credentials using the EC2 metadata service, we should see the lib/credentials/ec2_metadata_credentials.js file referenced in the graph if credentials were actually being retrieved, which I don't see at all in this graph. The SDK does cache credentials, 

Based on this graph alone, I can't say that the SDK is not spending a lot of CPU time on getting credentials, I just don't think it tells us much except how many times those methods are called.

Did you create flame graphs for other versions of nodeJS as well? Specifically those that take ~60ms vs ~15ms?

**Comment by davidporter-id-au** [comment]
I must admit to being fairly new to interpreting the data as well, but to quote the guy who wrote the graphing library: 

> "The width of the box shows the total time it was on-CPU or part of an ancestry that was on-CPU (based on sample count). Functions with wide boxes may consume more CPU per execution than those with narrow boxes, or, they may simply be called more often. The call count is not shown (or known via sampling)."

http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html

Regarding the node version issue, I did node versions `0.12.9`, `4.3.0` and `5.7.0`. To me they all look similar in basic structure and in that the credential calls dominate CPU time.

**Comment by davidporter-id-au** [comment]
Ah, sorry, I forgot to mention. the tests run for 30 seconds. 

In thinking about your point about the frequency of the calls versus the CPU time consumed per call, you're right, I don't think I can make that determination. Nonetheless, would you expect that the quantity of events (in terms of CPU time spent net on those calls, irrespective of their being of great quantity or infrequently but with an expensive call) to be of that distribution?

**Comment by der-flo** [comment]
I hope this is not too off-topic: I have a similar issue with the Lambda client. A test lambda calls a noop lambda with an overhead of ~ 50 ms.

The logs of the noop lambda show a duration of <1 ms per call (warmed). My measurings in the test lambda show >45 ms.

**Comment by dlsniper** [comment]
I too am experiencing this issue.
To see if it helps, I've hardcoded some credentials and then run the tests again and I've managed to get a 5-10% increase in throughput.
Clearly I don't want to run any production service with hardcoded credentials so I'll have to find a way around this.

**Comment by der-flo** [comment]
Whoops, working better now!
With the SDK version 2.6.3 and enabled keep-alive the overhead dropped to <10 ms.

**Comment by IhostVlad** [comment]
Given AWS Lambda on NodeJS 6-th version, which performs very simple test-purposes CRUD interaction with DynamoDB table. Measured performance is extremely slow, independent to selected Lambda RAM memory or RCU/WCU units for Dynamodb.

There was performed benchmark, and results are unsatisfied. Event MySQL database in micro container has performance, which is better compare to DynamoDB with some times. 
```
Update operations        1000            10000             20000            100000

RCU=1000/WCU=1000      104708 ms       176109 ms         276689 ms         N/A >5min
                        942 MB          707 MB            896 MB         

RCU=2000/WCU=2000      45953 ms        167686 ms         245937 ms         N/A >5min
                        646 MB          829 MB            896 MB       

RCU=3000/WCU=3000      74205 ms        151072 ms         253800 ms         N/A >5min
                        657 MB          840 MB            854 MB      

RCU=4000/WCU=4000      76636 ms        175258 ms         257238 ms         N/A >5min
                        896 MB          896 MB            896 MB      
```

After fast research reason of such behavior was found: DynamoDB performs new HTTP(S) request on each CRUD operation! (https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L25) It's extremely slow, event in TLS connection, which has relatively big establishment time, including key exchanges. Also, it's extremely big overhead for HTTP headers, which some times bigger than CRUD payload.

So question: is there available method to communicate with DynamoDB in persistent connection in NodeJS Labmda? Batch operations is not apropriate solution, since they does not support UPDATE operations.

**Comment by IhostVlad** [comment]
https://github.com/aws/aws-sdk-js/issues/1918

**Comment by chrisradek** [comment]
Closing old issue. Looks like this has been resolved.

**Comment by wjrjerome** [comment]
> @davidporter-id-au
> By default, keepAlive is not enabled in node. Enabling this should speed things up as existing sockets will be reused. Do you mind testing this option out? You can do this by instantiating your `DynamoDB` client with the following options:
> 
> ```js
> var dynamo = new AWS.DynamoDB({
>   region: "ap-southeast-2",
>   httpOptions: {
>     agent: new https.Agent({
>       rejectUnauthorized: true,
>       keepAlive: true
>     })
>   }
> });
> ```

@chrisradek do you know how long is the keep live time? It look like the connection can only keep for 5s only.

**Comment by chrisradek** [comment]
@wjrjerome 
It will depend on how many concurrent connections are being made against a host. There is a maxSockets parameter that can also be passed to the agent which controls the maximum number of sockets that can be opened to a host at once. By default, node sets this value to Infinity so this can cause each request to use a different socket. You can set a lower value to ensure a socket gets reused. You can find more info on `maxSockets` and `maxFreeSockets` in the [node documentation](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_agent_maxfreesockets).

I don't know if you can change how long keep-alive is set for, but node might be closing the connection after requests complete if maxSockets Infinity.
