### ISSUE TITLE
TypeError: AWS.CloudSearchDomain is not a function

### ISSUE THREAD

**Issue by akshath4u** [aws/aws-sdk-js#913]
Hi,

How can I use cloud search domain service from my js sdk. Its showing function undefined. I have referred aws official doc but same problem persist. 

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudSearchDomain.html

do you have any solution for this?

**Comment by chrisradek** [comment]
@akshath4u 
Are you using the browser version of the SDK? This service isn't included in the browser version of the SDK because it doesn't support CORS:
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

You can build a browser version of the SDK that includes CloudSearchDomain if you know that the environment you'll be running the SDK in does not enforce CORS:
https://sdk.amazonaws.com/builder/js/

Let me know if that helps!

**Comment by akshath4u** [comment]
@chrisradek Thanks for you response. I have a meteor app from which i have to access cloud search domain service. Currently I am using meteor plugin which is build from browser version of SDK. So Could you please suggest me the exact way to use the SDK in my client app.

**Comment by akshath4u** [comment]
@chrisradek  ..Actually i was using browser version SDK when i moved it into server basis its working fine. Thanks your support
