### ISSUE TITLE
bucket.upload() passes "key" vs "Key" to callback upon successful upload of simple vs multipart

### ISSUE THREAD

**Issue by naknomum** [aws/aws-sdk-js#918]
minor issue, but calling `.upload()` returns slightly different results depending on if the file was large enough to trigger a multipart chunked upload.  in the **multipart** case, the result object has a key of _Key_ (not upper-K), whereas the simpler upload (smaller files) it is only _key_ (lower-k).  it can be worked around by, for example, using `result.Key || result.key`, but thought it might be worth posting.

**Comment by LiuJoyceC** [comment]
Hi @naknomum 
Thanks for pointing this out. We will look into whether there is a way to introduce more consistency in the result object without causing breaking changes to current customers.

**Comment by jardakotesovec** [comment]
This inconsistency also kicked us recently..

**Comment by LiuJoyceC** [comment]
Hi @naknomum and @jardakotesovec 
Thank for pointing out this inconsistency. Now 'Key' with uppercase K should appear on the result object for `s3.upload()` for either the smaller file upload or for the multipart upload. I've also added 'Bucket' to the result object for the smaller file upload to again be consistent with the multipart upload, and because it's useful information to return anyway. Please do note that the result object still has 'key' with lowercase k when the smaller file upload is triggered (so it now has both 'Key' and 'key' and they contain identical values). This is to prevent a breaking change for customers who currently depend on the lowercase k for small file uploads.

**Comment by naknomum** [comment]
thanks for the quick fix!

**Comment by sholladay** [comment]
> note that the result object still has 'key' with lowercase k

Can we get lowercase for everything since uppercase is weird and this is JavaScript and none of these things are constructors?  😇
