### ISSUE TITLE
Dynamodb Connection retry issue.

### ISSUE THREAD

**Issue by kalidossmm** [aws/aws-sdk-js#921]
We are trying to do the stress testing for our service, We have noticed the DynamoDB is taking lot of time(2 to 3 minutes) to respond to the query during the peak hours.  When we dig into the issue we understand its trying to retry the DB connection please see this image.

![image](https://cloud.githubusercontent.com/assets/8724615/13484043/0631b712-e0af-11e5-9f2a-e9993eeca84a.png)

1) We are using this aws-sdk npm module for establishing the connection and hitting the query to DB. 
2) Query is really simple query. 
3) when we are trying 14 req per sec, we are getting this kind of behavior. 

4) why this retry is happening? Do i need to do some special setting during the DB connection/query? Please suggest me.

**Comment by chrisradek** [comment]
@kalidossmm 
Can you provide details on what the actual error being returned is?

There are certain errors that the SDK will retry by default. For dynamodb with those errors, the SDK will retry up to 10 times while applying exponential backoff.
https://github.com/aws/aws-sdk-js/blob/master/lib/services/dynamodb.js#L43-L52

**Comment by kalidossmm** [comment]
Retry logic and delay is working perfectly, We are trying to hit the DynamoDB for querying and we are seeing this retry/delay behavior during peak load and the response for the http request is taking lot of time and As per newRelic request is spending time on retrying the connection with DynamoDB. 

Configuration on the table 50 read and 50 write. 

We are analyzing on why this connection is not establishing during the 1st hit it self and why its going on multiple retries. 

How to find the maximum number of connection open with DynamoDB?
Is there any restriction on DynamoDB or Aws-sdk on max open connection?

**Comment by chrisradek** [comment]
@kalidossmm 
What version of node are you running? Can you share what the specific error message you are getting is, or do you never see one because one of the retries is succeeding?

One thing you might want to try is setting the `maxSockets` your dynamodb client can use.

Example:
```javascript
var dynamodb = new AWS.DynamoDB({
  httpOptions: {
    agent:  new https.Agent({
      rejectUnauthorized: true,
      maxSockets: 100 // value was chosen arbitrarily
    })
  }
});
```

By default, node v0.12+ sets `maxSockets` to Infinity, and depending how many requests you're sending at once, this can cause issues. I don't know what limits DynamoDB might have in place, but I have seen issues due to socket timeouts caused when too many requests were being created at once, which were mitigated by setting `maxSockets`.

**Comment by chrisradek** [comment]
@kalidossmm 
Are you still having any issues?

**Comment by kalidossmm** [comment]
We found the root cause of the issue. Thanks for your help and inputs on configuration parameters.
