### ISSUE TITLE
Node.js type error while creating an AWS SQS queue

### ISSUE THREAD

**Issue by cananhas** [aws/aws-sdk-js#975]
We are trying to create an SQS queue on AWS from an EC2 instance using node.js. From the same instance, we can access S3 and list the buckets, etc. using node.js. The instance has an IAM role granting full access to S3 and SQS.

Executing the below code fails although it successfully works on local PC. 
Here is the code 
```
var AWS = require('aws-sdk');
AWS.config.update({region:'eu-central-1'});
//console.log("awsv "+AWS.VERSION); --> 2.3.5
var sqs = new AWS.SQS();
 var params = {
  QueueName: "MyQueue1"
 };
 sqs.createQueue(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else {
        if(data)
                console.log(data);           // successful response
        else
                console.log("Other unknown error");
   }
 });
```
Error message:

/home/ubuntu/aws-nodejs-sample/node_modules/aws-sdk/lib/http/node.js:121
      callback();
      ^
TypeError: undefined is not a function
    at Writable.writer._write (/home/ubuntu/aws-nodejs-sample/node_modules/aws-sdk/lib/http/node.js:121:7)
    at Writable.write (_stream_writable.js:176:8)
    at write (_stream_readable.js:481:24)
    at Array.forEach (native)
    at flow (_stream_readable.js:493:19)
    at _stream_readable.js:458:7
    at process._tickCallback (node.js:427:13)
    at process._makeCallback (node.js:345:15)

Could you please help us to solve this problem?
Thank you very much.

Canan Has

**Comment by LiuJoyceC** [comment]
Hi @cananhas 
It looks like your stream `Writable` class is not properly passing a callback function to the `_write` method. This is out of the SDK's control, as the SDK does not call `writer._write`, but I can try to point you in the right direction. From your stack trace, you can see that line 176 of `_stream_writable.js` (a file that comes installed with Node) is where the `_write` method is being called within `Writable.write`, so you can trace from there to see why a callback is not being passed. If a callback is not passed to `Writable.write`, it should be replacing the undefined with a default callback, so `_write` should never be called without a callback. I was not able to replicate your error when I ran Node versions 0.8 up through 6.0 on an Amazon Linux instance. Since your code is working on your local PC but not on the EC2 instance, make sure you have Node properly installed on your instance. Let me know if this helps!
