### ISSUE TITLE
AWS.SES is not a constructor

### ISSUE THREAD

**Issue by adolfosrs** [aws/aws-sdk-js#980]
I'm currently developing a angular application and I'm using aws-sdk-js 2.3.7. I'm not being able to contruct an AWS SES instance. Currently getting the following error:

`aws-sdk.js:4749 Uncaught TypeError: AWS.SES is not a constructor`

```
AWS.config.update({ accessKeyId: self.getAwsCreds().access_key, secretAccessKey: self.getAwsCreds().secret_key });
AWS.config.region = 'us-west-2';
var ses = new AWS.SES();
```

What is wrong here?

**Comment by ondruska** [comment]
SES does not work in browser (angular): for more see http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

**Comment by LiuJoyceC** [comment]
Hi @adolfosrs 
Thanks for your question. Currently, SES is not built into the browser SDK by default because the service does not yet support CORS, but we are working towards implementing CORS support in more services. For a list of the services that are currently supported by the default browser SDK, see: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

If you are working in an environment that doesn't enforce CORS, you can override this default and build your own custom version of the SDK: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html
However, be aware that if your browser enforces CORS, then you will get errors if you attempt to make requests with AWS.SES in your custom build.

Hope that clears up any confusion!

**Comment by flackend** [comment]
The latest version of aws-sdk supports SES in the browser.

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

**Comment by LiuJoyceC** [comment]
That is correct. The SDK supports SES in the browser in version `2.3.11` (released May 12).
