### ISSUE TITLE
DynamoDB Issue is not authorized to perform: dynamodb:GetItem on resource

### ISSUE THREAD

**Issue by Madhesk** [aws/aws-sdk-js#984]
DynamoDB not allowed the user for "SPECIFIC_ATTRIBUTES" only, but "ALL_ATTRIBUTES" is working fine. 

Here is my policy:

{

"Version": "2012-10-17",

"Statement": [

  {

   "Effect": "Allow",

   "Action": [

    "dynamodb:GetItem",

    "dynamodb:Query"

   ],

   "Resource": [

    "*"

   ],

   "Condition": {

    "ForAllValues:StringEquals": {

     "dynamodb:LeadingKeys": [

      "${graph.facebook.com:id}"

     ],

     "dynamodb:Attributes": [

      "UserId",

      "FirstName",

      "LastName"

     ]

    },

    "StringEqualsIfExists": {

     "dynamodb:Select": "SPECIFIC_ATTRIBUTES",

     "dynamodb:ReturnValues": [

      "NONE",

      "UPDATED_OLD",

      "UPDATED_NEW"

     ]

    }

   }

  }

]

}

**Comment by LiuJoyceC** [comment]
Hi @Madhesk 
I have reached out to the DynamoDB service team, as this does not seem to be an SDK issue, and I will keep you updated. Please also feel free to post your question on the AWS Forum for DynamoDB: https://forums.aws.amazon.com/forum.jspa?forumID=131
Here is also the link to the forum for IAM: https://forums.aws.amazon.com/forum.jspa?forumID=76

**Comment by schwar** [comment]
There are a few reasons DynamoDB may deny access for a fine-grained access control policy.

Here are a few things to check:
1) Are all attributes that are keys (either on the table or any indexes) included in the policy? If a user is denied access to a hash key or range key, DynamoDB cannot evaluate the request.
2) Are you specifying the ProjectionExpression parameter in the request? Here is a link to the [GetItem#ProjectionExpression documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html#DDB-GetItem-request-ProjectionExpression) and here is general [documentation for ProjectionExpression](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html). If you don't specify this parameter, DynamoDB attempts to retrieve the entire item, which would be denied because the user only has permission to specific attributes.

**Comment by Madhesk** [comment]
Hi @LiuJoyceC
Thanks for replying me. I will check those links and update it.
