### ISSUE TITLE
Cannot stream file to s3 using signature version v4

### ISSUE THREAD

**Issue by rloehr** [aws/aws-sdk-js#998]
I am using node 0.10.30.    I would like to stream a large file to S3 in multipart fashion.    
This works when using signatureVersion V2.    If I change to signatureVersion v4, the operation fails with the error:  The provided 'x-amz-content-sha256' header does not match what was computed when uploading the first part.

```
(function() {
  'use strict';

  // universal stuff
  var fs = require('fs'),

  // configurable options
    AWS = require('aws-sdk'),
    bucket = 'yourbucketname',
    key = 'testing-multipart/6mb.txt',
    // created with command: dd if=/dev/zero of=/tmp/6mb.txt bs=6291456 count=1
    fileName = '/tmp/6mb.txt';


  AWS.config.update(
    {
      accessKeyId: 'akeyid',
      secretAccessKey: 'asecretkeyid',
      region: 'us-east-1'
    });

  var s3 = new AWS.S3({
    maxRetries: 1,
    signatureVersion: 'v4',    //if you comment this out, everything works
    logger: process.stdout
  });


  if (require.main === module) {

    var createParams = {
      Bucket: bucket,
      Key: key,
      ServerSideEncryption: 'AES256'
    };

    var req = s3.createMultipartUpload(createParams);

    req.send(function (err, createResponse) {

      var uploadId = createResponse.UploadId,
        partResults = [],
        firstPart = {
          Bucket: bucket,
          Key: key,
          UploadId: uploadId,
          PartNumber: '1',
          Body: fs.createReadStream(fileName, {
            start: 0,
            end: 5242879
          }),
          ContentLength: 5242880
        };


      var reqPart1 = s3.uploadPart(firstPart);


      reqPart1.send(function (err, firstPartResult) {
        if (err) {
          console.log('failed to upload first part: ' + JSON.stringify(err, null, '  '));
          s3.abortMultipartUpload({
            Bucket: bucket,
            Key: key,
            UploadId: uploadId
          });
        } else {
          console.log('successfully uploaded the first part');
        }
      });
    });

  }
})();
```

I'm trying to determine if this is a SDK bug or a procedural piece that I am missing.

My understanding is the SDK should handle setting all the headers correctly.    Is that correct or am i missing a step when trying to move to sig version V4?

I also understand that there is an abstraction for managed uploads, but this does not workl on node 10 with streams of large files

Any thoughts on how best to proceed?

**Comment by bdmayes** [comment]
Also seeing this behavior on SDK v2.3.8. The ManagedUpload works but creating the multipart upload and uploading parts individually fails with this same error. The two implementations are creating different x-amz-content-sha256 headers which seems wrong to me.

I tweaked the code above to listen for the 'sign' event on the upload of the first part:

```
req.on('sign', function(stuff) {
  console.log('sha256: ' + stuff.httpRequest.headers['X-Amz-Content-Sha256']);
});
```

I also wrote a slightly different version that uses the ManagedUpload object:

```
var uploadReq = s3.upload(params, options);

uploadReq.send(function(err) {
  if (err) {
    console.log('Got an error: ' + JSON.stringify(err, null, '  '));
  } else {
    console.log('it worked');
  }
});
```

and then to capture the sha256 sum for this second implementation, I modified aws-sdk/lib/s3/managed_upload.js and added the same event listener below line 475 so that the file looks like this:

```
var partInfo = {ETag: null, PartNumber: partNumber};
self.completeInfo[partNumber] = partInfo;

var req = self.service.uploadPart(partParams);
req.on('sign', function(stuff) {
  console.log('sha256: ' + stuff.httpRequest.headers['X-Amz-Content-Sha256']);
});
self.parts[partNumber] = req;
req._lastUploadedBytes = 0;
req._managedUpload = self;
```


Looking at how that HMAC signature is created (http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html), it uses the secret key and the date (yyyymmdd) as part of the calculation. Since the date is the same and my secret is the same, I would expect both implementations to generate the same value for this header but they do not.

I can run the script that uses the ManagedUpload multiple times, and every time it outputs the exact same sha256. Similarly, I can run the "low-level" implementation and it generates the same sha256 each time. So the values are consistent each time I run them, but the values are _not_ consistent across the two different implementations.

It seems like there might be a bug when using the "low-level" implementation that it generates the wrong sha256 header. I'm trying to determine exactly where it generates that to see why the signature is different.

**Comment by chrisradek** [comment]
@rloehr 
Does the same code you provided above work if you remove the `ServerSideEncryption` parameter? I was able to run a quick test without that parameter, modeled on what you provided, and my test worked in node.js 0.10.30.  Can you also share what version of the SDK you are running?

**Comment by rloehr** [comment]
I've tried this with 2.3.8 and 2.3.14 of aws-sdk lib.

Removing the ServerSideEncryption param yielded the same error for me.

If you have a code snippet that works for you, please share it and I'll be happy to test against my particular buckets and test files.

**Comment by chrisradek** [comment]
Here's the exact test I'm running, in case there's any discrepancies. 
```javascript
var fs = require('fs');

var AWS = require('aws-sdk');

var bucket = '<MYBUCKET>';
var key = 'testing/output.txt';
var filename = '/tmp/6mb.txt';

var s3 = new AWS.S3({
    maxRetries: 1,
    signatureVersion: 'v4',
    logger: process.stdout
});

var createParams = {
    Bucket: bucket,
    Key: key,
    ServerSideEncryption: 'AES256'
};

var createReq = s3.createMultipartUpload(createParams);
createReq.send(function(err, data) {
    var uploadId = data.UploadId;
    var partResults = [];
    firstPart = {
        Bucket: bucket,
        Key: key,
        UploadId: uploadId,
        PartNumber: '1',
        Body: fs.createReadStream(filename, {
            start: 0,
            end: 5242879
        }),
        ContentLength: 5242880
    };
    
    var uploadReq1 = s3.uploadPart(firstPart);
    uploadReq1.send(function(err, data) {
        if (err) {
            console.log('fail');
        } else {
            console.log('success');  //Outputs: success
        }
    })
})

console.log(AWS.VERSION);  //outputs: 2.3.8
```

This is only uploading a single part. I added `ServerSideEncryption` and it worked as well. I created the tmp file using the same method you did above.

**Comment by chrisradek** [comment]
One thing, are you certain the region your bucket is in matches what your SDK is configured for?

**Comment by rloehr** [comment]
@chrisradek 

I tried your code and received the error.

The properties listed for my bucket through the web console are:

Bucket:	mybucketname
Region:	US Standard

My bucketname does have an underscore in it.     My secret accesskey has characters such as / and +

I'll attempt the same test with a bucket in my own personal (non business) aws account.

**Comment by chrisradek** [comment]
@rloehr 
What environment are you running under? I ran my test on mac osx 10.11.4. Have you tried with different versions of node.js?

**Comment by rloehr** [comment]
@chrisradek 

I tried this against my own dev bucket (no underscores in name) and received the same result.

I'm on osx 10.10.5.   
Also tried on ubuntu 14.04
Tested on node 0.10.30 and node 4 latest.

We have also tried on different wireless networks.

In the error message I am returned a requestId and extendedRequestId.   Would either of those be helpful debugging wise?

**Comment by rloehr** [comment]
@chrisradek 

Added logging of config just for comparison purposes
```
 credentials:
   { expired: false,
     expireTime: null,
     accessKeyId: 'myaccesskeyid',
     sessionToken: undefined },
  credentialProvider: { providers: [ [Function], [Function], [Function], [Function] ] },
  region: 'us-east-1',
  logger: null,
  apiVersions: {},
  apiVersion: null,
  endpoint: undefined,
  httpOptions: { timeout: 120000 },
  maxRetries: undefined,
  maxRedirects: 10,
  paramValidation: true,
  sslEnabled: true,
  s3ForcePathStyle: false,
  s3BucketEndpoint: false,
  computeChecksums: true,
  convertResponseTypes: true,
  correctClockSkew: false,
  customUserAgent: null,
  dynamoDbCrc32: true,
  systemClockOffset: 0,
  signatureVersion: null,
  signatureCache: true,
  retryDelayOptions: { base: 100 },
  useAccelerateEndpoint: false }
```
2.3.14

**Comment by bdmayes** [comment]
I'm on 10.10.5 and node 0.10.40. I'm also testing in us-east-1. I just tried running a fresh npm install aws-sdk in a different directory to get 2.3.14 and I see the same failing behavior. My parent company is known for locking down our network pretty hardcode, so I just came home and tried it here. For grins I also tried using a bucket and an S3 path that has absolutely no special characters in it. It's still failing.

All I have to do is comment out that ```signatureVersion: 'v4'``` option and it works fine. Unfortunately that means that I cannot do anything with KMS, since uploading with the ```SSEKMSKeyId``` option requires the signature version to be set to v4.

**Comment by chrisradek** [comment]
I'm finally able to reproduce the error now. Looking into it!

We have a PR that will allow you to disable body signing with sha256, instead calculating a content-md5 (this leads to a big performance boost in the browser, but could help here as well).
https://github.com/aws/aws-sdk-js/pull/988

If possible, you can give that branch a try and see if it helps for your scenario. I'll still look into why a sha256 mismatch is occurring.

**Comment by chrisradek** [comment]
Found the cause of the issue:
https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L703

The SDK is creating a new read stream to calculate the sha256 value. It will always use the full file instead of just the range you specified. This is relatively easy to fix by checking for the `start` and `end` properties of the stream and passing those along as well. I'll just need to verify that works for all versions of node.js we support.

**Comment by chrisradek** [comment]
PR #1000 created to fix this issue.

**Comment by bdmayes** [comment]
Super! I just tested these changes and I can confirm that it works for me, with or without the v4 signature. Thanks for the quick turnaround.

**Comment by chrisradek** [comment]
The pr has been merged into master. It'll be available via npm with the next release.

Thanks @rloehr and @bdmayes for reporting this issue!

**Comment by rloehr** [comment]
@chrisradek 
Right on.  I appreciate the fast response.  This helps us move forward.
